Repository obsproject/obs-studio, pull requests merged in 2018-09, with the labels that each got.

#1362 cmake: Use less automagic during configure
  deps/obs-scripting/CMakeLists.txt
  plugins/obs-filters/CMakeLists.txt
Labels: Pending Review

#1363 image-source: Add psd and *.* to file filter.
  plugins/image-source/image-source.c
Labels: Design Issue

#1364 [win-capture] Modify log for sharedmem
  plugins/win-capture/game-capture.c
Labels: Pending Review

#1416 Cleanup Compilation warnings
  UI/window-basic-main-profiles.cpp
  plugins/obs-outputs/librtmp/handshake.h
  plugins/obs-outputs/librtmp/hashswf.c
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Compile Issue

#1346 libobs/UI: Allow Access To argc/argv
  UI/obs-app.cpp
  libobs/obs.c
  libobs/obs.h
Labels: Delayed (issue)

#1406 UI: Add Search to Hotkeys settings menu
  UI/data/locale/en-US.ini
  UI/window-basic-settings.cpp
Labels: Design Issue

#1323 libobs: Add HLSL annotation parsing
  docs/sphinx/reference-libobs-graphics-effects.rst
  libobs-d3d11/d3d11-shader.cpp
  libobs/graphics/effect-parser.c
  libobs/graphics/effect-parser.h
  libobs/graphics/effect.c
  libobs/graphics/effect.h
  libobs/graphics/graphics.h
Labels: Pending Review

#1418 obs-qsv: Expose additional QSV encoder settings through GUI
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/obs-qsv11.c
Labels: Pending Review
