Repository obsproject/obs-studio, pull requests merged in 2019-11, with the labels that each got.

#2145 UI: Upgrade stream key link into button
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/url-push-button.cpp
  UI/url-push-button.hpp
  UI/window-basic-settings-stream.cpp
Labels: Enhancement

#2142 UI: Add fade to black in studio mode
  UI/data/locale/en-US.ini
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#2146 UI: Fix audio bitrate not being set in simple mode
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#2148 UI: Fall back to XGetWMName if XFetchName fails
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
Labels: Bug Fix

#2153 win-capture: Fix rare crash when OpenGL programs exit with graphics-hook
  plugins/win-capture/graphics-hook/gl-capture.c
Labels: Bug Fix

#2168 rtmp-services: Type check apply_encoder_settings
  plugins/rtmp-services/rtmp-common.c
Labels: Bug Fix, Linux

#2144 UI: Fix main transition being set to the quick one
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#1917 libobs/obs-filters: Add toggle for scroll filter looping
  libobs/obs-source.c
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/scroll-filter.c
Labels: Enhancement

#1919 obs-filters: Reload the mask image when file change is detected
  plugins/obs-filters/mask-filter.c
Labels: Enhancement

#1927 Just a couple of more X.org / Unix hotkey defines.
  libobs/obs-hotkeys.h
  libobs/obs-nix.c
Labels: Enhancement

#1990 UI: Use radio buttons for FLV track selection
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#1974 decklink-ui: Show the state of outputs in the decklink dialog
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
  UI/frontend-plugins/decklink-output-ui/forms/output.ui
Labels: Enhancement

#2081 CMake 3.10, C++17, SWIG warnings
  CMakeLists.txt
  UI/platform-windows.cpp
  deps/obs-scripting/CMakeLists.txt
  deps/obs-scripting/obslua/CMakeLists.txt
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Enhancement, Seeking Other Contributors, Work In Progress

#2042 UI: Add support for Custom (Legacy) Twitch Dashboard Docks
  UI/window-extra-browsers.cpp
Labels: Enhancement

#2010 win-dshow: fix H264 to mjpeg issue
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix, Incomplete

#1914 rtmp-services: Add YouNow service and implement ingest lookup
  plugins/rtmp-services/CMakeLists.txt
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
  plugins/rtmp-services/younow.c
  plugins/rtmp-services/younow.h
Labels: Enhancement, Services

#2125 Fixes to make OBS work on Catalina
  CI/before-deploy-osx.sh
  CI/install-dependencies-osx.sh
  CI/install/osx/Info.plist
  CI/install/osx/background.png
  CI/install/osx/background.pxd/QuickLook/Icon.tiff
  CI/install/osx/background.pxd/QuickLook/Preview.tiff
  CI/install/osx/background.pxd/QuickLook/Thumbnail.tiff
  CI/install/osx/background.pxd/data/556CF265-5721-4F18-BE83-8CF39483B4C2
  CI/install/osx/background.pxd/data/8CA689C3-ED2A-459E-952C-E08026CFCD07
  CI/install/osx/background.pxd/metadata.info
  CI/install/osx/background.tiff
  CI/install/osx/background@2x.png
  CI/install/osx/buildDMG
  CI/install/osx/dylibBundler
  CI/install/osx/makeRetinaBG
  CI/install/osx/obs.icns
  CI/install/osx/packageApp.sh
  CI/install/osx/settings.json
  UI/platform-osx.mm
  deps/obs-scripting/CMakeLists.txt
  deps/obs-scripting/obs-scripting-lua.c
  libobs/CMakeLists.txt
  libobs/obs-cocoa.m
Labels: Bug Fix, Seeking Testers, macOS

#2077 obs-qsv: Enable option for Custom Quantization Matrix
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#2085 obs-scripting: Fix Python on MacOS
  UI/CMakeLists.txt
  cmake/Modules/ObsHelpers.cmake
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Enhancement, Seeking Testers, macOS

#2079 obs-text: text transform add locale and start case
  plugins/obs-text/data/locale/en-US.ini
  plugins/obs-text/gdiplus/obs-text.cpp
Labels: Enhancement

#2179 UI: Remove help icon from Interact titlebars
  UI/window-basic-interaction.cpp
Labels: Bug Fix

#2180 obs-text: add missing include to fix build
  plugins/obs-text/gdiplus/obs-text.cpp
Labels: Bug Fix

#2092 libobs: add missing multimedia hotkeys for Windows
  libobs/obs-hotkeys.h
  libobs/obs-windows.c
Labels: Bug Fix, Enhancement, Windows

#2093 UI: Implement system tray icon for when the recording is paused
  UI/forms/images/obs_paused.png
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
Labels: Enhancement, Seeking Testers

#2183 obs-scripting: Fix Python in new MacOS .app bundles
  CI/before-deploy-osx.sh
  CI/install/osx/packageApp.sh
  deps/obs-scripting/obs-scripting-python.c
Labels: Bug Fix

#2101 UI: Add dropdown for Twitch chat extension
  UI/auth-twitch.cpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/obs-app.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement, Request for Comments, Seeking Testers

#2104 UI: Change advanced networking strings
  UI/data/locale/en-US.ini
  UI/window-basic-settings.cpp
Labels: Enhancement

#2107 UI: Fix swap scene issue with double click mode
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#2151 mac-vth264: Manually mark priority bits for frames
  plugins/mac-vth264/encoder.c
Labels: Bug Fix, macOS

#2124 Use PCI database IDs instead of string matching for devices
  libobs-d3d11/d3d11-subsystem.cpp
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Code Cleanup

#2094 UI: Add copy/paste of multiple selected sources
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#2102 UI: Add ability to change projector type
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#2167 obs-ffmpeg: Remove unexposed vaapi parameters
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix, Linux

#2184 obs-outputs: Log FTL during configure
  plugins/obs-outputs/CMakeLists.txt
Labels: Code Cleanup

#2152 libobs: Fix cursor draw position bug when cropping a window capture.
  plugins/linux-capture/xcompcap-main.cpp
  plugins/linux-capture/xcursor.c
  plugins/linux-capture/xcursor.h
Labels: Bug Fix

#1910 UI: Create an API to open projectors
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#2069 Enable Aarch64 support via SIMDe.
  deps/media-playback/CMakeLists.txt
  libobs/CMakeLists.txt
  libobs/graphics/quat.h
  libobs/graphics/vec3.h
  libobs/graphics/vec4.h
  libobs/media-io/format-conversion.c
  libobs/obs-audio-controls.c
  libobs/util/aarch/check.h
  libobs/util/aarch/hedley.h
  libobs/util/aarch/mmx.h
  libobs/util/aarch/simde-arch.h
  libobs/util/aarch/simde-common.h
  libobs/util/aarch/sse.h
  libobs/util/aarch/sse2.h
  libobs/util/sse-intrin.h
  plugins/decklink/audio-repack.c
  plugins/win-capture/game-capture.c
Labels: Enhancement, Work In Progress

#2206 libobs: fix building modules once installed
  libobs/graphics/quat.h
  libobs/graphics/vec3.h
  libobs/graphics/vec4.h
  libobs/media-io/format-conversion.c
  libobs/obs-audio-controls.c
Labels: Bug Fix, Code Cleanup

#2210 libobs: add missing FreeBSD #include to fix build
  libobs/util/platform-nix.c
Labels: Bug Fix

#2196 win-dshow: Suppress MJPEG error spam
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix
