Repository obsproject/obs-studio, pull requests merged in 2019-04, with the labels that each got.

#1573 obs-ffmpeg: Bind network buffer size in the UI
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Design Issue

#1641 UI: Refactor Audio Settings UI and move Monitoring Device from Advanced
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Work In Progress

#1667 linux-capture: Add randr support
  CI/install-dependencies-linux-ubuntu16.sh
  CI/install-dependencies-linux.sh
  plugins/linux-capture/CMakeLists.txt
  plugins/linux-capture/xhelpers.c
  plugins/linux-capture/xhelpers.h
  plugins/linux-capture/xshm-input.c
Labels: Pending Review

#1685 obs-filters: Add luma key filter
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/data/luma_key_filter.effect
  plugins/obs-filters/luma-key-filter.c
  plugins/obs-filters/obs-filters.c
Labels: Pending Review

#1743 Linux: add AppStream metadata
  UI/CMakeLists.txt
  UI/xdg-data/CMakeLists.txt
  UI/xdg-data/com.obsproject.Studio.appdata.xml.in
  UI/xdg-data/com.obsproject.Studio.desktop
Labels: Pending Review

#1752 vlc-video: Enable audio track selection
  plugins/vlc-video/data/locale/en-US.ini
  plugins/vlc-video/vlc-video-source.c
Labels: Work In Progress

#1577 Decklink: preview out support
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.h
  UI/frontend-plugins/decklink-output-ui/forms/output.ui
Labels: Pending Review

#1742 win-wasapi: Fix audio capture after USB sound card unplugging
  plugins/win-wasapi/win-wasapi.cpp
Labels: Pending Review

#1747 UI: Estimate recording time left until disk is full
  UI/data/locale/en-US.ini
  UI/window-basic-stats.cpp
  UI/window-basic-stats.hpp
Labels: Pending Review
