Repository obsproject/obs-studio, pull requests merged in 2019-12, with the labels that each got.

#2213 UI: Fix Qt deprecation warnings
  UI/properties-view.cpp
Labels: Bug Fix, Code Cleanup

#2215 UI: Rename deprecated QPalette::ColorRole
  UI/window-remux.cpp
Labels: Bug Fix, Code Cleanup

#2225 libobs: Remove C99 hacks for older VC++
  libobs/CMakeLists.txt
  libobs/util/c99defs.h
  libobs/util/vc/vc_inttypes.h
  libobs/util/vc/vc_stdbool.h
  libobs/util/vc/vc_stdint.h
Labels: Code Cleanup

#2227 Decklink: Explicit casts for truncation warnings
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix, Code Cleanup

#2232 rtmp-services: Add Konduit.live
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2211 UI: Add Grid Mode to Scenes Widget
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/OBSBasic.ui
  UI/scene-tree.cpp
  UI/scene-tree.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Request for Comments

#2203 UI: Streaming Settings Validation On Stream Start & User Help
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/ui-validation.cpp
  UI/ui-validation.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Request for Comments, Seeking Testers

#2240 rtmp-services: Increase FB max bitrate to 6Mbps
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2236 CI: Fix framework symlinks when building osx app
  CI/before-deploy-osx.sh
  CI/install/osx/Info.plist
  CI/install/osx/packageApp.sh
Labels: Bug Fix

#2220 obs-ffmpeg: Enable VAAPI Rate Control
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix, Enhancement

#1937 obs-qsv: Add all target usage options
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement, Seeking Testers

#1815 linux-v4l2: add support for controls
  plugins/linux-v4l2/CMakeLists.txt
  plugins/linux-v4l2/v4l2-controls.c
  plugins/linux-v4l2/v4l2-controls.h
  plugins/linux-v4l2/v4l2-input.c
Labels: Enhancement, Linux

#1748 obs-ffmpeg: UI and back-end for obs-encoded streaming over various protocols such as SRT
  UI/window-basic-main-outputs.cpp
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-encoded-output.c
  plugins/obs-ffmpeg/ffmpeg-encoded-output.h
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Enhancement, Pending Review, Seeking Testers

#2068 UI: Add option to use percent instead of dB
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/data/locale/en-US.ini
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
Labels: Enhancement

#2263 deps/obs-scripting: Expose matrix3 & 4 to scripting
  deps/obs-scripting/obslua/obslua.i
  deps/obs-scripting/obspython/obspython.i
Labels: Enhancement

#2267 UI: add option to show all sources to adv audio dialog
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/data/locale/en-US.ini
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
Labels: Enhancement

#2141 Add t-bar to studio mode
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
  libobs/obs-internal.h
  libobs/obs-source-transition.c
  libobs/obs-source.c
  libobs/obs.h
Labels: Enhancement

#2277 UI: Convert remux path separators to OS native style
  UI/window-remux.cpp
Labels: Bug Fix

#2276 Add monospace font for multiline text property
  UI/properties-view.cpp
  libobs/obs-properties.c
  libobs/obs-properties.h
Labels: Enhancement

#2279 UI: Properly inform user if recording path is invalid
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix
