Repository obsproject/obs-studio, pull requests merged in 2020-08, with the labels that each got.

#2939 UI: Add log viewer window
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/log-viewer.cpp
  UI/log-viewer.hpp
  UI/obs-app.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#3238 UI: Remove unused variable
  UI/window-basic-main-screenshot.cpp
Labels: Code Cleanup

#2356 Color space refinements
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main.cpp
  deps/media-playback/media-playback/media.c
  libobs/media-io/video-io.h
  libobs/media-io/video-matrices.c
  libobs/media-io/video-scaler-ffmpeg.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-x264/obs-x264.c
Labels: Bug Fix, Enhancement

#2955 UI: Make select/deselect signals work w/ group items
  UI/source-tree.cpp
  UI/source-tree.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#3253 mac-decklink: Fix C++ virtual function warnings
  plugins/decklink/DecklinkBase.cpp
  plugins/decklink/DecklinkBase.h
  plugins/decklink/DecklinkInput.hpp
Labels: Code Cleanup

#3273 CI: Add QtNetwork to bundle to restore Streamdeck support
  .github/workflows/main.yml
  CI/full-build-macos.sh
Labels: Bug Fix, Seeking Testers

#3223 rtmp-services: Add Nimo TV auto server
  UI/window-basic-auto-config-test.cpp
  plugins/rtmp-services/CMakeLists.txt
  plugins/rtmp-services/nimotv.c
  plugins/rtmp-services/nimotv.h
  plugins/rtmp-services/rtmp-common.c
Labels: Enhancement

#3233 Add context menu to Scripts list with "Open file location"
  UI/frontend-plugins/frontend-tools/data/locale/en-US.ini
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/frontend-plugins/frontend-tools/scripts.hpp
Labels: Enhancement

#3239 UI: Check and fail when launched under ChromeOS
  UI/data/locale/en-US.ini
  UI/obs-app.cpp
Labels: Linux, Seeking Testers

#2942 obs-x264: Log when options are ignored
  plugins/obs-x264/CMakeLists.txt
  plugins/obs-x264/obs-x264-options.c
  plugins/obs-x264/obs-x264-options.h
  plugins/obs-x264/obs-x264-test.c
  plugins/obs-x264/obs-x264.c
Labels: Enhancement

#3245 libobs: Fix deferred update sometimes using stale data
  libobs/obs-internal.h
  libobs/obs-source.c
Labels: Bug Fix

#3247 UI: Mac fix — remove wizard background padding
  UI/window-basic-auto-config.cpp
Labels: Bug Fix

#3261 libobs: Fix undefined behavior
  libobs/util/utf8.c
Labels: Code Cleanup

#3263 obs-filters: Add RNNoise to noise suppression filter
  cmake/Modules/FindLibrnnoise.cmake
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/obs-filters-config.h.in
  plugins/obs-filters/obs-filters.c
Labels: Enhancement

#3268 Add Source Toolbar
  UI/CMakeLists.txt
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/filter.svg
  UI/data/themes/Dark/media/media_next.svg
  UI/data/themes/Dark/media/media_pause.svg
  UI/data/themes/Dark/media/media_play.svg
  UI/data/themes/Dark/media/media_previous.svg
  UI/data/themes/Dark/media/media_restart.svg
  UI/data/themes/Dark/media/media_stop.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/OBSBasic.ui
  UI/forms/images/filter.svg
  UI/forms/images/media/media_next.svg
  UI/forms/images/media/media_pause.svg
  UI/forms/images/media/media_play.svg
  UI/forms/images/media/media_previous.svg
  UI/forms/images/media/media_restart.svg
  UI/forms/images/media/media_stop.svg
  UI/forms/obs.qrc
  UI/forms/source-toolbar/browser-source-toolbar.ui
  UI/forms/source-toolbar/color-source-toolbar.ui
  UI/forms/source-toolbar/device-select-toolbar.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
  UI/forms/source-toolbar/image-source-toolbar.ui
  UI/forms/source-toolbar/media-controls.ui
  UI/forms/source-toolbar/text-source-toolbar.ui
  UI/locked-checkbox.cpp
  UI/locked-checkbox.hpp
  UI/media-controls.cpp
  UI/media-controls.hpp
  UI/media-slider.cpp
  UI/media-slider.hpp
  UI/obs-app.cpp
  UI/obs-proxy-style.cpp
  UI/obs-proxy-style.hpp
  UI/properties-view.cpp
  UI/source-tree.cpp
  UI/visibility-checkbox.cpp
  UI/visibility-checkbox.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-properties.cpp
Labels: Enhancement, Seeking Testers

#3295 UI: Render tabs and spaces in Log Viewer
  UI/log-viewer.cpp
Labels: Bug Fix

#3284 UI: Provide Open button in the Log Viewer
  UI/data/locale/en-US.ini
  UI/log-viewer.cpp
  UI/log-viewer.hpp
Labels: Enhancement

#3313 UI: Fix transition enumeration
  UI/api-interface.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#3317 UI: Fix always on top w/ projectors on Linux
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
Labels: Bug Fix

#3324 UI: Fix projector not working on secondary monitors
  UI/window-projector.cpp
Labels: Bug Fix

#3325 obs-ffmpeg: Fix crash when seeking with no media
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#3326 UI: Don't open second dialog if close event is ignored
  UI/window-basic-main.cpp
Labels: Bug Fix

#3331 CI: Add Sphinx Docs generator Github Action
  .github/workflows/docs.yml
Labels: Enhancement

#3332 UI / Log Viewer: Bring to front rather than close, add minimize/maximize buttons
  UI/log-viewer.cpp
  UI/window-basic-main.cpp
Labels: Enhancement

#3333 UI: Align Advanced Audio Percent toggle to Volume text
  UI/window-basic-adv-audio.cpp
Labels: Bug Fix

#3339 UI: Fix tray icon appearing when disabled in settings
  UI/window-basic-main.cpp
Labels: Bug Fix

#3342 UI: Disable scene rename shortcut key while renaming
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#3343 UI: Fix output channels not being deleted
  UI/window-basic-main.cpp
Labels: Bug Fix, Code Cleanup

#3336 CI: Update macOS CLI build script
  CI/full-build-macos.sh
Labels: Bug Fix, Code Cleanup, Enhancement

#3346 libobs: Log Windows 10 Hardware GPU Scheduler
  libobs/obs-windows.c
Labels: Enhancement

#3344 Fix compiling warnings
  UI/forms/source-toolbar/device-select-toolbar.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
  plugins/obs-outputs/flv-mux.c
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/rtmp-stream.c
  plugins/obs-x264/obs-x264.c
Labels: Code Cleanup

#3349 UI: Add missing tab stop fields in Settings
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#3260 win-capture: Remove Vulkan CTS workaround
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Code Cleanup

#3354 CI: Update macOS deps to fix crash from invalid linking
  .github/workflows/main.yml
Labels: Bug Fix
