Repository obsproject/obs-studio, pull requests merged in 2020-07, with the labels that each got.

#2876 obs-ffmpeg: Add auto reconnect to remote media sources
  deps/media-playback/media-playback/media.c
  deps/media-playback/media-playback/media.h
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#2884 UI: Change audio device string in settings
  UI/data/locale/en-US.ini
Labels: Enhancement

#2907 frontend-tools: Add defaults button to script dialog
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/frontend-plugins/frontend-tools/scripts.hpp
Labels: Enhancement

#2915 UI: Fix bug where stats dock steals focus of main windows
  UI/window-basic-main.cpp
Labels: Bug Fix

#2917 frontend-tools: Automatically select scripts
  UI/frontend-plugins/frontend-tools/scripts.cpp
Labels: Enhancement

#2916 UI: Allow the use of Esc key to quit settings window
  UI/window-basic-interaction.hpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#2927 UI: Add TBar controls to obs-frontend-api
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main-transitions.cpp
Labels: Enhancement

#2940 UI: Log monitoring type for global audio devices
  UI/window-basic-main.cpp
Labels: Enhancement

#2954 UI: Allow drag & drop reorder of property lists
  UI/properties-view.cpp
  UI/properties-view.hpp
Labels: Enhancement

#2965 UI: Show help text for launch parameters on Windows
  UI/obs-app.cpp
Labels: Enhancement

#2978 linux-v4l2: Selective stream restart
  .gitignore
  plugins/linux-v4l2/data/locale/en-US.ini
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix, Linux

#2988 obs-ffmpeg: Allow continuous network streaming
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#3004 UI: Delete projector when monitor is disconnected
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#3030 obs-qsv11: Set preference for encode to iGPU in case of i+i
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#3141 UI: Update Facebook get stream key URL
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#3035 obs-qsv11: Simplify QSV settings in UI and Enable AVC VDEnc on ICL+
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/data/locale/en-US.ini
  plugins/obs-qsv11/libmfx/include/msdk/include/mfxstructures.h
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#3050 UI: Fix warnings for Qt 5.15
  UI/forms/OBSBasic.ui
  UI/properties-view.cpp
  UI/qt-display.hpp
  UI/qt-wrappers.cpp
  UI/source-label.hpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-interaction.cpp
  UI/window-basic-main.cpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
Labels: Bug Fix

#3074 win-capture: Remove game capture scaling
  plugins/win-capture/cursor-capture.c
  plugins/win-capture/cursor-capture.h
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook-info.h
  plugins/win-capture/graphics-hook/d3d10-capture.cpp
  plugins/win-capture/graphics-hook/d3d11-capture.cpp
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
  plugins/win-capture/graphics-hook/d3d1x_shaders.hpp
  plugins/win-capture/graphics-hook/d3d8-capture.cpp
  plugins/win-capture/graphics-hook/d3d9-capture.cpp
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
  plugins/win-capture/graphics-hook/gl-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
  plugins/win-capture/graphics-hook/graphics-hook.h
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Code Cleanup, Enhancement

#3078 obs-outputs: Handle NetStream.Publish.BadName from rtmp server
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix, Seeking Testers

#3085 libobs: Reset audio data on timestamp jump
  libobs/obs-source.c
Labels: Bug Fix

#3101 UI: Set remove prompt default action
  UI/window-basic-main.cpp
Labels: Bug Fix

#3108 mac-capture: Add several virtual audio drivers to Desktop audio
  plugins/mac-capture/audio-device-enum.c
Labels: Bug Fix, Enhancement

#3109 CI: Update build script to use pre-built SWIG and QT dependencies
  .github/workflows/clang-format.yml
  .github/workflows/main.yml
  CI/full-build-macos.sh
  CI/scripts/macos/Brewfile
  CI/scripts/macos/app/dylibbundler
  cmake/Modules/FindSwigDeps.cmake
Labels: Code Cleanup, Seeking Testers

#3104 UI: Add informative messages to auto-config dialog
  UI/data/locale/en-US.ini
  UI/forms/AutoConfigStartPage.ui
Labels: Code Cleanup

#3113 win-capture: Decouple swap and frame indices
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3121 win-capture: Don't use Chrome classes for priority
  plugins/win-capture/window-helpers.c
Labels: Bug Fix, Enhancement

#3123 UI: Fix unreadable Connecting Stream button
  UI/window-basic-main.cpp
Labels: Bug Fix

#3125 UI: Fix scene switcher not detecting some windows
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
Labels: Bug Fix

#3133 libobs: Fix video scalar copy heights
  libobs/media-io/video-scaler-ffmpeg.c
Labels: Bug Fix

#3110 UI: Add setting for taskbar color
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/obs-app.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
Labels: Enhancement

#3140 UI: Make color display, don't show alpha value in color label
  UI/properties-view.cpp
Labels: Bug Fix

#3149 win-capture Fix 32-bit Vulkan capture
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3122 Add "Taryana - Apachat" streaming service.
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3151 libobs: Translate F13-F24 hotkeys on Windows
  libobs/obs-windows.c
Labels: Bug Fix

#3142 obs-outputs: Use FLV codec IDs for videocodecid/audiocodecid
  plugins/obs-outputs/flv-mux.c
Labels: Bug Fix

#3168 CI: Add fix for macOS builds failing on push for Azure CI
  CI/before-deploy-osx.sh
Labels: Bug Fix, Seeking Testers

#3167 win-capture: Log duplicator display when updating properties
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Enhancement

#3175 UI, obs-ffmpeg, obs-filters: Fix compile warnings
  UI/window-basic-settings.cpp
  UI/window-basic-status-bar.cpp
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-filters/color-grade-filter.c
Labels: Code Cleanup

#3180 libobs: Add arm support
  libobs/util/simde/simde-math.h
  libobs/util/sse-intrin.h
  libobs/util/sse2neon.h
Labels: Enhancement

#3179 coreaudio-encoder: Fix encoding of 4.0 speaker layout
  plugins/coreaudio-encoder/encoder.cpp
  plugins/coreaudio-encoder/windows-imports.h
Labels: Bug Fix, Seeking Testers

#3150 win-capture: Remove fixed-size Vulkan arrays
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3144 frontend-tools: Make links in script description clickable
  UI/frontend-plugins/frontend-tools/data/locale/en-US.ini
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/frontend-plugins/frontend-tools/scripts.hpp
Labels: Enhancement

#3185 FFmpeg deprecation warnings
  libobs/graphics/graphics-ffmpeg.c
  libobs/media-io/media-remux.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix

#3187 UI: Fix warning about missing override
  UI/window-basic-settings.hpp
Labels: Code Cleanup

#3188 More FFmpeg cleanup
  deps/libff/libff/ff-util.c
  deps/media-playback/media-playback/decode.h
  libobs/media-io/media-remux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
Labels: Bug Fix, Code Cleanup

#3189 deps/media-playback: Preload video when seeking paused
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#3204 CI: Disable Python on macOS
  CI/install/osx/packageApp.sh
  CI/scripts/macos/packageApp.sh
Labels: Bug Fix

#3091 UI/CI/rtmp-services: Remove Mixer
  .github/workflows/main.yml
  CI/install-script-win.cmd
  UI/CMakeLists.txt
  UI/auth-mixer.cpp
  UI/auth-mixer.hpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/ui-config.h.in
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  azure-pipelines.yml
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
Labels: Code Cleanup, Services

#3197 win-capture: Improve Vulkan hook stability
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix

#3208 obs-qsv11: Fix bug mapping old qsv settings to new
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix

#3198 UI: Fix clickable text on boolean properties with tooltips
  UI/properties-view.cpp
Labels: Bug Fix

#3206 Fix preloaded video behavior
  libobs/obs-source.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Seeking Testers

#3202 UI: Add ability to make screenshots
  UI/CMakeLists.txt
  UI/api-interface.cpp
  UI/data/locale/en-US.ini
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/screenshot-obj.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-screenshot.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#2961 UI: Redesign transitions dock
  UI/forms/OBSBasic.ui
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Enhancement
