Repository obsproject/obs-studio, pull requests merged in 2020-03, with the labels that each got.

#2445 obs-ffmpeg: Fix type conversion warning
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix, Code Cleanup

#2450 CMake: Enable /OPT:REF for Windows
  CMakeLists.txt
Labels: Code Cleanup, Enhancement

#2451 CMake: Disable incremental linking on Windows
  CMakeLists.txt
Labels: Bug Fix, Code Cleanup

#2452 UI: Dynamically set widget index when renaming sources
  UI/source-tree.cpp
Labels: Bug Fix

#2458 obs-ffmpeg: Fix some incorrect settings for srt output
  plugins/obs-ffmpeg/ffmpeg-encoded-output.c
Labels: Bug Fix

#2459 UI: Fix scenes as sources for SL import
  UI/importers/sl.cpp
Labels: Bug Fix

#2462 win-capture: Handle NULL VkApplicationInfo
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#2463 libobs: Only manipulate input source ref counts
  libobs/obs-source.c
Labels: Bug Fix

#2464 win-capture: Fix format string warning
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
Labels: Code Cleanup

#2466 win-capture clean-up
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Code Cleanup

#2467 Fix build for armhf and powerpc
  plugins/linux-v4l2/v4l2-controls.c
Labels: Bug Fix

#2472 win-capture: Restore Vulkan 1.1 version hack
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#2469 libobs-winrt: win-capture: HDC cursor capture for WGC
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  plugins/win-capture/window-capture.c
Labels: Enhancement

#2475 obs-scripting: Add missing symbols in -python-import.[ch]
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obs-scripting-python-import.h
Labels: Bug Fix

#2477 UI: Fix windowed multiview title
  UI/window-projector.cpp
Labels: Bug Fix

#2474 Show friendly monitor names on Display Capture on Windows & Projectors
  UI/window-basic-main.cpp
  libobs-d3d11/d3d11-duplicator.cpp
  libobs/graphics/graphics.h
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/monitor-capture.c
Labels: Enhancement

#2444 UI: Show help icon for properties with tooltips
  UI/forms/images/help.svg
  UI/forms/images/help_light.svg
  UI/forms/obs.qrc
  UI/properties-view.cpp
Labels: Enhancement

#2486 win-capture: Handle vkCreateSwapchainKHR errors
  plugins/win-capture/graphics-hook-ver.h
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#2479 tests: fix Windows compile error
  test/win/test.cpp
Labels: Bug Fix

#2492 UI: Fix filter rename crash
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
Labels: Bug Fix

#2493 UI: Support Unicode for Windows fullscreen projectors
  UI/window-basic-main.cpp
Labels: Bug Fix, Seeking Testers

#2495 win-capture: Vulkan surface refactor
  plugins/win-capture/graphics-hook-ver.h
  plugins/win-capture/graphics-hook/graphics-hook.c
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix

#2498 UI: Increment filter name automatically
  UI/window-basic-filters.cpp
Labels: Enhancement

#2515 UI: Restart when browser hardware acceleration changed
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#2520 UI: Add setting for Mixer add-on choice (MixrElixr)
  UI/auth-mixer.cpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
Labels: Enhancement

#2523 Warning pass 2020-03-19
  UI/importers/importers.hpp
  libobs/obs-source.c
  libobs/obs.hpp
  libobs/util/util.hpp
  libobs/util/windows/CoTaskMemPtr.hpp
Labels: Code Cleanup

#2524 UI: Fix crash on settings update
  UI/window-basic-settings.cpp
Labels: Bug Fix

#2528 obs-qsv11: Fix target usage values
  plugins/obs-qsv11/QSV_Encoder.h
Labels: Bug Fix

#2533 obs-filters: Fix LUT file extension filter on Linux
  plugins/obs-filters/color-grade-filter.c
Labels: Bug Fix

#2534 UI: Make links in updater dialog clickable
  UI/forms/OBSUpdate.ui
Labels: Enhancement

#2497 linux-capture: Use RandR monitors for screen information
  plugins/linux-capture/xhelpers.c
  plugins/linux-capture/xhelpers.h
  plugins/linux-capture/xshm-input.c
Labels: Bug Fix, Enhancement

#2555 UI: Fix silent scenes with imported SL scenes
  UI/importers/sl.cpp
Labels: Bug Fix

#2582 obs-ffmpeg: Expose old NVENC on Windows 7
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Bug Fix, Regression

#2574 libobs-winrt: Stronger exception handling
  libobs-winrt/winrt-capture.cpp
Labels: Bug Fix

#2580 UI: Fix text handling for dialogs
  UI/window-importer.cpp
  UI/window-remux.cpp
Labels: Bug Fix

#2578 rmtp-services: Remove executable bits from json files
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2563 Fix QuickSync LA_ICQ encoder settings
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
Labels: Bug Fix, Regression
