Repository obsproject/obs-studio, pull requests merged in 2020-06, with the labels that each got.

#3017 libobs: Use correct data pointer for hotkey pair
  libobs/obs-hotkey.c
Labels: Bug Fix

#2977 libobs: Fix os_get_executable_path_ptr on Linux
  libobs/util/platform-nix.c
Labels: Bug Fix

#2993 obs-qsv11: Simplify QSV settings in UI and Enable AVC VDEnc on ICL+
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/libmfx/include/msdk/include/mfxstructures.h
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#3022 rtmp-services: Add Mixcloud service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3020 libobs-winrt: Require Windows 10 SDK 19041
  libobs-winrt/winrt-capture.cpp
Labels: Enhancement

#2820 UI: Update NSIS installer script
  UI/installer/OBSBanner.bmp
  UI/installer/OBSHeader.bmp
  UI/installer/mp-installer.nsi
  UI/installer/obs.ico
Labels: Code Cleanup, Work In Progress

#3084 rtmp-services: add angelthump
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3058 Media playback fixes
  deps/media-playback/media-playback/closest-format.h
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#3051 libobs: Use autoreleasepool for graphics thread
  libobs/obs-cocoa.m
  libobs/obs-internal.h
  libobs/obs-video.c
  libobs/obs.c
Labels: Bug Fix

#3048 libobs/media-io: Remove unused code
  libobs/media-io/audio-io.c
Labels: Code Cleanup

#3049 win-capture: Remove dead VkResult values
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix, Code Cleanup

#3009 libobs-winrt: Move project to core VS filter
  libobs-winrt/CMakeLists.txt
Labels: Code Cleanup

#3014 libobs: Remove excessive null checks
  libobs/obs.c
Labels: Code Cleanup

#3065 UI: Delete existing fullscreen projector
  UI/window-basic-main.cpp
Labels: Bug Fix

#3015 win-capture: Improve Vulkan synchronization
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3067 UI: Auto update projector settings
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#3006 libos: Freshen SIMDe code copy
  CMakeLists.txt
  libobs/util/simde/README.libobs
  libobs/util/simde/check.h
  libobs/util/simde/debug-trap.h
  libobs/util/simde/hedley.h
  libobs/util/simde/mmx.h
  libobs/util/simde/simde-arch.h
  libobs/util/simde/simde-common.h
  libobs/util/simde/simde-diagnostic.h
  libobs/util/simde/simde-features.h
  libobs/util/simde/sse.h
  libobs/util/simde/sse2.h
Labels: Enhancement

#3037 oss-audio: Add en-US translation data file
  plugins/oss-audio/CMakeLists.txt
  plugins/oss-audio/data/locale/en-US.ini
  plugins/oss-audio/oss-input.c
Labels: Enhancement

#3066 UI: Fix projector always on top not working on Linux
  UI/window-projector.cpp
Labels: Bug Fix

#3034 rtmp-services: AfreecaTV Update
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3042 image-source: change color source default color to d1d1d1
  plugins/image-source/color-source.c
  plugins/image-source/image-source.c
Labels: Enhancement

#3038 UI: Fix GetPreferredLocales locale detection
  UI/platform-x11.cpp
Labels: Bug Fix

#2970 UI: Add percent checkbox to advanced audio dialog
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
Labels: Code Cleanup

#2956 UI: Fix GetUnusedSceneCollectionFile filename creation
  UI/window-basic-main-scene-collections.cpp
Labels: Bug Fix

#2882 win-capture: Log window capture method
  plugins/win-capture/window-capture.c
Labels: Code Cleanup

#2890 CI: Add all-in-one macOS build script
  CI/full-build-macos.sh
  CI/scripts/macos/Brewfile
  CI/scripts/macos/app/entitlements.plist
Labels: Code Cleanup

#3061 win-capture: Reset command pool rather than buffer
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix

#3089 rtmp-services: Remove offline servers/services
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3090 UI: Update volmeters at 60hz
  UI/volume-control.cpp
Labels: Enhancement

#2376 UI: Fix buttons changing minimum window width
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
Labels: Bug Fix

#2662 Enhance Log dialog with description and Analyze button
  UI/data/locale/en-US.ini
  UI/forms/OBSLogReply.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-log-reply.cpp
  UI/window-log-reply.hpp
Labels: Enhancement

#2701 UI: sort audio sources by name locale aware
  UI/item-widget-helpers.hpp
Labels: Enhancement

#2690 UI: Add "Fit window to content" to windowed projectors
  UI/data/locale/en-US.ini
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#2699 rtmp-services: Add weabook.live
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2721 UI: Highlight unknown audio device label in settings
  UI/window-basic-settings.cpp
Labels: Bug Fix

#2755 libobs: Don't check filter compatibility on not loaded sources
  libobs/obs-source.c
Labels: Bug Fix

#2744 UI: Remove first run auto-config prompts
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
Labels: Code Cleanup

#2786 Add CFLAGS necessary on PPC64(LE) to libobs.pc
  libobs/CMakeLists.txt
  libobs/libobs.pc.in
Labels: Bug Fix

#2790 linux-capture: Add support for cropping the input source
  plugins/linux-capture/xshm-input.c
Labels: Enhancement

#2795 obs-text, text-freetype2: Add Enable Antialiasing option
  plugins/obs-text/data/locale/en-US.ini
  plugins/obs-text/gdiplus/obs-text.cpp
  plugins/text-freetype2/data/locale/en-US.ini
  plugins/text-freetype2/text-freetype2.c
  plugins/text-freetype2/text-freetype2.h
  plugins/text-freetype2/text-functionality.c
Labels: Enhancement

#2836 Fix FFmpeg YUV to RGB conversion by adding extra destination padding to line sizes
  deps/media-playback/media-playback/media.c
  libobs/graphics/graphics-ffmpeg.c
  libobs/media-io/video-scaler-ffmpeg.c
Labels: Bug Fix

#2821 UI: Add always on top checkbox to projector context menu
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#2774 libobs: Add sample unit tests leveraging cmocka
  .github/workflows/main.yml
  CI/install-dependencies-osx.sh
  CI/scripts/macos/Brewfile
  CMakeLists.txt
  test/CMakeLists.txt
  test/cmocka/CMakeLists.txt
  test/cmocka/test_darray.c
  test/cmocka/test_serializer.c
  test/osx/test.mm
Labels: Tests
