Repository obsproject/obs-studio, pull requests merged in 2020-12, with the labels that each got.

#3810 UI: Use Qt::MiddleButton instead of deprecated Qt::MidButton
  UI/hotkey-edit.cpp
  UI/obs-app.cpp
  UI/slider-absoluteset-style.cpp
Labels: Bug Fix, Code Cleanup

#3813 UI: Fix disabled sliders
  UI/properties-view.cpp
Labels: Bug Fix

#3785 mac-virtualcam: Fix remaining global namespaces
  plugins/mac-virtualcam/src/obs-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.h
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, macOS

#3778 vlc-video: Free media struct
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#3779 mac-virtualcam: Build a universal x86_64+arm64 binary for M1 Macs
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
Labels: Enhancement, macOS

#3833 UI: Scale Interact cursor position based on display DPI
  UI/window-basic-interaction.cpp
Labels: Bug Fix

#3842 obs-scripting: Fix removing signal handlers in lua
  deps/obs-scripting/obs-scripting-lua.c
Labels: Bug Fix, Seeking Testers

#3826 linux-v4l2: Fix bashism in v4l2loopback detection
  plugins/linux-v4l2/linux-v4l2.c
Labels: Bug Fix, Linux

#3837 sndio: remove strerror_l
  plugins/sndio/sndio-input.c
Labels: Code Cleanup

#3860 libobs: fix the pending stop trick
  libobs/obs-audio.c
Labels: Bug Fix

#3868 CI: Update macOS to Qt 5.15.2 and deps 2020-12-11
  .github/workflows/main.yml
Labels: macOS

#3768 UI: Handle (de)select scene items queued
  UI/source-tree.cpp
Labels: Bug Fix

#3857 linux-pulseaudio: fix race conditions
  libobs/audio-monitoring/pulse/pulseaudio-output.c
Labels: Bug Fix, Linux

#3856 linux-jack: fix timestamps, deadlock on shutdown, and port type
  plugins/linux-jack/jack-wrapper.c
Labels: Bug Fix, Linux

#3855 rtmp-services: Update Steam
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3917 CI: Remove obsolete and unused files
  CI/before-deploy-osx.sh
  CI/before-script-osx.sh
  CI/install-dependencies-osx.sh
  CI/install/osx/CMakeLists.pkgproj
  CI/install/osx/Info.plist
  CI/install/osx/OBSPublicDSAKey.pem
  CI/install/osx/SyphonInject.pkg
  CI/install/osx/background.png
  CI/install/osx/background.pxd/QuickLook/Icon.tiff
  CI/install/osx/background.pxd/QuickLook/Preview.tiff
  CI/install/osx/background.pxd/QuickLook/Thumbnail.tiff
  CI/install/osx/background.pxd/data/556CF265-5721-4F18-BE83-8CF39483B4C2
  CI/install/osx/background.pxd/data/8CA689C3-ED2A-459E-952C-E08026CFCD07
  CI/install/osx/background.pxd/metadata.info
  CI/install/osx/background.tiff
  CI/install/osx/background@2x.png
  CI/install/osx/buildDMG
  CI/install/osx/build_app.py
  CI/install/osx/dylibBundler
  CI/install/osx/makeRetinaBG
  CI/install/osx/obs.icns
  CI/install/osx/obs.png
  CI/install/osx/packageApp.sh
  CI/install/osx/package_util.py
  CI/install/osx/post-install.sh
  CI/install/osx/settings.json
  CI/osxcert/Certificates.p12.enc
  CI/util/build-package-deps-osx.sh
  CI/util/win32.sh
  CI/util/win64.sh
Labels: Code Cleanup, Seeking Testers

#3805 CI: Add necessary changes for CEF 4183
  .github/workflows/main.yml
  CI/full-build-macos.sh
  CI/scripts/macos/helpers/helper-gpu-entitlements.plist
  CI/scripts/macos/helpers/helper-plugin-entitlements.plist
  CI/scripts/macos/helpers/helper-renderer-entitlements.plist
Labels: Enhancement, macOS

#3889 mac-virtualcam: Fix file mode
  plugins/mac-virtualcam/src/dal-plugin/Defines.h
Labels: Code Cleanup, macOS

#3895 CI: Fix macOS 10.13 crashes and dependency incompatibilities
  .github/workflows/main.yml
  cmake/Modules/FindLibcurl.cmake
Labels: NOT READY TO MERGE, Seeking Testers, macOS

#3907 decklink: Fix automatic pixel format detection
  plugins/decklink/DecklinkInput.cpp
  plugins/decklink/DecklinkInput.hpp
  plugins/decklink/OBSVideoFrame.cpp
  plugins/decklink/OBSVideoFrame.h
  plugins/decklink/const.h
  plugins/decklink/data/locale/en-US.ini
  plugins/decklink/decklink-device-instance.cpp
  plugins/decklink/decklink-device-instance.hpp
  plugins/decklink/decklink-source.cpp
Labels: Bug Fix, Seeking Testers

#3877 UI/rtmp-services: Remove Smashcast
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3950 CI: Remove jack, speex and fdk-aac from default builds for macOS
  .github/workflows/main.yml
  CI/full-build-macos.sh
  CI/scripts/macos/Brewfile
Labels: Bug Fix, Seeking Testers, macOS

#3970 mac-virtualcam: Mark parameters as unused
  plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.mm
  plugins/mac-virtualcam/src/dal-plugin/Logging.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPluginMain.mm
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Code Cleanup

#3975 mac-virtualcam: Remove unnecessary logging
  plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Labels: Code Cleanup

#3988 UI: Support fractional scaling for Canvas/Base size
  UI/window-basic-main.cpp
Labels: Bug Fix

#3944 coreaudio-encoder: Set compiler flag for mingw before adding resource file
  plugins/coreaudio-encoder/CMakeLists.txt
Labels: Bug Fix, Windows
