Repository obsproject/obs-studio, pull requests merged in 2020-09, with the labels that each got.

#3386 Vulkan instance fallback, and uninitialized member fix
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3393 UI: Fix source ref bug causing crash on exit
  UI/qt-wrappers.cpp
Labels: Bug Fix, Seeking Testers

#3383 UI: Fix compiler warning about needing parenthesis
  UI/window-basic-main.cpp
Labels: Code Cleanup

#3394 UI: Fix memory leak when dropping files
  UI/window-basic-main-dropfiles.cpp
Labels: Bug Fix

#3397 UI: Fix rec time left not showing in stats
  UI/window-basic-stats.cpp
Labels: Bug Fix

#3377 UI: Don't save invalid colors via Source Toolbar (Freetype 2 Source)
  UI/context-bar-controls.cpp
Labels: Bug Fix

#3405 UI: Refine context bar
  UI/forms/OBSBasic.ui
  UI/forms/source-toolbar/browser-source-toolbar.ui
  UI/forms/source-toolbar/color-source-toolbar.ui
  UI/forms/source-toolbar/device-select-toolbar.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
  UI/forms/source-toolbar/image-source-toolbar.ui
  UI/forms/source-toolbar/media-controls.ui
  UI/forms/source-toolbar/text-source-toolbar.ui
Labels: Enhancement

#3422 UI: Allow adjusting media slider with arrow buttons
  UI/media-controls.cpp
  UI/media-controls.hpp
  UI/media-slider.cpp
  UI/media-slider.hpp
Labels: Bug Fix

#3404 UI: Set restart state when there is no media
  UI/media-controls.cpp
Labels: Bug Fix

#3425 UI: Ensure tray icon is themed in all cases
  UI/window-basic-main.cpp
Labels: Bug Fix

#3400 UI: Fix studio mode load bug
  UI/window-basic-main.cpp
Labels: Bug Fix

#3431 UI: Remove duplicate media timer code
  UI/media-controls.cpp
Labels: Code Cleanup

#3432 UI: Fix vcam button not changing colors when checked
  UI/data/themes/Rachni.qss
Labels: Bug Fix

#3398 UI: Fix scene tree event handling
  UI/scene-tree.cpp
Labels: Bug Fix

#3433 deps/media-playback: Fix fast-forward after reset
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#2838 rtmp-services: Add SHOWROOM
  plugins/rtmp-services/CMakeLists.txt
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
  plugins/rtmp-services/rtmp-services-main.c
  plugins/rtmp-services/showroom.c
  plugins/rtmp-services/showroom.h
Labels: Enhancement, Services

#3441 CI: Fix Azure macOS pipeline to use new build script
  CI/full-build-macos.sh
  azure-pipelines.yml
Labels: Seeking Testers

#3439 obs-ffmpeg: fix crash with rawvideo
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix

#3438 UI: Fix recording check when using url output
  UI/window-basic-main.cpp
Labels: Bug Fix

#3451 UI:Fix crash on log upload
  UI/window-basic-main.cpp
Labels: Bug Fix

#3468 obs-scripting: Fix script_path() python memory corruption
  deps/obs-scripting/obs-scripting-python.c
Labels: Bug Fix

#3429 linux-v4l2: Fix boolean and menu control types
  plugins/linux-v4l2/v4l2-controls.c
Labels: Bug Fix

#3482 rtmp-services: Added Mux to services.json
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3473 win-dshow: Set current working directory in VirtualCam scripts
  plugins/win-dshow/virtualcam-install.bat.in
  plugins/win-dshow/virtualcam-uninstall.bat.in
Labels: Bug Fix

#3388 mac-capture: show actual windows in Window Capture sources
  plugins/mac-capture/window-utils.h
  plugins/mac-capture/window-utils.m
Labels: Bug Fix

#3488 frontend-tools: Free xdisplay on Linux auto scene switcher
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-osx.mm
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-win.cpp
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.hpp
Labels: Bug Fix

#3490 deps/media-playback: Fix current time at not standard speed
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#3496 rtmp-services: Update Vaughn Live / iNSTAGIB & Breakers
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3507 v4l2-linux: Fix nv12 linesize
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix

#3508 v4l2-linux: Fix fourcc order
  plugins/linux-v4l2/v4l2-input.c
Labels: Code Cleanup

#3509 UI: Always parse log contents for Log Viewer as UTF-8
  UI/log-viewer.cpp
Labels: Bug Fix
