Repository obsproject/obs-studio, pull requests merged in 2020-02, with the labels that each got.

#2357 obs-outputs: Various librtmp mbedtls fixes
  CI/install-dependencies-linux.sh
  plugins/obs-outputs/librtmp/dh.h
  plugins/obs-outputs/librtmp/handshake.h
  plugins/obs-outputs/librtmp/hashswf.c
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/librtmp/rtmp.h
  plugins/obs-outputs/librtmp/rtmp_sys.h
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix, Seeking Testers

#2365 obs-ffmpeg, vlc-video: Add media control support
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
  plugins/vlc-video/vlc-video-plugin.c
  plugins/vlc-video/vlc-video-plugin.h
  plugins/vlc-video/vlc-video-source.c
Labels: Enhancement

#2369 UI: Always prompt when updates are available
  UI/win-update/win-update.cpp
Labels: Bug Fix, Code Cleanup

#2370 win-capture: Faster display / window capture updates
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#2375 UI: Fix transitions being disabled
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#2371 UI: Show source icons in Advanced Audio Properties
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
  UI/window-basic-main.cpp
Labels: Enhancement

#2373 UI: Use absolute path for portable mode multi-instance check
  UI/platform-windows.cpp
Labels: Bug Fix

#2264 Fix OpenGL thread-safety on Mac to use latest Xcode
  libobs-opengl/gl-cocoa.m
  libobs-opengl/gl-helpers.h
  libobs-opengl/gl-subsystem.c
  libobs-opengl/gl-subsystem.h
  libobs-opengl/gl-windows.c
  libobs-opengl/gl-x11.c
Labels: Bug Fix

#2382 libobs: Fix Mac linker error
  libobs/graphics/half.h
Labels: Bug Fix

#2385 libobs: fix obs_sceneitem_group_XXX_item API
  libobs/obs-scene.c
Labels: Bug Fix, Code Cleanup

#2386 UI: Add Chromium-compatible NSApplication subclass
  UI/obs-app.cpp
  UI/platform-osx.mm
Labels: Bug Fix, Enhancement

#2397 rtmp-services: Uncanny.gg
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2394 obs-ffmpeg: Use callbacks when starting/ending
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#2402 UI: Allow resizing docks when hotkeys are disabled
  UI/obs-app.cpp
Labels: Bug Fix

#2257 libobs: Don't corrupt obs_properties in ..._remove_by_name
  libobs/obs-properties.c
Labels: Bug Fix

#1956 UI: Add advanced scene collection importer
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/forms/OBSImporter.ui
  UI/importers/classic.cpp
  UI/importers/importers.cpp
  UI/importers/importers.hpp
  UI/importers/sl.cpp
  UI/importers/studio.cpp
  UI/importers/xsplit.cpp
  UI/window-basic-main-scene-collections.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
  UI/window-importer.cpp
  UI/window-importer.hpp
Labels: Enhancement, Request for Comments, Seeking Testers

#2403 UI: Use OBS dock menu instead of Qt dock context menu
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#2409 UI: Add ability to lock volume
  UI/data/locale/en-US.ini
  UI/volume-control.cpp
  UI/volume-control.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#2412 decklink: Fix crash when no outputs are available
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix

#2408 UI: Restart program when audio/locale changed
  UI/data/locale/en-US.ini
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#2413 rtmp-services: Add Whalebone.tv
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2419 obs-scripting: Update text source IDs
  UI/frontend-plugins/frontend-tools/data/scripts/countdown.lua
  UI/frontend-plugins/frontend-tools/data/scripts/url-text.py
Labels: Bug Fix

#2401 deps/media-playback: Fix buffering/sync issues
  deps/media-playback/media-playback/media.c
  deps/media-playback/media-playback/media.h
Labels: Bug Fix, Seeking Testers

#2407 mac-vth264: Manually mark priority bits for VideoToolbox frames
  plugins/mac-vth264/encoder.c
Labels: Bug Fix

#2417 Acri theme fixes: Tables
  UI/data/themes/Acri.qss
  UI/window-extra-browsers.cpp
Labels: Bug Fix

#2420 UI: Fix Import Profile in Portable Mode
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix

#2208 Windows Graphics Capture support
  CI/install-script-win.cmd
  CMakeLists.txt
  azure-pipelines.yml
  libobs-d3d11/d3d11-rebuild.cpp
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-winrt/CMakeLists.txt
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
  libobs/obs-source.c
  libobs/obs-video.c
  libobs/util/windows/ComPtr.hpp
  plugins/win-capture/data/locale/en-US.ini
  plugins/win-capture/window-capture.c
  plugins/win-capture/window-helpers.c
  plugins/win-capture/window-helpers.h
Labels: Enhancement, Request for Comments, Seeking Testers, Windows, Work In Progress

#2422 CI: Remove unused Linux script
  CI/install-dependencies-linux-ubuntu16.sh
Labels: Code Cleanup

#2423 UI: Return 0 when launch cancelled or failed
  UI/obs-app.cpp
Labels: Bug Fix

#2428 UI: Fix compilation warning re signed/unsigned
  UI/window-basic-adv-audio.cpp
Labels: Bug Fix

#2429 libobs: Pump graphics loop one final time for cleanup
  libobs/obs-video.c
Labels: Bug Fix

#2431 UI: Make t-bar smaller
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
Labels: Code Cleanup

#2433 WGC improvements: context-specific options and client area toggle
  libobs-winrt/CMakeLists.txt
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  plugins/win-capture/data/locale/en-US.ini
  plugins/win-capture/window-capture.c
Labels: Bug Fix, Enhancement

#2427 libobs/util: Retry pipe writes to avoid spurious failures on short write.
  libobs/util/pipe-posix.c
Labels: Bug Fix

#1759 obs-browser: Enable Linux support
  CI/before-script-linux.sh
  CI/install-dependencies-linux.sh
  UI/obs-app.cpp
  UI/window-basic-main.cpp
  plugins/CMakeLists.txt
Labels: Enhancement, Linux, Seeking Testers, Work In Progress

#2435 libobs-d3d11: Enable NV12 for Intel on newer platforms
  libobs-d3d11/CMakeLists.txt
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/intel-nv12-support.hpp
Labels: Enhancement

#2440 Decklink: Fix crash when no device selected
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix

#2438 UI: Remove dock margins
  UI/forms/OBSBasic.ui
Labels: Enhancement

#2439 frontend-plugins: Refactor Decklink out UI
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.h
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.h
  UI/frontend-plugins/decklink-output-ui/forms/output.ui
Labels: Code Cleanup, Enhancement

#2443 CI: Fix case of PlugIns directory
  CI/install/osx/packageApp.sh
Labels: Bug Fix, macOS

#1871 win-capture: Fix hook collisions with multiple game captures
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
Labels: Bug Fix, Enhancement

#2156 Vulkan Game Capture
  UI/win-update/updater/CMakeLists.txt
  UI/win-update/updater/init-hook-files.c
  UI/win-update/updater/updater.cpp
  cmake/Modules/FindVulkan.cmake
  plugins/win-capture/CMakeLists.txt
  plugins/win-capture/game-capture-file-init.c
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook-info.h
  plugins/win-capture/graphics-hook-ver.h
  plugins/win-capture/graphics-hook/CMakeLists.txt
  plugins/win-capture/graphics-hook/graphics-hook-config.h.in
  plugins/win-capture/graphics-hook/graphics-hook.c
  plugins/win-capture/graphics-hook/graphics-hook.h
  plugins/win-capture/graphics-hook/graphics-hook.rc
  plugins/win-capture/graphics-hook/obs-vulkan32.json
  plugins/win-capture/graphics-hook/obs-vulkan64.json
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
  plugins/win-capture/inject-helper/inject-helper.c
  plugins/win-capture/plugin-main.c
Labels: Enhancement, Seeking Testers, Work In Progress
