Repository obsproject/obs-studio, pull requests merged in 2020-11, with the labels that each got.

#3677 vlc-video: Use case insensitive compare for valid extension check
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#3675 Don't update the source context bar when it is hidden
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#3671 linux-v4l2: Hide modinfo from terminal
  plugins/linux-v4l2/linux-v4l2.c
Labels: Code Cleanup

#3679 linux-v4l2: avoid OOB write
  plugins/linux-v4l2/v4l2-output.c
Labels: Code Cleanup

#2857 decklink: Add ability to ingest/embed cea 708 captions
  UI/frontend-plugins/CMakeLists.txt
  UI/frontend-plugins/decklink-captions/CMakeLists.txt
  UI/frontend-plugins/decklink-captions/data/.keepme
  UI/frontend-plugins/decklink-captions/decklink-captions.cpp
  UI/frontend-plugins/decklink-captions/decklink-captions.h
  UI/frontend-plugins/decklink-captions/forms/captions.ui
  libobs/CMakeLists.txt
  libobs/obs-internal.h
  libobs/obs-output.c
  libobs/obs-source.c
  libobs/obs-source.h
  libobs/obs.h
  libobs/util/bitstream.c
  libobs/util/bitstream.h
  plugins/decklink/OBSVideoFrame.cpp
  plugins/decklink/OBSVideoFrame.h
  plugins/decklink/decklink-device-instance.cpp
  plugins/decklink/decklink-device-instance.hpp
  plugins/decklink/decklink-source.cpp
  plugins/decklink/linux/CMakeLists.txt
  plugins/decklink/mac/CMakeLists.txt
  plugins/decklink/platform.hpp
  plugins/decklink/win/CMakeLists.txt
  plugins/decklink/win/platform.cpp
  test/cmocka/CMakeLists.txt
  test/cmocka/test_bitstream.c
Labels: Enhancement

#3687 Remove BUILD_CAPTIONS build flag
  .github/workflows/main.yml
  CI/before-script-linux.sh
  CI/before-script-osx.sh
  CI/full-build-macos.sh
  CI/install-script-win.cmd
  CMakeLists.txt
  UI/frontend-plugins/frontend-tools/CMakeLists.txt
  UI/frontend-plugins/frontend-tools/frontend-tools-config.h.in
  UI/frontend-plugins/frontend-tools/frontend-tools.c
  deps/CMakeLists.txt
  deps/obs-scripting/CMakeLists.txt
  deps/obs-scripting/obs-scripting-config.h.in
  libobs/CMakeLists.txt
  libobs/obs-output.c
  libobs/obs.h
  libobs/obsconfig.h.in
Labels: Bug Fix

#3690 CI: Remove caching of obs-deps for Github CI
  .github/workflows/main.yml
Labels: Code Cleanup

#3691 decklink: Clean up warnings introduced by caption code
  UI/frontend-plugins/decklink-captions/decklink-captions.cpp
  libobs/obs-output.c
  plugins/decklink/OBSVideoFrame.cpp
  plugins/decklink/OBSVideoFrame.h
  plugins/decklink/decklink-device-instance.cpp
  test/cmocka/test_serializer.c
Labels: Code Cleanup

#3711 rtmp-services: Increase twitch audio bitrate
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3714 Add OpenBSD support
  UI/obs-app.cpp
  libobs/obs-nix.c
  libobs/util/platform-nix.c
  libobs/util/profiler.c
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Enhancement

#3715 Add sndio support
  .github/workflows/main.yml
  cmake/Modules/FindSndio.cmake
  plugins/CMakeLists.txt
  plugins/sndio/CMakeLists.txt
  plugins/sndio/data/locale/en-US.ini
  plugins/sndio/sndio-input.c
  plugins/sndio/sndio-input.h
  plugins/sndio/sndio.c
Labels: Enhancement

#3700 win-capture: Fix our own Vulkan spec violation
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#3670 UI: Detect other instances of obs on FreeBSD
  UI/CMakeLists.txt
  UI/obs-app.cpp
  UI/platform-x11.cpp
  UI/platform.hpp
Labels: Bug Fix

#3668 mac-virtualcam: Update locales
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Code Cleanup

#3737 obs-ffmpeg: Add error detection to ffmpeg-mux network streams
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix

#3736 win-capture: Clean up remaining /W4 warnings
  plugins/win-capture/app-helpers.c
  plugins/win-capture/inject-library.c
  plugins/win-capture/load-graphics-offsets.c
  plugins/win-capture/plugin-main.c
  plugins/win-capture/window-helpers.c
Labels: Bug Fix

#3741 UI: fix build on older FreeBSD versions
  UI/platform-x11.cpp
Labels: Bug Fix

#3742 mac-virtualcam: Remove old test card
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/dal-plugin/Stream.mm
  plugins/mac-virtualcam/src/dal-plugin/TestCard.h
  plugins/mac-virtualcam/src/dal-plugin/TestCard.mm
Labels: Code Cleanup

#3758 mac-virtualcam: Fix global namespace issues in DAL plugin
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/dal-plugin/Info.plist
  plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALObjectStore.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALObjectStore.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugin.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugin.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPluginMain.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Labels: Bug Fix, Seeking Testers, macOS

#3761 obs-outputs: Log unhandled status description as debug level
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix

#3762 UI: Set default source toolbar visibility to true & simplify its setting initialisation
  UI/obs-app.cpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#3759 frontend-tools: Don't give every loaded filter focus
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
Labels: Bug Fix

#3760 UI: Fix Save Replay button staying highlighted
  UI/window-basic-main.cpp
Labels: Bug Fix

#3756 libobs: Allow wrapping D3D11 object with gs_texture_t
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-d3d11/d3d11-texture2d.cpp
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
Labels: Enhancement

#3766 UI: Various screen reader fixes
  UI/adv-audio-control.cpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicFilters.ui
  UI/hotkey-edit.cpp
  UI/obs-app.cpp
  UI/slider-ignorewheel.cpp
  UI/slider-ignorewheel.hpp
  UI/source-tree.cpp
  UI/volume-control.cpp
  UI/window-basic-settings.cpp
Labels: Accessibility, Bug Fix

#3765 Improve scene collection importer
  UI/window-importer.cpp
Labels: Bug Fix
