Repository obsproject/obs-studio, pull requests merged in 2020-04, with the labels that each got.

#2620 Decklink: Fix crash when no matching device
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix

#2591 win-capture: Fix crash if GPU can't Vulkan capture
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#2649 UI: Don't stretch server field in Qt 5.14
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#2679 UI: Fix missing includes
  UI/properties-view.moc.hpp
  UI/source-tree.hpp
  UI/window-basic-stats.hpp
Labels: Code Cleanup

#2571 rtmp-services: Update Bongacams servers and settings
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2639 UI: Require selected source for Transform shortcut
  UI/window-basic-main.cpp
Labels: Bug Fix

#2537 UI: Don't open Studio Mode's "Program" label in a window
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#2641 obs-outputs: Fix warnings WITH_RTMPS=OFF
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Code Cleanup

#2598 rtmp-services: Fix memory leak when updating rtmp-custom-service.
  plugins/rtmp-services/rtmp-custom.c
Labels: Bug Fix

#2682 rtmp-services: Add niconico
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2109 Encoder error feedback
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-output.c
  libobs/obs.h
  plugins/obs-ffmpeg/jim-nvenc-helpers.c
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/jim-nvenc.h
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Enhancement, Request for Comments

#2697 rtmp-services: Add wasd.tv
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2667 linux-v4l2: Fix build with Clang 10.0
  plugins/linux-v4l2/v4l2-controls.c
Labels: Bug Fix

#2710 CI: Add qt5-xml package for FreeBSD build task
  .cirrus.yml
Labels: Bug Fix

#2745 rtmp-services: Update ChathostessModels service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2739 libobs: Don't save removed sources
  libobs/obs.c
Labels: Bug Fix

#2700 lib-ffmpeg: Fix media source not closing file when inactive
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#1786 obs-qsv: Enable QSV texture-based encoding
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/common_directx11.cpp
  plugins/obs-qsv11/common_utils.h
  plugins/obs-qsv11/obs-qsv11-plugin-main.c
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#2746 UI: Remove all scenes in ClearSceneData
  UI/window-basic-main.cpp
Labels: Bug Fix

#2648 UI: Fix previewLabel styling
  UI/window-basic-main.cpp
Labels: Bug Fix

#2723 docs/sphinx: Add Property Grouping
  docs/sphinx/reference-properties.rst
Labels: Documentation

#2658 plugins: Build ALSA plugin for FreeBSD
  plugins/CMakeLists.txt
Labels: Enhancement

#2732 UI: Adjust a few margins
  UI/forms/OBSBasic.ui
Labels: Enhancement

#2720 UI: Add status icons for recording and streaming
  UI/forms/images/recording-active.svg
  UI/forms/images/recording-inactive.svg
  UI/forms/images/recording-pause-inactive.svg
  UI/forms/images/recording-pause.svg
  UI/forms/images/streaming-active.svg
  UI/forms/images/streaming-inactive.svg
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-basic-status-bar.cpp
  UI/window-basic-status-bar.hpp
Labels: Enhancement

#1944 CMake: Build Windows modules with file descriptors
  CMakeLists.txt
  UI/frontend-plugins/decklink-output-ui/CMakeLists.txt
  UI/frontend-plugins/frontend-tools/CMakeLists.txt
  UI/obs-frontend-api/CMakeLists.txt
  cmake/winrc/obs-module.rc.in
  deps/glad/CMakeLists.txt
  deps/obs-scripting/CMakeLists.txt
  deps/w32-pthreads/CMakeLists.txt
  libobs-d3d11/CMakeLists.txt
  libobs-opengl/CMakeLists.txt
  libobs/CMakeLists.txt
  plugins/coreaudio-encoder/CMakeLists.txt
  plugins/decklink/win/CMakeLists.txt
  plugins/image-source/CMakeLists.txt
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-outputs/CMakeLists.txt
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-text/CMakeLists.txt
  plugins/obs-transitions/CMakeLists.txt
  plugins/obs-x264/CMakeLists.txt
  plugins/rtmp-services/CMakeLists.txt
  plugins/text-freetype2/CMakeLists.txt
  plugins/vlc-video/CMakeLists.txt
  plugins/win-dshow/CMakeLists.txt
  plugins/win-ivcam/CMakeLists.txt
  plugins/win-mf/CMakeLists.txt
  plugins/win-wasapi/CMakeLists.txt
Labels: Enhancement, Request for Comments

#2656 mac-capture: Use window id to identify windows on MacOS
  plugins/mac-capture/window-utils.h
  plugins/mac-capture/window-utils.m
Labels: Bug Fix

#2753 UI: Remove unnecessary global variables
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#2749 libobs-opengl: Fix viewport flip
  libobs-opengl/gl-subsystem.c
Labels: Bug Fix

#2770 rtmp-services: Change Stripchat streaming service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2793 rtmp-services: Add Nimo TV
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2833 obs-ffmpeg: Update error message in process_packet
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Code Cleanup
