Repository obsproject/obs-studio, pull requests merged in 2020-10, with the labels that each got.

#3536 UI: Improve macOS performance by disabling Qt colourspace conversion
  UI/platform-osx.mm
  UI/platform.hpp
  UI/window-basic-main.cpp
Labels: Enhancement

#3534 UI: Implement exit on CTRL + Q for linux
  UI/window-basic-main.cpp
Labels: Enhancement

#3520 rtmp-services: Set actual integer value of bframes in services
  plugins/rtmp-services/rtmp-common.c
Labels: Bug Fix

#3539 UI: Skip ChromeOS test on FreeBSD
  UI/obs-app.cpp
Labels: Code Cleanup

#3516 CI: Use tag number only for macOS plist when triggered by version tag
  .github/workflows/main.yml
Labels: Bug Fix, macOS

#3530 UI: Fix tab order for controls dock
  UI/window-basic-main.cpp
Labels: Accessibility, Bug Fix

#3533 Remove weabook.live from services.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3544 Update FreeBSD CI for package name change
  .cirrus.yml
Labels: Bug Fix

#3477 win-capture: Fix mask handling on some color cursors
  plugins/win-capture/cursor-capture.c
Labels: Bug Fix

#3461 obs-ffmpeg: Signal a remote disconnect for network streams from ffmpeg-mux
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Labels: Bug Fix, Enhancement

#3460 obs-ffmpeg: Add error detection to ffmpeg-mux
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix

#3549 win-capture: Violate Vulkan spec for compatibility
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix, Seeking Testers

#3550 libobs-winrt: Use native cursor draw for WGC
  libobs-winrt/winrt-capture.cpp
Labels: Bug Fix, Seeking Testers

#3553 rtmp-services: Update AfreecaTV
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3568 UI: After source rename, set focus back to label
  UI/source-tree.cpp
Labels: Bug Fix

#3594 Docs: Fix Frontend Finish Loading event
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation

#3574 UI: Prevent disabling replay buffer if it's active
  UI/window-basic-settings.cpp
Labels: Bug Fix

#3592 UI: Add the replay buffer saved event to the frontend api
  UI/obs-frontend-api/obs-frontend-api.h
  UI/window-basic-main.cpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#3114 Add HLS streaming output
  UI/data/locale/en-US.ini
  UI/forms/AutoConfigStreamPage.ui
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.hpp
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-mux/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.h
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.h
  plugins/obs-ffmpeg/obs-ffmpeg.c
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
  plugins/rtmp-services/rtmp-format-ver.h
Labels: Enhancement, Seeking Testers

#3447 win-capture: Fix D3D leaks on swap chain release
  plugins/win-capture/get-graphics-offsets/dxgi-offsets.cpp
  plugins/win-capture/get-graphics-offsets/get-graphics-offsets.c
  plugins/win-capture/get-graphics-offsets/get-graphics-offsets.h
  plugins/win-capture/graphics-hook-info.h
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
  plugins/win-capture/load-graphics-offsets.c
Labels: Bug Fix

#3599 UI: Fix text clipping on non-English locales in certain locations
  UI/adv-audio-control.cpp
Labels: Bug Fix

#3604 UI: Keep showing time label when paused
  UI/window-basic-status-bar.cpp
Labels: Enhancement

#2239 UI, libobs: Add ability to copy/paste single filter
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  libobs/obs-source.c
  libobs/obs.h
Labels: Enhancement, Seeking Testers

#3616 UI: Apply minimum width to Stats fields
  UI/window-basic-stats.cpp
Labels: Bug Fix

#3617 UI: Update Twitch Get Stream Key link
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#3618 obs-filter: Fix potential symbol clashing on Linux (RNNoise)
  plugins/obs-filters/CMakeLists.txt
Labels: Bug Fix

#3586 UI: Add duplicate filter
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
Labels: Enhancement

#3558 UI: Detect other instances of OBS on MacOS
  UI/obs-app.cpp
  UI/platform-osx.mm
  UI/platform.hpp
Labels: Bug Fix, macOS

#3548 linux-alsa: Support more device formats
  plugins/linux-alsa/alsa-input.c
Labels: Bug Fix

#3630 UI: Fix replay buffer saved event in advanced mode
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#3621 CI: Fix Windows artifact issues and housekeeping
  .github/workflows/main.yml
  CI/full-build-macos.sh
  CI/scripts/macos/app/Info.plist
  CI/scripts/macos/packageApp.sh
  CI/scripts/macos/prepareApp.sh
Labels: Seeking Testers

#3407 UI: Report detailed output errors for Replay Buffer
  UI/window-basic-main-outputs.cpp
Labels: Enhancement

#3365 libobs: Return default obj and array rather than current
  libobs/obs-data.c
Labels: Bug Fix

#3381 obs-transitions: Expose hardware decoding for Stingers, enable by default
  plugins/obs-transitions/data/locale/en-US.ini
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement

#3649 UI: Run Autoconfig Wizard on New Profile Creation
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/forms/NameDialog.ui
  UI/obs-app.cpp
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-namedialog.cpp
  UI/window-namedialog.hpp
Labels: Enhancement

#3662 obs-ffmpeg: Add MX350 to NVENC blacklist
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Bug Fix

#3182 linux-v4l2: Add virtual camera output
  .github/workflows/main.yml
  CI/install-dependencies-linux.sh
  plugins/linux-v4l2/CMakeLists.txt
  plugins/linux-v4l2/linux-v4l2.c
  plugins/linux-v4l2/v4l2-output.c
Labels: Enhancement

#3665 rtmp-services: Add Viloud service
  plugins/rtmp-services/data/services.json
Labels: Services

#3657 rtmp-services: Add YouTube RTMPS beta service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3654 UI: Detect other instances of obs on Linux
  UI/obs-app.cpp
  UI/platform-x11.cpp
  UI/platform.hpp
Labels: Enhancement, Linux

#3083 UI: Enable sps/pps (video headers) repetition (for srt/mpegts)
  UI/window-basic-main-outputs.cpp
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-x264/obs-x264.c
  plugins/rtmp-services/rtmp-custom.c
Labels: Bug Fix, Enhancement, Seeking Testers

#3492 mac-virtualcam: Add virtual cam output to OBS as bundled plugin on macOS
  .github/workflows/main.yml
  CI/full-build-macos.sh
  plugins/CMakeLists.txt
  plugins/mac-virtualcam/CMakeLists.txt
  plugins/mac-virtualcam/data/locale/en-US.ini
  plugins/mac-virtualcam/src/common/MachProtocol.h
  plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.h
  plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.mm
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/dal-plugin/Defines.h
  plugins/mac-virtualcam/src/dal-plugin/Device.h
  plugins/mac-virtualcam/src/dal-plugin/Device.mm
  plugins/mac-virtualcam/src/dal-plugin/Info.plist
  plugins/mac-virtualcam/src/dal-plugin/Logging.h
  plugins/mac-virtualcam/src/dal-plugin/MachClient.h
  plugins/mac-virtualcam/src/dal-plugin/MachClient.mm
  plugins/mac-virtualcam/src/dal-plugin/ObjectStore.h
  plugins/mac-virtualcam/src/dal-plugin/ObjectStore.mm
  plugins/mac-virtualcam/src/dal-plugin/PlugIn.h
  plugins/mac-virtualcam/src/dal-plugin/PlugIn.mm
  plugins/mac-virtualcam/src/dal-plugin/PlugInInterface.h
  plugins/mac-virtualcam/src/dal-plugin/PlugInInterface.mm
  plugins/mac-virtualcam/src/dal-plugin/PlugInMain.mm
  plugins/mac-virtualcam/src/dal-plugin/Stream.h
  plugins/mac-virtualcam/src/dal-plugin/Stream.mm
  plugins/mac-virtualcam/src/dal-plugin/TestCard.h
  plugins/mac-virtualcam/src/dal-plugin/TestCard.mm
  plugins/mac-virtualcam/src/dal-plugin/placeholder.png
  plugins/mac-virtualcam/src/obs-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/obs-plugin/Defines.h
  plugins/mac-virtualcam/src/obs-plugin/MachServer.h
  plugins/mac-virtualcam/src/obs-plugin/MachServer.mm
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Enhancement, Seeking Testers, macOS

#3666 UI: Disable stream simple output encoder when output active
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Bug Fix
