Repository obsproject/obs-studio, pull requests merged in 2020-01, with the labels that each got.

#2284 Remove volume render targets
  libobs-d3d11/d3d11-rebuild.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-d3d11/d3d11-texture3d.cpp
  libobs-opengl/gl-texture3d.c
Labels: Code Cleanup

#2282 Supply Windows manifest file (incl. compatibility info)
  .gitignore
  UI/CMakeLists.txt
  UI/obs.manifest
Labels: Bug Fix, Seeking Testers

#2289 obs-ffmpeg: Fix VC++ warnings
  plugins/obs-ffmpeg/ffmpeg-encoded-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix

#2295 libobs-opengl: Fix volume texture leak
  libobs-opengl/gl-subsystem.c
  libobs-opengl/gl-texture3d.c
Labels: Bug Fix

#2286 obs-scripting: Add Python functions for frontend events
  deps/obs-scripting/obs-scripting-python-frontend.c
Labels: Enhancement

#2287 CMake: Fix build on ppc64
  CMakeLists.txt
  deps/media-playback/CMakeLists.txt
  libobs/CMakeLists.txt
Labels: Bug Fix, Incomplete

#2303 rtmp-services: Update/remove services
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2304 obs-outputs: Fix mbedtls use of deprecated functions
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/librtmp/rtmp_sys.h
Labels: Code Cleanup

#2307 docs/sphinx: Fix obs_property_list_item_disable entry
  docs/sphinx/reference-properties.rst
Labels: Documentation

#2305 UI: Display aspect ratios in video settings
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Enhancement

#2312 UI: Fix audio restart message not hiding
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Bug Fix

#2314 librtmp: Allow partial success for mbedtls
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix, Linux, Seeking Testers

#2273 Support for URL/web link drag and drop
  UI/data/locale/en-US.ini
  UI/window-basic-main-dropfiles.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Seeking Testers

#2291 Cube LUT file support
  libobs-opengl/gl-subsystem.h
  libobs/CMakeLists.txt
  libobs/graphics/half.h
  plugins/obs-filters/color-grade-filter.c
  plugins/obs-filters/data/LUTs/grayscale.cube
  plugins/obs-filters/data/LUTs/original.cube
Labels: Enhancement, Seeking Testers

#2319 win-dshow: Fix upside-down RGB DIBs
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix

#2256 UI: Upgrade stream key link to button in Wizard
  UI/forms/AutoConfigStreamPage.ui
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#2285 obs-plugins: Change defaults of various plugins
  plugins/image-source/color-source.c
  plugins/image-source/image-source.c
  plugins/obs-text/gdiplus/obs-text.cpp
  plugins/text-freetype2/text-freetype2.c
  plugins/text-freetype2/text-freetype2.h
Labels: Code Cleanup, Enhancement, Seeking Testers

#2317 UI: Support URL/web DnD in linuxbrowser
  UI/window-basic-main-dropfiles.cpp
Labels: Enhancement, Linux

#2318 UI: Fix studio mode transition bugs
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, Code Cleanup

#2324 rtmp-services: Update to the SermonAudio entry
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2328 audio-monitoring: Fix Pulse Audio crash
  libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
Labels: Bug Fix

#2329 docs/sphinx: Add obs_group_from_source and obs_enum_scenes
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-scenes.rst
Labels: Documentation

#2332 libobs: Rename DEPRECATED to OBS_DEPRECATED
  libobs/obs-encoder.c
  libobs/obs-properties.h
  libobs/obs.c
  libobs/obs.h
  libobs/util/c99defs.h
Labels: Bug Fix, Code Cleanup

#2333 UI: Fix Qt 5.14 deprecation warnings
  UI/frontend-plugins/frontend-tools/output-timer.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-stats.cpp
  UI/window-basic-status-bar.cpp
Labels: Code Cleanup

#2327 libobs: Add VIDEO_CS_SRGB enum value
  libobs/media-io/video-io.h
Labels: Enhancement

#2338 rtmp-services: Add Uscreen
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#2339 UI: Fix t-bar not working with transition override
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#2336 libobs, obs-x264: Fix compiler warnings
  libobs/media-io/video-io.h
  libobs/media-io/video-scaler-ffmpeg.c
  plugins/obs-x264/obs-x264.c
Labels: Code Cleanup

#2341 Add support for MIPS architecture
  CMakeLists.txt
  deps/media-playback/CMakeLists.txt
  libobs/CMakeLists.txt
  libobs/obsconfig.h.in
  libobs/util/simde/check.h
  libobs/util/simde/hedley.h
  libobs/util/simde/mmx.h
  libobs/util/simde/simde-arch.h
  libobs/util/simde/simde-common.h
  libobs/util/simde/sse.h
  libobs/util/simde/sse2.h
  libobs/util/sse-intrin.h
  plugins/linux-v4l2/v4l2-controls.c
Labels: Enhancement

#2342 UI: Fix aspect ratio triggering settings change
  UI/window-basic-settings.cpp
Labels: Bug Fix

#2351 Set stinger media source's name
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement

#2345 UI: Fix crash when entering large resolutions
  UI/window-basic-settings.cpp
Labels: Bug Fix

#2359 UI: Fix transtions not enabled
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#2358 UI: Use input validator on resolution line edit
  UI/window-basic-settings.cpp
Labels: Bug Fix

#2300 media-playback: Add functions to pause/seek media source
  deps/media-playback/media-playback/media.c
  deps/media-playback/media-playback/media.h
Labels: Enhancement

#2274 libobs: Add media control support to backend
  libobs/obs-source.c
  libobs/obs-source.h
  libobs/obs.h
Labels: Enhancement

#2366 obs-transitions: Halve stinger padding to 250ms
  plugins/obs-transitions/transition-stinger.c
Labels: Bug Fix
