Repository obsproject/obs-studio, pull requests merged in 2020-05, with the labels that each got.

#2835 libobs: Add Windows 10 release version to crash log
  libobs/obs-win-crash-handler.c
Labels: Code Cleanup

#2817 obs-scripting: Expose platform functions to scripts
  deps/obs-scripting/obslua/obslua.i
  deps/obs-scripting/obspython/obspython.i
Labels: Enhancement

#2814 obs-plugins: Check if sources are showing for media hotkeys
  plugins/image-source/obs-slideshow.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix, Code Cleanup

#2831 libobs: Additionally use SetThreadDescription if possible
  libobs/util/threading-windows.c
Labels: Enhancement

#2818 rtmp-services: Add Xlovecam.com streaming service
  plugins/rtmp-services/data/services.json
Labels: Services

#2789 vlc-video: Add procedure to receive media metadata
  plugins/vlc-video/vlc-video-plugin.c
  plugins/vlc-video/vlc-video-plugin.h
  plugins/vlc-video/vlc-video-source.c
Labels: Enhancement

#2738 libobs: Don't allow duplicating scene sources
  libobs/obs-scene.c
  libobs/obs-source.c
Labels: Bug Fix

#2880 libobs-winrt: win-capture: Detect GraphicsCaptureItem closure
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#2877 CI: Update Github Actions with caching and macOS improvements
  .github/workflows/main.yml
  CI/scripts/macos/Brewfile
  CI/scripts/macos/app/dylibbundler
  CI/scripts/macos/package/dylibBundler
  CI/scripts/macos/package/settings.json
  CI/scripts/macos/package/settings.json.template
Labels: Code Cleanup

#2870 obs-ffmpeg: Fix AVFrame handling in FFmpeg output
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix

#2712 plugins: Add oss-audio input support
  cmake/Modules/FindOSS.cmake
  plugins/CMakeLists.txt
  plugins/oss-audio/CMakeLists.txt
  plugins/oss-audio/oss-audio.c
  plugins/oss-audio/oss-input.c
  plugins/oss-audio/oss-platform.h.in
Labels: Enhancement

#2930 libobs: Return target instead of current in calc_torquef
  libobs/graphics/math-extra.c
Labels: Bug Fix

#2929 win-capture: Reset WGC fail flag for new window
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#2947 UI: Hide script tabs if no python settings
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/frontend-plugins/frontend-tools/scripts.cpp
Labels: Code Cleanup

#2665 obs-ffmpeg: Fix srt output
  UI/window-basic-main-outputs.cpp
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-encoded-output.c
  plugins/obs-ffmpeg/ffmpeg-encoded-output.h
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Bug Fix, Code Cleanup

#2506 Show accurate path in Crash dialog
  UI/obs-app.cpp
Labels: Bug Fix

#2539 UI: Don't clip meters when resizing with no input
  UI/volume-control.cpp
Labels: Bug Fix

#2551 Implement CUBE LUT domain properly, tetrahedral interpolation for 3D LUTs
  libobs-opengl/gl-shaderparser.c
  plugins/obs-filters/color-grade-filter.c
  plugins/obs-filters/data/color_grade_filter.effect
Labels: Bug Fix

#2570 UI: Use standard resolutions with auto-config
  UI/window-basic-auto-config-test.cpp
Labels: Enhancement

#2589 win-capture: Use VkAllocationCallbacks
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix

#2595 Vulkan hook COM clean up, and extension check
  plugins/win-capture/graphics-hook/CMakeLists.txt
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Code Cleanup

#2619 Expose more levels and profiles for FFmpeg VAAPI
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Linux, Seeking Testers

#2637 cmake: Fix warnings and normalize variables/errors
  UI/win-update/updater/CMakeLists.txt
  cmake/Modules/FindLibVLC.cmake
  cmake/Modules/FindLibv4l2.cmake
  cmake/Modules/FindMbedTLS.cmake
  cmake/Modules/FindUDev.cmake
  cmake/Modules/FindXCB.cmake
  cmake/Modules/FindZLIB.cmake
  libobs/CMakeLists.txt
  plugins/linux-v4l2/CMakeLists.txt
  plugins/obs-outputs/CMakeLists.txt
  plugins/vlc-video/CMakeLists.txt
Labels: Code Cleanup

#2908 Fix WGC minimize handling
  libobs-winrt/winrt-capture.cpp
  plugins/win-capture/CMakeLists.txt
  plugins/win-capture/window-helpers.c
Labels: Bug Fix

#2921 win-capture: Fail on unsupported Vulkan formats
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix

#2964 Set up dispatcher queue for WGC stability
  libobs-winrt/CMakeLists.txt
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  libobs-winrt/winrt-dispatch.cpp
  libobs-winrt/winrt-dispatch.h
  libobs/obs-video.c
Labels: Bug Fix

#2967 libobs: Fix potential truncation warnings
  libobs/graphics/graphics.c
Labels: Bug Fix

#2384 media-playback: Unbuffered Media Source
  deps/media-playback/media-playback/media.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#2442 Windows: Taskbar icon & colour
  UI/CMakeLists.txt
  UI/forms/images/active.png
  UI/forms/images/paused.png
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  cmake/Modules/CopyMSVCBins.cmake
Labels: Enhancement, Windows

#2657 libobs: Implement and use better scaling function for 64-bit integers
  UI/window-basic-auto-config-test.cpp
  libobs/CMakeLists.txt
  libobs/audio-monitoring/win32/wasapi-output.c
  libobs/media-io/audio-io.c
  libobs/media-io/audio-io.h
  libobs/media-io/video-io.c
  libobs/obs-audio.c
  libobs/obs-encoder.c
  libobs/obs-output.c
  libobs/obs-scene.c
  libobs/obs-source-transition.c
  libobs/obs-source.c
  libobs/util/util_uint64.h
  plugins/decklink/decklink-device-instance.cpp
  plugins/decklink/decklink-output.cpp
  plugins/linux-alsa/alsa-input.c
  plugins/linux-pulseaudio/pulse-input.c
  plugins/obs-filters/async-delay-filter.c
  plugins/obs-filters/gpu-delay.c
  plugins/win-capture/game-capture.c
  plugins/win-wasapi/win-wasapi.cpp
  test/test-input/sync-pair-aud.c
Labels: Enhancement
