Repository obsproject/obs-studio, pull requests merged in 2021-03, with the labels that each got.

#4232 mac-virtualcam: DAL PlugIn check for custom png file
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Labels: Enhancement

#4278 CI: Fix missing entitlements on CEF components for obs-browser
  .github/workflows/main.yml
  CI/full-build-macos.sh
  CI/scripts/macos/helpers/helper-entitlements.plist
Labels: Bug Fix, Seeking Testers, macOS

#4253 obs-ffmpeg: Fix bug with obs_source_media_play_pause
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#4306 libobs/util: Compiler barriers for ARM64 atomics
  libobs/util/threading-windows.h
Labels: Bug Fix

#4308 UI: Remove redundant code
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#2777 frontend-tools: Add edit script button
  UI/frontend-plugins/frontend-tools/data/locale/en-US.ini
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/frontend-plugins/frontend-tools/scripts.hpp
Labels: Enhancement

#4311 UI: fixed warning for auto connect signal
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#4318 UI: Fix Qt6 build issues
  UI/log-viewer.cpp
  UI/obs-app.cpp
  UI/qt-wrappers.hpp
  UI/window-basic-main.cpp
Labels: Bug Fix, Code Cleanup

#4314 UI: Don't attempt to resize parent group when changing cursor
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
Labels: Bug Fix

#4324 cmake: Require Qt if UI is enabled
  CMakeLists.txt
Labels: Bug Fix

#4322 cmake: Fix some Qt files not being logged in CMake output
  cmake/Modules/CopyMSVCBins.cmake
Labels: Bug Fix

#4321 UI: Remove UpdateSceneCollection function from header
  UI/window-basic-main.hpp
Labels: Code Cleanup

#4300 libobs: Fix crash when no context
  libobs/obs-nix-x11.c
Labels: Bug Fix

#4310 Make drag and drop insensitive to file extension case
  UI/window-basic-main-dropfiles.cpp
Labels: Bug Fix

#4271 UI: Add css on Drag and Drop
  UI/window-basic-main-dropfiles.cpp
Labels: Enhancement

#4338 UI: Save video settings after 'Resize output (source size)'
  UI/window-basic-main.cpp
Labels: Bug Fix

#3603 obs-filters: Add RTX denoiser
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvafx-load.h
  plugins/obs-filters/obs-filters.c
Labels: Enhancement, Seeking Testers, Windows

#4349 Only set AA_DontCreateNativeWidgetSiblings on Wayland
  UI/obs-app.cpp
Labels: Bug Fix

#4348 Sync Flatpak manifest with Flathub
  CI/flatpak/com.obsproject.Studio.json
  CI/flatpak/ffmpeg-libsrt.patch
Labels: Bug Fix, Linux, Seeking Testers

#4352 UI: Remove x11info dependency
  UI/CMakeLists.txt
  UI/obs-app.cpp
Labels: Code Cleanup, Linux

#4344 obs-ffmpeg: Align both NVENC implementations
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Code Cleanup

#1905 UI: Add visibility transitions
  UI/data/locale/en-US.ini
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-properties.cpp
  docs/sphinx/reference-scenes.rst
  libobs/obs-scene.c
  libobs/obs-scene.h
  libobs/obs.h
Labels: Enhancement, Request for Comments, Seeking Testers

#4360 libobs: fix property group check
  libobs/obs-properties.c
Labels: Bug Fix

#3931 rtmp-services: Add Dacast
  plugins/rtmp-services/CMakeLists.txt
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
  plugins/rtmp-services/rtmp-services-main.c
  plugins/rtmp-services/service-specific/dacast.c
  plugins/rtmp-services/service-specific/dacast.h
Labels: Enhancement, Services

#4370 win-dshow: Fix memory leak caused by using incorrect API
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix

#4385 flatpak: Don't specify luajit commit
  CI/flatpak/com.obsproject.Studio.json
Labels: Linux, Seeking Testers

#4393 UI: Fix canvas resolution in auto-config
  UI/window-basic-auto-config.cpp
Labels: Bug Fix, Regression

#3426 UI: Implement Undo/Redo System
  UI/CMakeLists.txt
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/properties-view.cpp
  UI/properties-view.hpp
  UI/source-tree.cpp
  UI/undo-stack-obs.cpp
  UI/undo-stack-obs.hpp
  UI/window-basic-filters.cpp
  UI/window-basic-main-scene-collections.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
  UI/window-basic-properties.cpp
  UI/window-basic-source-select.cpp
  UI/window-basic-source-select.hpp
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
  docs/sphinx/reference-scenes.rst
  docs/sphinx/reference-settings.rst
  docs/sphinx/reference-sources.rst
  libobs/obs-data.c
  libobs/obs-data.h
  libobs/obs-internal.h
  libobs/obs-scene.c
  libobs/obs-source.c
  libobs/obs.h
  plugins/text-freetype2/text-freetype2.c
Labels: Enhancement, Seeking Testers

#4287 Wayland / PipeWire capture
  .github/workflows/main.yml
  CI/before-script-linux.sh
  CI/flatpak/com.obsproject.Studio.json
  cmake/Modules/FindGio.cmake
  cmake/Modules/FindPipeWire.cmake
  libobs-opengl/gl-egl-common.c
  libobs-opengl/gl-egl-common.h
  libobs-opengl/gl-nix.c
  libobs-opengl/gl-nix.h
  libobs-opengl/gl-wayland-egl.c
  libobs-opengl/gl-x11-egl.c
  libobs-opengl/gl-x11-glx.c
  libobs/graphics/device-exports.h
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
  plugins/linux-capture/CMakeLists.txt
  plugins/linux-capture/data/locale/en-US.ini
  plugins/linux-capture/linux-capture.c
  plugins/linux-capture/pipewire-capture.c
  plugins/linux-capture/pipewire-capture.h
  plugins/linux-capture/pipewire.c
  plugins/linux-capture/pipewire.h
Labels: Enhancement, Linux, Seeking Testers

#4404 x264 minor alignment with FFmpeg
  plugins/obs-x264/obs-x264.c
Labels: Code Cleanup

#4386 libobs: fix property group check
  libobs/obs-properties.c
Labels: Bug Fix

#3927 obs-ffmpeg: Enable macOS hardware decoding for media source
  deps/media-playback/media-playback/decode.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement, macOS

#4397 CI: Quote all bash variables containing paths
  CI/full-build-macos.sh
Labels: Bug Fix

#4395 UI: Remove ifdefs for Qt 5.9 and older
  UI/window-basic-main.cpp
Labels: Code Cleanup

#4411 UI: Fix locale key name
  UI/data/locale/en-US.ini
Labels: Bug Fix

#4381 obs-ffmpeg: Hangs when global_stream_key is not configured
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix

#4377 cmake: Better failure message for no OBS_VERSION
  cmake/Modules/ObsCpack.cmake
Labels: Code Cleanup

#4412 UI: Fix Horizontal Center Text
  UI/window-basic-main.cpp
Labels: Bug Fix

#4373 UI: fix UI block after dragging source #2609
  UI/source-tree.cpp
Labels: Bug Fix

#4371 win-capture: clear last video frame if settings of window source is empty #2321
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#4361 UI: Remove Qt5MacExtras
  UI/CMakeLists.txt
Labels: Code Cleanup

#4414 Document gs_texture_create_from_dmabuf
  docs/sphinx/reference-libobs-graphics-graphics.rst
Labels: Documentation

#4416 Add exit codes for silent installer
  UI/installer/mp-installer.nsi
Labels: Enhancement

#4420 UI: Remove special character ('…') to prevent vs2019 compiler error
  UI/window-basic-main.cpp
Labels: Code Cleanup

#4419 UI: Fix crash on exit with stuck encoder
  UI/window-basic-main.cpp
  UI/window-basic-status-bar.cpp
Labels: Bug Fix

#4418 win-capture: Restore GL capture deduplication
  plugins/win-capture/graphics-hook/gl-capture.c
Labels: Bug Fix

#4417 Fix crashing when using a custom vcam placeholder
  plugins/win-dshow/virtualcam-module/placeholder.cpp
  plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp
  plugins/win-dshow/virtualcam-module/virtualcam-filter.hpp
Labels: Bug Fix

#4421 UI: Ignore scene source which has been removed
  UI/source-tree.cpp
Labels: Bug Fix
