Repository obsproject/obs-studio, pull requests merged in 2021-12, with the labels that each got.

#5594 obs-ffmpeg: Fix memory leaks if replay buffer failed
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Labels: Bug Fix

#5588 UI/importers: Automatically detect SL Collections on macOS
  UI/importers/sl.cpp
Labels: Bug Fix, Seeking Testers, macOS

#5593 UI: Pass parent QWidget to Browser Docks
  UI/auth-restream.cpp
  UI/auth-twitch.cpp
  UI/auth-youtube.cpp
  UI/window-extra-browsers.cpp
Labels: Enhancement

#5612 UI: Generate unique identifiers for Custom Browser Docks
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-extra-browsers.cpp
  UI/window-extra-browsers.hpp
Labels: Enhancement

#5618 CI: Don't publish betas to Flathub stable
  .github/workflows/flatpak.yml
Labels: Enhancement, Linux

#5623 CI: Increase Crowdin Sync Checkout Fetch Depth
  .github/workflows/crowdin-sync-download.yml
  .github/workflows/crowdin-sync-upload.yml
Labels: Bug Fix

#5591 aja: Static analysis bug fixes
  plugins/aja/aja-card-manager.cpp
  plugins/aja/aja-output.cpp
  plugins/aja/aja-routing.cpp
  plugins/aja/aja-routing.hpp
  plugins/aja/aja-source.cpp
  plugins/aja/routing/hdmi_rgb_capture.h
  plugins/aja/routing/hdmi_rgb_display.h
  plugins/aja/routing/hdmi_ycbcr_capture.h
  plugins/aja/routing/hdmi_ycbcr_display.h
  plugins/aja/routing/sdi_rgb_capture.h
  plugins/aja/routing/sdi_rgb_display.h
  plugins/aja/routing/sdi_ycbcr_capture.h
  plugins/aja/routing/sdi_ycbcr_display.h
Labels: Bug Fix

#5627 aja: Disable plugin if no devices are found
  UI/frontend-plugins/aja-output-ui/CMakeLists.txt
  UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp
  plugins/aja/main.cpp
Labels: Enhancement

#5586 aja: Fix crash in output settings when no card present
  plugins/aja/aja-common.cpp
  plugins/aja/aja-output.cpp
  plugins/aja/aja-source.cpp
Labels: Bug Fix

#5633 aja: .rc file for the aja plugin
  plugins/aja/CMakeLists.txt
Labels: Enhancement, Seeking Testers

#5641 Set donation, bugtracker, and translate AppData fields
  UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Labels: Enhancement, Linux

#5634 docs: add missing source output flags
  docs/sphinx/reference-sources.rst
Labels: Documentation

#5611 UI: Add UUID to Twitch panel URLs
  UI/auth-twitch.cpp
  UI/auth-twitch.hpp
Labels: Bug Fix

#5636 pipewire: only deinit if we init'ed
  plugins/linux-capture/pipewire-capture.c
Labels: Bug Fix, Linux

#4506 vlc-video: Emit media ended signal regardless of loop setting
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#5336 obs-ffmpeg: Set DRI devices and their name persistently
  .github/workflows/main.yml
  cmake/Modules/FindLibpci.cmake
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix, Seeking Testers, Linux

#5503 XComposite: Fix capturing on software rasterization setups
  plugins/linux-capture/xcompcap-main.cpp
Labels: Bug Fix, Linux

#5655 CI: Run Flatpak jobs on release branches too
  .github/workflows/flatpak.yml
Labels: Enhancement, Linux

#5580 libobs: Add AutoRelease OBSRef wrappers for OBS types
  UI/adv-audio-control.cpp
  UI/api-interface.cpp
  UI/auth-oauth.cpp
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
  UI/frontend-plugins/frontend-tools/captions.cpp
  UI/frontend-plugins/frontend-tools/output-timer.cpp
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/obs-app.cpp
  UI/properties-view.cpp
  UI/qt-wrappers.cpp
  UI/source-tree.cpp
  UI/volume-control.cpp
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-filters.cpp
  UI/window-basic-main-dropfiles.cpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main-scene-collections.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
  UI/window-basic-properties.cpp
  UI/window-basic-properties.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-source-select.cpp
  UI/window-basic-stats.cpp
  UI/window-basic-transform.cpp
  UI/window-missing-files.cpp
  UI/window-projector.cpp
  libobs/obs.hpp
Labels: Code Cleanup, Seeking Testers

#5661 UI: Fix a stack overlow caused by using OBSScene
  UI/window-basic-transform.cpp
Labels: Bug Fix

#5663 win-capture: Fix bug that WGC capture is stopped
  plugins/win-capture/window-capture.c
Labels: Bug Fix, Windows

#5501 Fix FFmpeg deprecations up to FFmpeg 4.4 and current FFmpeg git
  deps/media-playback/media-playback/media.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-formats.h
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-ffmpeg/obs-ffmpeg.c
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix, Enhancement

#5654 Remove Qt Windows Extra for Qt 6 and later
  UI/CMakeLists.txt
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Windows

#5150 UI: Add undo/redo for "Add existing source"
  UI/window-basic-source-select.cpp
Labels: Bug Fix

#5014 obs-outputs: Reset dbr bitrate before end_data_capture_thread start
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix

#4327 UI: Add checks for overwrite setting to replay buffer
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#5167 UI: Update the filters window to be resizeable
  UI/forms/OBSBasicFilters.ui
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
Labels: Enhancement

#5666 libobs: Add preprocessor directive for AutoRelease types
  libobs/obs.hpp
Labels: Bug Fix

#5509 win-virtualcam: Make sure virtualcam output thread safe
  plugins/win-dshow/virtualcam.c
Labels: Bug Fix, Windows

#5669 libobs: Hold source ref during `source_remove` signal
  libobs/obs-source.c
Labels: Bug Fix

#4863 mac-capture: Improve window capture performance
  plugins/mac-capture/mac-display-capture.m
  plugins/mac-capture/mac-window-capture.m
  plugins/mac-capture/window-utils.h
  plugins/mac-capture/window-utils.m
Labels: Enhancement, Code Cleanup, Seeking Testers, macOS

#5681 libobs-d3d11: DuplicateOutput1 for DXGI capture
  libobs-d3d11/d3d11-duplicator.cpp
Labels: Bug Fix, Windows

#5527 CI: Use Windows obs-deps release
  .github/workflows/main.yml
Labels: Enhancement, Seeking Testers

#5683 libobs: Rename obs_audio_monitoring_supported to _available
  UI/adv-audio-control.cpp
  UI/window-basic-adv-audio.cpp
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  docs/sphinx/reference-core.rst
  libobs/CMakeLists.txt
  libobs/audio-monitoring/null/null-audio-monitoring.c
  libobs/audio-monitoring/osx/coreaudio-monitoring-available.c
  libobs/audio-monitoring/pulse/pulseaudio-monitoring-available.c
  libobs/audio-monitoring/win32/wasapi-monitoring-available.c
  libobs/obs.c
  libobs/obs.h
Labels: Code Cleanup

#5684 Flatpak: Add AJA NTV2 and deduplicate CEF
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers, Linux, CI

#5670 UI: Filter out incompatible audio filters in A/V list
  UI/window-basic-filters.cpp
Labels: Bug Fix

#5675 docs: Document obs_get_scene_by_name
  docs/sphinx/reference-core.rst
Labels: Documentation

#5678 UI: Remove unneeded call when removing scene
  UI/window-basic-main.cpp
Labels: Code Cleanup

#5693 UI: Hold refs to old sources during remove source undo
  UI/window-basic-main.cpp
Labels: Bug Fix

#5687 Stop setting SO_SNDBUF and instead log the initial and final values
  plugins/obs-outputs/rtmp-stream.c
Labels: Enhancement, Windows

#5709 docs: Fix names of filter/properties functions
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation

#5710 UI: Add `obs_frontend_open_source_interaction()`
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#5714 UI: Fix build with YT integration without browser
  UI/CMakeLists.txt
Labels: Bug Fix

#5715 Publish to the correct Flathub branches
  .github/workflows/flatpak.yml
Labels: Bug Fix, Linux

#5716 UI: Fix vertical grayscale meters when volume is muted
  UI/volume-control.cpp
Labels: Bug Fix
