Repository obsproject/obs-studio, pull requests merged in 2021-05, with the labels that each got.

#4571 CI: Remove unneeded runtime deps
  .github/workflows/main.yml
  CI/install-dependencies-linux.sh
Labels: Bug Fix, Seeking Testers

#4612 UI: Move clearing of copy/paste variables
  UI/window-basic-main.cpp
Labels: Code Cleanup

#4620 README.rst: Use High DPI Discord Badge
  README.rst
Labels: Documentation

#4621 docs: Remove block quotes
  CONTRIBUTING.rst
  README.rst
Labels: Documentation

#4644 image-source: Allow linear space alpha
  plugins/image-source/data/locale/en-US.ini
  plugins/image-source/image-source.c
Labels: Enhancement

#4647 obs-filters: Fix shader for LUT on OpenGL
  plugins/obs-filters/data/color_grade_filter.effect
Labels: Bug Fix, Seeking Testers

#4658 win-capture: Fix WGC disable index for display
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Bug Fix

#4669 libobs: Fix deadlock removing scene item
  libobs/obs-scene.c
Labels: Bug Fix

#4650 rtmp-services: Add Brime Live service
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4617 rtmp-services: add Odysee.com
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
  plugins/rtmp-services/data/services.json
Labels: Services

#4578 UI: Disable transition props menu when transitioning
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#4557 Enable browser source for real in Flatpak
  CI/flatpak/com.obsproject.Studio.json
Labels: Seeking Testers

#4556 cmake: Remove outdated osxbundle files
  CMakeLists.txt
  cmake/Modules/ObsHelpers.cmake
  cmake/helper_subdir/CMakeLists.txt
  cmake/osxbundle/Info.plist
  cmake/osxbundle/fixup_bundle.sh
  cmake/osxbundle/obs.icns
  cmake/osxbundle/obslaunch.sh
Labels: Code Cleanup, Seeking Testers

#4637 UI: Fade to black fixes
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#4677 obs-transitions: Blend in linear space
  plugins/obs-transitions/data/fade_to_color_transition.effect
  plugins/obs-transitions/data/fade_transition.effect
  plugins/obs-transitions/data/luma_wipe_transition.effect
  plugins/obs-transitions/data/slide_transition.effect
  plugins/obs-transitions/data/stinger_matte_transition.effect
  plugins/obs-transitions/data/swipe_transition.effect
  plugins/obs-transitions/transition-fade-to-color.c
  plugins/obs-transitions/transition-fade.c
  plugins/obs-transitions/transition-luma-wipe.c
  plugins/obs-transitions/transition-slide.c
  plugins/obs-transitions/transition-stinger.c
  plugins/obs-transitions/transition-swipe.c
Labels: Bug Fix

#4688 obs-filters: Fix color key distance
  plugins/obs-filters/data/color_key_filter_v2.effect
Labels: Bug Fix

#4686 Premultiply image sources on load
  libobs/data/default.effect
  libobs/graphics/graphics-ffmpeg.c
  libobs/graphics/graphics.h
  libobs/graphics/image-file.c
  libobs/graphics/image-file.h
  libobs/graphics/srgb.h
  libobs/graphics/vec4.h
  libobs/obs-source.c
  plugins/image-source/image-source.c
Labels: Bug Fix, Enhancement

#4690 decklink: Fix crash during shutdown when output is on
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix

#4657 cmake: Fix FindJack to support finding PipeWire's libjack
  cmake/Modules/FindJack.cmake
Labels: Bug Fix

#4700 libobs: Add srgb.h to CMakeLists.txt
  libobs/CMakeLists.txt
Labels: Bug Fix

#4705 obs-transitions: Make sure gs calls are in graphics context
  plugins/obs-transitions/transition-stinger.c
Labels: Bug Fix

#4704 Fix scene collection importer OS translation
  UI/importers/studio.cpp
Labels: Bug Fix, Seeking Testers

#4692 decklink-output-ui: Decklink fixes
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Labels: Bug Fix

#4723 CI: Add check for code signing credentials used by notarization
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers, macOS

#4728 graphics-hook: Add Detours include dir
  plugins/win-capture/graphics-hook/CMakeLists.txt
Labels: Bug Fix

#4735 cmake: Fix Detours package name CMake warning
  cmake/Modules/FindDetours.cmake
Labels: Bug Fix

#4744 UI: Fix null string being passed to blog()
  UI/adv-audio-control.cpp
Labels: Bug Fix

#4745 libobs: Straight alpha blend for filtered inputs
  libobs/obs-source.c
Labels: Bug Fix

#4749 UI: Correct add_action repeatable arg type
  UI/window-basic-filters.cpp
Labels: Bug Fix

#4769 Test if NVAFX denoiser is supported when loading obs-filters
  plugins/obs-filters/noise-suppress-filter.c
Labels: Enhancement

#4780 CI: Fix dmgbuild breaking CI by pinning its version number
  .github/workflows/main.yml
Labels: Seeking Testers, macOS
