Repository obsproject/obs-studio, pull requests merged in 2021-08, with the labels that each got.

#5094 UI: Autoremux Replay Buffer
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#5096 UI: Show autoremux progress bar
  UI/window-remux.cpp
Labels: Bug Fix

#5047 YouTube Integration
  .github/workflows/main.yml
  CI/full-build-macos.sh
  UI/CMakeLists.txt
  UI/auth-base.cpp
  UI/auth-base.hpp
  UI/auth-listener.cpp
  UI/auth-listener.hpp
  UI/auth-oauth.cpp
  UI/auth-oauth.hpp
  UI/auth-restream.cpp
  UI/auth-restream.hpp
  UI/auth-twitch.cpp
  UI/auth-twitch.hpp
  UI/auth-youtube.cpp
  UI/auth-youtube.hpp
  UI/data/locale/en-US.ini
  UI/forms/AutoConfigStreamPage.ui
  UI/forms/OBSBasic.ui
  UI/forms/OBSBasicSettings.ui
  UI/forms/OBSYoutubeActions.ui
  UI/obs-app.cpp
  UI/remote-text.cpp
  UI/remote-text.hpp
  UI/ui-config.h.in
  UI/win-update/win-update.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
  UI/window-youtube-actions.cpp
  UI/window-youtube-actions.hpp
  UI/youtube-api-wrappers.cpp
  UI/youtube-api-wrappers.hpp
Labels: Enhancement, Seeking Testers

#5092 libobs/util: Fix reading memory usage on Linux
  libobs/util/platform-nix.c
Labels: Bug Fix, Linux

#4504 obs-frontend-api: Send OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP event
  UI/api-interface.cpp
Labels: Bug Fix

#5107 UI: Add functions to open properties and filters
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#5123 linux-capture: Load XSHM capture on EGL/X11
  plugins/linux-capture/linux-capture.c
Labels: Bug Fix, Linux

#5119 obs-outputs: Fix binding to IPv6 addresses on *nix
  plugins/obs-outputs/net-if.c
Labels: Bug Fix, Linux

#4496 UI: Force Wayland usage under Wayland session
  UI/obs-app.cpp
Labels: Enhancement, Linux

#5124 UI: Create YouTube LiveStream objects as non-reusable
  UI/youtube-api-wrappers.cpp
Labels: Bug Fix, Seeking Testers

#5006 deps/media-playback: Fix bug about audio without best_effort_timestamp
  deps/media-playback/media-playback/decode.c
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#5127 graphics-hook: Fix D3D11On12 usages
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
Labels: Bug Fix, Code Cleanup, Windows

#4518 mac-virtualcam: Move DAL plugin to plugin data directory
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Code Cleanup, macOS

#4920 rtmp-services: Add BoxCast
  plugins/rtmp-services/data/services.json
Labels: Services

#5126 UI,obs-transitions: Enable missing files dialog for stinger transition
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement

#4331 cmake: Remove local files for checking threading support
  UI/CMakeLists.txt
  cmake/Modules/CheckForPthreads.c
  cmake/Modules/FindThreads.cmake
  libobs/CMakeLists.txt
Labels: Bug Fix, Code Cleanup

#5093 UI: Apply QSS to generic hotkey settings label
  UI/window-basic-settings.cpp
Labels: Bug Fix

#5144 UI: Show name of scene item in Transform window title
  UI/data/locale/en-US.ini
  UI/window-basic-transform.cpp
Labels: Enhancement

#4768 UI: Remove macOS-Default Full Screen Menu Item
  UI/obs-app.cpp
  UI/platform-osx.mm
  UI/platform.hpp
Labels: Bug Fix, macOS

#5138 mac-virtualcam: Move DAL plugin to plugin data directory
  .github/workflows/main.yml
  CI/full-build-macos.sh
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Seeking Testers, macOS

#5072 UI: Dim hidden source items in source tree
  UI/source-tree.cpp
  UI/source-tree.hpp
Labels: Enhancement

#4939 graphics-hook: Fix D3D12 third party overlay capture setting
  plugins/win-capture/graphics-hook/d3d10-capture.cpp
  plugins/win-capture/graphics-hook/d3d11-capture.cpp
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
  plugins/win-capture/graphics-hook/graphics-hook.h
Labels: Bug Fix, Windows

#5129 UI: Add menu bar item to show missing files dialog
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#5125 UI: Show source icon in context bar
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
Labels: Enhancement

#5143 UI: Clean up other UI form file markup
  UI/forms/AutoConfigStreamPage.ui
  UI/forms/OBSAbout.ui
  UI/forms/OBSBasicFilters.ui
  UI/forms/OBSBasicInteraction.ui
  UI/forms/OBSBasicSettings.ui
  UI/forms/OBSBasicTransform.ui
  UI/forms/OBSExtraBrowsers.ui
  UI/forms/OBSImporter.ui
  UI/forms/OBSMissingFiles.ui
  UI/forms/OBSRemux.ui
  UI/forms/OBSUpdate.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
  UI/forms/source-toolbar/text-source-toolbar.ui
Labels: Code Cleanup, Seeking Testers

#5153 UI: Fix redo recreating sources in the wrong scene
  UI/window-basic-source-select.cpp
Labels: Bug Fix

#5157 libobs-winrt: Replace casts with data access
  libobs-winrt/winrt-capture.cpp
Labels: Code Cleanup

#4233 UI: Add option to draw safe areas in preview
  UI/display-helpers.hpp
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#4678 UI: Log viewer fixes
  UI/log-viewer.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, Code Cleanup

#5172 UI: Use inline const for shared vector
  UI/auth-youtube.hpp
Labels: Code Cleanup

#4921 cmake: Copy correct file for Qt imageformat plugin
  cmake/Modules/CopyMSVCBins.cmake
Labels: Bug Fix

#5161 UI: Add styling for YouTube integration
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/left.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/OBSYoutubeActions.ui
  UI/window-basic-main.cpp
  UI/window-youtube-actions.cpp
Labels: Enhancement, Code Cleanup

#5134 UI: Add YouTube Chat Dock
  UI/auth-youtube.cpp
  UI/auth-youtube.hpp
  UI/window-youtube-actions.cpp
Labels: Enhancement, Seeking Testers, New Feature

#5162 UI: Adjustments to YouTube integration strings
  UI/data/locale/en-US.ini
Labels: Enhancement

#4720 Finish Detours integration for remaining game capture APIs
  plugins/win-capture/funchook.c
  plugins/win-capture/funchook.h
  plugins/win-capture/graphics-hook-ver.h
  plugins/win-capture/graphics-hook/CMakeLists.txt
  plugins/win-capture/graphics-hook/d3d10-capture.cpp
  plugins/win-capture/graphics-hook/d3d11-capture.cpp
  plugins/win-capture/graphics-hook/d3d8-capture.cpp
  plugins/win-capture/graphics-hook/d3d9-capture.cpp
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
  plugins/win-capture/graphics-hook/gl-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
Labels: Enhancement, Windows

#5166 decklink: Fix deactivate when not showing
  plugins/decklink/decklink-source.cpp
Labels: Bug Fix, Seeking Testers

#5187 UI: Adjust minimum size of source toolbars
  UI/context-bar-controls.cpp
  UI/forms/OBSBasic.ui
  UI/forms/source-toolbar/device-select-toolbar.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
  UI/forms/source-toolbar/image-source-toolbar.ui
Labels: Enhancement

#5209 win-capture: Clear stale pointers for game capture
  plugins/win-capture/game-capture.c
Labels: Bug Fix

#5180 Fix a bunch of pthread leaks
  deps/obs-scripting/obs-scripting-lua-source.c
  deps/obs-scripting/obs-scripting-lua.c
  deps/obs-scripting/obs-scripting-python.c
  libobs/CMakeLists.txt
  libobs/callback/signal.c
  libobs/media-io/audio-io.c
  libobs/media-io/video-io.c
  libobs/obs-encoder.c
  libobs/obs-scene.c
  libobs/obs-source.c
  libobs/obs.c
  libobs/util/config-file.c
  libobs/util/profiler.c
  libobs/util/threading.h
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/obs-filters.c
Labels: Bug Fix

#5210 UI: Fix crash when output source 0 is null
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#5213 UI: Add missing properties to ResetBroadcast
  UI/youtube-api-wrappers.cpp
Labels: Bug Fix

#5219 UI: Change YouTube description input to QPlainTextEdit
  UI/forms/OBSYoutubeActions.ui
  UI/window-youtube-actions.cpp
Labels: Bug Fix, Enhancement

#5212 Fixes for YouTube integration when delay is enabled
  UI/window-basic-main.cpp
Labels: Bug Fix

#5220 libobs/util: Improve SetThreadDescription usage
  libobs/util/threading-windows.c
Labels: Bug Fix, Code Cleanup, Windows
