Repository obsproject/obs-studio, pull requests merged in 2021-06, with the labels that each got.

#4788 libobs: Assume sRGB instead of linear for 64 bpp
  libobs/graphics/graphics-ffmpeg.c
Labels: Bug Fix

#4793 obs-filters: Fix swapped chroma distance values
  plugins/obs-filters/data/chroma_key_filter_v2.effect
Labels: Bug Fix

#4792 Disable Copy Filter menu items when source/scene has no filters
  UI/window-basic-main.cpp
Labels: Bug Fix, Seeking Testers

#4794 CI: Bump dmgbuild to 1.5.2 to fix detach error
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers

#4819 UI: Don't execute or track empty SceneItem move actions
  UI/window-basic-main.cpp
Labels: Bug Fix

#4825 obs-ffmpeg: Support lack of Psycho Visual Tuning
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Bug Fix, Seeking Testers

#4820 UI: Translate Undo action "Delete Scene" and include scene name
  UI/window-basic-main.cpp
Labels: Bug Fix

#4833 obs-ffmpeg: NVENC usage fixes
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Bug Fix

#4837 UI: Fix filters changes not properly being added to undo stack
  UI/window-basic-filters.cpp
Labels: Bug Fix

#4838 obs-ffmpeg: Add missing return statement
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Bug Fix

#4813 UI: Optimize backup scene for undo/redo
  UI/source-tree.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, Enhancement, Seeking Testers

#4830 Handle mac-vth264 encoder ID changes
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix, Seeking Testers, macOS

#4867 libobs,deps/media-playback: Avoid bitfields
  deps/media-playback/media-playback/media.c
  libobs/obs-source.c
  libobs/obs.h
Labels: Bug Fix

#4868 UI: Fix unused parameter warning
  UI/window-basic-main.cpp
Labels: Code Cleanup

#4814 UI/installer: Silently install Visual C++ Redistributables
  UI/installer/mp-installer.nsi
Labels: Enhancement, Request for Comments

#4936 pipewire: Properly account for cursor hotspot
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Linux

#4715 obs-ffmpeg: Don't purge packets when there are none
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Labels: Bug Fix, Seeking Testers

#4765 libobs-winrt: Use better Windows SDK version check
  libobs-winrt/winrt-capture.cpp
Labels: Code Cleanup, Windows

#4755 UI: Make projector display resolutions DPI-aware
  UI/window-basic-main.cpp
Labels: Bug Fix, Regression

#4394 UI: Remove fractional scaling ifdefs
  UI/display-helpers.hpp
  UI/window-basic-interaction.cpp
  UI/window-basic-main.cpp
  UI/window-basic-preview.cpp
Labels: Code Cleanup

#4859 Handle HTTP errors in log uploader & file downloader
  UI/remote-text.cpp
Labels: Bug Fix

#4909 mac-capture: Update display names to be human readable
  plugins/mac-capture/mac-display-capture.m
Labels: Enhancement, Seeking Testers, macOS
