Repository obsproject/obs-studio, pull requests merged in 2021-11, with the labels that each got.

#3046 linux-v4l2: Support for Motion-JPEG codec
  plugins/linux-v4l2/CMakeLists.txt
  plugins/linux-v4l2/v4l2-helpers.h
  plugins/linux-v4l2/v4l2-input.c
  plugins/linux-v4l2/v4l2-mjpeg.c
  plugins/linux-v4l2/v4l2-mjpeg.h
Labels: Enhancement, Seeking Testers, Linux

#4806 libobs-opengl: Use PBO for macOS device_stage_texture as same as Linux
  libobs-opengl/gl-stagesurf.c
Labels: Enhancement, Code Cleanup, Seeking Testers

#5192 UI: Filter Menu fixes
  UI/window-basic-filters.cpp
Labels: Bug Fix

#5482 CI: Fix error when uninstalling curl and php
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers

#4994 Integrate services on Flatpak builds
  .github/workflows/flatpak.yml
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers, Linux

#3153 UI: Match Windows taskbar state to tray icon (v2)
  UI/CMakeLists.txt
  UI/forms/images/active.png
  UI/forms/images/paused.png
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  cmake/Modules/CopyMSVCBins.cmake
Labels: Enhancement

#5486 UI: Remove duplicated StreamingActive() function
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#5487 UI: Set correct text in system tray on startup
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#5485 UI, libobs, obs-plugins: Fix compiler warnings
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  UI/window-youtube-actions.hpp
  UI/youtube-api-wrappers.cpp
  libobs/obs-audio-controls.c
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Code Cleanup

#5472 rtmp-services: Add Kuaishou live
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4908 pulse: fill audio monitor buffer more aggressively
  libobs/audio-monitoring/pulse/pulseaudio-output.c
Labels: Bug Fix, Seeking Testers, Linux

#5481 obs-ffmpeg: Fix starting video packet offset in replay-buffer
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Labels: Bug Fix

#5497 UI: Add undo/redo for context bar text changes
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
Labels: Bug Fix

#5495 UI: Don't load existing sources for scene removal undo
  UI/window-basic-main.cpp
Labels: Bug Fix

#5504 libobs: Add obs_get_transition_by_name
  docs/sphinx/reference-core.rst
  libobs/obs.c
  libobs/obs.h
Labels: Enhancement

#5505 rtmp-services: add Utreon
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5423 rtmp-services: Add Autistici.org
  plugins/rtmp-services/data/services.json
Labels: Services

#5299 UI: Add undo/redo for resetting filters properties
  UI/window-basic-filters.cpp
Labels: Bug Fix

#5512 rtmp-services: add PhoneLivestreaming
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5513 obs-transitions: Fix stinger transition looping
  plugins/obs-transitions/transition-stinger.c
Labels: Bug Fix

#5340 UI: Apply transforms/crops correctly to sources on paste
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-source-select.cpp
  UI/window-basic-source-select.hpp
Labels: Bug Fix

#5188 linux-v4l2: Change search strategy for v4l2loopback devices
  plugins/linux-v4l2/v4l2-output.c
Labels: Bug Fix, Linux

#5507 UI: Link python when obs-scripting python is enabled
  UI/CMakeLists.txt
Labels: Bug Fix, Linux

#5514 obs-qsv11: Remove Intel discrete device ID checking
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement, Code Cleanup

#5473 rtmp-services: Add Manyvids.com
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5525 UI: Update python linkage for older compilers
  UI/CMakeLists.txt
Labels: Bug Fix, Linux

#5459 obs-frontend-api: Add scripting shutdown event
  UI/obs-frontend-api/obs-frontend-api.h
  UI/window-basic-main.cpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#5522 docs: Document obs_group_or_scene_from_source
  docs/sphinx/reference-scenes.rst
Labels: Documentation

#5518 libobs/graphics: Add support for NT Handle shared textures
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-d3d11/d3d11-texture2d.cpp
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
Labels: Enhancement

#5536 UI: Import Streamlabs Screen Capture source type
  UI/importers/sl.cpp
Labels: Bug Fix, Enhancement

#5234 text-freetype2: Move default settings to .get_defaults
  plugins/text-freetype2/text-freetype2.c
  plugins/text-freetype2/text-freetype2.h
Labels: Bug Fix, Code Cleanup

#5557 inject-helper: Remove UNUSED_PARAMETER macro
  plugins/win-capture/inject-helper/inject-helper.c
Labels: Code Cleanup

#4576 UI: Fix crash on *nix caused by OBSQTDisplay destruction after draw surface invalidation
  UI/qt-display.cpp
Labels: Bug Fix

#5558 ipc-util: Fix potential ready_event hang
  deps/ipc-util/ipc-util/pipe-windows.c
  deps/ipc-util/ipc-util/pipe-windows.h
Labels: Bug Fix, Windows

#5271 aja: Capture and Output plugin for AJA Video Systems IO devices
  CI/full-build-macos.sh
  UI/frontend-plugins/CMakeLists.txt
  UI/frontend-plugins/aja-output-ui/AJAOutputUI.cpp
  UI/frontend-plugins/aja-output-ui/AJAOutputUI.h
  UI/frontend-plugins/aja-output-ui/CMakeLists.txt
  UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp
  UI/frontend-plugins/aja-output-ui/aja-ui-main.h
  UI/frontend-plugins/aja-output-ui/data/.keepme
  UI/frontend-plugins/aja-output-ui/data/locale/en-US.ini
  UI/frontend-plugins/aja-output-ui/forms/output.ui
  cmake/Modules/FindLibAJANTV2.cmake
  formatcode.sh
  plugins/CMakeLists.txt
  plugins/aja/CMakeLists.txt
  plugins/aja/README.md
  plugins/aja/aja-card-manager.cpp
  plugins/aja/aja-card-manager.hpp
  plugins/aja/aja-common.cpp
  plugins/aja/aja-common.hpp
  plugins/aja/aja-enums.hpp
  plugins/aja/aja-output.cpp
  plugins/aja/aja-output.hpp
  plugins/aja/aja-props.cpp
  plugins/aja/aja-props.hpp
  plugins/aja/aja-routing.cpp
  plugins/aja/aja-routing.hpp
  plugins/aja/aja-source.cpp
  plugins/aja/aja-source.hpp
  plugins/aja/aja-ui-props.hpp
  plugins/aja/aja-widget-io.cpp
  plugins/aja/aja-widget-io.hpp
  plugins/aja/data/.keepme
  plugins/aja/data/locale/en-US.ini
  plugins/aja/main.cpp
  plugins/aja/routing/hdmi_rgb_capture.h
  plugins/aja/routing/hdmi_rgb_display.h
  plugins/aja/routing/hdmi_ycbcr_capture.h
  plugins/aja/routing/hdmi_ycbcr_display.h
  plugins/aja/routing/sdi_rgb_capture.h
  plugins/aja/routing/sdi_rgb_display.h
  plugins/aja/routing/sdi_ycbcr_capture.h
  plugins/aja/routing/sdi_ycbcr_display.h
Labels: Enhancement, Seeking Testers

#5538 libobs: Fix gs_texture_2d::BackupTexture with GS_TEXTURE_CUBE
  libobs-d3d11/d3d11-texture2d.cpp
Labels: Bug Fix, Feedback required

#5548 UI: Use std::gcd for aspect ratio
  UI/window-basic-settings.cpp
Labels: Code Cleanup

#5552 UI: Fix context bar shutdown crash
  UI/context-bar-controls.cpp
Labels: Bug Fix

#5357 UI: Fix bug with audio balance slider not updating
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  docs/sphinx/reference-sources.rst
  libobs/obs-source.c
Labels: Bug Fix

#5567 libobs: Free async cache when sources output NULL frames
  libobs/obs-source.c
Labels: Bug Fix

#5539 UI: Set Twitch Panel Dark Mode using OBS theme
  UI/auth-twitch.cpp
  UI/obs-app.cpp
  UI/obs-app.hpp
Labels: Bug Fix, Enhancement

#5535 libobs: Add raw audio callback function
  docs/sphinx/reference-core.rst
  libobs/obs.c
  libobs/obs.h
Labels: Enhancement

#5566 Correct logo on Linux
  UI/xdg-data/CMakeLists.txt
  UI/xdg-data/icons/obs-logo-128.png
  UI/xdg-data/icons/obs-logo-256.png
  UI/xdg-data/icons/obs-logo-512.png
  UI/xdg-data/icons/obs-logo-scalable.svg
Labels: Bug Fix, Linux

#5412 UI: Minimize context bar when too small
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Seeking Testers

#5576 UI: Expose cURL error if Remote Text error text is empty
  UI/remote-text.cpp
Labels: Enhancement

#4691 CI: Crowdin Synchronization
  .gitattributes
  .github/workflows/crowdin-sync-download.yml
  .github/workflows/crowdin-sync-upload.yml
Labels: Enhancement

#5573 Unassorted Flatpak updates and extensions
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers, Linux

#5544 UI: Move Docks into top level menu
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
Labels: Enhancement

#5581 Add kudos to AppData file
  UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Labels: Enhancement, Linux

#5585 linux-capture: Fallback to SHM on older PipeWire versions
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Seeking Testers, Linux
