Repository obsproject/obs-studio, pull requests merged in 2021-07, with the labels that each got.

#4919 UI: Check if recording is paused when trying to pause
  UI/window-basic-main.cpp
Labels: Bug Fix

#4971 libobs/callback: Fix signal_handler_disconnect_global
  libobs/callback/signal.c
Labels: Bug Fix

#4970 UI: Fix audio mixer UI not updating from threads
  UI/window-basic-main.cpp
Labels: Bug Fix

#4940 cmake: Enable full optimizations for RelWithDebInfo MSVC builds
  CMakeLists.txt
Labels: Enhancement, Windows

#4914 UI: Log Show/Hide transitions on scene collection load
  UI/window-basic-main.cpp
Labels: Enhancement

#4900 libobs: Fix memory overrun if libobs version mismatches
  libobs/obs-module.c
Labels: Bug Fix

#4894 text-freetype2: Add alpha channel property
  plugins/text-freetype2/text-freetype2.c
Labels: Enhancement

#4985 pipewire: Properly pass sizes to gs_draw_sprite_subregion
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Linux

#4847 rtmp-services: Add "Bilibili Live"
  UI/window-basic-settings-stream.cpp
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4812 List Flatpak search paths
  libobs/obs-nix.c
Labels: Enhancement, Linux

#4337 libobs, UI: Add support for button properties as links
  UI/data/locale/en-US.ini
  UI/properties-view.cpp
  docs/sphinx/reference-properties.rst
  libobs/obs-properties.c
  libobs/obs-properties.h
Labels: Enhancement

#4701 libobs: Add `obs_enum_all_sources()` to enumerate all source types
  libobs/obs.c
  libobs/obs.h
Labels: Enhancement

#4525 UI: Add obs_frontend_get_current_profile_path() to frontend-api
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#4515 obs-app: Add startup flag to disable missing files window
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/window-basic-main.cpp
Labels: Enhancement

#4536 UI: Add obs-frontend-api functions to create/delete profiles
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#4923 UI: Fix displayed autoremux file name
  UI/window-remux.cpp
Labels: Bug Fix

#4935 libobs: Add DrawSrgbDecompressPremultiplied technique to default effects
  libobs/data/default.effect
  libobs/data/default_rect.effect
Labels: Enhancement

#4950 Manual SRGB filtering
  docs/sphinx/reference-sources.rst
  libobs-d3d11/d3d11-duplicator.cpp
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-opengl/gl-subsystem.h
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  libobs/data/default.effect
  libobs/graphics/graphics.h
  libobs/obs-internal.h
  libobs/obs-scene.c
  libobs/obs-source.c
  libobs/obs.h
  plugins/win-capture/dc-capture.c
  plugins/win-capture/dc-capture.h
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/game-capture.c
  plugins/win-capture/monitor-capture.c
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#4566 decklink: Don't show incompatible formats in Decklink output window
  plugins/decklink/decklink-device-mode.cpp
  plugins/decklink/decklink-device-mode.hpp
  plugins/decklink/decklink-output.cpp
Labels: Bug Fix

#4455 UI: Add "18 Scenes" multiview option
  UI/data/locale/en-US.ini
  UI/window-basic-settings.cpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Enhancement

#5009 libobs: Fix stack buffer overflow in build_current_order_info
  libobs/obs-scene.c
Labels: Bug Fix

#5018 libobs: Round up chroma sizes for odd resolutions
  libobs/media-io/video-frame.c
  libobs/obs-source.c
Labels: Bug Fix

#5026 decklink: Fix truncation warnings
  plugins/decklink/decklink-device-mode.cpp
  plugins/decklink/decklink-device-mode.hpp
Labels: Code Cleanup

#5022 Reenable drag/drop on Linux scenes/sources
  UI/source-tree.cpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#5049 obs-filters: Use linear value of secondary texture
  plugins/obs-filters/mask-filter.c
Labels: Bug Fix

#5050 obs-ffmpeg: Translate VAAPI property names
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix, Linux

#4916 UI: Fix undo delete scene that is used as source
  UI/window-basic-main.cpp
Labels: Bug Fix

#5024 rtmp-services: Add "Lovecast"
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services
