Repository obsproject/obs-studio, pull requests merged in 2021-10, with the labels that each got.

#5342 UI: Adjust minimum size of source toolbar smaller
  UI/forms/OBSBasic.ui
  UI/forms/source-toolbar/game-capture-toolbar.ui
Labels: Bug Fix

#5365 UI: Remove thread from YouTube auto config
  UI/window-basic-auto-config.cpp
Labels: Bug Fix

#5359 Test darray type during CI
  CMakeLists.txt
  libobs/graphics/effect-parser.c
  libobs/graphics/effect-parser.h
  libobs/graphics/shader-parser.c
  libobs/obs-output.c
  libobs/util/array-serializer.c
  libobs/util/darray.h
Labels: Enhancement, Code Cleanup

#5368 UI: Fix Twitch bandwidth test checkbox
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#5360 libobs: Remove DrawSrgbDecompressPremultiplied
  libobs/data/default.effect
  libobs/data/default_rect.effect
Labels: Code Cleanup

#5367 UI: Do not disable AutoConf bandwidth test for YouTube
  UI/window-basic-auto-config.cpp
Labels: Code Cleanup

#5370 UI: Fix tab stop order for Draw safe areas
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#5467 obs-ffmpeg-mux: Add support for rist protocol
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Enhancement
