Repository obsproject/obs-studio, pull requests merged in 2021-09, with the labels that each got.

#5227 UI: Use OBS locale for YouTube categories API
  UI/window-youtube-actions.cpp
  UI/youtube-api-wrappers.cpp
  UI/youtube-api-wrappers.hpp
Labels: Bug Fix

#3072 UI: Disable hotkeys when a user is expected to type text
  UI/source-tree.cpp
  UI/window-basic-filters.cpp
  UI/window-basic-interaction.cpp
  UI/window-basic-main.cpp
  UI/window-basic-properties.cpp
  UI/window-basic-source-select.cpp
  UI/window-namedialog.cpp
Labels: Bug Fix

#5258 rtmp-services: Add "Disciple Media"
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5256 UI: Update volume controls by callback
  UI/volume-control.cpp
  UI/volume-control.hpp
Labels: Enhancement

#5266 libobs-d3d11: Use ALLOW_TEARING if supported
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
Labels: Enhancement, Windows

#4405 libobs: Add profiler section for send_packet
  libobs/obs-encoder.c
Labels: Enhancement

#4664 libobs: Fix a deadlock caused by obs_enter_graphics
  libobs/obs-scene.c
Labels: Bug Fix

#4746 libobs: Restrict emmintrin.h to x86(_64) MSVC platform
  libobs/util/sse-intrin.h
Labels: Bug Fix, Windows

#4907 deps/media-playback: Handle discontinuities to fix video stalls
  deps/media-playback/media-playback/media.c
Labels: Bug Fix, Seeking Testers

#5274 libobs: Block sceneitem creation if item source is removed
  libobs/obs-scene.c
Labels: Bug Fix

#5273 UI: Remove unused RemoveSelectedSceneItem slot
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#5275 UI: Fix used source for SetCurrentScene during undo
  UI/window-basic-properties.cpp
Labels: Bug Fix

#5242 Adjustments to YouTube Broadcast Setup
  UI/auth-base.cpp
  UI/auth-base.hpp
  UI/auth-youtube.hpp
  UI/data/locale/en-US.ini
  UI/forms/OBSYoutubeActions.ui
  UI/window-basic-auto-config.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-youtube-actions.cpp
  UI/window-youtube-actions.hpp
  UI/youtube-api-wrappers.cpp
  UI/youtube-api-wrappers.hpp
Labels: Enhancement, Seeking Testers

#5216 UI: Add Thumbnail uploading to YouTube integration
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/OBSYoutubeActions.ui
  UI/remote-text.cpp
  UI/remote-text.hpp
  UI/window-youtube-actions.cpp
  UI/window-youtube-actions.hpp
  UI/youtube-api-wrappers.cpp
  UI/youtube-api-wrappers.hpp
  cmake/Modules/CopyMSVCBins.cmake
Labels: Enhancement

#5285 libobs-d3d11: Fix present skip comment
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Code Cleanup

#5286 UI: Force minimum reconnect delay of 1 second
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main.cpp
Labels: Bug Fix

#5293 CI: Fix double zip by uploading build folders
  .github/workflows/main.yml
Labels: Code Cleanup, Seeking Testers

#5294 linux-capture: Lookup session handle without typechecks
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Linux

#5311 win-dshow: Don't buffer Elgato Facecam by default
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix

#5312 docs: Add transition duration changed event
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation

#5322 UI: Prevent Restream OAuth disconnection
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#5319 libobs: Make portal inhibitor asynchronous
  libobs/util/platform-nix-portal.c
Labels: Bug Fix, Seeking Testers, Linux

#5326 linux-capture: Add libdrm dependency check
  cmake/Modules/FindLibdrm.cmake
  plugins/linux-capture/CMakeLists.txt
Labels: Bug Fix, Linux

#5330 linux-capture: Fail when libdrm missing
  plugins/linux-capture/CMakeLists.txt
Labels: Bug Fix, Linux

#5344 libobs: Simplify util_mul_div64 for x64 on Windows
  libobs/util/util_uint64.h
Labels: Enhancement, Windows
