Repository obsproject/obs-studio, pull requests merged in 2021-04, with the labels that each got.

#4116 rtmp-services: Include format version in update URL
  plugins/rtmp-services/rtmp-services-main.c
Labels: Bug Fix

#3953 UI: Add save notifications to status bar
  UI/data/locale/en-US.ini
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main-screenshot.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-remux.cpp
Labels: Enhancement

#4459 linux-capture: De-escalate assertion to a warning
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Seeking Testers

#4458 obs-filters: RTX denoiser initialization fix and code cleanup
  plugins/obs-filters/noise-suppress-filter.c
Labels: Bug Fix, Seeking Testers

#4464 UI: Conform transition duration in Scene Transition dock
  UI/forms/OBSBasic.ui
Labels: Bug Fix

#4437 UI: Add maximum number of items in undo/redo stack
  UI/undo-stack-obs.cpp
Labels: Bug Fix

#4449 UI: Wipe undo/redo stack when switching scene collections
  UI/undo-stack-obs.cpp
  UI/undo-stack-obs.hpp
  UI/window-basic-main-scene-collections.cpp
Labels: Bug Fix

#4478 obs-filters: Add color settings to correction v2
  plugins/obs-filters/color-correction-filter.c
  plugins/obs-filters/data/locale/en-US.ini
Labels: Enhancement

#4453 UI: Force current scene when using undo/redo
  UI/context-bar-controls.cpp
  UI/source-tree.cpp
  UI/window-basic-filters.cpp
  UI/window-basic-main.cpp
  UI/window-basic-preview.cpp
  UI/window-basic-properties.cpp
  UI/window-basic-source-select.cpp
  UI/window-basic-transform.cpp
Labels: Bug Fix

#4450 UI: Update context bar when using undo/redo
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#4489 UI: Fix reordering scenes not working properly
  UI/window-basic-main.cpp
Labels: Bug Fix

#4448 UI: Fix wrong behavior with undo/redo and groups
  UI/window-basic-transform.cpp
  libobs/obs-scene.c
Labels: Bug Fix

#4477 obs-ffmpeg: Expose psycho-aq setting
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Bug Fix

#4454 UI: Fix spamming of log when setting current scene
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#4495 Remove Azure Pipelines from CI
  README.rst
  azure-pipelines.yml
Labels: Code Cleanup

#4503 CI: Specify arch for prebuilt deps
  .github/workflows/main.yml
  CI/full-build-macos.sh
Labels: Seeking Testers

#4505 vlc-video: Ignore URLs when checking for missing files
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#4514 UI: Use newer Twitch Dashboard docks for integration
  UI/auth-twitch.cpp
Labels: Bug Fix, Code Cleanup

#4513 mac-virtualcam: Fix memory leaks
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Labels: Bug Fix, macOS

#4507 libobs: Return target vec not current when within EPSILON
  libobs/graphics/math-extra.c
Labels: Bug Fix

#4512 mac-capture: Add another virtual audio device to the list
  plugins/mac-capture/audio-device-enum.c
Labels: Enhancement, macOS

#4508 mac-virtualcam: Hide logging behind debug flag
  plugins/mac-virtualcam/src/dal-plugin/Logging.h
Labels: Bug Fix, Code Cleanup

#4431 Reenable browser source in Flatpak
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers

#4529 UI: Fix missing files dialog crash loading source icon
  UI/window-missing-files.cpp
Labels: Bug Fix

#4550 UI: Fix invalid check for Remove Multiple Sources dialog result
  UI/window-basic-main.cpp
Labels: Bug Fix

#4544 UI: Fix crash when closing missing files window
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#4552 Make VirtualCam work with Flatpak
  CI/flatpak/com.obsproject.Studio.json
  plugins/linux-v4l2/v4l2-output.c
Labels: Bug Fix

#4542 CI: Use flatpak-builder subaction
  .github/workflows/flatpak.yml
Labels: Code Cleanup, Enhancement

#4537 UI: Delete unimplemented declaration, LoadProfile()
  UI/window-basic-main.hpp
Labels: Code Cleanup

#4549 obs-transitions: Track Matte fixes for Source Visibility transitions
  plugins/obs-transitions/transition-stinger.c
Labels: Bug Fix

#4559 rtmp-service: Add Luzento.com
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4582 obs-filters: Reduce NVIDIA AFX loading delays
  plugins/obs-filters/noise-suppress-filter.c
Labels: Enhancement, Seeking Testers, Windows

#4532 obs-filters: Better describe denoiser methods in menu
  plugins/obs-filters/data/locale/en-US.ini
Labels: Code Cleanup

#4574 libobs: Fix crash when calling missing files functions on a source with invalid context data
  libobs/obs-source.c
Labels: Bug Fix

#4573 Switch transition interpolation back to nonlinear SRGB
  plugins/obs-transitions/data/fade_to_color_transition.effect
  plugins/obs-transitions/transition-fade-to-color.c
  plugins/obs-transitions/transition-fade.c
  plugins/obs-transitions/transition-luma-wipe.c
  plugins/obs-transitions/transition-slide.c
  plugins/obs-transitions/transition-swipe.c
Labels: Bug Fix

#4586 text-freetype2: Render in nonlinear space
  plugins/text-freetype2/text-freetype2.c
Labels: Bug Fix

#4587 Apply alpha in nonlinear space for images and async video
  libobs/data/default.effect
  libobs/obs-source.c
  plugins/image-source/image-source.c
Labels: Bug Fix

#4580 UI: Cleanup on_scenes_currentItemChanged function
  UI/window-basic-main.cpp
Labels: Code Cleanup

#4608 obs-filters: Use correct branding for NVIDIA Noise Removal
  plugins/obs-filters/data/locale/en-US.ini
Labels: Bug Fix, Seeking Testers

#4572 CI: use a stable version of the flatpak action
  .github/workflows/flatpak.yml
Labels: Code Cleanup, Seeking Testers

#4619 obs-filters: Fix bad math in Color Key v1
  plugins/obs-filters/data/color_key_filter.effect
Labels: Bug Fix, Seeking Testers

#4627 UI: Fix Undo/Redo for pasting multiple filters
  UI/window-basic-main.cpp
Labels: Bug Fix
