Repository obsproject/obs-studio, pull requests merged in 2021-01, with the labels that each got.

#3995 libobs: Update to SIMDe 0.7.0 via a single file
  CMakeLists.txt
  libobs/CMakeLists.txt
  libobs/obsconfig.h.in
  libobs/util/simde/README.libobs
  libobs/util/simde/check.h
  libobs/util/simde/hedley.h
  libobs/util/simde/simde-align.h
  libobs/util/simde/simde-arch.h
  libobs/util/simde/simde-common.h
  libobs/util/simde/simde-constify.h
  libobs/util/simde/simde-detect-clang.h
  libobs/util/simde/simde-diagnostic.h
  libobs/util/simde/simde-features.h
  libobs/util/simde/simde-math.h
  libobs/util/simde/x86/mmx.h
  libobs/util/simde/x86/sse.h
  libobs/util/simde/x86/sse2.h
  libobs/util/sse-intrin.h
  libobs/util/sse2neon.h
Labels: Code Cleanup, Enhancement

#3965 docs/sphinx: Add missing obs_frontend_open_projector
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation

#3994 image-source: Fix slideshow transition not working when randomized
  plugins/image-source/obs-slideshow.c
Labels: Bug Fix

#3954 UI: Fix padding on Acri context bar buttons
  UI/data/themes/Acri.qss
Labels: Bug Fix

#3879 linux-jack: fix timestamps, deadlock on shutdown, and port type
  plugins/linux-jack/jack-wrapper.c
Labels: Bug Fix

#4026 rtmp-services: Add MyFreeCams
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4028 rtmp-services: Add CamSoda service
  plugins/rtmp-services/data/services.json
Labels: Services

#3933 libobs: Add texture sharing support for macOS/OpenGL
  .github/workflows/main.yml
  CI/full-build-macos.sh
  libobs-opengl/gl-cocoa.m
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
Labels: Enhancement, macOS

#3934 UI: Enable HW acceleration switch for browser sources on Mac
  UI/obs-app.cpp
  UI/window-basic-settings.cpp
Labels: Enhancement, macOS

#4040 CI: Update Qt and Deps on Windows
  .github/workflows/main.yml
  CI/install-qt-win.cmd
  CI/install-script-win.cmd
Labels: Bug Fix

#4030 libobs: Fix gs_duplicator_get_texture function check
  libobs/graphics/graphics.c
Labels: Bug Fix, Incomplete

#4003 .gitattributes: Normalize en-US.ini
  .gitattributes
Labels: Code Cleanup

#4049 obs-qsv11: Fix bframes=0 not working
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
Labels: Bug Fix

#3930 libobs: Fix missing Linux libraries with certain flags
  libobs/CMakeLists.txt
Labels: Bug Fix, Linux

#4004 linux-v4l2: Improve error and debug logging
  plugins/linux-v4l2/v4l2-helpers.c
  plugins/linux-v4l2/v4l2-helpers.h
  plugins/linux-v4l2/v4l2-input.c
Labels: Code Cleanup, Linux

#3996 UI: Fix crash in Source Toolbar
  UI/context-bar-controls.cpp
Labels: Bug Fix, Enhancement, Linux

#3910 libobs: Cleanup uses of objc_msgSend in Objective-C code
  libobs/obs-cocoa.m
Labels: Code Cleanup, macOS

#4057 rtmp-services: Add Glimesh service
  UI/window-basic-auto-config.cpp
  UI/window-basic-settings-stream.cpp
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3867 ftl-stream: Fix reconnect loop on FTL ingest disconnect
  plugins/obs-outputs/ftl-stream.c
Labels: Bug Fix

#3864 obs-ffmpeg: Fix media sources not reconnecting properly
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#3834 UI: Support FTL URLs for custom streaming service
  UI/window-basic-main-outputs.cpp
  plugins/obs-outputs/ftl-stream.c
Labels: Enhancement

#3844 obs-frontend-api: Add frontend api functions for the virtual camera
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  docs/sphinx/reference-frontend-api.rst
Labels: Enhancement

#3913 rtmp-services: update Piczel.tv recommended
  plugins/rtmp-services/data/services.json
Labels: Services

#4061 rtmp-services: Use official Twitch endpoint to fetch ingests
  plugins/rtmp-services/twitch.c
Labels: Enhancement

#4073 UI: Use FileNameWithoutSpace for screenshot output
  UI/window-basic-main-screenshot.cpp
Labels: Bug Fix

#4070 libobs-winrt: Disable WGC border on insider SDK
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-dispatch.cpp
Labels: Enhancement, Windows

#4069 UI: Add virtual camera to system tray
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#4067 Load plugins from path specified by OBS_PLUGINS_PATH
  UI/window-basic-main.cpp
Labels: Enhancement

#4060 CI: Fix CEF version for both Linux & macOS
  CI/before-script-linux.sh
  CI/full-build-macos.sh
  CI/install-dependencies-linux.sh
  azure-pipelines.yml
Labels: Bug Fix, Seeking Testers

#4080 mac-virtualcam: Make DAL filename case consistent
  plugins/mac-virtualcam/src/dal-plugin/OBSDALDevice.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugIn.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugIn.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInMain.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
Labels: Bug Fix, macOS

#4052 UI: Fix color of filters icon
  UI/data/themes/Dark/filter.svg
Labels: Bug Fix

#4051 UI: Add interact button to source toolbar
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/interact.svg
  UI/forms/OBSBasic.ui
  UI/forms/images/interact.svg
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#4018 obs-outputs: Use system-wide FTL-SDK if present
  plugins/obs-outputs/CMakeLists.txt
Labels: Bug Fix

#3816 deps: Update cmake_minimum_required to 2.8.12
  deps/jansson/CMakeLists.txt
  deps/libcaption/CMakeLists.txt
  deps/libff/CMakeLists.txt
  deps/obs-scripting/CMakeLists.txt
  deps/obs-scripting/obslua/CMakeLists.txt
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Code Cleanup

#3825 UI: Fix mac can't use crash report in menu tab
  UI/window-basic-main.cpp
Labels: Bug Fix, macOS

#3812 libobs: Add os_is_obs_plugin function
  docs/sphinx/reference-libobs-util-platform.rst
  libobs/obs-module.c
  libobs/util/platform-nix.c
  libobs/util/platform-windows.c
  libobs/util/platform.h
Labels: Enhancement, Seeking Testers

#3811 UI: Replace deprecated QLayout->setMargin with setContentsMargin
  UI/hotkey-edit.hpp
  UI/window-importer.cpp
  UI/window-remux.cpp
Labels: Bug Fix, Code Cleanup

#4106 mac-avcapture: Add additional capture presets
  plugins/mac-avcapture/av-capture.mm
Labels: Enhancement

#4005 linux-v4l2: Add auto reset on timeout option
  plugins/linux-v4l2/data/locale/en-US.ini
  plugins/linux-v4l2/v4l2-helpers.c
  plugins/linux-v4l2/v4l2-helpers.h
  plugins/linux-v4l2/v4l2-input.c
Labels: Enhancement, Linux

#4114 libobs: Fix dstr leak
  libobs/util/platform-windows.c
Labels: Bug Fix

#4122 obs-filters: Fix pow arguments
  plugins/obs-filters/data/chroma_key_filter_v2.effect
  plugins/obs-filters/data/color_correction_filter.effect
  plugins/obs-filters/data/color_key_filter_v2.effect
Labels: Bug Fix

#4132 libobs, linux-v4l2: Set thread names
  libobs/obs-hotkey.c
  plugins/linux-v4l2/v4l2-input.c
Labels: Code Cleanup

#4127 rtmp-services: Update MyFreeCams
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#3871 libobs: Add function to get module lib
  docs/sphinx/reference-modules.rst
  libobs/obs-module.c
  libobs/obs.h
Labels: Enhancement

#4136 linux-capture: Fix lock ordering
  plugins/linux-capture/xcompcap-main.cpp
Labels: Bug Fix

#4130 CI: use a KDE image for Flatpak
  .github/workflows/flatpak.yml
Labels: Bug Fix, Seeking Testers

#3819 libobs: Duplicate source name for private sources
  libobs/obs-scene.c
Labels: Bug Fix

#4149 libcaption: Fix header missing in install
  deps/libcaption/CMakeLists.txt
Labels: Bug Fix

#4141 rtmp-services: Add PolyStreamer service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#4151 linux-capture: Ensure locks are initialized
  plugins/linux-capture/xcompcap-main.cpp
Labels: Bug Fix

#4158 libobs: Fix leaking obs-internal.h
  deps/libcaption/CMakeLists.txt
  libobs/obs-scene.c
  libobs/obs-scene.h
Labels: Code Cleanup

#4144 linux-v4l2: added range check for try_connect()
  plugins/linux-v4l2/v4l2-output.c
Labels: Code Cleanup

#4162 Another warning clean-up pass
  UI/platform-x11.cpp
  UI/window-basic-main.cpp
  deps/libcaption/caption/caption.h
  deps/libcaption/caption/cea708.h
  libobs-opengl/gl-subsystem.c
  libobs/obs-audio.c
  libobs/util/platform-nix.c
  plugins/linux-v4l2/v4l2-output.c
  plugins/obs-filters/luma-key-filter.c
  plugins/rtmp-services/rtmp-custom.c
Labels: Code Cleanup

#4140 Add display capture via Windows Graphics Capture
  libobs-d3d11/d3d11-duplicator.cpp
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
  plugins/win-capture/data/locale/en-US.ini
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/window-capture.c
Labels: Enhancement, Windows

#2233 libobs + UI: Add Missing Files API & Dialog
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/alert.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/OBSMissingFiles.ui
  UI/forms/images/alert.svg
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-missing-files.cpp
  UI/window-missing-files.hpp
  libobs/CMakeLists.txt
  libobs/obs-missing-files.c
  libobs/obs-missing-files.h
  libobs/obs-source.c
  libobs/obs-source.h
  libobs/obs.h
  plugins/image-source/image-source.c
  plugins/image-source/obs-slideshow.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
  plugins/obs-text/gdiplus/obs-text.cpp
  plugins/text-freetype2/text-freetype2.c
  plugins/text-freetype2/text-freetype2.h
  plugins/vlc-video/vlc-video-source.c
Labels: Enhancement, Request for Comments, Seeking Testers
