Repository obsproject/obs-studio, pull requests merged in 2022-06, with the labels that each got.

#6575 rtmp-services: Update Eventials ingests
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#6576 CI: Update deps to obs-deps 2022-05-23 releases
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, Seeking Testers, CI

#6584 libobs: Ensure active copy surfaces are active
  libobs/obs-video.c
Labels: Bug Fix

#6555 libobs: Deprecate obs_hotkey_enable_strict_modifiers
  libobs/obs-hotkey.h
Labels: Code Cleanup

#6521 UI: Simple Output Mode for NVENC HEVC
  UI/data/locale/en-US.ini
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
Labels: New Feature, UI/UX

#6593 CI: Fix FreeBSD definition of streaming service
  CI/freebsd/02_build_obs.sh
Labels: Bug Fix

#6597 UI: Fix multithread-unsafe GetCurrentScene
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#6602 libobs-opengl: Remove unused code
  libobs-opengl/gl-x11-egl.c
Labels: Code Cleanup, Linux

#6590 obs-ffmpeg: Remove codec property from VAAPI encoder
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Code Cleanup

#6606 UI: handle theme file names with "." characters
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6604 UI: Fix position of reset filters button
  UI/forms/OBSBasicFilters.ui
Labels: Enhancement, UI/UX

#6603 UI: Make transform dialog spinboxes consistant
  UI/forms/OBSBasicTransform.ui
Labels: Enhancement, UI/UX

#6610 decklink: Avoid sending 0x0 frame to libobs
  plugins/decklink/decklink-device-instance.cpp
Labels: Bug Fix

#6613 UI: Add eventFilter to media slider
  UI/media-slider.cpp
  UI/media-slider.hpp
Labels: Bug Fix

#6573 mac-virtualcam: Avoid transcoding where possible
  plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.h
  plugins/mac-virtualcam/src/dal-plugin/CMSampleBufferUtils.mm
  plugins/mac-virtualcam/src/dal-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugIn.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.h
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
  plugins/mac-virtualcam/src/obs-plugin/CMakeLists.txt
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.h
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Enhancement, Code Cleanup, macOS

#5420 linux-v4l2: Support for H264 codec
  plugins/linux-v4l2/CMakeLists.txt
  plugins/linux-v4l2/v4l2-decoder.c
  plugins/linux-v4l2/v4l2-decoder.h
  plugins/linux-v4l2/v4l2-input.c
Labels: Enhancement, Linux

#6569 UI: Cleanup advanced audio window
  UI/CMakeLists.txt
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/forms/OBSAdvAudio.ui
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
Labels: Enhancement

#6618 deps/media-playback: Fix metadata for hw_accel
  deps/media-playback/media-playback/decode.c
Labels: Bug Fix

#6622 libobs/util: Add function to get Rosetta translation status
  UI/obs-app.cpp
  UI/platform-osx.mm
  UI/platform.hpp
  docs/sphinx/reference-libobs-util-platform.rst
  libobs/util/platform-cocoa.m
  libobs/util/platform-nix.c
  libobs/util/platform-windows.c
  libobs/util/platform.h
Labels: Enhancement, Seeking Testers

#6650 UI: Fix cut transition not being initialised
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#6628 Check return value of obs_encoder_get_extra_data
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-outputs/flv-output.c
  plugins/obs-outputs/ftl-stream.c
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix

#6633 UI: Fix crash if missing module in context bar
  UI/context-bar-controls.cpp
Labels: Bug Fix

#6634 mac-avcapture: Make "High" preset default
  plugins/mac-avcapture/av-capture.mm
Labels: Enhancement, macOS

#6639 mac-virtualcam: Fix IOSurface memory leak
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
  plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
Labels: Bug Fix, macOS

#6636 rtmp-services: Add Mildom and Nonolive
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#6644 mac-vth264: Fix PTS passed to the encoder
  plugins/mac-vth264/encoder.c
Labels: Bug Fix, macOS

#6645 Various cleanups to linux-pipewire
  plugins/linux-pipewire/CMakeLists.txt
  plugins/linux-pipewire/linux-pipewire.c
  plugins/linux-pipewire/pipewire-capture.c
  plugins/linux-pipewire/pipewire.c
  plugins/linux-pipewire/pipewire.h
  plugins/linux-pipewire/portal.c
  plugins/linux-pipewire/portal.h
  plugins/linux-pipewire/screencast-portal.c
  plugins/linux-pipewire/screencast-portal.h
Labels: Code Cleanup, Seeking Testers, Linux

#6653 CI: Use static 7zip build instead of PPA
  .github/workflows/steam.yml
Labels: Bug Fix

#6530 UI: Disable network features if a non-RTMP service is set
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/streaming-helpers.cpp
  UI/streaming-helpers.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement, UI/UX

#3726 UI: Add ability to reset entire UI
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#5263 UI: Try closing remux before initiating shutdown
  UI/window-basic-main.cpp
Labels: Bug Fix

#5160 Add info (text label) property as text sub-type in properties API
  UI/properties-view.cpp
  docs/sphinx/reference-properties.rst
  libobs/obs-properties.c
  libobs/obs-properties.h
Labels: New Feature, UI/UX

#6656 CI: Fix git usage inside Flatpak action container
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
Labels: Bug Fix, CI

#6672 UI: Fix YouTube Chat build failure with Qt 6
  UI/auth-youtube.cpp
Labels: Bug Fix
