Repository obsproject/obs-studio, pull requests merged in 2022-10, with the labels that each got.

#7450 obs-scripting: Fix compile when python is not found
  deps/obs-scripting/obs-scripting.c
Labels: Bug Fix

#7477 UI: Fix AutoRemux not working in Simple Output mode when custom FFmpeg output is configured
  UI/window-basic-main.cpp
Labels: Bug Fix, Seeking Testers

#7467 CI: fix build on non-x86 Linux platforms
  CI/linux/01_install_dependencies.sh
Labels: Bug Fix, Linux

#7480 docs: Add links to python functions
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-libobs-callback.rst
  docs/sphinx/reference-properties.rst
  docs/sphinx/reference-scenes.rst
Labels: Documentation

#7482 obs-scripting: Re-enable Python annotations; Enable Python autodoc
  deps/obs-scripting/obspython/obspython.i
Labels: Bug Fix, Enhancement

#7484 UI: Remove unnecessary styles
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Code Cleanup

#7486 UI: Fix tabstop on settings dialog
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix, Enhancement, UI/UX

#7494 mac-videotoolbox: Remove unused defines
  plugins/mac-videotoolbox/data/locale/en-US.ini
  plugins/mac-videotoolbox/encoder.c
Labels: Code Cleanup, macOS

#7248 UI: Fix alignment of volume sliders
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/volume-control.cpp
Labels: Bug Fix, UI/UX

#7555 rtmp-services: Update Glimesh to add RTMP ingests
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7573 win-capture: Fix reporting valid width and height if not capturing
  plugins/win-capture/game-capture.c
Labels: Bug Fix, Seeking Testers, Windows

#7566 UI: Clamp float values possibly representing infinity to integer size
  UI/volume-control.cpp
  UI/volume-control.hpp
Labels: Bug Fix, Seeking Testers

#7565 win-capture: Update D3D9 signature for Win 11 22H2
  plugins/win-capture/get-graphics-offsets/d3d9-offsets.cpp
Labels: Seeking Testers, Windows

#7561 UI: Fix NVENC AV1 preset while resetting encoders
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix, Windows

#7558 linux-pulseaudio: Use DONT_MOVE for non-default devices
  plugins/linux-pulseaudio/pulse-input.c
Labels: Bug Fix, Linux

#7556 obs-vst: Toggle properties button visibility upon VST selection
  plugins/obs-vst/obs-vst.cpp
Labels: Bug Fix, Seeking Testers

#7570 rtmp-services: Update ingest list for Restream.io
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7551 vlc-video: Fix crash at removing files from missing-file dialog
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#7513 mac-videotoolbox: Remove "None" profile
  plugins/mac-videotoolbox/data/locale/en-US.ini
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix, macOS

#7563 obs-scripting: Fix script state variable being reset by tick callback
  deps/obs-scripting/obs-scripting-python.c
Labels: Bug Fix, Seeking Testers

#7553 mac-capture: Log CoreAudio device sample rate
  plugins/mac-capture/mac-audio.c
Labels: Enhancement

#7600 UI: Swap mq and hq NVENC Preset mappings
  UI/obs-app.cpp
Labels: Bug Fix

#7589 UI: Fix possible crash due to UI property access from graphics thread
  UI/window-basic-preview.cpp
Labels: Bug Fix, Seeking Testers

#7583 obs-frontend-api: Add theme functions
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#7599 UI: Use correct title for failed replay buffer start
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#7603 CI: Update GitHub Actions for set-output deprecation
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
  .github/workflows/steam.yml
Labels: Bug Fix, Enhancement, Seeking Testers, CI

#7605 CI: Fix services check using deprecated GHA output
  CI/check-services.py
Labels: CI

#7581 mac-virtualcam: Fix crashes in apps loading virtual camera and performance fixes
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, Seeking Testers, macOS

#7620 CI: Fix Steam launching x86 version under Rosetta
  CI/steam/scripts_macos/launch.sh
Labels: Bug Fix, CI

#7606 UI: Fix theme if apply and cancel in settings
  UI/window-basic-settings.cpp
Labels: Bug Fix

#7613 UI: Fix stats widget apparence and font size
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/window-basic-stats.cpp
  UI/window-basic-stats.hpp
Labels: Bug Fix, Seeking Testers, UI/UX

#7587 docs: Fix sphinx import error on Python 3.10+
  docs/sphinx/conf.py
  docs/sphinx/requirements.txt
Labels: Bug Fix

#7078 Fix virtual camera can only be started once on Linux
  plugins/linux-v4l2/v4l2-output.c
Labels: Bug Fix, Linux

#7621 UI: Hide --portable from help text if disallowed
  UI/obs-app.cpp
Labels: Enhancement

#7625 UI: Set preset2 instead preset for simple mode NVENC
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix, Seeking Testers

#7585 obs-frontend-api: Add screenshot event
  UI/obs-frontend-api/obs-frontend-api.h
  UI/window-basic-main-screenshot.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#7629 UI: Fix stream setting page being wrong on Wayland
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix, Seeking Testers

#7644 UI: Fix placeholder element not being deleted
  UI/window-basic-about.cpp
Labels: Bug Fix

#7554 rtmp-services: Add Vindral service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7153 obs-filters: Add upward compressor filter
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/expander-filter.c
  plugins/obs-filters/obs-filters.c
Labels: Seeking Testers, New Feature

#7673 obs-ffmpeg: Fix Ubuntu 20.04 detection
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Linux

#7682 obs-filters: Fix typo in Upward.Compressor
  plugins/obs-filters/data/locale/en-US.ini
Labels: Bug Fix

#7645 win-capture: Disable clang-format for assembly patterns
  plugins/win-capture/get-graphics-offsets/d3d9-offsets.cpp
Labels: Code Cleanup

#7650 libobs: Add media key support for linux
  libobs/obs-nix-wayland.c
  libobs/obs-nix-x11.c
Labels: Enhancement, Linux

#7671 libobs: Fix blend method in studio mode
  libobs/obs-scene.c
Labels: Bug Fix

#7680 obs-frontend-api: Add functions to get last saved files
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main-screenshot.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#7652 UI: Change adv audio background color
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#7693 Adjust NVENC preset migrations
  UI/obs-app.cpp
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix, Enhancement, Seeking Testers

#7692 libobs: Force SRGB conversion for tonemapped video
  libobs/obs-source.c
Labels: Bug Fix
