Repository obsproject/obs-studio, pull requests merged in 2022-08, with the labels that each got.

#6887 libobs: obs-ffmpeg: Update codec priority handling
  libobs/obs-avc.c
  libobs/obs-avc.h
  libobs/obs-hevc.c
  libobs/obs-hevc.h
  libobs/obs-nal.h
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.h
Labels: Enhancement

#6888 win-wasapi: Don't log if reconnect fails
  plugins/win-wasapi/win-wasapi.cpp
Labels: Enhancement

#6890 UI: Restore color format/space warning
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Bug Fix

#6891 obs-ffmpeg: Make muxers respect ENABLE_HEVC
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
Labels: Bug Fix

#6886 UI: Remove compatibility for QT < 5.10
  UI/auth-youtube.cpp
  UI/auth-youtube.hpp
  UI/obs-proxy-style.cpp
  UI/properties-view.cpp
Labels: Code Cleanup

#6881 UI: Fix crash if there is no monitoring available
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6892 media-playback: Fix crash on free
  deps/media-playback/media-playback/decode.c
Labels: Bug Fix

#6241 CI: Change build file names
  .github/workflows/main.yml
  CI/freebsd/03_package_obs.sh
  CI/linux/03_package_obs.sh
  CI/macos/03_package_obs.sh
  CI/windows/03_package_obs.ps1
Labels: Code Cleanup, Seeking Testers, CI

#6900 aja: Remove unused code from output plugin
  plugins/aja/aja-output.cpp
  plugins/aja/aja-output.hpp
Labels: Code Cleanup

#6902 CI: Fix packaging scripts
  .github/workflows/main.yml
  CI/linux/03_package_obs.sh
  CI/macos/03_package_obs.sh
  CI/windows/03_package_obs.ps1
Labels: Bug Fix, CI

#6904 CI: Update deps to obs-deps 2022-08-02 release
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, Seeking Testers

#6910 UI: Properly store manual file splitting type
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6912 UI: Add missing Icon in Rachni theme
  UI/data/themes/Rachni.qss
Labels: Bug Fix

#6913 UI: Add missing Icon in Acri theme
  UI/data/themes/Acri.qss
Labels: Bug Fix

#6918 CI: Install Xcode 14 beta for tagged builds
  .github/workflows/main.yml
Labels: macOS, CI

#6915 obs-scripting: Fix issues between runtime and compile-time versions
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obs-scripting-python-import.h
  deps/obs-scripting/obs-scripting-python.c
Labels: Bug Fix, Seeking Testers

#6898 CI: Update Steam workflow for Apple Silicon builds
  .github/workflows/steam.yml
  CI/steam/scripts_macos/launch.sh
  CI/steam/scripts_windows/install.bat
  CI/steam/scripts_windows/installscript.vdf
  CI/steam/scripts_windows/uninstall.bat
Labels: CI

#6921 CI: Fix Flathub workflow tag validation
  .github/workflows/flatpak.yml
Labels: CI

#6920 mac-capture: Show "hidden" checkbox for app capture on update as well
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix, macOS

#6952 UI: Don't hardcode margins in lineedit-autoresize
  UI/lineedit-autoresize.cpp
Labels: Bug Fix

#6943 obs-ffmpeg, obs-transitions: Use property suffixes Pt. 2
  plugins/obs-ffmpeg/texture-amf.cpp
  plugins/obs-transitions/data/locale/en-US.ini
  plugins/obs-transitions/transition-stinger.c
Labels: Bug Fix

#6933 UI: Unregister file splitting hotkey when clearing hotkeys
  UI/window-basic-main.cpp
Labels: Bug Fix

#6945 cmake: fix default version if `git describe` fails
  cmake/Modules/VersionConfig.cmake
Labels: Bug Fix

#6925 UI: Increase maximum limit of automatic file splitting
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix, Enhancement

#6926 test: Only build osx tests for OS_MACOS
  test/CMakeLists.txt
Labels: Bug Fix

#6930 UI: Make spacing helpers DPI aware
  UI/window-basic-preview.cpp
Labels: Bug Fix

#6935 Fix typo in Yami theme
  UI/data/themes/Yami.qss
Labels: Bug Fix

#6941 UI: Fix spacer lines not using accessibility color
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
Labels: Bug Fix

#6942 libobs: Prevent D3D11 projectors from tearing
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-opengl/gl-cocoa.m
  libobs-opengl/gl-nix.c
  libobs-opengl/gl-windows.c
  libobs/graphics/device-exports.h
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
  libobs/obs-display.c
Labels: Enhancement, Windows

#6951 UI: Fix buttons in settings dialog
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#6963 obs-ffmpeg: Fix crash when retrying init encoder for NVENC
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix

#6964 UI: Fix spacing with media controls
  UI/forms/source-toolbar/media-controls.ui
Labels: Bug Fix

#6967 flatpak: Use FFmpeg GitHub mirror
  CI/flatpak/com.obsproject.Studio.json
Labels: Bug Fix, Enhancement, CI

#6973 win-wasapi: Add missing locale text
  plugins/win-wasapi/data/locale/en-US.ini
Labels: Bug Fix

#6971 obs-ffmpeg: fix USAGE typo
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Code Cleanup

#6922 obs-filters: Reset RTX greenscreen on cuda error
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Bug Fix

#6980 libobs: Fix missing pair of GS_DEBUG_MARKER
  libobs/obs-display.c
Labels: Bug Fix

#6981 cmake: Fix plugin RPATH entry on Linux
  cmake/Modules/ObsDefaults_Linux.cmake
Labels: Bug Fix, Linux

#6987 UI: Fix ffmpeg path browse button not showing
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#6958 obs-scripting: Fix SWIG flags for non-macOS POSIX
  deps/obs-scripting/CMakeLists.txt
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Bug Fix

#6988 obs-filters: Fix NVIDIA greenscreen issues
  plugins/obs-filters/data/rtx_greenscreen.effect
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Bug Fix, Seeking Testers

#6994 cmake: Fix broken pthread detection on Windows with CMake 3.24
  cmake/Modules/CompilerConfig.cmake
Labels: Bug Fix, Windows

#6997 cmake: Fix M1-based OBS.app appearing as an "iOS" app
  cmake/bundle/macOS/Info.plist.in
Labels: Bug Fix, Seeking Testers, macOS

#6929 UI/installer: Require Windows 10 64bit minimum
  UI/installer/mp-installer.nsi
Labels: Enhancement, Windows

#6978 mac-videotoolbox: Reject color formats other than NV12 and I420
  plugins/mac-videotoolbox/data/locale/en-US.ini
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix, macOS

#7008 libobs-opengl: Check window creation for errors
  libobs-opengl/gl-x11-egl.c
Labels: Enhancement, Linux

#7014 cmake: Fix cmake package export templates for CMake 3.24
  deps/w32-pthreads/cmake/w32-pthreadsConfig.cmake.in
  libobs/cmake/libobsConfig.cmake.in
Labels: Bug Fix, Windows

#7013 mac-videotoolbox: Fix typo 'diffent'
  plugins/mac-videotoolbox/data/locale/en-US.ini
Labels: Bug Fix

#6992 obs-filters: Support HDR AI greenscreen
  plugins/obs-filters/data/color.effect
  plugins/obs-filters/data/rtx_greenscreen.effect
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Enhancement, Seeking Testers

#6983 libobs: Remove display GPU markers without draws
  libobs/obs-display.c
Labels: Enhancement

#6577 libobs: Add support for multiple video mixes
  UI/CMakeLists.txt
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicVCamConfig.ui
  UI/record-button.cpp
  UI/record-button.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-vcam-config.cpp
  UI/window-basic-vcam-config.hpp
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-source-deinterlace.c
  libobs/obs-video-gpu-encode.c
  libobs/obs-video.c
  libobs/obs-view.c
  libobs/obs.c
  libobs/obs.h
Labels: Seeking Testers, New Feature

#7017 obs-filters: Remove param from AI greenscreen
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Code Cleanup

#7016 libobs-d3d11: Force SDR for legacy swap chain
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Bug Fix

#7042 .gitignore: Add "install_temp" folder
  .gitignore
Labels: Code Cleanup

#7022 UI: Disable QDialog button icons on all non-system themes
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix, Linux, UI/UX

#7026 UI: Fix padding with vertical volume meters
  UI/volume-control.cpp
Labels: Bug Fix

#7032 obs-filters: Add HDR Tonemap filter
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-filters/data/color.effect
  plugins/obs-filters/data/hdr_tonemap_filter.effect
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/hdr-tonemap-filter.c
  plugins/obs-filters/obs-filters.c
Labels: New Feature

#7034 mac-virtualcam: Avoid conversion of P010
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, Enhancement, macOS

#7036 mac-virtualcam: Don't convert color space when converting color format
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, Enhancement, macOS

#7040 UI: Fix crash when pausing/unpausing recording
  UI/window-basic-main.cpp
Labels: Bug Fix

#7043 libobs: Fix gpu thread termination when additional video mixes are added
  libobs/obs-internal.h
  libobs/obs-video.c
  libobs/obs-view.c
  libobs/obs.c
Labels: Bug Fix

#7046 CI: Update FreeBSD Cirrus-CI configuration
  .cirrus.yml
Labels: Other OS (*nix), CI

#7003 win-capture: Fix memory leak in dc-capture.c
  plugins/win-capture/dc-capture.c
Labels: Bug Fix

#6982 UI: Fix settings properties view background
  UI/data/themes/Yami.qss
  UI/properties-view.cpp
Labels: Bug Fix

#7018 UI: Fix grid mode spacing with Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix

#7029 CI: Switch to included Xcode 14 Beta
  .github/workflows/main.yml
Labels: Seeking Testers, CI

#7035 README.rst: Update urls of translation guide and Crowdin badge
  README.rst
Labels: Enhancement, Documentation

#7055 win-dshow: Fix building without Virtual Camera
  plugins/win-dshow/CMakeLists.txt
Labels: Bug Fix

#6883 UI: Add WhatsNew Feature for *nix systems
  UI/CMakeLists.txt
  UI/data/OBSPublicRSAKey.pem
  UI/nix-update/crypto-helpers-mac.mm
  UI/nix-update/crypto-helpers-mbedtls.cpp
  UI/nix-update/crypto-helpers.hpp
  UI/nix-update/nix-update-helpers.cpp
  UI/nix-update/nix-update-helpers.hpp
  UI/nix-update/nix-update.cpp
  UI/nix-update/nix-update.hpp
  UI/obs-app.cpp
  UI/remote-text.cpp
  UI/window-basic-main.cpp
  deps/CMakeLists.txt
Labels: Seeking Testers, macOS, Linux, New Feature

#6747 linux-v4l2: Add socket to signal select on shutdown
  plugins/linux-v4l2/v4l2-udev.c
Labels: Enhancement

#7065 UI: Add missing Icon in System theme
  UI/data/themes/System.qss
Labels: Bug Fix, UI/UX

#7067 UI/themes: Add macOS separator fix to Dark and System
  UI/data/themes/Dark.qss
  UI/data/themes/System.qss
Labels: Bug Fix, UI/UX

#6966 UI: Fix Yami list widget hover color
  UI/data/themes/Yami.qss
Labels: Bug Fix

#7087 UI/themes: Add missing fixes on Yami variants
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
Labels: Bug Fix, UI/UX

#7082 CI: remove UNIX_STRUCTURE from FreeBSD Cirrus-CI config
  .cirrus.yml
Labels: Code Cleanup

#7045 UI: Fix theme leak
  UI/obs-app.cpp
  UI/obs-app.hpp
Labels: Bug Fix

#7079 obs-ffmpeg: Prevent invalid AMF combinations, and fix leaks
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Enhancement

#7080 obs-qsv11: Prevent 8-bit HDR, and 10-bit anything
  plugins/obs-qsv11/data/locale/en-US.ini
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#7081 obs-qsv11: Replace CRITICAL_SECTION with SRWLOCK
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix

#7090 obs-x264: Block 10-bit formats
  plugins/obs-x264/data/locale/en-US.ini
  plugins/obs-x264/obs-x264.c
Labels: Bug Fix, Enhancement

#7094 obs-ffmpeg: Block 8-bit HDR for AV1 encoders
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
Labels: Bug Fix, Enhancement

#7101 aja: Correct typos in README.md
  plugins/aja/README.md
Labels: Documentation

#7102 CI: Build ALSA support on FreeBSD
  .cirrus.yml
Labels: Enhancement

#7105 libobs: Read /etc/os-release on FreeBSD
  libobs/obs-nix.c
Labels: Enhancement

#7093 obs-ffmpeg: Prevent invalid NVENC combinations
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Bug Fix, Enhancement

#7107 UI: Fix use-after-free in properties view
  UI/properties-view.hpp
Labels: Bug Fix

#7041 obs-ffmpeg: Add b-frame logging for the AMD encoder
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Enhancement

#7052 obs-qsv11: Do not apply limits if CPU generation is unknown
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/obs-qsv11.c
Labels: Seeking Testers, Windows

#7033 UI: Fix crash when hiding audio mixer item
  UI/window-basic-main.cpp
Labels: Bug Fix, Linux

#7089 UI: Enforce macOS plugin bundle on M1; don’t load plugin bundles globally
  UI/window-basic-main.cpp
Labels: macOS

#7113 linux-v4l2: Correct udev fd poll event test
  plugins/linux-v4l2/v4l2-udev.c
Labels: Bug Fix

#7114 UI: Don't set theme if it didn't change
  UI/window-basic-settings.cpp
Labels: Bug Fix

#7116 UI: Only set QStyle on app start
  UI/obs-app.cpp
Labels: Bug Fix

#7121 libobs-d3d11: Unbind framebuffer before Present
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Enhancement, Windows

#7115 obs-x264: Remove unused HDR code
  plugins/obs-x264/obs-x264.c
Labels: Code Cleanup

#7117 UI: Free virtual cam memory on shutdown
  UI/window-basic-main.cpp
  UI/window-basic-vcam-config.cpp
  UI/window-basic-vcam-config.hpp
  libobs/obs-view.c
Labels: Bug Fix

#7119 UI: Remove unused stylesheet code
  UI/window-basic-main.cpp
Labels: Code Cleanup

#7118 UI: Reintroduce faster theme switching
  UI/obs-app.cpp
Labels: Bug Fix

#7123 UI: Save virtual camera config outside of the modules object
  UI/window-basic-main.cpp
  UI/window-basic-vcam-config.cpp
  UI/window-basic-vcam-config.hpp
Labels: Enhancement

#7023 UI: Fix sub-item's SpacingHelper render on group
  UI/window-basic-preview.cpp
Labels: Bug Fix, Enhancement

#6879 UI: Remove spaces from translation keys
  UI/obs-app.cpp
Labels: Bug Fix

#7126 UI: Check for virtual camera enablement before loading config
  UI/window-basic-main.cpp
Labels: Bug Fix

#7128 obs-ffmpeg: Fix ffmpeg_output memory leak
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix

#7129 libobs: Initialize main_view video mix before video thread
  libobs/obs.c
Labels: Bug Fix

#7135 mac-capture: Add missing locale text
  plugins/mac-capture/data/locale/en-US.ini
Labels: Bug Fix, macOS

#7142 UI: Use backspace icon to indicate "Clear" in hotkey-edit
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/entry-clear.svg
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Light/entry-clear.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/forms/images/entry-clear.svg
  UI/forms/obs.qrc
  UI/hotkey-edit.cpp
Labels: Bug Fix

#7145 cmake: Fix missing interface include directory on Framework export
  cmake/Modules/ObsHelpers_macOS.cmake
Labels: Bug Fix, macOS

#7125 UI: Reset volume/media sliders on theme change
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#7149 mac-capture: Clip gamut to sRGB
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix

#7152 UI: Properly register VoidFunc in Meta Object System
  UI/obs-app.cpp
Labels: Bug Fix

#7150 UI: Remove separate trash icon themeID
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/forms/images/trash.svg
  UI/forms/obs.qrc
  UI/window-extra-browsers.cpp
Labels: Code Cleanup

#7165 cmake: Set RELEASE_CANDIDATE/BETA based on git describe
  cmake/Modules/VersionConfig.cmake
Labels: Enhancement

#6965 UI: Fix disabled sliders with Yami
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#7166 UI: Fix scripts dialog buttons
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
Labels: Bug Fix

#7163 mac-capture: Use cleaner render patterns
  plugins/mac-capture/mac-screen-capture.m
Labels: Code Cleanup

#6969 UI: Force fixed font in plain text edits
  UI/CMakeLists.txt
  UI/crash-report.cpp
  UI/crash-report.hpp
  UI/forms/OBSLogViewer.ui
  UI/frontend-plugins/aja-output-ui/CMakeLists.txt
  UI/frontend-plugins/decklink-output-ui/CMakeLists.txt
  UI/frontend-plugins/frontend-tools/CMakeLists.txt
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/log-viewer.cpp
  UI/plain-text-edit.cpp
  UI/plain-text-edit.hpp
  UI/properties-view.cpp
Labels: Bug Fix, UI/UX

#7006 UI: Fix color select buttons with Yami
  UI/forms/ColorSelect.ui
Labels: Bug Fix, UI/UX

#7175 libobs: Emulate clear with draw for displays
  libobs/obs-display.c
Labels: Bug Fix, Windows

#7173 libobs: Fix Windows 10/11 Gamemode detection
  libobs/obs-windows.c
Labels: Bug Fix, Windows

#7162 libobs-opengl: Fix Mac projector color space
  libobs-opengl/gl-cocoa.m
Labels: Bug Fix

#7167 Fix crash when toggling volume control mode
  UI/window-basic-main.cpp
Labels: Bug Fix

#7161 UI: Fix extra browsers trash icon
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix

#7156 Remove allProjectors list from window-projector.cpp
  UI/window-projector.cpp
Labels: Bug Fix

#7148 obs-ffmpeg: Change AMF bitrate logging to kbps
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Enhancement

#7159 libobs: Use system header notation for pthread.h include
  libobs/CMakeLists.txt
  libobs/util/threading.h
Labels: Bug Fix, Windows

#7178 mac-capture: Replace false with 0
  plugins/mac-capture/mac-screen-capture.m
Labels: Code Cleanup

#7188 obs-filters: Fix HDR tonemap filter for scRGB
  plugins/obs-filters/hdr-tonemap-filter.c
Labels: Bug Fix

#7177 libobs: Avoid display clear workaround if possible
  libobs/obs-display.c
  libobs/obs-internal.h
Labels: Enhancement

#7198 obs-filters: Clarify that HDR Tone Mapping filter is optional
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/hdr-tonemap-filter.c
Labels: Enhancement

#6985 UI: Fix source tree item color height
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/source-tree.cpp
  UI/source-tree.hpp
Labels: Bug Fix, UI/UX

#7201 UI: Fix crash with adding source
  UI/source-tree.cpp
Labels: Bug Fix

#7193 obs-ffmpeg: Fix NVENC async usage pattern
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix

#7200 UI: Add workaround for scenes being unselected
  UI/scene-tree.cpp
  UI/scene-tree.hpp
Labels: Bug Fix

#7216 obs-ffmpeg: Don't use NVENC async mode
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix

#7214 libobs: Extend NVIDIA anti-flicker to desktops
  libobs/obs-display.c
Labels: Bug Fix

#7211 obs-ffmpeg: Add AVContentLightMetadata to MPEG-TS
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
Labels: Bug Fix

#7215 plugins: Rename Partial to Limited in localization files
  plugins/decklink/data/locale/en-US.ini
  plugins/linux-v4l2/data/locale/en-US.ini
  plugins/mac-avcapture/data/locale/en-US.ini
  plugins/obs-ffmpeg/data/locale/en-US.ini
Labels: Bug Fix, Enhancement

#7213 UI: Fix position of Sources dock actions on horizontal resize
  UI/source-tree.cpp
Labels: Bug Fix

#7195 UI: Make settings margins consistant
  UI/forms/OBSBasicSettings.ui
Labels: Enhancement, UI/UX

#7204 UI: Change groupbox radius
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Enhancement, UI/UX

#7203 UI: Fix Grid Mode operations
  UI/scene-tree.cpp
Labels: Bug Fix, UI/UX

#7202 UI: Fix scene tree item spacing
  UI/scene-tree.cpp
Labels: Bug Fix, UI/UX

#7223 obs-ffmpeg: Fix NVENC HEVC regression
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix

#7217 Non-Yami Theme Source Context Bar Height Fixes
  UI/data/themes/Dark.qss
  UI/data/themes/System.qss
Labels: Bug Fix, UI/UX

#7220 obs-ffmpeg: Log codec when creating NVENC encoders
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
Labels: Enhancement

#6500 Allow updater to delete files specified as removed in manifest
  UI/win-update/updater/hash.cpp
  UI/win-update/updater/updater.cpp
Labels: Windows, New Feature

#7229 UI: Fix source tree hovering being inconsistent
  UI/source-tree.cpp
  UI/source-tree.hpp
Labels: Bug Fix, UI/UX

#7221 UI: Fix styling of buttons in scene switcher dialog
  UI/frontend-plugins/frontend-tools/forms/auto-scene-switcher.ui
Labels: Bug Fix, UI/UX

#7222 UI: Make list widget styles consistent
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/forms/OBSBasicFilters.ui
  UI/frontend-plugins/frontend-tools/forms/auto-scene-switcher.ui
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/properties-view.cpp
Labels: Bug Fix, UI/UX

#7224 UI: Fix properties tool button styling
  UI/properties-view.cpp
Labels: Bug Fix, UI/UX
