Repository obsproject/obs-studio, pull requests merged in 2022-05, with the labels that each got.

#6414 libobs-winrt: Support window transparency for WGC
  libobs-winrt/winrt-capture.cpp
Labels: Enhancement, Windows

#5137 CI: Use manifest hash as Flatpak cache key
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
Labels: Code Cleanup, Seeking Testers, Linux

#5223 libobs: Orient images based on EXIF metadata
  libobs/graphics/graphics-ffmpeg.c
Labels: Bug Fix

#6231 Add support for GPU conversion of YUV422P10LE, YUV444P12LE, YUVA444P12LE
  deps/media-playback/media-playback/closest-format.h
  deps/media-playback/media-playback/media.c
  libobs/data/format_conversion.effect
  libobs/media-io/video-frame.c
  libobs/media-io/video-io.h
  libobs/media-io/video-matrices.c
  libobs/media-io/video-scaler-ffmpeg.c
  libobs/obs-internal.h
  libobs/obs-source.c
  libobs/obs-video.c
  libobs/obs.c
  plugins/obs-ffmpeg/obs-ffmpeg-formats.h
  plugins/win-dshow/ffmpeg-decode.c
Labels: New Feature

#6424 vlc-source: Fix surround sound not properly downmixed
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix, Seeking Testers

#6426 obs-x264: Disallow HDR attempts gracefully
  plugins/obs-x264/obs-x264.c
Labels: Bug Fix

#6402 vlc-video: Fix video rotation and aspect ratio
  plugins/vlc-video/vlc-video-plugin.c
  plugins/vlc-video/vlc-video-plugin.h
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#6416 mac-capture: Improve window capture performance
  plugins/mac-capture/mac-window-capture.m
Labels: Enhancement, macOS

#6434 UI: Restore portable mode on Windows
  UI/obs-app.cpp
Labels: Bug Fix, Windows

#6441 libobs: Reduce PQ shader math
  libobs/data/color.effect
Labels: Enhancement, Code Cleanup

#6454 libobs: Fix reserved word in variable names
  libobs/data/color.effect
Labels: Bug Fix

#6456 UI: Find Qt WinExtras only in Qt 5
  UI/CMakeLists.txt
Labels: Bug Fix

#6436 libobs,image-source,UI: Add JXR support on Windows
  UI/window-basic-main-dropfiles.cpp
  libobs/graphics/graphics-ffmpeg.c
  libobs/graphics/graphics.h
  libobs/graphics/image-file.c
  libobs/graphics/image-file.h
  libobs/obs-source-transition.c
  plugins/image-source/image-source.c
Labels: Windows, New Feature

#6091 linux-capture: Rewrite xcomposite
  CI/linux/01_install_dependencies.sh
  plugins/linux-capture/CMakeLists.txt
  plugins/linux-capture/linux-capture.c
  plugins/linux-capture/xcompcap-helper.cpp
  plugins/linux-capture/xcompcap-helper.hpp
  plugins/linux-capture/xcompcap-main.cpp
  plugins/linux-capture/xcompcap-main.hpp
  plugins/linux-capture/xcomposite-input.c
  plugins/linux-capture/xcomposite-input.h
  plugins/linux-capture/xcomposite-main.cpp
  plugins/linux-capture/xcursor-xcb.c
  plugins/linux-capture/xcursor-xcb.h
  plugins/linux-capture/xcursor.c
  plugins/linux-capture/xcursor.h
  plugins/linux-capture/xhelpers.c
  plugins/linux-capture/xhelpers.h
  plugins/linux-capture/xshm-input.c
Labels: Bug Fix, Enhancement, Code Cleanup, Seeking Testers, Linux

#6439 obs-scripting: Fix loading of scripting libraries with runtime lookup
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obs-scripting-python-import.h
Labels: Bug Fix, macOS

#6442 UI: Use Shift instead of Alt for Copy/Paste Transform
  UI/forms/OBSBasic.ui
Labels: Bug Fix

#6444 UI: Put program on top in vertical studio mode
  UI/window-basic-main.cpp
Labels: Enhancement

#6462 UI: Add rename signal to adv audio dialog
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
Labels: Bug Fix

#6467 libobs: Lock scene to video color space
  libobs/obs-scene.c
Labels: Bug Fix

#6470 libobs: Cap HLG video at 1000 nits
  libobs/obs-source.c
Labels: Enhancement

#6167 linux-v4l2: Fix camera reconnecting issue
  plugins/linux-v4l2/CMakeLists.txt
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix, Linux

#6494 UI: Fix memory leak with Manage Broadcast dialog
  UI/window-basic-main.cpp
Labels: Bug Fix

#6495 docs: Update speaker_layout enum values
  docs/sphinx/reference-libobs-media-io.rst
Labels: Documentation

#6464 Accept Qt 5 or Qt 6 in CopyMSVCBins and other improvements
  cmake/Modules/CopyMSVCBins.cmake
Labels: Enhancement, Windows

#6498 libobs: Ignore lower six bits for P010 sources
  libobs/data/format_conversion.effect
Labels: Bug Fix

#6499 libobs: Default 10-bit video to sRGB instead of PQ
  libobs/obs-internal.h
  libobs/obs-source.c
Labels: Enhancement

#6496 win-wasapi: Log source name when showing device errors
  plugins/win-wasapi/win-wasapi.cpp
Labels: Enhancement, Windows

#6476 obs-ffmpeg: Set 1000 nits for HLG metadata
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Enhancement

#6506 vlc-video: Fix sign-compare warning
  plugins/vlc-video/vlc-video-source.c
Labels: Code Cleanup

#6510 obs-ffmpeg: Nitpick/fixes for jim-nvenc
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix, Windows

#6371 UI: Move taskbar overlay functions into platform.hpp
  UI/platform-osx.mm
  UI/platform-windows.cpp
  UI/platform-x11.cpp
  UI/platform.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup, Windows

#6516 UI: Use correct terminology for Program in Studio Mode
  UI/data/locale/en-US.ini
Labels: Enhancement

#6518 libobs: Clamp audio NaN to 0.0f
  libobs/media-io/audio-io.c
Labels: Bug Fix

#6501 decklink-output-ui: Fix crash when stopping preview
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Labels: Bug Fix, Seeking Testers

#6488 deps/media-playback: Fix video looping
  deps/media-playback/media-playback/decode.c
  deps/media-playback/media-playback/decode.h
Labels: Bug Fix

#6505 libobs: Only warn when releasing non-NULL source
  libobs/obs-source.c
Labels: Bug Fix

#6509 UI: Don't transition in studio mode if scenes are the same
  UI/window-basic-main-transitions.cpp
Labels: Bug Fix

#6519 obs-ffmpeg: Remove duplicate "FFmpeg Options" locale
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Code Cleanup

#6520 UI: Remove m3u8 format from simple output mode
  UI/forms/OBSBasicSettings.ui
Labels: Enhancement

#6512 libobs: Fix hotkey with right-side modifiers
  libobs/obs-nix-x11.c
Labels: Bug Fix, Linux

#6527 CI: Ping authors of failed services in removal PR
  .github/workflows/services-json.yml
  CI/check-services.py
Labels: CI

#6528 CI: Update service-removal PR description
  CI/check-services.py
Labels: Enhancement, CI

#5449 mac-avcapture: Capture audio if supported
  plugins/mac-avcapture/av-capture.mm
  plugins/mac-avcapture/data/locale/en-US.ini
Labels: Enhancement, Seeking Testers, macOS

#6533 linux-capture: Check da_erase target is valid
  plugins/linux-capture/xcomposite-input.c
Labels: Bug Fix, Seeking Testers, Linux

#6538 UI: Add suffixes to transform dialog
  UI/forms/OBSBasicTransform.ui
Labels: Enhancement, UI/UX

#6549 obs-ffmpeg: Improve dialog text for NVENC errors
  plugins/obs-ffmpeg/jim-nvenc-helpers.c
  plugins/obs-ffmpeg/jim-nvenc.c
  plugins/obs-ffmpeg/jim-nvenc.h
Labels: Enhancement, Code Cleanup

#6391 libobs/util: Add %s string replacement for unix time
  UI/data/locale/en-US.ini
  libobs/util/platform.c
Labels: Enhancement, Seeking Testers

#6541 cmake: Fix enabling PulseAudio monitoring
  CMakeLists.txt
  libobs/CMakeLists.txt
  plugins/linux-pulseaudio/CMakeLists.txt
Labels: Bug Fix, Linux

#6526 libobs: Fix rendering null sprite
  libobs/obs-source.c
Labels: Bug Fix

#6487 UI: close display before native surfaces
  UI/qt-display.cpp
  UI/qt-display.hpp
  UI/window-basic-main.cpp
Labels: Bug Fix, Seeking Testers

#6475 Au revoir, GLX
  UI/obs-app.cpp
  UI/qt-wrappers.cpp
  deps/glad/CMakeLists.txt
  deps/glad/include/glad/glad_glx.h
  deps/glad/src/glad_glx.c
  libobs-opengl/CMakeLists.txt
  libobs-opengl/gl-nix.c
  libobs-opengl/gl-x11-glx.c
  libobs-opengl/gl-x11-glx.h
  libobs/obs-nix-platform.c
  libobs/obs-nix-platform.h
  libobs/obs-nix.c
  plugins/linux-capture/linux-capture.c
  plugins/linux-capture/xcomposite-input.c
  plugins/linux-pipewire/linux-pipewire.c
Labels: Code Cleanup, Seeking Testers, Linux

#5095 Don't trigger hotkeys without modifiers if user is holding down modifiers (strict)
  libobs/obs-hotkey.c
  libobs/obs.c
Labels: Bug Fix

#6490 UI: Truncate names in advanced audio dialog
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/qt-wrappers.cpp
  UI/qt-wrappers.hpp
Labels: Enhancement, UI/UX

#6561 flatpak: Install CMake config files
  CI/flatpak/com.obsproject.Studio.json
Labels: Bug Fix, Regression

#5717 Add additional buffer when writing to file with obs-ffmpeg-mux
  plugins/obs-ffmpeg/ffmpeg-mux/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Enhancement, Seeking Testers
