Repository obsproject/obs-studio, pull requests merged in 2022-09, with the labels that each got.

#7272 obs-ffmpeg: Fix seek offset being calculated incorrectly
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix, Seeking Testers

#7261 UI/updater: Only run updater on Windows 10+
  UI/win-update/updater/updater.cpp
  UI/win-update/updater/updater.hpp
Labels: Bug Fix, Enhancement

#7273 Revert "UI: Remove "Resize output (source size)" menu"
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: UI/UX

#7238 image-source: Add JXR HDR support to slide show
  plugins/image-source/obs-slideshow.c
Labels: Enhancement

#7290 libobs-winrt,win-capture: Allow forcing SDR
  libobs-winrt/winrt-capture.cpp
  libobs-winrt/winrt-capture.h
  plugins/win-capture/data/locale/en-US.ini
  plugins/win-capture/window-capture.c
Labels: Enhancement

#7296 cmake: Fix Sparkle framework permissions
  cmake/Modules/ObsHelpers_macOS.cmake
Labels: Bug Fix, Seeking Testers, macOS

#7306 obs-ffmpeg: Fix memory leak with mpegts
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
Labels: Bug Fix

#7308 win-capture: Remove unused wildcard code
  plugins/win-capture/window-capture.c
Labels: Code Cleanup

#7309 libobs: Remove unnecessary branch
  libobs/obs-video.c
Labels: Code Cleanup

#7320 UI: Don't save/overwrite browser docks if CEF hasn't loaded
  UI/window-basic-main.cpp
Labels: Bug Fix

#7335 image-source: Update media states when source is de-/activated
  plugins/image-source/obs-slideshow.c
Labels: Bug Fix

#7341 UI: Remove spacing from scene and source tree
  UI/forms/OBSBasic.ui
  UI/scene-tree.cpp
Labels: Bug Fix, UI/UX

#7352 linux-capture: Ensure name pixmap is checked
  plugins/linux-capture/xcomposite-input.c
Labels: Bug Fix, Linux

#7349 UI: Fix hotkey settings screen not accepting all input on macOS
  UI/hotkey-edit.cpp
  UI/hotkey-edit.hpp
Labels: Bug Fix, Seeking Testers, macOS

#7350 deps: Fix broken prefix for obspython binary module on Linux
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Bug Fix, Seeking Testers, Linux

#7351 cmake: Fix CMake package files not being installed on FreeBSD
  cmake/Modules/ObsHelpers.cmake
Labels: Bug Fix, Other OS (*nix)

#7358 Fix resource leak v4l2 output
  plugins/linux-v4l2/v4l2-output.c
Labels: Bug Fix, Linux

#7362 cmake: Fix rundir installation accepting DESTDIR environment variable
  cmake/Modules/ObsHelpers.cmake
Labels: Bug Fix, Linux, Other OS (*nix)

#7365 UI: Ignore left-click on non-multiview projectors
  UI/window-projector.cpp
Labels: Bug Fix, Seeking Testers

#7373 UI: Fix source name edit textbox not accepting input on enter
  UI/source-tree.cpp
Labels: Bug Fix, Seeking Testers, macOS

#7376 libobs-opengl: Disable deprecation warnings on macOS
  libobs-opengl/gl-cocoa.m
Labels: macOS

#7382 w32-pthreads: Add pthread.h as public header
  deps/w32-pthreads/CMakeLists.txt
Labels: Bug Fix, Windows

#7388 libobs: Add support for reading NV12/YUY2 PQ/HLG
  libobs/data/format_conversion.effect
  libobs/obs-source.c
Labels: Enhancement

#7383 rtmp-services: Add Livepush service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7391 obs-outputs: Drop unused config file
  plugins/obs-outputs/obs-outputs-config.h.in
Labels: Code Cleanup

#7267 UI: Refine YouTube dialog
  UI/data/locale/en-US.ini
  UI/forms/OBSYoutubeActions.ui
Labels: Bug Fix, Enhancement, Seeking Testers, UI/UX

#7389 Fix service check cache
  .github/workflows/services-json.yml
Labels: Bug Fix, CI

#7418 CI: Fix Xcode selection in new runner image
  .github/workflows/main.yml
Labels: CI

#7392 mac-capture: Undeprecate traditional capture sources on macOS 12
  plugins/mac-capture/data/locale/en-US.ini
  plugins/mac-capture/mac-screen-capture.m
  plugins/mac-capture/plugin-main.c
Labels: Bug Fix, Enhancement, macOS

#7411 UI: Update volume controls decay rate on profile switch
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix, Seeking Testers, UI/UX

#7406 UI: Fix in Light theme
  UI/data/themes/Light.qss
Labels: Bug Fix, UI/UX

#7412 UI: Fix crash when removing filter after changing a value.
  UI/window-basic-filters.cpp
Labels: Bug Fix, Seeking Testers, UI/UX

#7431 obs-filter: Update model for NVIDIA Audio FX
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvafx-load.h
Labels: Bug Fix, Seeking Testers

#7405 libobs,UI: Swap red/blue render/output channels
  UI/window-basic-main.cpp
  libobs/obs-video.c
  libobs/obs.c
Labels: Enhancement

#7432 UI: Fix dock titlebar icons not loading
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#7434 UI: Fix color of popout icon
  UI/data/themes/Light/popout.svg
Labels: Bug Fix, UI/UX

#7445 obs-ffmpeg: Cap AMF encoder at 100 Mbps
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Seeking Testers

#7446 linux-capture: Fixup window name/class checking
  plugins/linux-capture/xcomposite-input.c
Labels: Bug Fix, Linux, Regression

#7447 libobs/media-io: Avoid scaler for range diff
  libobs/media-io/video-io.c
Labels: Bug Fix, Regression

#7465 libobs/media-io: Restore color range conversion
  libobs/media-io/video-io.c
  libobs/media-io/video-scaler-ffmpeg.c
Labels: Bug Fix, Seeking Testers

#7470 linux-pipewire: Close sessions as we are done with them
  plugins/linux-pipewire/screencast-portal.c
Labels: Bug Fix, Linux

#7379 obs-ffmpeg: Fix m3u8 recording in AMF
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Seeking Testers

#7499 UI: Don't reselect SceneTree items if tree is clearing
  UI/item-widget-helpers.cpp
  UI/scene-tree.cpp
Labels: Bug Fix
