Repository obsproject/obs-studio, pull requests merged in 2022-07, with the labels that each got.

#6671 UI: Make properties window default to 50/50 split
  UI/forms/OBSBasicProperties.ui
Labels: Enhancement, UI/UX

#6660 UI,mac-avcapture: Use consistent variables in locales
  UI/data/locale/en-US.ini
  UI/window-basic-filters.cpp
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main-scene-collections.cpp
  UI/window-basic-main.cpp
  UI/window-missing-files.cpp
  plugins/mac-avcapture/av-capture.mm
  plugins/mac-avcapture/data/locale/en-US.ini
Labels: Code Cleanup

#6682 cmake: Fix hardcoded SWIG_LIB path on macOS
  cmake/Modules/ObsDefaults_macOS.cmake
Labels: macOS

#6683 UI: Fix network feature visibility after loading settings
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6685 deps/obs-scripting: Log script load/unload
  deps/obs-scripting/obs-scripting-lua.c
  deps/obs-scripting/obs-scripting-python.c
Labels: Enhancement

#6630 cmake: Fix build architectures and deployment target not set to defaults
  cmake/Modules/ObsDefaults_macOS.cmake
Labels: Bug Fix, macOS

#6691 docs: Fix encoder .get_defaults2 arguments
  docs/sphinx/reference-encoders.rst
Labels: Documentation

#6694 obs-scripting: Fix swig runtime header generation for macOS
  deps/obs-scripting/CMakeLists.txt
Labels: Bug Fix, macOS

#6695 CI: Switch to universal Qt builds on CI
  .github/workflows/main.yml
  CI/include/build_support_macos.sh
  CI/macos/01_install_dependencies.sh
Labels: Bug Fix, macOS, CI

#6704 obs-ffmpeg: Add m4v extension to open file dialog
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#6635 obs-ffmpeg: Add NVIDIA Tesla NVENC support
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Bug Fix

#6686 UI: Yami font adjustments
  UI/data/themes/Yami.qss
Labels: Bug Fix, Seeking Testers, UI/UX

#6693 obs-qsv11: Use same adapter as OBS
  plugins/obs-qsv11/QSV_Encoder.cpp
Labels: Bug Fix, Windows

#6699 aja: Fix 8ch audio capture offset by a channel
  plugins/aja/aja-source.cpp
Labels: Bug Fix

#6703 obs-ffmpeg: Fix srt/rist not working with new buffer code
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix, Seeking Testers

#6677 aja: Fix memory overrun on aja-source
  plugins/aja/aja-source.cpp
Labels: Bug Fix

#6651 obs-outputs: Rework RTMP context init/deinit
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix, Code Cleanup, Seeking Testers

#6631 mac-avcapture: Fix deprecation warning for AVCaptureDevice list
  plugins/mac-avcapture/av-capture.mm
Labels: Code Cleanup, macOS

#6579 UI: Fix reset ui warning showing on first start
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#5757 UI: Move multiview render into a new class
  UI/CMakeLists.txt
  UI/multiview.cpp
  UI/multiview.hpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Code Cleanup

#6658 UI: Implement Taskbar Overlay for Qt6
  UI/platform-windows.cpp
Labels: Enhancement, Windows

#6471 UI: Use more descriptive tooltips
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
Labels: Enhancement, UI/UX

#6632 mac-syphon: Fix usage of methods deprecated since macOS 11.0
  plugins/mac-syphon/syphon.m
Labels: Code Cleanup, macOS

#6705 UI: Add bitdepth and chroma subsampling to output pixel format name
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#6666 CI: Fix Flatpak releases
  .github/workflows/flatpak.yml
Labels: Bug Fix, Linux, CI

#6714 CI: Update Ubuntu versions
  .github/workflows/main.yml
Labels: Enhancement

#6709 UI: Fix text shifting on lineEdits in Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix

#6729 obs-scripting: Fix crashes introduced by Swig update to 4.1.0
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Bug Fix

#6696 CI: Update deps to obs-deps 2022-07-08 release
  .github/workflows/main.yml
  CI/macos/01_install_dependencies.sh
  CI/windows/01_install_dependencies.ps1
Labels: Enhancement, Seeking Testers, Windows, macOS, CI

#6727 UI: Fix color format warning
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6679 obs-qsv11: Fix timestamp for fractional frame rate
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix, Windows

#6716 UI: Fix menu icons not showing up
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
Labels: Bug Fix, UI/UX

#6745 UI: Correctly spell "ChromeOS" again
  UI/data/locale/en-US.ini
Labels: Bug Fix

#6732 libobs: Fix pulseaudio crash
  libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
Labels: Bug Fix, Linux

#6735 deps/media-playback: Fix invalid seek at reset
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#6736 UI: Add menu icons to resource folder
  UI/forms/images/dots-vert.svg
  UI/forms/images/dots.svg
  UI/forms/obs.qrc
Labels: Bug Fix, UI/UX

#6741 UI: Add frame around transitions dock
  UI/forms/OBSBasic.ui
Labels: Bug Fix

#6743 aja: Increment aja-source version for buffering setting
  plugins/aja/aja-output.cpp
  plugins/aja/aja-source.cpp
  plugins/aja/main.cpp
Labels: Enhancement

#6744 UI: Check output path when starting replay buffer
  UI/window-basic-main.cpp
Labels: Bug Fix

#6746 cmake: Fix pkgconfig generation on Linux
  cmake/Modules/ObsHelpers_Linux.cmake
  libobs/pkgconfig/libobs.pc.in
Labels: Bug Fix, Seeking Testers, Linux

#6752 UI: Add media control icons to Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#6755 CI: Update deps to obs-deps 2022-07-18 release
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers, CI

#6762 aja: Remove unnecessary .keepme files
  UI/frontend-plugins/aja-output-ui/data/.keepme
  plugins/aja/data/.keepme
Labels: Code Cleanup

#6750 UI: Fix undo stack uninitialized ui warning
  UI/window-basic-main.hpp
Labels: Code Cleanup

#6771 Remove OBS_UNUSED
  UI/frontend-plugins/aja-output-ui/aja-ui-main.cpp
  deps/obs-scripting/obs-scripting-python-import.h
  libobs-opengl/gl-egl-common.c
  libobs-opengl/gl-nix.c
  libobs-opengl/gl-wayland-egl.c
  libobs/graphics/graphics-ffmpeg.c
  libobs/obs-scene.c
  libobs/obs-video.c
  libobs/util/bmem.c
  libobs/util/c99defs.h
  plugins/aja/aja-common.cpp
  plugins/aja/aja-common.hpp
  plugins/aja/aja-output.cpp
  plugins/aja/aja-routing.cpp
  plugins/aja/aja-source.cpp
  plugins/image-source/image-source.c
  plugins/linux-capture/xcomposite-input.c
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.h
Labels: Code Cleanup

#6757 UI: Remove disable_high_dpi_scaling option on Qt 6
  UI/obs-app.cpp
  UI/obs-app.hpp
Labels: Code Cleanup

#6767 mac-syphon: Ignore 10.13-only deprecation warning
  plugins/mac-syphon/syphon.m
Labels: Code Cleanup, macOS

#6774 UI: Suppress LNK4098
  UI/CMakeLists.txt
Labels: Bug Fix, Windows

#6751 Use property suffixes for units everywhere
  plugins/image-source/data/locale/en-US.ini
  plugins/image-source/obs-slideshow.c
  plugins/linux-capture/data/locale/en-US.ini
  plugins/linux-capture/xcomposite-input.c
  plugins/linux-capture/xshm-input.c
  plugins/mac-videotoolbox/data/locale/en-US.ini
  plugins/mac-videotoolbox/encoder.c
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-outputs/data/locale/en-US.ini
  plugins/obs-outputs/rtmp-stream.c
  plugins/obs-qsv11/data/locale/en-US.ini
  plugins/obs-qsv11/obs-qsv11.c
  plugins/obs-x264/data/locale/en-US.ini
  plugins/obs-x264/obs-x264.c
  plugins/vlc-video/data/locale/en-US.ini
  plugins/vlc-video/vlc-video-source.c
  plugins/win-mf/data/locale/en-US.ini
  plugins/win-mf/mf-h264.cpp
Labels: Code Cleanup, UI/UX

#6760 Fix discarded-qualifiers warnings with FFmpeg 5
  deps/libff/libff/ff-util.c
  deps/media-playback/media-playback/decode.c
  deps/media-playback/media-playback/decode.h
  libobs/graphics/graphics-ffmpeg.c
  plugins/linux-v4l2/v4l2-decoder.h
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-ffmpeg/obs-ffmpeg-video-encoders.h
  plugins/obs-ffmpeg/obs-ffmpeg.c
  plugins/win-dshow/ffmpeg-decode.c
  plugins/win-dshow/ffmpeg-decode.h
Labels: Code Cleanup

#6748 v4l2,scripting: Add more thread names
  deps/obs-scripting/obs-scripting.c
  plugins/linux-v4l2/v4l2-udev.c
Labels: Enhancement

#6764 UI: Hide network features if a non-RTMP service is set
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement

#6785 obs-outputs: Fix TLS_client init for mbedTLS 3.1.0+
  plugins/obs-outputs/librtmp/rtmp.h
Labels: Bug Fix

#6789 UI: Remove unused functions for audio mixers
  UI/window-basic-main.cpp
Labels: Code Cleanup

#6796 UI: Fix crash on macOS if no python path is set in configuration
  UI/frontend-plugins/frontend-tools/scripts.cpp
Labels: Bug Fix, Seeking Testers, macOS

#6664 UI: Enforce Fusion Qt style on Linux
  UI/obs-app.cpp
Labels: Bug Fix, Linux

#6724 UI: Cleanup theme combobox code
  UI/window-basic-settings.cpp
Labels: Code Cleanup

#6431 obs-outputs: Improve librtmp timeouts on Linux
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix, Seeking Testers

#6617 cmake: Enable ENABLE_HEVC by default
  CMakeLists.txt
Labels: Enhancement

#5218 win-wasapi: Add support for capturing a process
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/sources/windowaudio.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/forms/images/sources/windowaudio.svg
  UI/forms/obs.qrc
  UI/window-basic-main-icons.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  libobs/CMakeLists.txt
  libobs/obs-source.h
  libobs/util/windows/WinHandle.hpp
  libobs/util/windows/obfuscate.c
  libobs/util/windows/obfuscate.h
  libobs/util/windows/window-helpers.c
  libobs/util/windows/window-helpers.h
  plugins/win-capture/CMakeLists.txt
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook/CMakeLists.txt
  plugins/win-capture/graphics-hook/graphics-hook.c
  plugins/win-capture/inject-helper/CMakeLists.txt
  plugins/win-capture/inject-helper/inject-helper.c
  plugins/win-capture/inject-library.c
  plugins/win-capture/window-capture.c
  plugins/win-capture/window-helpers.h
  plugins/win-wasapi/data/locale/en-US.ini
  plugins/win-wasapi/plugin-main.cpp
  plugins/win-wasapi/win-wasapi.cpp
Labels: Seeking Testers, Windows, New Feature

#6372 obs-filter: Add new RTX audio fx (dereverb & combined denoiser+ dereverb)
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvafx-load.h
Labels: Seeking Testers, New Feature

#6365 obs-filter: NVIDIA RTX AI Greenscreen filter (Background removal)
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/data/rtx_greenscreen.effect
  plugins/obs-filters/nvidia-greenscreen-filter.c
  plugins/obs-filters/nvvfx-load.h
  plugins/obs-filters/obs-filters-config.h.in
  plugins/obs-filters/obs-filters.c
Labels: Seeking Testers, New Feature

#6797 mac-syphon: Fix issues on modern macOS versions
  plugins/mac-syphon/syphon.m
Labels: Bug Fix, macOS

#6781 UI: Add initialization to ensure compat between pthread and NSThread
  UI/obs-app.cpp
  UI/platform-osx.mm
  UI/platform.hpp
Labels: Enhancement, macOS

#6808 libobs: Don't monitor hidden sources on macOS
  libobs/audio-monitoring/osx/coreaudio-output.c
Labels: Bug Fix, macOS

#6801 UI: Add audioProcessOutputIcon to Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#6792 obs-filters: Add HDR bypass for color correction
  plugins/obs-filters/color-correction-filter.c
  plugins/obs-filters/data/locale/en-US.ini
Labels: Enhancement, UI/UX

#6809 obs-filters: Add HDR bypass for various filters
  plugins/obs-filters/chroma-key-filter.c
  plugins/obs-filters/color-grade-filter.c
  plugins/obs-filters/color-key-filter.c
  plugins/obs-filters/luma-key-filter.c
  plugins/obs-filters/mask-filter.c
Labels: Enhancement

#6811 UI: Remove padding on QStackedWidget in Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#6542 libobs: Add shader enhancements for better colors
  libobs/data/color.effect
Labels: Enhancement

#6805 UI: Add functions to check for and request macOS permissions
  UI/CMakeLists.txt
  UI/obs-app.cpp
  UI/platform-osx.mm
  UI/platform.hpp
Labels: macOS, New Feature

#3914 libobs: Rewrite macOS hotkeys implementation
  libobs/obs-cocoa.m
Labels: Enhancement, Seeking Testers, macOS

#6472 UI: Add scene names to preview/program labels
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#5455 UI: Relatively center multiple scene items
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#6322 UI: Add Self-Repair Option
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/win-update/win-update.cpp
  UI/win-update/win-update.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Windows, New Feature, UI/UX

#6814 UI/themes: Correctly specify rgb instead of rgba
  UI/data/themes/Yami.qss
Labels: Bug Fix

#6825 CI: Fix clang-format if path has spaces
  CI/check-format.sh
Labels: Bug Fix

#6826 libobs: Remove unused cmake configure files
  libobs/LibObsConfig.cmake.in
  libobs/LibObsConfigVersion.cmake.in
  libobs/libobs.pc.in
Labels: Code Cleanup

#2212 UI: Add various preview improvements
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
Labels: Enhancement, Seeking Testers, Request for Comments, UI/UX

#5174 UI: Clean up Settings Output form
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Enhancement

#6788 UI: Search combo property item with QVariant type
  UI/properties-view.cpp
Labels: Bug Fix

#6844 obs-ffmpeg: Don't show preloaded video when the media source without video
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#6845 UI: Deduplicate UI element names
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#6850 libobs: Include plugin path in log error message
  libobs/obs-module.c
Labels: Bug Fix

#6846 CI: Update deps to obs-deps 2022-07-29 release
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, Seeking Testers, Windows, macOS

#6698 graphics-hook: Avoid conflict between Vulkan and DXGI Present
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
  plugins/win-capture/graphics-hook/graphics-hook.h
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix, Windows

#6865 graphics-hook: Track DXGI status with counter
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
Labels: Bug Fix

#6858 UI/themes: Add image to QGroupBox checkbox on Yami
  UI/data/themes/Yami.qss
Labels: Bug Fix

#6857 image-source: Correctly assign to variable next_hotkey instead of prev_hotkey
  plugins/image-source/obs-slideshow.c
Labels: Bug Fix

#6702 UI: Add support for theme meta, parent theme palette
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/obs-app.cpp
  UI/obs-app.hpp
Labels: Enhancement, UI/UX

#6854 rtmp-services: Add Streamvi service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#6863 mac-capture: Don't exclude desktop windows in SCK window capture
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix, macOS

#6134 obs-ffmpeg: Support native SRT & RIST output
  CI/linux/02_build_obs.sh
  cmake/Modules/FindLibrist.cmake
  cmake/Modules/FindLibsrt.cmake
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-ffmpeg/obs-ffmpeg-rist.h
  plugins/obs-ffmpeg/obs-ffmpeg-srt.h
  plugins/obs-ffmpeg/obs-ffmpeg-url.h
Labels: Bug Fix, Enhancement, Seeking Testers

#6855 CI: Use xcrun notarytool instead of xcnotary
  CI/include/build_support_macos.sh
  CI/macos/03_package_obs.sh
Labels: Code Cleanup, macOS

#6834 UI: Fix studio mode label not updating
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#6839 obs-transitions: Reduce code duplication
  plugins/obs-transitions/data/fade_transition.effect
Labels: Code Cleanup

#6840 UI: Fix close display before native surfaces
  UI/qt-display.cpp
Labels: Bug Fix, Seeking Testers

#6827 obs-filters: Add HDR support to Render Delay
  plugins/obs-filters/gpu-delay.c
Labels: Enhancement

#6828 obs-filters: Add HDR bypass for sharpen
  plugins/obs-filters/sharpness-filter.c
Labels: Enhancement

#6852 UI: JXR screenshots on Windows
  UI/screenshot-obj.hpp
  UI/window-basic-main-screenshot.cpp
Labels: Enhancement

#6861 aja: Only allow output formats matching OBS framerate
  plugins/aja/aja-common.cpp
  plugins/aja/aja-common.hpp
  plugins/aja/aja-output.cpp
Labels: Bug Fix

#6867 CI: Bump CEF/Chromium from 4638 (95) to 5060 (103)
  .github/workflows/main.yml
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers

#6868 CI: Fix Sparkle cache location for local macOS CI build
  CI/macos/01_install_dependencies.sh
Labels: Bug Fix, macOS, CI

#6869 libobs: Improve failed module loading logging
  docs/sphinx/reference-modules.rst
  libobs/obs-defs.h
  libobs/obs-module.c
Labels: Bug Fix, Enhancement

#6870 obs-filters: Reset RTX Greenscreen if parent is updated
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Bug Fix, Seeking Testers

#6874 CI: Fix Linux package filename version
  CI/linux/03_package_obs.sh
Labels: Bug Fix, CI

#6862 mac-capture: Add transparent background option to SCK App Capture
  plugins/mac-capture/mac-screen-capture.m
Labels: Enhancement, macOS

#5471 UI: Show spacing helpers in preview
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/obs-app.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
  UI/window-basic-settings.cpp
Labels: New Feature, UI/UX

#6872 plugins/obs-ffmpeg: Mark rist/srt required when flag enabled
  plugins/obs-ffmpeg/CMakeLists.txt
Labels: Code Cleanup

#6838 obs-transitions: Add HDR support to stinger
  plugins/obs-transitions/data/stinger_matte_transition.effect
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement

#6830 obs-filters: Add HDR support to Scroll
  plugins/obs-filters/scroll-filter.c
Labels: Enhancement

#6812 UI: Add toolButton style property for transitions dock
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/forms/OBSBasic.ui
Labels: Enhancement

#5128 UI: Add audio mixer toolbar
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/cogs.svg
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/forms/OBSBasic.ui
  UI/forms/images/cogs.svg
  UI/forms/obs.qrc
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#6824 UI: Include OpenSans font with OBS
  UI/data/themes/Yami.qss
  UI/forms/fonts/OpenSans-Bold.ttf
  UI/forms/fonts/OpenSans-Italic.ttf
  UI/forms/fonts/OpenSans-Regular.ttf
  UI/forms/obs.qrc
  UI/obs-app.cpp
Labels: Bug Fix, Enhancement, UI/UX

#6847 flatpak: Update deps with obs-deps, Qt and allow some headers to be kept
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Seeking Testers

#6880 flatpak: Change obs-deps tag to 2022-07-29
  CI/flatpak/com.obsproject.Studio.json
Labels: Bug Fix, Seeking Testers, Linux

#6882 cmake: Remove prefix suppression for scripting plugins.
  cmake/Modules/ObsHelpers.cmake
Labels: Bug Fix, Windows

#6856 UI: Fix Qt UI call from graphics thread
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
Labels: Bug Fix, macOS

#6877 CI: Use Qt6 by default when available
  .github/workflows/main.yml
  CI/linux/01_install_dependencies.sh
  CI/macos/01_install_dependencies.sh
  CI/windows/01_install_dependencies.ps1
  cmake/Modules/ObsHelpers.cmake
Labels: Bug Fix, New Feature, CI
