Repository obsproject/obs-studio, pull requests merged in 2022-04, with the labels that each got.

#6221 cmake: check empty OBS_MODULE_LIST and OBS_SCRIPTING_MODULE_LIST on macOS
  cmake/Modules/ObsHelpers_macOS.cmake
Labels: Bug Fix

#6260 linux-pipewire: remove call to pw_deinit
  plugins/linux-pipewire/CMakeLists.txt
  plugins/linux-pipewire/linux-pipewire.c
  plugins/linux-pipewire/pipewire-common.c
  plugins/linux-pipewire/pipewire-common.h
Labels: Bug Fix, Code Cleanup, Linux

#6242 obs-filters: Fix scale undistort, attempt two
  plugins/obs-filters/scale-filter.c
Labels: Bug Fix

#6244 aja: Use correct colorspace/range for SD or HD/UHD/4K
  plugins/aja/aja-source.cpp
Labels: Bug Fix

#6253 libobs-winrt: Add null checks to capture
  libobs-winrt/winrt-capture.cpp
Labels: Bug Fix, Windows

#6158 Add I010/P010 support, video_trc enum
  deps/media-playback/media-playback/closest-format.h
  deps/media-playback/media-playback/media.c
  docs/sphinx/reference-libobs-media-io.rst
  docs/sphinx/reference-outputs.rst
  docs/sphinx/reference-sources.rst
  libobs/data/color.effect
  libobs/data/deinterlace_base.effect
  libobs/data/deinterlace_blend.effect
  libobs/data/deinterlace_blend_2x.effect
  libobs/data/deinterlace_discard.effect
  libobs/data/deinterlace_discard_2x.effect
  libobs/data/deinterlace_linear.effect
  libobs/data/deinterlace_linear_2x.effect
  libobs/data/deinterlace_yadif.effect
  libobs/data/deinterlace_yadif_2x.effect
  libobs/data/format_conversion.effect
  libobs/media-io/video-frame.c
  libobs/media-io/video-io.h
  libobs/media-io/video-scaler-ffmpeg.c
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-source-deinterlace.c
  libobs/obs-source.c
  libobs/obs-video-gpu-encode.c
  libobs/obs-video.c
  libobs/obs.c
  libobs/obs.h
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
  plugins/obs-ffmpeg/obs-ffmpeg-formats.h
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/win-dshow/data/locale/en-US.ini
  plugins/win-dshow/ffmpeg-decode.c
  plugins/win-dshow/win-dshow.cpp
Labels: New Feature

#6278 cmake: Fixes plugins not being copied into application bundle on macOS
  cmake/Modules/ObsHelpers_macOS.cmake
Labels: Bug Fix, Seeking Testers

#6288 libobs: Clear image on color convert
  libobs/obs-source.c
Labels: Bug Fix

#6277 win-capture: Use normal blend equation for cursor
  plugins/win-capture/cursor-capture.c
Labels: Bug Fix, Windows

#6259 libobs: Fix image source not loading upper case file extensions
  libobs/graphics/image-file.c
Labels: Bug Fix

#6258 obs-ffmpeg, win-dshow, deps/media-playback: Use recommended API for AVCodecContext
  deps/media-playback/media-playback/decode.c
  libobs/graphics/graphics-ffmpeg.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix

#6219 UI: Add Rec. 2020 space and I010/P010 formats
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: New Feature

#6286 linux-capture: Don't initialize format info if init_obs_pipewire fails
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#6248 libobs, UI: Fix `--verbose` logging for stdout
  UI/obs-app.cpp
  libobs/util/base.c
Labels: Enhancement

#6306 deps/media-playback: Fix AVColorSpace usages
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#6307 libobs: Rename Rec. 2020 to Rec. 2100
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  deps/media-playback/media-playback/media.c
  docs/sphinx/reference-libobs-media-io.rst
  docs/sphinx/reference-outputs.rst
  libobs/media-io/video-io.h
  libobs/media-io/video-matrices.c
  libobs/media-io/video-scaler-ffmpeg.c
  libobs/obs-scene.c
  libobs/obs.c
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/win-dshow/data/locale/en-US.ini
  plugins/win-dshow/ffmpeg-decode.c
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix

#6235 obs-filters: Add HDR support to Scaling filter
  plugins/obs-filters/scale-filter.c
Labels: New Feature

#6308 win-dshow: Add Rec. 2020 HLG support
  plugins/win-dshow/data/locale/en-US.ini
  plugins/win-dshow/win-dshow.cpp
Labels: Windows, New Feature

#5371 Automatic file splitting
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.h
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.h
Labels: Seeking Testers, New Feature

#6313 libobs-opengl: Use gl helpers in create_dmabuf_image
  libobs-opengl/gl-egl-common.c
Labels: Bug Fix, Seeking Testers, Linux

#6238 obs-ffmpeg: Add mxf extension to open file dialog filters
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: New Feature

#6256 CI: Fix Windows/macOS release jobs
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
  CI/freebsd/03_package_obs.sh
  CI/linux/03_package_obs.sh
  CI/macos/03_package_obs.sh
  CI/windows/03_package_obs.ps1
Labels: Seeking Testers, CI

#6314 win-dshow: Use Rec. 2100 (PQ) by default for P010
  plugins/win-dshow/win-dshow.cpp
Labels: Enhancement, Windows

#6057 UI: Fix show/hide toggle with minimize to taskbar
  UI/window-basic-main.cpp
Labels: Bug Fix, Linux

#6323 libobs: Remove redundant async_color_format member
  libobs/obs-internal.h
  libobs/obs-source-deinterlace.c
  libobs/obs-source.c
Labels: Code Cleanup

#6330 virtualcam-module: Copy Windows virtual camera files to rundir
  plugins/win-dshow/virtualcam-module/CMakeLists.txt
Labels: Bug Fix, Seeking Testers, Windows

#6315 deps/media-playback: Use avcodec_free_context to free AVCodecContext
  deps/media-playback/media-playback/decode.c
Labels: Bug Fix

#6316 obs-ffmpeg: Add max luminance metadata for PQ
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
Labels: Enhancement

#6326 UI: Add shortcut for larger movement steps in preview
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#6327 rtmp-services: Update Bilibili Live
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#6344 CI: Fix clang-format to include Objective-C
  CI/check-format.sh
Labels: Bug Fix

#6345 deps/media-playback: Add P010 to closest_format
  deps/media-playback/media-playback/closest-format.h
Labels: Bug Fix

#6346 libobs: Fix color space auto-convert blending
  libobs/obs-source.c
Labels: Bug Fix

#6347 obs-transitions: More HDR support
  plugins/obs-transitions/data/luma_wipe_transition.effect
  plugins/obs-transitions/data/slide_transition.effect
  plugins/obs-transitions/data/swipe_transition.effect
  plugins/obs-transitions/transition-luma-wipe.c
  plugins/obs-transitions/transition-slide.c
  plugins/obs-transitions/transition-swipe.c
Labels: Enhancement

#6185 CI: Add Steam build uploader
  .github/workflows/steam.yml
  CI/steam/obs_build.vdf
  CI/steam/scripts/install.bat
  CI/steam/scripts/installscript.vdf
  CI/steam/scripts/uninstall.bat
Labels: CI

#6228 UI: Fix manage broadcast crash
  UI/forms/OBSYoutubeActions.ui
Labels: Bug Fix

#6363 CI: Do not run Steam workflow on forks
  .github/workflows/steam.yml
Labels: CI

#6364 flatpak: Cleanup PipeWire module
  CI/flatpak/com.obsproject.Studio.json
Labels: CI

#6367 libobs-opengl: Disable vsync during present
  libobs-opengl/gl-x11-egl.c
Labels: Bug Fix, Linux

#6369 win-dshow: Respect TRC of encoded video
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix, Windows

#6359 aja: Subtract packet time from audio timestamp
  plugins/aja/aja-source.cpp
Labels: Bug Fix

#6362 obs-transitions: Remove unused shader functions
  plugins/obs-transitions/data/luma_wipe_transition.effect
  plugins/obs-transitions/data/slide_transition.effect
  plugins/obs-transitions/data/swipe_transition.effect
Labels: Code Cleanup

#6361 CI: Respect user-specified build directory
  CI/windows/02_build_obs.ps1
Labels: Bug Fix

#6325 libobs,UI: Issue appropriate signals on group / ungroup
  UI/source-tree.cpp
  libobs/obs-scene.c
Labels: Bug Fix, Enhancement

#6377 libobs,obs-outputs: Fix librtmp1 dependency interference on some linuxes
  libobs/util/c99defs.h
  plugins/obs-outputs/CMakeLists.txt
Labels: Bug Fix, Linux

#6379 libobs: Fix NaNs when using EETF for HLG
  libobs/data/color.effect
Labels: Bug Fix

#6387 CI: Update macOS image to macOS 12
  .github/workflows/main.yml
Labels: Enhancement, Seeking Testers

#6388 Fix indent on multiline comments
  UI/window-basic-main.cpp
  UI/youtube-api-wrappers.cpp
  libobs/obs-source.c
  plugins/aja/aja-presets.cpp
  plugins/obs-filters/color-correction-filter.c
  plugins/win-capture/get-graphics-offsets/d3d9-offsets.cpp
Labels: Code Cleanup

#6374 obs-outputs: Implement send timeout in librtmp (Fix RTMP output deadlock)
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/librtmp/rtmp.h
Labels: Bug Fix, Seeking Testers

#6393 obs-libfdk: Enable 7.1 channel surround for Linux
  plugins/obs-libfdk/obs-libfdk.c
Labels: Bug Fix, Linux

#6396 aja: Fix UHD/4K HDMI output on Kona5-8K firmware
  plugins/aja/aja-presets.cpp
  plugins/aja/aja-props.cpp
Labels: Bug Fix

#6376 backport: libobs-opengl: Use gl helpers in create_dmabuf_image
  libobs-opengl/gl-egl-common.c
Labels: Bug Fix, Seeking Testers, Linux

#6352 UI: Only use volume scrollbars when needed
  UI/forms/OBSBasic.ui
Labels: Enhancement, Seeking Testers
