Repository obsproject/obs-studio, pull requests merged in 2022-02, with the labels that each got.

#5898 rtmp-services: Update YouNow ingest
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5907 UI: Add Wine detection/warning
  UI/data/locale/en-US.ini
  UI/obs-app.cpp
  UI/platform-windows.cpp
  UI/platform.hpp
Labels: Seeking Testers, Linux

#5950 rtmp-services: Update Picarto ingests
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#5931 UI: Correctly style "Chrome OS"
  UI/data/locale/en-US.ini
Labels: Bug Fix

#5936 libobs/util: Fix VS static analysis warnings
  libobs/util/platform-windows.c
Labels: Bug Fix, Windows

#5945 UI: Avoid emiting events 2 times when renaming a profile
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix

#5969 wayland: Map keymap with MAP_PRIVATE
  libobs/obs-nix-wayland.c
Labels: Bug Fix, Linux

#5955 linux-capture: Fix for pipewire capture leaking texture handles
  plugins/linux-capture/pipewire.c
Labels: Bug Fix, Linux

#5962 obs-ffmpeg: Force mpegts & disable restart on activate for srt/rist
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#5980 win-wasapi: Only enable work queue on Windows 10+
  plugins/win-wasapi/win-wasapi.cpp
Labels: Bug Fix, Windows

#5985 UI: Refresh edit menu on item select/deselect
  UI/source-tree.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#5983 libobs: Adjust path for legacy browser source block
  libobs/obs-module.c
Labels: Bug Fix, macOS

#5958 linux-v4l2: fixup mjpeg pixel format computation
  plugins/linux-v4l2/v4l2-helpers.h
  plugins/linux-v4l2/v4l2-input.c
  plugins/linux-v4l2/v4l2-mjpeg.c
Labels: Bug Fix, Linux

#5973 UI: Use std::unique_ptr for ui variables
  UI/context-bar-controls.cpp
  UI/context-bar-controls.hpp
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/frontend-plugins/frontend-tools/scripts.hpp
  UI/media-controls.cpp
  UI/media-controls.hpp
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  UI/window-extra-browsers.cpp
  UI/window-extra-browsers.hpp
Labels: Code Cleanup

#5991 Set a fixed size socket buffer on Windows 7
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix

#6006 CI: Update workflow to copy SOVERSION symlinks
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers

#6028 win-wasapi: Fall back to old code if RTWQ fails
  plugins/win-wasapi/win-wasapi.cpp
Labels: Bug Fix, Windows

#5999 linux-v4l2: Fix warnings in mjpeg
  plugins/linux-v4l2/v4l2-mjpeg.c
  plugins/linux-v4l2/v4l2-mjpeg.h
Labels: Code Cleanup, Linux

#5994 UI: Fix performance issues with the Log Viewer
  UI/log-viewer.cpp
  UI/log-viewer.hpp
Labels: Bug Fix, Enhancement

#5997 obs-ffmpeg: Update nv-codec-header files
  plugins/obs-ffmpeg/external/dynlink_cuda.h
  plugins/obs-ffmpeg/external/nvEncodeAPI.h
Labels: Code Cleanup

#6025 UI: Refresh edit menu on item locked signal
  UI/source-tree.cpp
Labels: Bug Fix

#6031 decklink: Don't load modules if Decklink not found
  UI/frontend-plugins/decklink-captions/decklink-captions.cpp
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
  plugins/decklink/plugin-main.cpp
Labels: Bug Fix

#6038 UI: Add shortcuts for Copy/Paste Transform
  UI/forms/OBSBasic.ui
Labels: Enhancement

#5852 UI: Move "Check For Updates" menu to app menu on macOS
  UI/window-basic-main.cpp
Labels: Enhancement

#5233 Improve scaling of audio meter (issue 3915)
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/volume-control.cpp
  UI/volume-control.hpp
Labels: Bug Fix, Seeking Testers

#5262 UI: Disable downscale filter setting for same resolutions
  UI/data/locale/en-US.ini
  UI/window-basic-settings.cpp
Labels: Enhancement

#6042 win-dshow: Add hardware decode status to log
  plugins/win-dshow/win-dshow.cpp
Labels: Enhancement

#6043 win-dshow: Fix wrong AVCodecContext free call
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix, Code Cleanup, Windows

#5965 UI: Additional product details
  UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Labels: Linux, Documentation
