Repository obsproject/obs-studio, pull requests merged in 2022-11, with the labels that each got.

#7696 Fix Simple Output Mode NVENC Preset migrations
  UI/obs-app.cpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
Labels: Bug Fix

#7700 obs-ffmpeg: Cap NVENC Max B-frames according to GPU caps
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix, Seeking Testers

#7560 CI: Upload beta builds as Steam Playtest
  .github/workflows/steam.yml
  CI/steam/obs_playtest_build.vdf
Labels: CI

#7721 Fix always on top not being saved on exit
  UI/window-basic-main.cpp
Labels: Bug Fix

#7694 docs: Add clarifications
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-encoders.rst
  docs/sphinx/reference-frontend-api.rst
  docs/sphinx/reference-libobs-callback.rst
  docs/sphinx/reference-outputs.rst
  docs/sphinx/reference-properties.rst
  docs/sphinx/reference-scenes.rst
  docs/sphinx/reference-services.rst
  docs/sphinx/reference-settings.rst
  docs/sphinx/reference-sources.rst
Labels: Documentation

#7393 libobs: Add "source_update" signal
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-sources.rst
  libobs/obs-source.c
  libobs/obs.c
Labels: Enhancement

#7133 libobs: Move async filtering from render to tick
  libobs/obs-source-deinterlace.c
  libobs/obs-source.c
Labels: Bug Fix

#7734 libobs: Fix reading Windows release name
  libobs/util/platform-windows.c
Labels: Seeking Testers, Windows

#7538 mac-avcapture: Add deskcam support
  plugins/mac-avcapture/av-capture.mm
Labels: macOS, New Feature

#7307 decklink-output-ui: Pipeline GPU data for preview
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Labels: Enhancement

#7634 libobs-d3d11: Support advanced SDR window preview
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
Labels: Enhancement, Seeking Testers

#7737 UI: Fix QStyle memory leak
  UI/window-basic-main.cpp
Labels: Bug Fix

#7662 aja: Fix KonaHDMI UHD/4K YUV capture
  plugins/aja/aja-presets.cpp
  plugins/aja/aja-props.cpp
  plugins/aja/aja-source.cpp
Labels: Bug Fix, Seeking Testers

#7746 docs: Add info on funcs to use for properties
  docs/sphinx/reference-properties.rst
Labels: Documentation

#6842 Remove discouraged and deprecated usage of sprintf across the codebase
  UI/obs-app.cpp
  UI/qt-wrappers.cpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-profiles.cpp
  deps/libcaption/caption/caption.h
  deps/libcaption/src/caption.c
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obs-scripting-python.c
  libobs-d3d11/d3d11-subsystem.cpp
  libobs/util/platform.c
  plugins/coreaudio-encoder/encoder.cpp
  plugins/image-source/obs-slideshow.c
  plugins/linux-capture/xshm-input.c
  plugins/linux-v4l2/v4l2-input.c
  plugins/mac-capture/mac-display-capture.m
  plugins/mac-capture/mac-screen-capture.m
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-filters/scale-filter.c
  plugins/obs-outputs/librtmp/amf.c
  plugins/obs-outputs/librtmp/hashswf.c
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-x264/obs-x264.c
  plugins/win-capture/game-capture.c
  plugins/win-capture/graphics-hook/graphics-hook.c
Labels: Code Cleanup

#7466 obs-filters: Warn when NVIDIA FX needs update, Update to v0.7.1 Video SDK & Add a mask refresh slider
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvafx-load.h
  plugins/obs-filters/nvidia-greenscreen-filter.c
  plugins/obs-filters/nvvfx-load.h
Labels: Bug Fix, Enhancement, Seeking Testers

#7711 mac-videotoolbox: Support P010 and HDR color spaces
  plugins/mac-videotoolbox/encoder.c
Labels: macOS, New Feature

#7736 mac-capture: Disable all SCK modes besides WindowCapture on macOS 12
  plugins/mac-capture/data/locale/en-US.ini
  plugins/mac-capture/mac-screen-capture.m
Labels: Seeking Testers, macOS

#7730 UI: Remove number from multiview labels
  UI/multiview.cpp
Labels: Enhancement, UI/UX

#7760 rtmp-services: Add IRLToolkit
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7765 UI: Add separator in source toolbar
  UI/forms/OBSBasic.ui
Labels: Enhancement, UI/UX

#7787 CI: Fix building in PowerShell 7.3.x
  CI/windows/02_build_obs.ps1
Labels: Bug Fix, CI

#6128 UI: Fix projectors not closing when source is deleted
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Bug Fix

#6996 win-capture: Invert destination pixels when drawing monochrome cursors
  plugins/win-capture/cursor-capture.c
  plugins/win-capture/cursor-capture.h
Labels: Bug Fix

#7802 obs-ffmpeg: Fix SRT error type comparison
  plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Labels: Bug Fix

#7049 win-capture,UI: Look up display by id, not index
  UI/context-bar-controls.cpp
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Bug Fix, Enhancement, Seeking Testers

#7807 CI: Re-enable scripting in Windows builds
  CI/windows/02_build_obs.ps1
Labels: Bug Fix

#7806 UI: Change Simple Output NVENC default preset to P5
  UI/window-basic-main.cpp
Labels: Bug Fix, Enhancement

#7808 win-dshow: Recognise higher FPS values from devices
  plugins/win-dshow/win-dshow.cpp
Labels: Enhancement, Seeking Testers, Windows

#7805 UI: Add Apple Hardware Encoder to AutoConfig
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
Labels: Enhancement, macOS

#7767 mac-videotoolbox: Default to High profile
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix

#7771 flatpak: Add Jansson to modules
  CI/flatpak/com.obsproject.Studio.json
Labels: Linux, CI

#7785 UI: Clarify that RGB output format is BGRA
  UI/data/locale/en-US.ini
  UI/frontend-plugins/decklink-output-ui/forms/output.ui
  UI/window-basic-settings.cpp
Labels: Enhancement, UI/UX

#7786 decklink: Always output BGRA
  plugins/decklink/decklink-device-instance.cpp
  plugins/decklink/decklink-output.cpp
Labels: Enhancement, Code Cleanup

#7797 libobs: Allow overriding video resolution per view
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-scene.c
  libobs/obs-video.c
  libobs/obs-view.c
  libobs/obs.c
  libobs/obs.h
Labels: New Feature

#7799 obs-ffmpeg: Fix SVT-AV1 rate control mode selection
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
Labels: Bug Fix, Enhancement

#7804 UI: Remove Qt taskbar overlay
  UI/platform-windows.cpp
Labels: Code Cleanup

#7330 UI: Add filters button to scenes toolbar
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#6678 obs-ffmpeg: Use Libva to enable FFmpeg VA-API
  cmake/Modules/FindLibva.cmake
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
  plugins/obs-ffmpeg/vaapi-utils.c
  plugins/obs-ffmpeg/vaapi-utils.h
Labels: Seeking Testers, Linux, New Feature, UI/UX

#7626 libobs: Deprecate obs_get/set_master_volume
  docs/sphinx/reference-core.rst
  libobs/obs-internal.h
  libobs/obs.c
  libobs/obs.h
Labels: Code Cleanup

#7813 Fix svt-av1 and libaom-av1 CQP ratecontrol
  plugins/obs-ffmpeg/obs-ffmpeg-av1.c
Labels: Bug Fix

#7378 UI: Disable toolbar buttons when no source is selected
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
  UI/qt-wrappers.cpp
  UI/qt-wrappers.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Seeking Testers, UI/UX

#6833 Misc obs-vst cleanups
  plugins/obs-vst/VSTPlugin.cpp
  plugins/obs-vst/headers/VSTPlugin.h
  plugins/obs-vst/obs-vst.cpp
Labels: Code Cleanup, Seeking Testers

#3450 UI, image-source: Add slide counter to slideshow toolbar
  UI/media-controls.cpp
  UI/media-controls.hpp
  plugins/image-source/obs-slideshow.c
Labels: Enhancement, UI/UX

#7770 CI,obs-vst: Update Flatpak KDE Runtime to version 6.4
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
  CI/flatpak/com.obsproject.Studio.json
  plugins/obs-vst/obs-vst.cpp
Labels: Enhancement, Seeking Testers, Linux, CI

#7106 cmake: Specify utf-8 for MSVC builds
  cmake/Modules/CompilerConfig.cmake
Labels: Enhancement, Windows

#7823 CI: Update deps to obs-deps 2022-11-21 release
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, Seeking Testers

#7822 flatpak: Update deps based on obs-deps 2022-11-21
  CI/flatpak/com.obsproject.Studio.json
Labels: Seeking Testers, Linux

#7829 obs-ffmpeg: Disable VBAQ for HEVC CQP rate control
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix

#6522 obs-qsv11: Add HEVC support
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp
  plugins/obs-qsv11/obs-qsv11-plugin-main.c
  plugins/obs-qsv11/obs-qsv11.c
Labels: New Feature

#7840 UI: Delay timed update check until branch migration
  UI/window-basic-main.cpp
Labels: Bug Fix, Windows

#7862 UI: Hide "Update Channel" label on macOS
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Bug Fix

#7832 obs-ffmpeg: Disable VBAQ for H264 CQP rate control
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix
