Repository obsproject/obs-studio, pull requests merged in 2023-12, with the labels that each got.

#9759 UI:Properties view
  UI/properties-view.cpp
Labels: Bug Fix, macOS

#9931 libobs: Reuse matching mix's render texture if possible
  libobs/obs-video.c
Labels: Enhancement, Seeking Testers

#9937 libobs: Fix GPU scaling always using the main mix
  libobs/obs-encoder.c
Labels: Bug Fix

#9941 obs-ffmpeg: Add missing header to CMakeLists
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/cmake/legacy.cmake
Labels: Bug Fix

#9942 mac-videotoolbox: Fix handling of unsuccessful encoder creation
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix, macOS

#9949 libobs: Fix obs_view_remove only resetting the first matching mix
  libobs/obs-view.c
Labels: Bug Fix

#9954 libobs: Remove module UI functions
  libobs/CMakeLists.txt
  libobs/cmake/legacy.cmake
  libobs/obs-internal.h
  libobs/obs-module.c
  libobs/obs-ui.h
  libobs/obs.c
  libobs/obs.h
Labels: Code Cleanup

#9957 libobs: Pair video encoder with all audio encoders
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-output.c
  libobs/obs-video-gpu-encode.c
Labels: Bug Fix, Code Cleanup, Seeking Testers

#6337 libobs: Extra callback when removing scene
  libobs/obs-scene.c
Labels: Bug Fix

#8393 obs-vst: Fix incorrect VST window size on HiDPI display
  plugins/obs-vst/win/EditorWidget-win.cpp
Labels: Bug Fix

#9977 mac-capture: Fix ScreenCaptureKit deadlock when using invalid display ID
  plugins/mac-capture/mac-sck-video-capture.m
Labels: Bug Fix, Seeking Testers, macOS

#9576 UI: Don't paste transform on locked item
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#9575 UI: Disable edit transform if item is locked
  UI/window-basic-main.cpp
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
Labels: Bug Fix, UI/UX

#5261 image-source: Use mutex when accessing slideshow
  plugins/image-source/obs-slideshow.c
Labels: Bug Fix

#7686 libobs: Fix audio-only output did not receive raw_audio
  libobs/obs-output.c
Labels: Bug Fix

#8283 libobs: Render audio for all views
  libobs/obs-audio.c
Labels: Bug Fix

#9975 libobs-d3d11: Add display primaries to the log
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Enhancement, Windows

#9983 Revert "cmake: Align Product Name and Bundle Name on macOS"
  .github/scripts/.build.zsh
  cmake/macos/helpers.cmake
Labels: Bug Fix

#9984 CI: Downgrade flatpak-builder to fix Flatpak publish
  .github/workflows/publish.yaml
Labels: Bug Fix, Linux, CI

#10002 win-wasapi: Make reroute target a weak reference
  plugins/win-wasapi/win-wasapi.cpp
Labels: Bug Fix

#10004 Preparations for Camera portal, part 3
  plugins/linux-pipewire/pipewire.c
  plugins/linux-pipewire/pipewire.h
  plugins/linux-pipewire/screencast-portal.c
Labels: Enhancement, Seeking Testers, Linux

#7433 docs: Add property functions
  docs/sphinx/reference-properties.rst
Labels: Documentation

#8305 UI: Fix editableList inherits background-color of the group
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix, UI/UX

#7427 docs: Add missing sceneitem functions
  docs/sphinx/reference-scenes.rst
Labels: Documentation

#7910 UI: Fix the resize cursor with respecting the item transformation
  UI/window-basic-preview.cpp
Labels: Bug Fix, Seeking Testers

#9980 graphics-hook: Fix DXGI ref leak for D3D12 capture
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
Labels: Bug Fix

#9994 UI: Remove SignalBlocker
  UI/qt-wrappers.hpp
  UI/source-tree.cpp
Labels: Code Cleanup

#9996 libobs: Fix disk space reporting for attached network drives on macOS
  libobs/util/platform-cocoa.m
Labels: Bug Fix, macOS

#9999 win-capture: Toggle premultiplied alpha for games
  plugins/win-capture/data/locale/en-US.ini
  plugins/win-capture/game-capture.c
Labels: Enhancement, Windows

#10010 libobs: Remove obs-ui from public headers
  libobs/CMakeLists.txt
Labels: Bug Fix

#9918 CI: Use distributed network for service uptime check
  .github/actions/services-validator/action.yaml
  .github/scripts/utils.py/check-services.py
  .github/workflows/dispatch.yaml
  .github/workflows/scheduled.yaml
Labels: CI

#10009 UI: Remove double unit indication in replay buffer maximum string
  UI/data/locale/en-US.ini
Labels: UI/UX

#9990 UI: Remove lock & vis checkbox classes
  UI/cmake/legacy.cmake
  UI/cmake/ui-elements.cmake
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/locked-checkbox.cpp
  UI/locked-checkbox.hpp
  UI/source-tree.cpp
  UI/source-tree.hpp
  UI/visibility-checkbox.cpp
  UI/visibility-checkbox.hpp
  UI/visibility-item-widget.cpp
  UI/visibility-item-widget.hpp
Labels: Code Cleanup, UI/UX
