Repository obsproject/obs-studio, pull requests merged in 2023-02, with the labels that each got.

#8168 CI: Publish docs to Cloudflare Pages
  .github/workflows/docs.yml
Labels: Documentation, CI

#8208 obs-filters: Ensure gain is positive for upward compressor
  plugins/obs-filters/expander-filter.c
Labels: Bug Fix, Seeking Testers

#8178 UI: Add obs_frontend_open_sceneitem_edit_transform
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#8182 UI: Use input validator on advance resolution line edit
  UI/window-basic-settings.cpp
Labels: Bug Fix

#8184 obs-scripting: Add PyType_Modified import for Swig 4.1.1 compatibility
  deps/obs-scripting/obs-scripting-python-import.c
  deps/obs-scripting/obs-scripting-python-import.h
Labels: Bug Fix

#8187 UI: Add obs_frontend_add_undo_redo_action
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: New Feature

#8191 libobs-d3d11: Log display DPI and scale factor
  libobs-d3d11/CMakeLists.txt
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Seeking Testers, Windows

#8214 graphics-hook: Stop trying to connect early
  plugins/win-capture/graphics-hook/graphics-hook.c
Labels: Enhancement

#7920 UI: Disable properties button in source toolbar
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Code Cleanup, UI/UX

#8216 CI: Switch to curl for dependency downloads
  CI/windows/01_install_dependencies.ps1
Labels: Windows, CI

#8228 flatpak: Override PipeWire to 0.3.65
  CI/flatpak/com.obsproject.Studio.json
Labels: Bug Fix, Seeking Testers, Linux

#8218 UI: Fix properties widget being cut off until resize
  UI/properties-view.cpp
Labels: Bug Fix, Seeking Testers, UI/UX

#8232 obs-ffmpeg: Fix encoding of 2.1 with FFmpeg aac encoder
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
Labels: Bug Fix, Seeking Testers

#8227 obs-filters: Fix preset properties refresh
  plugins/obs-filters/expander-filter.c
Labels: Bug Fix

#8230 libobs: Avoid position underflow when mixing audio sources
  libobs/obs-scene.c
Labels: Bug Fix

#8239 obs-vst: Read plugins in symlink
  plugins/obs-vst/obs-vst.cpp
Labels: Bug Fix

#8244 UI: Add check for null widgetForAction result
  UI/qt-wrappers.cpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#8245 UI: Avoid excessive config reads when drawing preview
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
  UI/window-basic-settings.cpp
Labels: Bug Fix, UI/UX

#8246 UI: Remove workaround for current scene being deselectable on Qt 6.4.3+
  UI/item-widget-helpers.cpp
  UI/scene-tree.cpp
  UI/scene-tree.hpp
Labels: Code Cleanup

#8212 Improve Flatpak and Linux session logging
  libobs/obs-nix.c
Labels: Enhancement, Seeking Testers, Linux

#8238 UI: Fix scene item edit drag & drop bug
  UI/source-tree.cpp
Labels: Bug Fix, Seeking Testers

#8243 mac-videotoolbox: Load encoders from system asynchronously
  plugins/mac-videotoolbox/encoder.c
Labels: Enhancement, macOS

#8251 libobs-opengl: Accelerate dmabuf import
  libobs-opengl/gl-egl-common.c
  libobs-opengl/gl-texture2d.c
Labels: Enhancement, Seeking Testers, Linux

#8258 UI: Remove unused Qt crash reporter code
  UI/CMakeLists.txt
  UI/crash-report.cpp
  UI/crash-report.hpp
  UI/obs-app.cpp
Labels: Code Cleanup

#8272 linux-pipewire: Demote error to debug message
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#6680 vlc-video: Support subtitle track up to 1000
  plugins/vlc-video/vlc-video-source.c
Labels: Enhancement

#8271 libobs-opengl: Fix projector crash with external macOS displays
  libobs-opengl/gl-cocoa.m
Labels: Bug Fix, macOS

#6923 aja: Add audio channel selection to capture
  plugins/aja/CMakeLists.txt
  plugins/aja/aja-props.cpp
  plugins/aja/aja-props.hpp
  plugins/aja/aja-routing.cpp
  plugins/aja/aja-source.cpp
  plugins/aja/aja-source.hpp
  plugins/aja/aja-ui-props.hpp
  plugins/aja/audio-repack.c
  plugins/aja/audio-repack.h
  plugins/aja/audio-repack.hpp
  plugins/aja/data/locale/en-US.ini
Labels: Bug Fix, Seeking Testers, New Feature

#8190 CI/docs: Some fixes for CF Pages publishing
  .github/workflows/docs.yml
  docs/sphinx/conf.py
Labels: CI

#8261 UI: Correct browse behavior in non-empty input edit line
  UI/window-remux.cpp
Labels: Bug Fix

#8055 libobs/media-io: Check codec tag compatibility for out stream
  libobs/media-io/media-remux.c
Labels: Bug Fix

#8097 UI: Improved implementation for sorting filters menu
  UI/window-basic-filters.cpp
Labels: Enhancement, Code Cleanup

#8256 UI: Refactor / Clean up addNudge
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#7687 UI: Check item whether selected before select
  UI/source-tree.cpp
Labels: Bug Fix

#8279 linux-jack: Prepend devices with "OBS Studio: "
  plugins/linux-jack/jack-input.c
Labels: Enhancement

#7667 vlc-video: Fix videos larger than 1080p being squished
  plugins/vlc-video/vlc-video-source.c
Labels: Bug Fix

#8275 obs-ffmpeg: Relax 'lookahead' constraint when bitrate is updated
  plugins/obs-ffmpeg/jim-nvenc.c
Labels: Bug Fix, Seeking Testers

#8253 UI: Defer loading hotkeys until tab is switched
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Enhancement, Seeking Testers, UI/UX

#8267 UI: Remove bitness strings
  UI/obs-app.cpp
  UI/window-basic-about.cpp
Labels: Code Cleanup

#8278 UI: Connect Reset button in Transform menu with main window directly
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
Labels: Bug Fix

#8276 UI: Force Wayland usage on Ubuntu GNOME
  UI/obs-app.cpp
Labels: Seeking Testers, Linux

#8273 UI: Fix OBSPropertiesView button callback with its const char* constructor
  UI/properties-view.cpp
Labels: Bug Fix, Seeking Testers

#8146 UI: Use native color dialog on macOS
  UI/context-bar-controls.cpp
  UI/properties-view.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings-a11y.cpp
Labels: Enhancement, macOS

#8295 UI: Fix compile error when obs-browser disabled
  UI/update/shared-update.cpp
Labels: Bug Fix

#8296 UI: Don't double-delete children of deleted widgets
  UI/window-basic-settings.cpp
Labels: Bug Fix

#8254 UI: Massively improve hotkey search performance
  UI/window-basic-settings.cpp
Labels: Enhancement, Seeking Testers, UI/UX

#7347 UI: Use valueChanged() signal for T-Bar everywhere
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, Code Cleanup, UI/UX

#8172 UI: Add confirmation dialog for resetting properties
  UI/data/locale/en-US.ini
  UI/window-basic-filters.cpp
  UI/window-basic-properties.cpp
Labels: UI/UX

#7859 UI: Disable replay buffer checkbox when using custom FFmpeg
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Enhancement, UI/UX

#8311 Update Contribution Guidelines
  CONTRIBUTING.rst
Labels: Documentation

#8308 mac-capture: Fix various SCK memory leaks
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix, macOS

#8319 mac-videotoolbox: Refactor implementation and fix memory leaks
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix, Code Cleanup, macOS

#8330 libobs: Fix non-exhaustive switch statements introduced by ProRes 4444 support
  libobs/obs-source.c
Labels: Bug Fix

#7371 Drop win-ivcam
  UI/installer/mp-installer.nsi
  UI/win-update/updater/updater.cpp
  plugins/CMakeLists.txt
  plugins/win-ivcam/.clang-format
  plugins/win-ivcam/CMakeLists.txt
  plugins/win-ivcam/realsense.cpp
  plugins/win-ivcam/seg_library/Dependencies.h
  plugins/win-ivcam/seg_library/SegImage.cpp
  plugins/win-ivcam/seg_library/SegImage.h
  plugins/win-ivcam/seg_library/SegServer.h
  plugins/win-ivcam/seg_library/SegServerImpl.cpp
  plugins/win-ivcam/seg_library/SegServerImpl.h
  plugins/win-ivcam/seg_library/SegService.h
  plugins/win-ivcam/seg_library/SerServer.cpp
  plugins/win-ivcam/seg_service/CMakeLists.txt
  plugins/win-ivcam/seg_service/SegProc.cpp
  plugins/win-ivcam/seg_service/SegProc.h
  plugins/win-ivcam/seg_service/SegProc.rgs
  plugins/win-ivcam/seg_service/resource.h
  plugins/win-ivcam/seg_service/seg_service.cpp
  plugins/win-ivcam/seg_service/seg_service.idl
  plugins/win-ivcam/seg_service/seg_service.rc
  plugins/win-ivcam/seg_service/seg_service.rgs
  plugins/win-ivcam/seg_service/stdafx.cpp
  plugins/win-ivcam/seg_service/stdafx.h
  plugins/win-ivcam/seg_service/targetver.h
  plugins/win-ivcam/seg_service/xdlldata.c
  plugins/win-ivcam/seg_service/xdlldata.h
Labels: Code Cleanup, Windows

#8340 UI: Remove mf_aac references
  UI/audio-encoders.cpp
Labels: Code Cleanup

#7762 PipeWire buffer transform
  plugins/linux-pipewire/pipewire.c
Labels: Seeking Testers, Linux, New Feature

#8303 libobs: Fix pulseaudio monitoring, once and for all
  libobs/audio-monitoring/pulse/pulseaudio-output.c
Labels: Bug Fix, Seeking Testers, Linux

#8322 UI: Defer creation of hotkey dupe icon until needed
  UI/hotkey-edit.cpp
  UI/hotkey-edit.hpp
Labels: Bug Fix, UI/UX

#8323 UI: Set QT_NO_SUBTRACTOPAQUESIBLINGS env var
  UI/obs-app.cpp
Labels: Code Cleanup, UI/UX

#8325 UI: Use unordered_map for hotkey duplicate detection
  UI/window-basic-settings.cpp
Labels: Code Cleanup, Seeking Testers, UI/UX

#8326 docs: Fix layout and typos
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-libobs-graphics-effects.rst
  docs/sphinx/reference-modules.rst
  docs/sphinx/reference-outputs.rst
  docs/sphinx/reference-properties.rst
  docs/sphinx/reference-scenes.rst
  docs/sphinx/reference-sources.rst
  docs/sphinx/scripting.rst
  libobs/obs-properties.h
Labels: Documentation

#8341 libobs-d3d11: Log D3D11 adapter memory correctly
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Bug Fix

#8348 CI: Stop pinning Xcode to 14.1
  .github/workflows/main.yml
Labels: macOS, CI

#8217 Add option to fully decode and preload stinger video files into RAM
  deps/media-playback/CMakeLists.txt
  deps/media-playback/media-playback/cache.c
  deps/media-playback/media-playback/cache.h
  deps/media-playback/media-playback/decode.c
  deps/media-playback/media-playback/media-playback.c
  deps/media-playback/media-playback/media-playback.h
  deps/media-playback/media-playback/media.c
  deps/media-playback/media-playback/media.h
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
  plugins/obs-transitions/data/locale/en-US.ini
  plugins/obs-transitions/transition-stinger.c
Labels: Seeking Testers, New Feature

#8002 libobs: Fix bug with scene_audio_render()
  libobs/obs-scene.c
Labels: Bug Fix

#8349 obs-ffmpeg: Add full_decode to media source log
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#8353 UI: Remove unused variable in PopulateBitrateMap
  UI/audio-encoders.cpp
Labels: Code Cleanup
