Repository obsproject/obs-studio, pull requests merged in 2023-01, with the labels that each got.

#7936 obs-filters: Log NVIDIA Effects version only if lib is found
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvidia-greenscreen-filter.c
Labels: Bug Fix, Enhancement

#7933 UI: Use stream encoder when resetting encoders
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#7925 UI: Lock volume meter sliders to LTR to fix RTL slider direction
  UI/volume-control.cpp
Labels: Bug Fix

#8007 win-capture: Always reset timeout when searching for target display
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Bug Fix, Seeking Testers, Windows

#8006 CI: Revise repository conditions to validate JSON schema of services
  .github/workflows/services-json.yml
Labels: CI

#7919 docs: Add script_description to scripting
  docs/sphinx/scripting.rst
Labels: Documentation

#7932 docs: Clarify enum functions return value
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-scenes.rst
Labels: Documentation

#7942 UI: Disable qt5ct when compiled with qt6
  UI/obs-app.cpp
Labels: Bug Fix

#7986 linux-pipewire: Check format availablity against DRM only for dmabufs
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#7999 Prevent negative "disk full in" calculation when there's no output
  UI/window-basic-stats.cpp
Labels: Bug Fix

#8038 obs-filters: disable NVIDIA FX audio model loading if SDK is not installed
  plugins/obs-filters/noise-suppress-filter.c
Labels: Bug Fix

#8048 updater: Deduplicate Update Downloads
  UI/win-update/updater/updater.cpp
Labels: Bug Fix, Windows

#8036 rtmp-services: update Mildom servers
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#8058 obs-ffmpeg: Remove forced x264 and aac on RTMP
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix

#8059 UI: Reintroduce spacing to YouTube dialog buttons
  UI/forms/OBSYoutubeActions.ui
Labels: Bug Fix, UI/UX

#8017 libobs/util: Fix text-lookup not always case-insensitive
  libobs/util/text-lookup.c
Labels: Bug Fix

#8054 updater: Maintain portable state when relaunching
  UI/win-update/updater/updater.cpp
Labels: Bug Fix, Windows

#8025 libobs-opengl: Drop gl pointers on device_leave_context
  libobs-opengl/gl-cocoa.m
  libobs-opengl/gl-nix.c
Labels: Bug Fix

#7976 Improvements to Windows interface logging
  plugins/obs-outputs/rtmp-stream.c
Labels: Enhancement, Windows

#8003 libobs: Fix stopping transitions that are not active
  libobs/obs-source-transition.c
Labels: Bug Fix

#6960 Switch clean up (remove one-case switch and switch warning workaround)
  UI/platform-windows.cpp
  UI/source-tree.cpp
  UI/window-basic-stats.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs-opengl/gl-shader.c
  libobs-opengl/gl-windows.c
  libobs/graphics/graphics-ffmpeg.c
  libobs/obs-nix.c
  libobs/obs-scene.c
  libobs/obs-source-deinterlace.c
  libobs/obs-source.c
  libobs/obs.c
  plugins/linux-capture/linux-capture.c
  plugins/obs-ffmpeg/obs-ffmpeg-formats.h
  plugins/obs-filters/crop-filter.c
  plugins/obs-filters/gpu-delay.c
  plugins/obs-filters/nvidia-greenscreen-filter.c
  plugins/obs-filters/scale-filter.c
  plugins/obs-filters/scroll-filter.c
  plugins/obs-qsv11/common_directx9.cpp
  plugins/win-capture/graphics-hook/d3d8-capture.cpp
  plugins/win-capture/graphics-hook/d3d9-capture.cpp
  plugins/win-capture/graphics-hook/dxgi-helpers.hpp
Labels: Code Cleanup

#8044 mac-virtualcam: Fix memory access issues for shared IOSurfaces
  plugins/mac-virtualcam/src/dal-plugin/OBSDALMachClient.mm
  plugins/mac-virtualcam/src/obs-plugin/OBSDALMachServer.mm
Labels: Bug Fix, Seeking Testers, macOS

#8096 CI: Revert Qt to 6.3.1 on Windows
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, CI

#8091 libobs: Fix loading of custom_size for empty scenes
  libobs/obs-scene.c
Labels: Bug Fix

#8110 UI: Don't open properties dialog if item is scene
  UI/source-tree.cpp
Labels: Enhancement, UI/UX

#8106 updater: Hash files with multiple threads
  UI/win-update/updater/updater.cpp
Labels: Windows, New Feature

#8112 UI: Disable screenshot action if item has no video
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX

#7989 libobs/graphics: unbreak DMABUF on FreeBSD
  docs/sphinx/reference-libobs-graphics-graphics.rst
  libobs/graphics/device-exports.h
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
Labels: Bug Fix, Enhancement, Other OS (*nix), New Feature

#8099 obs-filters: Improve NVIDIA effects SDK version checks
  plugins/obs-filters/noise-suppress-filter.c
  plugins/obs-filters/nvafx-load.h
  plugins/obs-filters/nvidia-greenscreen-filter.c
  plugins/obs-filters/nvvfx-load.h
Labels: Bug Fix

#8122 libobs-opengl: Fixup dmabuf queries on X11
  libobs-opengl/gl-x11-egl.c
Labels: Bug Fix, Linux

#7891 frontend-tools: Fix crash on non X11 windowing systems
  UI/frontend-plugins/frontend-tools/auto-scene-switcher-nix.cpp
Labels: Bug Fix, Linux

#8139 obs-ffmpeg: Tell FFmpeg that BGRA uses alpha
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Bug Fix, Seeking Testers

#8135 UI: Work around Qt dock restore crash
  UI/auth-restream.cpp
  UI/auth-twitch.cpp
  UI/auth-youtube.cpp
Labels: Bug Fix, Seeking Testers

#8114 updater: Add additional status messages
  UI/win-update/updater/updater.cpp
Labels: Enhancement, Windows

#8081 win-capture: Support EnumDisplayDevices failure
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Bug Fix, Seeking Testers, Windows

#8070 updater: Pass AppData path to elevated process
  UI/win-update/updater/updater.cpp
Labels: Bug Fix, Windows

#8068 cmake,obs-ffmpeg: Refactor Libva finder
  cmake/Modules/FindLibva.cmake
  plugins/obs-ffmpeg/CMakeLists.txt
Labels: Bug Fix

#5614 linux-pipewire: check pipewire buffers for corruption
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#8121 obs-filters: Improve upward compressor & expander fix
  plugins/obs-filters/data/locale/en-US.ini
  plugins/obs-filters/expander-filter.c
Labels: Bug Fix, Seeking Testers

#8151 virtualcam-module: Update filter size immediately when used in OBS
  plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp
Labels: Bug Fix

#8116 UI: Re-raise properties window after picking files on macOS
  UI/properties-view.cpp
Labels: Bug Fix, macOS

#8150 UI: Unblock encoder comboboxes signals before change
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix, Seeking Testers

#8144 obs-vst: Add reporting of vendor name
  plugins/obs-vst/VSTPlugin.cpp
Labels: Enhancement

#8134 UI: Hide menu items if source is only audio
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX

#8169 updater: Deduplicate Delta Patch Downloads
  UI/win-update/updater/updater.cpp
Labels: Windows
