Repository obsproject/obs-studio, pull requests merged in 2023-05, with the labels that each got.

#8810 UI: Fix building macOS/Sparkle without Browser
  UI/CMakeLists.txt
  UI/cmake/feature-macos-update.cmake
  UI/cmake/feature-sparkle.cmake
  UI/cmake/feature-whatsnew.cmake
Labels: Bug Fix, Seeking Testers, macOS

#8838 UI: Relax mc_trans_video_imagescaler.dll DLL block
  UI/win-dll-blocklist.c
Labels: Bug Fix

#8853 cmake: Enforce -Wmaybe-uninitialized to never turn into an error
  cmake/Modules/CompilerConfig.cmake
Labels: Enhancement

#8847 UI: Do not show unassigned icon for monitored sources
  UI/volume-control.cpp
  UI/volume-control.hpp
Labels: Bug Fix, UI/UX

#8829 mac-capture: Fix possible division by zero error.
  plugins/mac-capture/mac-screen-capture.m
Labels: macOS

#8831 CI: Update ccache cache entries to enable restoration from master branch
  .github/workflows/main.yml
Labels: Enhancement, CI

#8833 UI: Change "Portable Mode" to translation key
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
Labels: Enhancement

#8835 mac-syphon: Remove macOS 10.15-only code
  plugins/mac-syphon/syphon.m
Labels: Code Cleanup, macOS

#8844 docs: Add missing elements in Services API
  docs/sphinx/reference-services.rst
Labels: Documentation

#8851 libobs: Fix luma sampling for packed 4:2:2 sources
  libobs/data/format_conversion.effect
Labels: Bug Fix

#8846 UI: Exit if clearing scene data fails
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: UI/UX

#8862 UI: Avoid registering CEF OAuth integrations on Wayland
  UI/auth-restream.cpp
  UI/auth-twitch.cpp
Labels: Bug Fix

#8871 UI: Fix crash on macOS when closing OAUTH browser panel
  UI/auth-oauth.cpp
  UI/auth-oauth.hpp
Labels: Bug Fix, macOS

#8868 test: Cover all array_output_serializer functions
  test/cmocka/test_serializer.c
Labels: Enhancement

#8875 obs-ffmpeg: Fix compilation when ENABLE_HEVC is not set
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix

#8891 UI: Fix crash when double-clicking projector
  UI/window-projector.cpp
Labels: Bug Fix

#8893 CI: Download Qt5 conditionally on Linux
  CI/linux/01_install_dependencies.sh
Labels: CI

#8894 deps/obs-scripting: Set file/chunk name when loading lua scripts
  deps/obs-scripting/obs-scripting-lua.c
Labels: Bug Fix

#8899 UI: Clean up disabling simpleFlvTracks
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Code Cleanup

#8901 UI: Process Qt events once after destroy queue finishes
  UI/window-basic-main.cpp
Labels: Bug Fix

#8623 mac-capture: Add option to hide OBS windows in desktop capture
  plugins/mac-capture/data/locale/en-US.ini
  plugins/mac-capture/mac-screen-capture.m
Labels: Seeking Testers, macOS, New Feature, UI/UX

#8671 obs-outputs: Fix keychain API deprecation warnings on macOS
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Code Cleanup, macOS

#8672 obs-scripting: Replace macro adding frontend functions with plain C code
  deps/obs-scripting/obs-scripting-lua-frontend.c
Labels: Code Cleanup

#8594 obs-ffmpeg,cmake: Replace external folder by obs-deps headers
  cmake/Modules/FindFFnvcodec.cmake
  cmake/finders/FindFFnvcodec.cmake
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/cmake/legacy.cmake
  plugins/obs-ffmpeg/external/.clang-format
  plugins/obs-ffmpeg/external/dynlink_cuda.h
  plugins/obs-ffmpeg/external/nvEncodeAPI.h
  plugins/obs-ffmpeg/jim-nvenc.h
  plugins/obs-ffmpeg/obs-nvenc-test/CMakeLists.txt
  plugins/obs-ffmpeg/obs-nvenc-test/jim-nvenc-test.c
Labels: Code Cleanup, Seeking Testers

#8539 UI: Redirect Qt log messages to OBS log
  UI/obs-app.cpp
Labels: Enhancement

#8873 libobs: Add sanity checks to some obs_output_t functions
  libobs/obs-output-delay.c
  libobs/obs-output.c
Labels: Code Cleanup

#8913 .gitignore: Add CMakeUserPresets.json
  .gitignore
Labels: Enhancement

#8917 libobs: Adds obs.hpp to exported header files
  libobs/CMakeLists.txt
Labels: Bug Fix

#6247 linux-pipewire: Add support for GS_R10G10B10A2
  plugins/linux-pipewire/pipewire.c
Labels: Seeking Testers, Linux, New Feature

#8830 UI: Remove tabs for About error statements
  UI/data/locale/en-US.ini
  UI/window-basic-about.cpp
Labels: Bug Fix

#8826 UI: Re-raise missing files dialog on macOS after file is selected
  UI/window-missing-files.cpp
Labels: Bug Fix, macOS

#8905 mac-videotoolbox: Fix incorrect keyframe interval calculation
  plugins/mac-videotoolbox/encoder.c
Labels: Bug Fix, Seeking Testers, macOS

#8885 libobs: Fix PulseAudio monitoring when device is set to default
  libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
Labels: Bug Fix, Linux

#8926 CI: Enable GPU priority for Windows builds
  .github/workflows/main.yml
  CI/windows/02_build_obs.ps1
Labels: Windows, CI

#8927 UI: Fix missing translations
  UI/data/locale/en-US.ini
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix, Code Cleanup

#8939 mac-virtualcam: Omit enqueue result codes
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Code Cleanup, macOS

#8874 libobs, plugins: Deprecate obs_output_t functions with flag parameters
  docs/sphinx/reference-outputs.rst
  libobs/obs-output-delay.c
  libobs/obs-output.c
  libobs/obs.h
  plugins/aja/aja-output.cpp
  plugins/decklink/decklink-output.cpp
  plugins/linux-v4l2/v4l2-output.c
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-outputs/flv-output.c
  plugins/obs-outputs/ftl-stream.c
  plugins/obs-outputs/null-output.c
  plugins/obs-outputs/rtmp-stream.c
  plugins/win-dshow/virtualcam.c
Labels: Code Cleanup, Seeking Testers

#8814 UI: Only defer property updates for input and transition sources
  UI/properties-view.cpp
  docs/sphinx/reference-properties.rst
Labels: Bug Fix, Documentation

#8823 obs-ffmpeg: Add FFmpeg Options for VA-API
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: New Feature

#8231 UI: Add scene grid mode to view menu
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#7938 win-dshow: Set audio only active when there is audio
  plugins/win-dshow/win-dshow.cpp
Labels: Enhancement

#8083 obs-ffmpeg: Add option to disable settings logging
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#8908 UI: Move saving of scene tree grid mode
  UI/scene-tree.cpp
  UI/window-basic-main.cpp
Labels: Code Cleanup

#8945 mac-virtualcam: Fix admin password locale string
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
Labels: Bug Fix, macOS

#8951 UI: Reset service selection to custom if name not found
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#8963 UI: Don't use ellipses in permissions window title
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
Labels: Bug Fix, UI/UX

#8969 mac-virtualcam: Adjust admin privilege strings to use Apple terminology
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
Labels: Bug Fix, Enhancement, macOS

#8975 UI: Fix crash on patronJsonThread
  UI/window-basic-main.cpp
Labels: Bug Fix

#8978 mac-virtualcam: Release pixel buffer pool for DAL as well
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, macOS

#8958 CONTRIBUTING.rst: Update Crowdin guide url
  CONTRIBUTING.rst
Labels: Code Cleanup

#8960 linux-alsa: Make "Custom" and "Default" translatable
  plugins/linux-alsa/alsa-input.c
  plugins/linux-alsa/data/locale/en-US.ini
Labels: Enhancement

#8977 UI: Fix menu actions missing shortcuts
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#8979 text-freetype2: Fix crash after reaching buffer size
  plugins/text-freetype2/text-functionality.c
Labels: Bug Fix

#8930 libobs: Fix ccache misses due to unstable obsconfig header
  UI/cmake/legacy.cmake
  UI/cmake/os-windows.cmake
  UI/obs-app.cpp
  UI/window-basic-about.cpp
  libobs/CMakeLists.txt
  libobs/cmake/legacy.cmake
  libobs/cmake/os-windows.cmake
  libobs/obs-internal.h
  libobs/obsconfig.h.in
  libobs/obsversion.c.in
  libobs/obsversion.h
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-outputs/flv-mux.c
  plugins/obs-outputs/ftl-stream.c
  plugins/win-capture/CMakeLists.txt
Labels: Enhancement, Code Cleanup, Seeking Testers

#7845 docs: Clarify source update_properties signal
  docs/sphinx/reference-sources.rst
Labels: Documentation

#7781 UI: Use main video on the virtual camera if program
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicVCamConfig.ui
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-vcam-config.cpp
  UI/window-basic-vcam-config.hpp
  UI/window-basic-vcam.hpp
Labels: Bug Fix, Seeking Testers, UI/UX
