Repository obsproject/obs-studio, pull requests merged in 2023-06, with the labels that each got.

#9009 UI: Fix filter shortcuts not showing in context menu
  UI/forms/OBSBasicFilters.ui
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
Labels: Bug Fix, Code Cleanup

#9006 Fix non-common services not being selectable
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#8991 obs-ffmpeg: Fix AMF encoder reconfiguration
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Enhancement

#8985 UI: Also toggle mixer toolbar in view menu
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX

#7246 UI: allow side docks to be tall
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, UI/UX

#7637 Avoid having two docks with the same object name
  UI/api-interface.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-frontend-api.rst
Labels: Bug Fix, Enhancement, New Feature

#7690 mac-capture: Sort application and window list alphabetically
  plugins/mac-capture/mac-screen-capture.m
Labels: Enhancement, macOS

#9032 mac-capture: Use system CGDisplayStream.h header on macOS 14 and newer
  plugins/mac-capture/mac-display-capture.m
Labels: Code Cleanup, macOS

#9034 obs-ffmpeg: Consider requested throughput in AMF preset fallback
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Enhancement

#7319 UI: Don't trigger a settings update when property list is empty
  UI/properties-view.cpp
Labels: Bug Fix

#5066 win-capture: Render nothing if window is iconic
  plugins/win-capture/window-capture.c
Labels: Bug Fix

#9041 win-capture: Skip compat helper matching if properties are null
  plugins/win-capture/compat-helpers.c
Labels: Bug Fix

#9025 libobs: Fix crash when properties are deleted in callback
  libobs/obs-properties.c
Labels: Bug Fix, Seeking Testers

#9057 rtmp-services: Remove extraneous comma in schema
  plugins/rtmp-services/data/schema/service-schema-v5.json
Labels: Bug Fix, Services

#9044 mac-capture: Explicitly set clear background for SCK
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix, macOS

#9052 libobs/util: Fix use-after-free in darray_insert_new
  libobs/util/darray.h
Labels: Bug Fix

#9045 libobs: Don't keep the sources mutex in tick_sources
  libobs/obs-internal.h
  libobs/obs-video.c
  libobs/obs.c
Labels: Enhancement

#9058 obs-scripting: Fix the pointer to current_lua_script when calling script_unload() in Lua script deinitialization
  deps/obs-scripting/obs-scripting-lua.c
Labels: Bug Fix

#9018 UI: Change name of ResetProxyStyleSliders function
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#9021 libobs,plugins: Remove new obs_output_*2 functions
  docs/sphinx/reference-outputs.rst
  libobs/obs-output-delay.c
  libobs/obs-output.c
  libobs/obs.h
  plugins/aja/aja-output.cpp
  plugins/decklink/decklink-output.cpp
  plugins/linux-v4l2/v4l2-output.c
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
  plugins/obs-outputs/flv-output.c
  plugins/obs-outputs/ftl-stream.c
  plugins/obs-outputs/null-output.c
  plugins/obs-outputs/rtmp-stream.c
  plugins/win-dshow/virtualcam.c
Labels: Code Cleanup

#9022 UI: Don't create combobox for radio buttons in properties view
  UI/properties-view.cpp
Labels: Bug Fix

#9046 docs: Clarify da_erase_range
  docs/sphinx/reference-libobs-util-darray.rst
Labels: Documentation

#9047 UI: Don't update text source when nothing changed
  UI/context-bar-controls.cpp
Labels: Bug Fix

#9063 UI: Don't show WHIP in stream settings if the protocol isn't registered
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#9067 obs-webrtc: Use old obs_output functions
  plugins/obs-webrtc/whip-output.cpp
Labels: Bug Fix

#8993 linux-pipewire: Skip processing video buffer if import failed
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#8952 updater: Refactor and cleanup
  UI/win-update/updater/hash.cpp
  UI/win-update/updater/http.cpp
  UI/win-update/updater/patch.cpp
  UI/win-update/updater/updater.cpp
  UI/win-update/updater/updater.hpp
Labels: Code Cleanup

#8619 UI: Render preview lines above safe areas
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX

#7835 text-freetype2: Improve text/file properties UX
  plugins/text-freetype2/data/locale/en-US.ini
  plugins/text-freetype2/text-freetype2.c
Labels: Enhancement, UI/UX

#8093 libobs: Add support to outputs for multi video encoders
  libobs/obs-internal.h
  libobs/obs-output.c
  libobs/obs-output.h
  libobs/obs.h
Labels: Enhancement, New Feature

#9078 UI: Move WHIP service to the bottom of the visible list
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#9087 obs-ffmpeg: Fix logic in one of the AMF preset fallback checks
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix

#9065 mac-capture: Add SCStreamDelegate to stream to log capture errors
  plugins/mac-capture/mac-screen-capture.m
Labels: Enhancement, macOS

#9090 mac-capture: Fix wrong CFString to NSNumber cast
  plugins/mac-capture/window-utils.m
Labels: Bug Fix, macOS

#9083 mac-syphon: Remove unused OBSSyphonKVObserver
  plugins/mac-syphon/syphon.m
Labels: Code Cleanup, macOS

#9069 libobs-d3d11: More detailed HAGS logging
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Seeking Testers

#9074 docs: Fix da_push_back return type
  docs/sphinx/reference-libobs-util-darray.rst
Labels: Documentation

#9076 obs-filters: Don't compile audio delay code in async-delay-filter
  plugins/obs-filters/async-delay-filter.c
Labels: Code Cleanup

#9081 rtmp-services: Update Bilibili Live
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#9085 UI: Capitalize "Full-Height Docks"
  UI/data/locale/en-US.ini
Labels: Enhancement

#9093 text-freetype2: Fix not updating chat log mode property
  plugins/text-freetype2/text-freetype2.c
Labels: Bug Fix

#9094 UI: Fix checked state of source toolbar menu item
  UI/window-basic-main.cpp
Labels: Bug Fix

#8774 UI: Disable Ok button in Add Source dialog if no source is selected
  UI/window-basic-source-select.cpp
Labels: Enhancement, UI/UX

#7929 obs-scripting: Add config file functions
  deps/obs-scripting/obslua/obslua.i
  deps/obs-scripting/obspython/obspython.i
Labels: New Feature

#9128 CI: Update deps to 2023-06-22 release
  .github/workflows/main.yml
  build-aux/modules/30-ffmpeg.json
  buildspec.json
Labels: Seeking Testers, CI

#7455 obs-ffmpeg: Prevent media source restart
  deps/media-playback/media-playback/media-playback.c
  deps/media-playback/media-playback/media-playback.h
  deps/media-playback/media-playback/media.c
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement

#9066 CI: Remove Ubuntu 20.04 build
  .github/workflows/main.yml
Labels: Code Cleanup, CI

#9106 rtmp-services: Update Vindral servers
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#9108 UI: Fix icon paths of transition buttons
  UI/forms/OBSBasic.ui
Labels: Bug Fix, UI/UX

#9115 docs: Add versionadded directives for 29.1
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-frontend-api.rst
  docs/sphinx/reference-libobs-util-platform.rst
  docs/sphinx/reference-outputs.rst
  docs/sphinx/reference-services.rst
  docs/sphinx/reference-sources.rst
Labels: Documentation

#9116 libobs: Detect and log presence of Lenovo Vantage on Windows
  libobs/obs-windows.c
Labels: Seeking Testers, Windows

#9137 obs-ffmpeg: Fix media source playing when inactive
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#9140 mac-capture: Fix show hidden windows option which doesn't work immediately.
  plugins/mac-capture/mac-screen-capture.m
Labels: Bug Fix, macOS

#9141 mac-capture: Improve various Objective-C code
  plugins/mac-capture/mac-screen-capture.m
Labels: Code Cleanup, macOS

#9123 UI: Change surround sound warning to signal YouTube support
  UI/data/locale/en-US.ini
Labels: Enhancement

#9129 rtmp-services: Enforce encoder settings according to protocol
  plugins/rtmp-services/rtmp-custom.c
Labels: Bug Fix

#9152 libobs: Fix obs_output_get_height2 returning width
  libobs/obs-output.c
Labels: Bug Fix

#9043 Add GPU based output scaling
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs.h
  plugins/obs-ffmpeg/obs-nvenc.c
  plugins/obs-ffmpeg/texture-amf.cpp
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement, New Feature

#8984 obs-scripting: Fix python save callback Py_BuildValue
  deps/obs-scripting/obs-scripting-python-frontend.c
Labels: Bug Fix

#9143 CI: Update main workflow to enable building with macOS 13 runners
  .github/workflows/main.yml
  cmake/macos/defaults.cmake
  cmake/macos/resources/package.applescript
Labels: Seeking Testers

#9176 CI: Fix call to base64 on macOS
  .github/workflows/main.yml
Labels: Seeking Testers, macOS, CI

#9182 cmake: Fix configuration errors with Windows legacy path
  libobs/cmake/legacy.cmake
  plugins/obs-ffmpeg/obs-nvenc-test/cmake/legacy.cmake
  plugins/win-capture/cmake/legacy.cmake
  plugins/win-dshow/cmake/legacy.cmake
Labels: Bug Fix

#9181 cmake: Add support for unobfuscated OAuth secrets
  UI/cmake/feature-restream.cmake
  UI/cmake/feature-twitch.cmake
  UI/cmake/feature-youtube.cmake
Labels: Bug Fix

#9092 cmake: Remove ObsPluginHelpers.cmake
  cmake/external/ObsPluginHelpers.cmake
Labels: Code Cleanup

#9177 cmake: Add flags for reproducible builds on Windows
  cmake/windows/compilerconfig.cmake
  cmake/windows/helpers.cmake
Labels: Bug Fix

#9077 UI: Log Program scene changes in studio mode
  UI/window-basic-main-transitions.cpp
Labels: Enhancement

#8778 mac-capture: Add macOS Audio Capture
  plugins/mac-capture/CMakeLists.txt
  plugins/mac-capture/data/locale/en-US.ini
  plugins/mac-capture/mac-sck-audio-capture.m
  plugins/mac-capture/mac-sck-common.h
  plugins/mac-capture/mac-sck-common.m
  plugins/mac-capture/mac-sck-video-capture.m
  plugins/mac-capture/plugin-main.c
Labels: macOS, New Feature
