Repository obsproject/obs-studio, pull requests merged in 2023-07, with the labels that each got.

#9186 mac-capture: Mark CoreAudio output capture source as deprecated
  plugins/mac-capture/plugin-main.c
Labels: Enhancement, macOS, UI/UX

#9183 UI: Fix utf-8 paths in shared updater components
  UI/update/shared-update.cpp
Labels: Bug Fix, Seeking Testers

#9188 cmake: Fix copy to rundir in Release and MinSizeRel configurations
  cmake/windows/helpers.cmake
Labels: Bug Fix, Windows

#9196 mac-capture: Remove unneeded debug log
  plugins/mac-capture/mac-sck-audio-capture.m
Labels: Code Cleanup, macOS

#9107 mac-capture: Add button to reactivate stopped capture
  plugins/mac-capture/data/locale/en-US.ini
  plugins/mac-capture/mac-sck-audio-capture.m
  plugins/mac-capture/mac-sck-common.h
  plugins/mac-capture/mac-sck-common.m
  plugins/mac-capture/mac-sck-video-capture.m
Labels: Enhancement, macOS

#9197 mac-capture: Use error code constant instead of magic number
  plugins/mac-capture/mac-sck-audio-capture.m
  plugins/mac-capture/mac-sck-video-capture.m
Labels: Bug Fix, Code Cleanup, macOS

#9001 Allow encoders to output at partial frame rates compared to main compositing frame rate
  libobs/media-io/video-io.c
  libobs/media-io/video-io.h
  libobs/obs-encoder.c
  libobs/obs-internal.h
  libobs/obs-output.c
  libobs/obs-video-gpu-encode.c
  libobs/obs.c
  libobs/obs.h
Labels: New Feature

#9189 mac-virtualcam: Fix use of collection without explicit type
  plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
Labels: Code Cleanup, macOS

#8014 QSV Cleanups
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/common_utils.h
  plugins/obs-qsv11/common_utils_windows.cpp
  plugins/obs-qsv11/obs-qsv11-plugin-main.c
  plugins/obs-qsv11/obs-qsv11.c
Labels: Code Cleanup, Seeking Testers

#9048 docs: Add example for DARRAY as function parameter
  docs/sphinx/reference-libobs-util-darray.rst
Labels: Documentation

#9214 updater: Fix updating without patch files
  UI/win-update/updater/updater.cpp
Labels: Bug Fix

#9095 UI: Fix scenes only multiview label position
  UI/multiview.cpp
Labels: Bug Fix

#9157 UI: Fix crash radio list without items
  UI/properties-view.cpp
Labels: Bug Fix

#9178 win-capture: Enable compatability data updates by default
  plugins/win-capture/CMakeLists.txt
  plugins/win-capture/cmake/legacy.cmake
Labels: Bug Fix

#9179 obs-ffmpeg: Increase initial buffer fullness for VAAPI
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Enhancement, Linux

#9200 UI: Soft-delete scene collections
  UI/window-basic-main-scene-collections.cpp
Labels: Enhancement

#9209 libobs: Fix flip not working with stretch to bounds
  libobs/obs-scene.c
Labels: Bug Fix

#9242 UI: Fix preprocessor directives for streaming platform integrations
  UI/window-basic-auto-config.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix, Code Cleanup

#9237 obs-filters: Fix legacy CMake obs_status for RNNoise
  plugins/obs-filters/cmake/legacy.cmake
Labels: Bug Fix, Code Cleanup

#9243 obs-qsv11: Fix missing ENABLE_HEVC definition for test executable
  plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt
Labels: Bug Fix, Windows

#9061 UI: Remove Qt 5 ifdef guards and code
  UI/focus-list.cpp
  UI/hotkey-edit.cpp
  UI/hotkey-edit.hpp
  UI/log-viewer.cpp
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/qt-display.cpp
  UI/qt-display.hpp
  UI/scene-tree.cpp
  UI/slider-ignorewheel.cpp
  UI/source-tree.cpp
  UI/source-tree.hpp
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
  UI/window-basic-interaction.cpp
  UI/window-basic-interaction.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-preview.cpp
  UI/window-basic-properties.cpp
  UI/window-basic-properties.hpp
  UI/window-basic-settings.cpp
Labels: Code Cleanup

#9254 libobs: Fix back-to-back GPU encoder sessions breaking
  libobs/obs-encoder.c
Labels: Bug Fix

#9226 UI, libobs: Add RAII wrappers for faders/volume meters
  UI/volume-control.cpp
  UI/volume-control.hpp
  libobs/obs.hpp
Labels: Code Cleanup

#9229 UI: Don't call activateWindow() when hidden
  UI/window-basic-main.cpp
Labels: Bug Fix, Enhancement

#9238 libobs: Export more libobs/util headers
  libobs/CMakeLists.txt
Labels: Bug Fix

#9239 mac-capture: Remove internal display settings from SCK Audio Capture
  plugins/mac-capture/mac-sck-audio-capture.m
Labels: Code Cleanup, macOS

#9240 UI: Localize font picker window title
  UI/context-bar-controls.cpp
  UI/data/locale/en-US.ini
  UI/properties-view.cpp
Labels: Enhancement

#9251 UI: Don't set fragmentation movflags in lossless mode
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#9252 docs: Add obs_properties_add_button2
  docs/sphinx/reference-properties.rst
Labels: Documentation

#9257 libobs-d3d11: Left-pad device PCI ID to 4 characters with zeroes
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Enhancement

#9260 cmake: Fix missing space between sentences
  CMakeLists.txt
Labels: Bug Fix

#9250 mac-capture: Set correct default type for application data
  plugins/mac-capture/mac-sck-audio-capture.m
  plugins/mac-capture/mac-sck-video-capture.m
Labels: Bug Fix

#9261 .git-blame-ignore-revs: Add recent clang-format changes
  .git-blame-ignore-revs
Labels: Code Cleanup

#9259 cmake: Fix missing libobs subdirectories in MSVC code navigator
  cmake/windows/helpers.cmake
Labels: Bug Fix, Windows

#9218 obs-ffmpeg: Fix media source always STATE_ENDED
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Bug Fix

#9217 UI: Fix transform shortcuts for audio only sources
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#8948 UI: Adjust properties view size policy
  UI/properties-view.cpp
Labels: Enhancement, Seeking Testers, UI/UX

#9266 README.rst: Fix GitHub Actions status badge
  README.rst
Labels: Documentation

#9126 obs-webrtc: Add user-agent, timestamp, and ssrc generation
  plugins/obs-webrtc/CMakeLists.txt
  plugins/obs-webrtc/cmake/legacy.cmake
  plugins/obs-webrtc/whip-output.cpp
  plugins/obs-webrtc/whip-output.h
  plugins/obs-webrtc/whip-utils.h
Labels: Bug Fix, Enhancement, New Feature

#9265 UI: Avoid QT_TO_UTF8(QTStr()) double conversion
  UI/window-basic-stats.cpp
Labels: Code Cleanup

#9026 obs-ffmpeg: Fix rendezvous mode with SRT
  plugins/obs-ffmpeg/obs-ffmpeg-srt.h
Labels: Bug Fix, Seeking Testers

#9271 CI: Fix Qt XML validator attempting to validate non-XML files
  .github/actions/qt-xml-validator/action.yaml
Labels: Bug Fix

#9270 CI: Fix scheduled Steam builds
  .github/workflows/scheduled.yaml
Labels: Bug Fix

#9279 CI: Remove label triggers from pull request workflow
  .github/workflows/pr-pull.yaml
Labels: Bug Fix, Seeking Testers

#9148 libobs: Change return type for getting filter index
  UI/window-basic-filters.cpp
  libobs/obs-source.c
  libobs/obs.h
Labels: Bug Fix

#9288 CI: Fix random password generation for macOS codesigning
  .github/actions/setup-macos-codesigning/action.yaml
Labels: Bug Fix

#9287 CI: Fix broken Flatpak cache generation on CI
  .github/workflows/build-project.yaml
  .github/workflows/publish.yaml
Labels: Bug Fix, CI

#9290 CI: Fix broken download of nightly build artifacts for Steam uploads
  .github/actions/steam-upload/action.yaml
Labels: Bug Fix, CI

#9269 Ignore libdshowcapture and add deps to the format script
  build-aux/.run-format.zsh
Labels: Bug Fix, Enhancement, CI

#9272 UI: Don't clear lastService immediately after setting it
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#9277 UI: Fix remaining status bar nits
  UI/window-basic-status-bar.cpp
Labels: Code Cleanup

#9291 updater: Update installed version in registry
  UI/win-update/updater/updater.cpp
Labels: Bug Fix, Windows

#9295 CI: Fix steamcmd being unable to find generated build file
  .github/actions/steam-upload/action.yaml
Labels: Bug Fix

#9296 CI: Fix Python 3.11 installation on macOS 13 runners
  .github/actions/services-validator/action.yaml
Labels: Bug Fix

#8455 Add Safe Mode
  UI/CMakeLists.txt
  UI/cmake/legacy.cmake
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  docs/sphinx/reference-modules.rst
  libobs/obs-internal.h
  libobs/obs-module.c
  libobs/obs.c
  libobs/obs.h
Labels: Seeking Testers, New Feature, UI/UX

#9249 libobs-d3d11: Implement shader cache
  UI/obs-app.cpp
  libobs-d3d11/d3d11-shader.cpp
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
Labels: Seeking Testers, Windows

#9275 build-aux: Add shader cache cleanup to steam uninstall script
  build-aux/steam/scripts_windows/uninstall.bat
Labels: Enhancement

#9162 docs: Add documentation for filter index functions
  docs/sphinx/reference-sources.rst
Labels: Documentation

#9292 updater: Migrate to nlohmann JSON
  UI/win-update/updater/CMakeLists.txt
  UI/win-update/updater/cmake/legacy.cmake
  UI/win-update/updater/manifest.hpp
  UI/win-update/updater/updater.cpp
  UI/win-update/updater/updater.hpp
Labels: Code Cleanup, Windows

#9274 rtmp-services: Add "VStream" RTMP service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#9120 IPv6 with IPv4 fast fallback (RFC 6555) for RTMP
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
  deps/CMakeLists.txt
  deps/happy-eyeballs/CMakeLists.txt
  deps/happy-eyeballs/happy-eyeballs.c
  deps/happy-eyeballs/happy-eyeballs.h
  plugins/obs-outputs/CMakeLists.txt
  plugins/obs-outputs/cmake/legacy.cmake
  plugins/obs-outputs/data/locale/en-US.ini
  plugins/obs-outputs/librtmp/rtmp.c
  plugins/obs-outputs/librtmp/rtmp.h
  plugins/obs-outputs/net-if.c
  plugins/obs-outputs/net-if.h
  plugins/obs-outputs/rtmp-stream.c
  plugins/obs-outputs/rtmp-stream.h
Labels: Enhancement, Seeking Testers

#9212 UI: Fixes to preview drawing and interactions with flipped sceneitems
  UI/window-basic-preview.cpp
Labels: Bug Fix

#9317 obs-qsv11: Link against Libva on Linux
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-qsv11/cmake/legacy.cmake
Labels: Bug Fix, Seeking Testers, Linux

#9211 libobs: Fix flip calculations in bounding box
  libobs/obs-scene.c
Labels: Bug Fix

#9323 libobs: Fix GPU scaled video encoder media not being cleared
  libobs/obs-encoder.c
Labels: Bug Fix

#9320 obs-outputs: Set videocodecid to HEVC/AV1 FourCC in E-RTMP
  plugins/obs-outputs/flv-mux.c
Labels: Bug Fix, Seeking Testers

#9325 UI: Avoid auto config selecting QSV on linux
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix, Linux

#9303 CI: Add fixes for tagged release runs and assorted minor issues
  .github/actions/build-obs/action.yaml
  .github/actions/qt-xml-validator/action.yaml
  .github/actions/run-clang-format/action.yaml
  .github/actions/run-cmake-format/action.yaml
  .github/actions/run-swift-format/action.yaml
  .github/actions/setup-macos-codesigning/action.yaml
  .github/actions/sparkle-appcast/action.yaml
  .github/actions/steam-upload/action.yaml
  .github/scripts/.package.zsh
  .github/scripts/utils.zsh/create_diskimage
  .github/scripts/utils.zsh/read_codesign_pass
  .github/workflows/build-project.yaml
  .github/workflows/dispatch.yaml
  .github/workflows/publish.yaml
  .github/workflows/push.yaml
Labels: Bug Fix

#9301 aja: Ignore return value from aja-common functions
  plugins/aja/aja-routing.cpp
Labels: Code Cleanup

#9302 UI: Migrate WhatsNew, update branches, and Windows update check to nlohmann JSON
  UI/cmake/feature-macos-update.cmake
  UI/cmake/feature-whatsnew.cmake
  UI/cmake/legacy.cmake
  UI/cmake/os-windows.cmake
  UI/obs-app.cpp
  UI/update/models/branches.hpp
  UI/update/models/whatsnew.hpp
  UI/update/win-update.cpp
  UI/win-update/updater/manifest.hpp
  UI/window-basic-main.cpp
Labels: Enhancement, Code Cleanup

#9304 obs-qsv11: Downgrade minimum required CMake version
  plugins/obs-qsv11/CMakeLists.txt
Labels: Bug Fix

#9308 build-aux: Add RNNoise Flatpak module
  build-aux/com.obsproject.Studio.json
  build-aux/modules/50-rnnoise.json
Labels: Enhancement, Seeking Testers, Linux

#9332 libobs: Add obs_source_info.filter_add
  docs/sphinx/reference-sources.rst
  libobs/obs-source.c
  libobs/obs-source.h
Labels: New Feature

#8689 UI: SIGNAL and SLOT macros begone!
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/auth-youtube.cpp
  UI/double-slider.cpp
  UI/double-slider.hpp
  UI/frontend-plugins/aja-output-ui/AJAOutputUI.cpp
  UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp
  UI/frontend-plugins/frontend-tools/output-timer.cpp
  UI/frontend-plugins/frontend-tools/scripts.cpp
  UI/lineedit-autoresize.cpp
  UI/media-controls.cpp
  UI/obs-app.cpp
  UI/properties-view.cpp
  UI/properties-view.hpp
  UI/visibility-item-widget.cpp
  UI/visibility-item-widget.hpp
  UI/volume-control.cpp
  UI/volume-control.hpp
  UI/window-basic-about.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-filters.cpp
  UI/window-basic-filters.hpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-properties.cpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
  UI/window-basic-status-bar.cpp
  UI/window-basic-status-bar.hpp
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
  UI/window-basic-vcam-config.cpp
  UI/window-importer.cpp
  UI/window-missing-files.cpp
  UI/window-projector.cpp
  UI/window-remux.cpp
Labels: Code Cleanup

#2538 UI: Split toggle preview program hotkey into hotkey pair
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#9335 deps/libff: Remove unused code and header files
  deps/libff/libff/ff-audio-decoder.c
  deps/libff/libff/ff-callbacks.c
  deps/libff/libff/ff-callbacks.h
  deps/libff/libff/ff-circular-queue.c
  deps/libff/libff/ff-circular-queue.h
  deps/libff/libff/ff-clock.c
  deps/libff/libff/ff-clock.h
  deps/libff/libff/ff-compat.h
  deps/libff/libff/ff-decoder.c
  deps/libff/libff/ff-decoder.h
  deps/libff/libff/ff-demuxer.c
  deps/libff/libff/ff-demuxer.h
  deps/libff/libff/ff-frame.h
  deps/libff/libff/ff-packet-queue.c
  deps/libff/libff/ff-packet-queue.h
  deps/libff/libff/ff-threading-posix.c
  deps/libff/libff/ff-threading-windows.c
  deps/libff/libff/ff-threading.h
  deps/libff/libff/ff-timer.c
  deps/libff/libff/ff-timer.h
  deps/libff/libff/ff-video-decoder.c
Labels: Code Cleanup

#8126 UI: Add new scene at current row
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX
