Repository obsproject/obs-studio, pull requests merged in 2023-03, with the labels that each got.

#7643 libobs: Make wcs<->utf8 conversion consistent
  libobs/util/utf8.c
Labels: Bug Fix, macOS, Linux

#8382 UI: Fix tabstops on settings dialog
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#8363 libobs: Clarify `memalign()` todo item
  libobs/util/bmem.c
Labels: macOS, Linux

#8383 libobs: Fix device functions not marked as EXPORT
  libobs/graphics/device-exports.h
  libobs/graphics/graphics-imports.c
Labels: Bug Fix

#8384 cmake: Remove FindRSSDK
  cmake/Modules/FindRSSDK.cmake
Labels: Code Cleanup

#8376 obs-ffmpeg: Fix for FFmpeg 6 deprecating a flag
  deps/media-playback/media-playback/decode.c
  deps/media-playback/media-playback/decode.h
  libobs/obs-ffmpeg-compat.h
  plugins/obs-ffmpeg/obs-ffmpeg-compat.h
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix

#8115 updater: Multi-threaded delta patching
  UI/win-update/updater/updater.cpp
Labels: Enhancement, Windows

#8334 rtmp-services: update Mildom more_info_link
  plugins/rtmp-services/data/services.json
Labels: Services

#8269 rtmp-services: Update Stripchat streaming service url
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#7921 rtmp-services: Update Streamvi
  plugins/rtmp-services/data/services.json
Labels: Services

#8381 More PipeWire cleanups
  plugins/linux-pipewire/pipewire.c
Labels: Code Cleanup, Linux

#8141 updater: Remove 32-bit Support
  UI/win-update/updater/updater.cpp
Labels: Code Cleanup, Windows

#8317 rtmp-services: Add Enchant.events to service list
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#8027 deps/media-playback: Enable CUDA HW decoder
  deps/media-playback/media-playback/decode.c
Labels: Enhancement, Seeking Testers

#8142 updater: Check if awaited instance matches current install
  UI/win-update/updater/updater.cpp
Labels: Windows

#8374 libobs/media-io: Add color range and colorspace data to conversion
  libobs/media-io/video-io.c
Labels: Bug Fix

#8391 obs-ffmpeg: Implement QVBR for AMF encoders
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Enhancement

#8347 Disable encoder scaling if scaled resolution matches output resolution
  libobs/obs-encoder.c
Labels: Enhancement, Request for Comments

#8366 obs-transitions: Add long description for full decode option
  plugins/obs-transitions/data/locale/en-US.ini
  plugins/obs-transitions/transition-stinger.c
Labels: Enhancement

#8367 Add mutex for writing to the log file
  UI/obs-app.cpp
Labels: Bug Fix

#8392 obs-ffmpeg: Fix crash during ratecontrol check
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix

#8394 Hold async mutex when calling set_async_texture_size
  libobs/obs-source.c
Labels: Bug Fix

#8401 CI: Update deps to 2023-03-04 release
  .github/workflows/main.yml
Labels: Enhancement, Code Cleanup, Seeking Testers, CI

#8403 UI: Fix spacing helpers when rotated and flipped
  UI/window-basic-preview.cpp
Labels: Bug Fix

#8404 UI: Don't hardcode properties label colors
  UI/properties-view.cpp
Labels: Code Cleanup

#8373 UI: Fix leak with empty path in stats
  libobs/util/platform-windows.c
Labels: Bug Fix

#8405 UI: Fix preview disabled in studio mode
  UI/window-basic-main.cpp
Labels: Bug Fix

#8406 UI: Fix wrong program scene if tbar is aborted
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#8408 UI: Set min/max zoom levels for preview
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
Labels: Bug Fix

#8321 UI: Fix disabled text color in dark theme
  UI/data/themes/Dark.qss
Labels: Bug Fix, UI/UX

#8337 UI: Make T-Bar unclickable
  UI/slider-ignorewheel.cpp
  UI/slider-ignorewheel.hpp
  UI/window-basic-main-transitions.cpp
Labels: Enhancement, UI/UX

#7830 CI: Create Sparkle appcast and deltas on tag
  .github/workflows/main.yml
  CI/macos/appcast_convert.py
  CI/macos/appcast_download.py
Labels: CI

#8299 obs-outputs: Fix RTMP undefined symbols if built without Mbed TLS
  plugins/obs-outputs/CMakeLists.txt
Labels: Bug Fix

#8205 libobs: Write default values to config
  libobs/util/config-file.c
Labels: Enhancement

#8365 Fix failures in reading public key file
  UI/update/shared-update.cpp
Labels: Bug Fix

#8427 win-capture: Suppress LNK4098
  plugins/win-capture/CMakeLists.txt
Labels: Bug Fix

#8428 UI: Do not set default locale
  UI/obs-app.cpp
Labels: Bug Fix

#8343 Add DLL blocking functionality for Windows
  UI/CMakeLists.txt
  UI/obs-app.cpp
  UI/obs-app.hpp
  UI/win-dll-blocklist.c
Labels: Seeking Testers, New Feature

#8423 obs-vst: Fix memory leaks on macOS when VST's fail to load
  plugins/obs-vst/mac/VSTPlugin-osx.mm
Labels: Bug Fix, macOS

#8429 UI: Re-raise remux dialog after selecting file on macOS
  UI/window-remux.cpp
Labels: Bug Fix

#8233 UI: Set flathub::manifest to manifest used to build Flatpak
  UI/xdg-data/CMakeLists.txt
  UI/xdg-data/com.obsproject.Studio.appdata.xml.in
Labels: Linux

#8442 media-playback: Fix libavutil version check
  deps/media-playback/media-playback/decode.c
Labels: Bug Fix

#8443 UI/installer: Add Quotes around UninstallString
  UI/installer/mp-installer.nsi
Labels: Bug Fix, Windows

#8444 UI: Create OBSPermissions on stack
  UI/obs-app.cpp
  UI/window-basic-main.cpp
Labels: Bug Fix, macOS

#8430 UI: Don't try to make OBSBasic parent of ControlsSplitButton
  UI/record-button.cpp
Labels: Bug Fix

#8426 UI: Limit preview scrolling
  UI/window-basic-main.cpp
  UI/window-basic-preview.cpp
  UI/window-basic-preview.hpp
Labels: Bug Fix

#8433 UI: Don't show video-only async filters for synchronous sources
  UI/window-basic-filters.cpp
Labels: Bug Fix

#8452 UI: Don't show Update section in settings when built without Sparkle
  UI/window-basic-settings.cpp
Labels: Bug Fix, macOS

#8467 linux-pipewire: Clear cursor texture on empty bitmap
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#8476 win-capture: Remove the redundant "-" in the CSGO launch option and Steam url language code
  plugins/win-capture/data/compatibility.json
  plugins/win-capture/data/locale/en-US.ini
Labels: Enhancement, Windows

#8461 flatpak: Add missing CMAKE_BUILD_TYPE
  CI/flatpak/com.obsproject.Studio.json
Labels: Enhancement, Linux

#8470 UI: Add Help menu action to show What's New dialog
  UI/data/locale/en-US.ini
  UI/forms/OBSBasic.ui
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: New Feature

#8473 Add old Vtuber Maker versions to DLL blocklist
  UI/win-dll-blocklist.c
Labels: Bug Fix

#8475 obs-outputs: Disable Windows-only options on non-Windows
  UI/window-basic-main-outputs.cpp
  plugins/obs-outputs/rtmp-stream.c
Labels: Bug Fix, macOS, Linux

#8477 UI: Properly update filter properties after resetting
  UI/properties-view.hpp
  UI/window-basic-filters.cpp
Labels: Bug Fix

#8483 deps/file-updater: Use LOG_INFO log priority for info logging
  deps/file-updater/file-updater/file-updater.c
Labels: Bug Fix

#8484 UI: Fix macOS crash when saving general settings without Sparkle
  UI/window-basic-settings.cpp
Labels: Bug Fix

#8486 test: Fix unused-parameter warnings in test-input
  test/test-input/sync-pair-vid.c
Labels: Bug Fix

#8364 Explicitly close RTMP socket on send error
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix, Seeking Testers

#6037 linux-v4l2: Fix fallback framerate for camera
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix, Linux

#8387 libobs: Fix Pulseaudio audio monitoring listing sources
  libobs/audio-monitoring/pulse/pulseaudio-enum-devices.c
  libobs/audio-monitoring/pulse/pulseaudio-output.c
  libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
  libobs/audio-monitoring/pulse/pulseaudio-wrapper.h
Labels: Bug Fix, Seeking Testers

#8411 UI: Fix media controls shortcuts being global
  UI/forms/source-toolbar/media-controls.ui
  UI/media-controls.cpp
Labels: Bug Fix

#8445 UI: Fix Dark and System themes select list height
  UI/data/themes/Dark.qss
  UI/data/themes/System.qss
Labels: Bug Fix, UI/UX

#8175 libobs: Reduce synchronization limit for multiple audio tracks
  libobs/obs-output.c
Labels: Bug Fix

#8229 Hashtable Adventures
  .clang-format
  UI/window-basic-main.cpp
  deps/CMakeLists.txt
  deps/uthash/.clang-format
  deps/uthash/CMakeLists.txt
  deps/uthash/uthash/LICENSE
  deps/uthash/uthash/uthash.h
  docs/sphinx/reference-core.rst
  libobs/CMakeLists.txt
  libobs/obs-data.c
  libobs/obs-hotkey-name-map.c
  libobs/obs-hotkey.c
  libobs/obs-internal.h
  libobs/obs-properties.c
  libobs/obs-scene.c
  libobs/obs-source.c
  libobs/obs-video.c
  libobs/obs.c
  libobs/obs.h
  libobs/util/config-file.c
  libobs/util/text-lookup.c
  libobs/util/text-lookup.h
  libobs/util/uthash.h
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Code Cleanup, Seeking Testers

#8491 win-capture: Fix compatibility info showing in any mode
  plugins/win-capture/game-capture.c
Labels: Bug Fix, Windows

#8095 RFC 45-6: Enable more connection info in Services API
  UI/audio-encoders.cpp
  UI/audio-encoders.hpp
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/ui-validation.cpp
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
  docs/sphinx/reference-outputs.rst
  docs/sphinx/reference-services.rst
  libobs/obs-internal.h
  libobs/obs-module.c
  libobs/obs-output.c
  libobs/obs-output.h
  libobs/obs-service.c
  libobs/obs-service.h
  libobs/obs.c
  libobs/obs.h
  plugins/coreaudio-encoder/data/locale/en-US.ini
  plugins/coreaudio-encoder/encoder.cpp
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-hls-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.h
  plugins/obs-libfdk/data/locale/en-US.ini
  plugins/obs-libfdk/obs-libfdk.c
  plugins/obs-outputs/ftl-stream.c
  plugins/obs-outputs/rtmp-stream.c
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/schema/service-schema-v4.json
  plugins/rtmp-services/data/services.json
  plugins/rtmp-services/rtmp-common.c
  plugins/rtmp-services/rtmp-custom.c
Labels: Enhancement, Seeking Testers

#8494 Fix audio codec settings change from RFC 45
  UI/window-basic-main.cpp
Labels: Bug Fix

#7601 libobs: Enable fast clear on Windows always
  libobs/obs-display.c
  libobs/obs-internal.h
Labels: Enhancement, Seeking Testers

#7814 decklink: Move preview output rescaling to GPU
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
  docs/sphinx/reference-outputs.rst
  libobs/obs-output.c
  libobs/obs.h
  plugins/decklink/decklink-output.cpp
Labels: Enhancement

#7978 libobs-d3d11,win-capture: Add Force SDR for DXGI duplicator
  libobs-d3d11/d3d11-duplicator.cpp
  libobs-d3d11/d3d11-subsystem.cpp
  libobs-d3d11/d3d11-subsystem.hpp
  libobs/graphics/graphics-imports.c
  libobs/graphics/graphics-internal.h
  libobs/graphics/graphics.c
  libobs/graphics/graphics.h
  plugins/win-capture/duplicator-monitor-capture.c
  plugins/win-capture/window-capture.c
Labels: Enhancement, Windows

#8503 CI: Update deps to 2023-03-20 release
  .github/workflows/main.yml
Labels: Bug Fix, Enhancement, Seeking Testers

#8500 UI: Fix inconsistencies in FindProtocol
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#8082 UI: Add space for right arrow in menu
  UI/data/themes/Acri.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/Yami.qss
Labels: Bug Fix

#8018 UI: Separate translation of filename format tooltip
  UI/data/locale/en-US.ini
  UI/window-basic-settings.cpp
Labels: Enhancement

#8499 UI: Fix simple fallback audio codec name
  UI/data/locale/en-US.ini
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
Labels: Bug Fix

#6758 obs-ffmpeg: Add HDR and HEVC to VA-API encoder
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
  plugins/obs-ffmpeg/vaapi-utils.c
  plugins/obs-ffmpeg/vaapi-utils.h
Labels: Enhancement

#8504 graphics-hook: Handle VK_KHR_imageless_framebuffer
  plugins/win-capture/graphics-hook-ver.h
  plugins/win-capture/graphics-hook/vulkan-capture.c
  plugins/win-capture/graphics-hook/vulkan-capture.h
Labels: Bug Fix

#8524 rtmp-services: Fix supported audio codecs in rtmp_common
  plugins/rtmp-services/rtmp-common.c
Labels: Bug Fix

#8519 UI: Remove outdated NSIS data
  UI/installer/OBSBanner.bmp
  UI/installer/OBSHeader.bmp
  UI/installer/mp-installer.nsi
Labels: Code Cleanup

#8523 libobs: Keep output as premultiplied alpha
  libobs/obs-video.c
Labels: Enhancement, Code Cleanup

#8526 UI: Fix issue from stream settings Qt slots refactor
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#8497 UI: Add unassigned indicator and warning to mixer
  UI/data/locale/en-US.ini
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Dark/unassigned.svg
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/mute-checkbox.hpp
  UI/volume-control.cpp
  UI/volume-control.hpp
Labels: Enhancement, UI/UX

#8506 Properly handle SIGINT on non-Windows platforms
  UI/obs-app.cpp
  UI/obs-app.hpp
Labels: Bug Fix, Seeking Testers

#8520 obs-scripting: Enable Python 3.11
  deps/obs-scripting/obs-scripting-python-import.c
Labels: Bug Fix, Enhancement, Seeking Testers

#8516 UI: Set fragmented MP4/MOV as default for pre-release versions
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
Labels: Enhancement

#8357 UI, libobs: Fix not handled in switch warnings
  UI/qt-wrappers.cpp
  libobs/obs-nix.c
  plugins/linux-v4l2/v4l2-decoder.c
Labels: Code Cleanup

#8289 libobs,obs-ffmpeg: Add option for recording lossless audio
  libobs/media-io/audio-io.c
  libobs/media-io/audio-io.h
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Seeking Testers, New Feature

#8277 UI: Fix transform dialog not being closable
  UI/forms/OBSBasicTransform.ui
  UI/window-basic-transform.cpp
Labels: Bug Fix

#8389 libobs: Copy private scene item data when duplicating scenes
  libobs/obs-scene.c
Labels: Bug Fix

#8530 UI: Switch format tooltip based on user selection
  UI/data/locale/en-US.ini
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Enhancement, UI/UX

#8474 Use more actionable error messages for hardware encoders
  plugins/obs-ffmpeg/data/locale/en-US.ini
Labels: Enhancement

#8531 UI: Remove unused variable
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix, Code Cleanup

#8532 UI: Switch RecFormat to RecFormat2
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#8535 libobs: Fix VIDEO_FORMAT_V210 shader for GLSL
  libobs/data/format_conversion.effect
Labels: Bug Fix, macOS, Linux

#8536 libobs: Add missing VIDEO_FORMAT_V210 handling in switch statements
  libobs/media-io/video-frame.c
  libobs/obs-video.c
Labels: Code Cleanup

#8534 UI: Ignore the leap seconds in tooltip of time format
  UI/data/locale/en-US.ini
Labels: Bug Fix

#8522 Enable AV1, HEVC via RTMP to YouTube
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
  libobs/obs-defs.h
  libobs/obs-hevc.c
  libobs/obs-hevc.h
  plugins/obs-outputs/CMakeLists.txt
  plugins/obs-outputs/flv-mux.c
  plugins/obs-outputs/flv-mux.h
  plugins/obs-outputs/rtmp-av1.c
  plugins/obs-outputs/rtmp-av1.h
  plugins/obs-outputs/rtmp-hevc.c
  plugins/obs-outputs/rtmp-hevc.h
  plugins/obs-outputs/rtmp-stream.c
  plugins/obs-outputs/rtmp-stream.h
  plugins/obs-outputs/utils.h
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/schema/service-schema-v4.json
  plugins/rtmp-services/data/services.json
Labels: New Feature

#8458 flatpak: Enable obs-libfdk
  CI/flatpak/com.obsproject.Studio.json
Labels: Seeking Testers, Linux

#8541 CI: Prevent build artifact creation for macOS without pushed tag
  .github/workflows/main.yml
Labels: Bug Fix, CI

#8540 obs-outputs: Fix compilation without ENABLE_HEVC
  plugins/obs-outputs/flv-mux.c
Labels: Bug Fix

#8492 CI: Only generate and use master branch Flatpak caches
  .github/workflows/flatpak.yml
  .github/workflows/main.yml
Labels: CI

#8479 flatpak: Update deps based on on obs-deps 2023-03-26
  CI/flatpak/com.obsproject.Studio.json
Labels: CI

#8542 CI: Update deps to 2023-03-26 release
  .github/workflows/main.yml
  buildspec.json
Labels: Bug Fix, Enhancement, CI

#8380 libobs/media-io: Use inputs_mutex during close
  libobs/media-io/video-io.c
Labels: Bug Fix

#8544 cmake: Fix OBS_INSTALL_PREFIX
  UI/cmake/os-freebsd.cmake
  UI/cmake/os-linux.cmake
  libobs/cmake/legacy.cmake
Labels: Bug Fix

#8545 cmake: Fix obs-frontend-apiConfig.cmake included from 3rd party plugin
  UI/obs-frontend-api/cmake/obs-frontend-apiConfig.cmake.in
Labels: Bug Fix

#8543 libobs: Log when libobs data file is not found
  libobs/obs.c
Labels: Enhancement

#8547 cmake: Ignore all Qt darwin permission plugins
  cmake/common/helpers_common.cmake
Labels: Bug Fix

#8555 UI: Add missing compile definitions for service integrations
  UI/cmake/legacy.cmake
Labels: Bug Fix

#8567 updater: Add workaround for broken CLI arguments
  UI/win-update/updater/updater.cpp
Labels: Bug Fix

#8566 UI: Fix updater parameters missing a space
  UI/update/win-update.cpp
Labels: Bug Fix

#8569 win-capture: Fix compat info showing in hotkey mode
  plugins/win-capture/game-capture.c
Labels: Bug Fix

#8579 deps: Fix lower CMake version boundary for file-updater
  deps/file-updater/CMakeLists.txt
Labels: Bug Fix, Linux

#8557 UI: Improve AV1 fallbacks while changing services
  UI/window-basic-settings-stream.cpp
Labels: Enhancement

#8571 UI: Only adjust size of properties on first draw
  UI/properties-view.cpp
Labels: Bug Fix

#8572 UI: Remux mp4/mov to mp4/mov with suffix
  UI/window-remux.cpp
Labels: Enhancement

#8573 UI: Auto-Remux fragmented containers to regular counterparts
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main.cpp
Labels: Bug Fix

#8599 CI: Fix GitHub labels check
  .github/workflows/main.yml
Labels: Bug Fix, Seeking Testers, CI

#8588 CI: Update service check PR job to remove set-output
  .github/workflows/services-json.yml
Labels: Bug Fix, CI

#8564 UI: Update Windows DLL blocklist
  UI/win-dll-blocklist.c
Labels: Enhancement, Seeking Testers, Windows

#8585 UI: Add AMD AV1 encoder to simple output mode
  UI/window-basic-settings-stream.cpp
Labels: Bug Fix

#8598 obs-ffmpeg: Fix memory corruption during cleanup
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix

#8601 CI: Update deps to 2023-03-30 release
  .github/workflows/main.yml
  CI/flatpak/com.obsproject.Studio.json
  buildspec.json
Labels: Bug Fix, Seeking Testers, CI
