Repository obsproject/obs-studio, pull requests merged in 2023-10, with the labels that each got.

#9647 obs-qsv11: Use translatable strings for target usage
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/data/locale/en-US.ini
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement, Code Cleanup

#9662 UI: Use C++11 ranged-for instead of Q_FOREACH
  UI/window-basic-main.cpp
Labels: Code Cleanup

#9663 UI: Use std::shared_ptr instead of QSharedPointer
  UI/volume-control.cpp
  UI/volume-control.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-extra-browsers.cpp
Labels: Enhancement, Code Cleanup

#9648 libobs,obs-filters: Fix NAN when tonemapping
  libobs/data/color.effect
  plugins/obs-filters/data/color.effect
Labels: Bug Fix

#9668 obs-ffmpeg: Readd OBS_ENCODER_CAP_DYN_BITRATE to AMF texture encoders
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix, Seeking Testers

#9649 libobs: Fix errors for gs_effect_create
  libobs/graphics/effect-parser.c
Labels: Bug Fix

#9654 rtmp-services: Update OnlyFans streaming service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#9657 linux-v4l2: Expand packed values to 4 bytes
  plugins/linux-v4l2/v4l2-helpers.c
  plugins/linux-v4l2/v4l2-helpers.h
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix

#9646 UI: Fix YouTubeAppDock causing hidden browser docks to automatically play audio on macOS
  UI/window-dock-youtube-app.cpp
Labels: Bug Fix, macOS

#9643 libobs: Fix hotkeys with groups and duplicate sceneitems
  libobs/obs-scene.c
Labels: Bug Fix, Seeking Testers

#9672 win-wasapi: Use provided timestamp for process capture and handle flags
  plugins/win-wasapi/win-wasapi.cpp
Labels: Bug Fix, Seeking Testers, Windows

#9676 win-wasapi: Remove 'BETA' from Application Audio Capture name
  plugins/win-wasapi/data/locale/en-US.ini
Labels: Windows

#9674 UI: Enable "Paste Filters" after copying from scenes or mixer
  UI/window-basic-main.cpp
Labels: Bug Fix

#9683 CI: Update deps to 2023-10-09 release
  buildspec.json
Labels: Bug Fix

#9686 cmake: Use dependency hashes to track revisions
  cmake/common/buildspec_common.cmake
Labels: Enhancement

#9684 CI: Update CEF builds
  buildspec.json
Labels: Bug Fix, Seeking Testers

#9685 build-aux: Update Flatpak CEF build
  build-aux/modules/99-cef.json
Labels: Bug Fix

#9638 mac-virtualcam: Always replace camera extension; Treat extension installation cancellation as error
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, macOS

#9675 mac-virtualcam: Check result of finished extension installation
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Enhancement, macOS

#9688 CI: Fix Steam upload (again)
  .github/actions/steam-upload/action.yaml
Labels: CI

#9690 UI: Fix compile error due to use of strlen in constexpr
  UI/update/win-update.cpp
Labels: Bug Fix

#9696 build-aux: Update Flatpak CEF build
  build-aux/modules/99-cef.json
Labels: Bug Fix

#9706 libobs: Fix rendering stats not being logged on output stop
  libobs/obs-output.c
Labels: Bug Fix, Seeking Testers

#9620 linux-v4l2: add support for linear alpha blending
  plugins/linux-v4l2/v4l2-input.c
Labels: Linux, New Feature

#9713 frontend-tools: Remove unused startAtLaunch variable
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.hpp
Labels: Code Cleanup

#9555 libobs-d3d11: Log VRAM in GiB
  libobs-d3d11/d3d11-subsystem.cpp
Labels: Enhancement, Windows

#9102 obs-scripting: Search native libraries in Lua script's location
  deps/obs-scripting/obs-scripting-lua.c
Labels: Enhancement

#9721 UI: Add missing NULL check for skipUpdateVer
  UI/update/win-update.cpp
Labels: Bug Fix, Windows

#9698 cmake: Explicitly fail if macOS SDK is too old
  cmake/macos/compilerconfig.cmake
Labels: Enhancement, macOS

#9724 obs-qsv11: Log more QSV settings
  plugins/obs-qsv11/obs-qsv11.c
Labels: Enhancement

#9746 linux-pipewire: Add locks to unsafe pipewire functions
  plugins/linux-pipewire/pipewire.c
Labels: Linux

#9743 linux-pipewire: Use the format properties for swap r/b
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#9745 linux-pipewire: Load glad symbols on start
  plugins/linux-pipewire/linux-pipewire.c
Labels: Bug Fix, Linux

#9712 decklink-output-ui: Decouple DeckLink output state
  UI/frontend-plugins/decklink-output-ui/decklink-ui-main.cpp
Labels: Bug Fix, Seeking Testers

#9726 UI: Remove iCCP data from PNGs
  UI/forms/images/active.png
  UI/forms/images/paused.png
Labels: Bug Fix

#9763 CI: Update deps to 2023-10-26 release
  buildspec.json
Labels: Bug Fix, Windows

#9762 libobs: Export SIMDe headers unconditionally for plugin development
  libobs/CMakeLists.txt
Labels: Bug Fix

#9768 mac-virtualcam: Correct device timer firing rate
  plugins/mac-virtualcam/src/camera-extension/OBSCameraDeviceSource.swift
Labels: Bug Fix

#9730 UI: Fix AMF AV1 simple recording presets
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#9747 win-wasapi: Log source name on initialization
  plugins/win-wasapi/win-wasapi.cpp
Labels: Enhancement, Windows

#9742 plugins: Remove old macOS version ifdefs
  plugins/mac-avcapture/av-capture.mm
  plugins/mac-capture/mac-sck-common.h
  plugins/mac-capture/mac-sck-common.m
  plugins/mac-capture/mac-sck-video-capture.m
  plugins/mac-capture/plugin-main.c
  plugins/mac-videotoolbox/encoder.c
Labels: Code Cleanup, macOS

#9584 UI: Replace SourceTreeSubItemCheckBox class with Qt property
  UI/data/themes/Acri.qss
  UI/data/themes/Dark.qss
  UI/data/themes/Grey.qss
  UI/data/themes/Light.qss
  UI/data/themes/Rachni.qss
  UI/data/themes/System.qss
  UI/data/themes/Yami.qss
  UI/source-tree.cpp
  UI/source-tree.hpp
Labels: Code Cleanup, UI/UX

#9767 obs-qsv11: Migrate target usage settings
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix

#9774 linux-pipwire: Pass obs_pw_stream to renegitation callback
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#9735 obs-ffmpeg: Add B-Frames option for VA-API
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-ffmpeg/vaapi-utils.c
  plugins/obs-ffmpeg/vaapi-utils.h
Labels: Enhancement, Linux, New Feature

#9758 obs-webrtc: Allow non-CBR rate control with WHIP
  plugins/obs-webrtc/whip-service.cpp
Labels: Enhancement

#9773 docs: Fix obs_sceneitem_get_group signature
  docs/sphinx/reference-scenes.rst
Labels: Documentation
