Repository obsproject/obs-studio, pull requests merged in 2024-11, with the labels that each got.

#11393 UI/themes: Fix control button pressed color in rachni theme
  UI/data/themes/Yami_Rachni.ovt
Labels: Bug Fix, UI/UX

#11480 UI: Create YouTube Dock when switching profile
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix

#11467 obs-filters: Move nvafx migration to queued task
  plugins/obs-filters/noise-suppress-filter.c
Labels: Bug Fix

#11473 obs-qsv11: Remove old MSDK 1.6 code
  plugins/obs-qsv11/obs-qsv11.c
Labels: Code Cleanup

#11474 obs-qsv11: Remove old DX9 code and DX11 checks
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-qsv11/common_utils_windows.cpp
Labels: Code Cleanup

#11477 mac-capture: Don't read channels for disconnected audio device
  plugins/mac-capture/mac-audio.c
Labels: Bug Fix, macOS

#11501 cmake: Fix build directory exclusion
  cmake/linux/cpackconfig.cmake
Labels: Bug Fix, Linux

#11375 win-capture: Avoid NULL deref when capture not initialized
  plugins/win-capture/graphics-hook/d3d10-capture.cpp
  plugins/win-capture/graphics-hook/d3d11-capture.cpp
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
  shared/obs-hook-config/graphics-hook-ver.h
Labels: Bug Fix

#11525 UI: Fix handling of Amazon IVS auto URLs when using multitrack video output
  UI/multitrack-video-output.cpp
  UI/multitrack-video-output.hpp
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#11532 UI: Fix autoconfig saving signed stream key
  UI/window-basic-auto-config.cpp
Labels: Bug Fix

#11534 UI: Fix falling back to non-multitrack output after error
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#11503 frontend-tools: Correctly pass settings to modified cb on reload
  UI/frontend-plugins/frontend-tools/scripts.cpp
Labels: Bug Fix

#11468 UI: Fix broken module paths provided via environment on macOS
  UI/window-basic-main.cpp
Labels: Bug Fix, macOS

#11510 obs-ffmpeg: Avoid setting negative bitrate for lossless audio codec
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
Labels: Bug Fix

#11553 UI: Fix missing unassigned icon in System theme
  UI/forms/images/unassigned.svg
  UI/forms/obs.qrc
Labels: Bug Fix, UI/UX

#11543 cmake: Fix build directory exclusion for real
  cmake/linux/cpackconfig.cmake
Labels: Bug Fix, CI
