Repository obsproject/obs-studio, pull requests merged in 2024-12, with the labels that each got.

#11566 UI: Fix collision of existing backup files for new scene collections
  UI/window-basic-main-scene-collections.cpp
Labels: Bug Fix

#11574 libobs: Fix scale calculation when applying new group transform
  libobs/obs-scene.c
Labels: Bug Fix

#11585 libobs: Remove relative scene item APIs
  docs/sphinx/reference-scenes.rst
  libobs/obs-scene.c
  libobs/obs.h
Labels: Code Cleanup

#11594 win-capture: Add Marvel Rivals to compatibility list
  plugins/win-capture/data/compatibility.json
  plugins/win-capture/data/package.json
Labels: Enhancement

#11601 win-capture: Add The Bazaar to compatibility list
  plugins/win-capture/data/compatibility.json
  plugins/win-capture/data/package.json
Labels: Enhancement

#11603 libobs/util: Improve inhibit portal detection on Linux
  libobs/util/platform-nix-portal.c
Labels: Bug Fix, Enhancement, Linux

#11614 obs-filters: Maintain order of migrated NVAFX filters
  plugins/obs-filters/noise-suppress-filter.c
Labels: Bug Fix

#11592 CI: Disable Flatpak bundling on publish
  .github/workflows/publish.yaml
Labels: Bug Fix

#11618 libobs-opengl: Avoid trying to allocate 0 byte on Linux
  libobs-opengl/gl-egl-common.c
Labels: Bug Fix, Linux
