Repository obsproject/obs-studio, pull requests merged in 2024-07, with the labels that each got.

#10941 libobs: Fix plane heights for odd values
  libobs/media-io/video-frame.c
Labels: Bug Fix

#10943 obs-ffmpeg: Honor preferred format in native NVENC
  plugins/obs-ffmpeg/obs-nvenc.c
Labels: Bug Fix, Seeking Testers, Windows, Linux

#10898 win-wasapi: Remove noisy and useless debug logging
  plugins/win-wasapi/win-wasapi.cpp
Labels: Code Cleanup, Windows

#10954 CI: Fix flatpak-builder-lint action
  .github/actions/flatpak-builder-lint/action.yaml
Labels: Bug Fix, CI

#10957 UI: Remove `QFuture` usage
  UI/CMakeLists.txt
  UI/goliveapi-network.hpp
  UI/multitrack-video-output.cpp
  UI/multitrack-video-output.hpp
  UI/qt-helpers.cpp
  UI/qt-helpers.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#10963 UI: Add field growth policy to form layouts
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix

#10967 UI: Fix `qt-helpers.{c,h}pp` not being removed from legacy.cmake
  UI/cmake/legacy.cmake
Labels: Bug Fix

#10674 libobs: Fix crash when mix is NULL
  libobs/obs.c
Labels: Bug Fix

#10975 UI: Fix source tree icon spacing
  UI/data/themes/Yami.obt
  UI/source-tree.cpp
Labels: Bug Fix, UI/UX

#10989 UI: Fix read-only QTextEdit background color
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Classic.ovt
Labels: Bug Fix, UI/UX

#10990 UI: Adjust sizing of Classic audio meter elements
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Classic.ovt
Labels: Bug Fix, Enhancement, UI/UX

#10993 libobs/graphics: Prevent heap overflow in libnsgif
  libobs/graphics/libnsgif/libnsgif.c
Labels: Bug Fix

#11010 UI: Fix cast of pointer type at invalid current scene setting on load
  UI/window-basic-main.cpp
Labels: Bug Fix

#10999 obs-outputs: Set FLV DTS offset based on first audio or video packet
  plugins/obs-outputs/flv-output.c
  plugins/obs-outputs/rtmp-stream.c
  plugins/obs-outputs/rtmp-stream.h
Labels: Bug Fix

#11002 libobs-opengl: Disable NV12/P010 on Windows
  libobs-opengl/gl-subsystem.c
Labels: Bug Fix

#11027 win-capture: Add Zenless Zone Zero to compatibility list
  plugins/win-capture/data/compatibility.json
  plugins/win-capture/data/package.json
Labels: Enhancement

#10521 UI: Remove legacy migrations
  UI/obs-app.cpp
  UI/window-basic-main.cpp
Labels: Code Cleanup

#10163 aja: Add v210 pixel format support to capture plugin
  plugins/aja/aja-common.cpp
  plugins/aja/aja-common.hpp
  plugins/aja/aja-output.cpp
  plugins/aja/aja-source.cpp
  plugins/aja/aja-vpid-data.cpp
  plugins/aja/aja-vpid-data.hpp
Labels: Enhancement, New Feature

#10839 UI: Return std::optional from ParseThemeMeta
  UI/obs-app-theming.cpp
Labels: Bug Fix, Code Cleanup

#10877 frontend-tools: Avoid initializing the scene switcher on Wayland
  UI/frontend-plugins/frontend-tools/auto-scene-switcher.cpp
Labels: Bug Fix, Linux

#10982 cmake: Set CFBundleDisplayName for camera extension
  plugins/mac-virtualcam/src/camera-extension/CMakeLists.txt
Labels: Bug Fix, Enhancement, macOS

#11046 rtmp-services: Update MasterStream.iR ingest
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#11006 mac-virtualcam: Update NotInstalled error text for macOS 15
  plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix
