Repository obsproject/obs-studio, pull requests merged in 2024-10, with the labels that each got.

#11322 UI: Fix What's New increment settings mismatch
  UI/window-basic-main.cpp
Labels: Bug Fix

#11296 libobs: Do not attempt to reconnect if stop event is set
  libobs/obs-output.c
Labels: Bug Fix

#11325 libobs: Remove unused is_in_bundle() method
  libobs/obs-cocoa.m
Labels: Code Cleanup

#11333 plugins/test: Remove legacy CMake remnants
  plugins/obs-ffmpeg/ffmpeg-mux/cmake/legacy.cmake
  plugins/obs-ffmpeg/obs-amf-test/cmake/legacy.cmake
  plugins/obs-qsv11/obs-qsv-test/cmake/legacy.cmake
  test/test-input/cmake/legacy.cmake
Labels: Code Cleanup

#11324 libobs: Assure large enough buffer in dstr_from_cfstring
  libobs/obs-cocoa.m
Labels: Bug Fix

#11226 UI: Replace themeID and style hints with class property
  UI/adv-audio-control.cpp
  UI/data/themes/System.obt
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Acri.ovt
  UI/data/themes/Yami_Light.ovt
  UI/forms/AutoConfigVideoPage.ui
  UI/forms/OBSAbout.ui
  UI/forms/OBSBasic.ui
  UI/forms/OBSBasicControls.ui
  UI/forms/OBSBasicFilters.ui
  UI/forms/OBSBasicSettings.ui
  UI/forms/OBSBasicVCamConfig.ui
  UI/forms/source-toolbar/browser-source-toolbar.ui
  UI/forms/source-toolbar/media-controls.ui
  UI/frontend-plugins/frontend-tools/forms/auto-scene-switcher.ui
  UI/frontend-plugins/frontend-tools/forms/scripts.ui
  UI/hotkey-edit.cpp
  UI/media-controls.cpp
  UI/mute-checkbox.hpp
  UI/scene-tree.cpp
  UI/source-tree.cpp
  UI/visibility-item-widget.cpp
  UI/volume-control.cpp
  UI/window-basic-about.cpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-stats.cpp
  UI/window-extra-browsers.cpp
  UI/window-youtube-actions.cpp
  shared/properties-view/properties-view.cpp
  shared/qt/icon-label/icon-label.hpp
  shared/qt/wrappers/qt-wrappers.cpp
  shared/qt/wrappers/qt-wrappers.hpp
Labels: Enhancement, Code Cleanup

#11291 shared/bpm: Fixed crash when using Stream Delay
  shared/bpm/bpm-internal.h
  shared/bpm/bpm.c
Labels: Bug Fix

#10751 libobs/util: Improve inhibit functions on Linux
  libobs/util/platform-nix.c
Labels: Enhancement, Seeking Testers, Linux

#11345 cmake: Use fixed SOVERSION everywhere
  cmake/linux/helpers.cmake
Labels: Bug Fix, Linux

#11277 linux-pipewire: Avoid trying to allocate 0 byte
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Enhancement, Linux

#11181 libobs/util: Crash on bmalloc(0)
  libobs/util/bmem.c
Labels: Enhancement

#11350 UI: Fix settings mismatch
  UI/obs-app.cpp
  UI/window-basic-interaction.cpp
  UI/window-basic-main.cpp
  UI/window-basic-settings.cpp
Labels: Bug Fix

#11353 obs-nvenc: Add missing locale text
  plugins/obs-nvenc/data/locale/en-US.ini
Labels: Bug Fix

#11355 win-update: Remove legacy CMake file
  UI/win-update/updater/cmake/legacy.cmake
Labels: Code Cleanup

#10597 obs-ffmpeg: Fix deadlock on shutting down muxer
  plugins/obs-ffmpeg/ffmpeg-mux/ffmpeg-mux.c
Labels: Bug Fix, Seeking Testers

#11365 UI: Explicitly convert profile config path via u8path
  UI/window-basic-main-profiles.cpp
Labels: Bug Fix

#11369 shared/opts-parser: Fix crash when no options were given to the parser
  shared/opts-parser/opts-parser.c
Labels: Bug Fix

#11373 CI: Fix rclone env var formatting in Windows Patches action
  .github/actions/windows-patches/action.yaml
Labels: Bug Fix, CI

#11376 UI/themes: Fix selectors in Yami Light
  UI/data/themes/Yami_Light.ovt
Labels: Bug Fix

#11374 libobs: Add source profiler to public headers
  libobs/CMakeLists.txt
Labels: Bug Fix

#11377 UI/themes: Consistently select indicator-mute instead of MuteCheckBox
  UI/data/themes/System.obt
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Acri.ovt
  UI/data/themes/Yami_Classic.ovt
  UI/data/themes/Yami_Light.ovt
  UI/data/themes/Yami_Rachni.ovt
Labels: Bug Fix

#11384 UI: Set minimum version for nlohmann_json to 3.11
  UI/cmake/feature-macos-update.cmake
  UI/cmake/feature-whatsnew.cmake
  UI/cmake/os-windows.cmake
  UI/win-update/updater/CMakeLists.txt
Labels: Enhancement, Code Cleanup

#11391 UI: Fix initialization bug when launching without existing profile
  UI/window-basic-main.cpp
Labels: Bug Fix

#11386 obs-qsv11: Update minimum VPL version to 2.9
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt
Labels: Code Cleanup

#11399 obs-outputs: Add cast to fix build with Clang 19
  plugins/obs-outputs/flv-mux.c
Labels: Enhancement

#11390 libobs: Fix scaling and positioning issues with groups in relative mode
  libobs/obs-scene.c
Labels: Bug Fix

#11415 UI: Update order of profiles and scene collections in their menus
  UI/window-basic-main-profiles.cpp
  UI/window-basic-main-scene-collections.cpp
Labels: Bug Fix, Enhancement

#11418 obs-nvenc: Force at least 4 b-frames when using UHQ tune
  plugins/obs-nvenc/nvenc.c
Labels: Bug Fix

#11424 build-aux: Remove CEF stripping workaround
  build-aux/com.obsproject.Studio.json
Labels: Linux

#11438 UI: Log Twitch 403 error bodies
  UI/auth-twitch.cpp
Labels: Bug Fix

#11445 cmake: Fix target_add_resource ARGN support on Linux
  cmake/linux/helpers.cmake
Labels: Bug Fix, Linux

#11422 UI: Split out Whats New dialog to fix shutdown crash on Linux
  UI/cmake/ui-windows.cmake
  UI/window-basic-main.cpp
  UI/window-whats-new.cpp
  UI/window-whats-new.hpp
Labels: Bug Fix, Enhancement

#11437 cmake/plugins: Enable -Wswitch on GCC
  cmake/linux/compilerconfig.cmake
  plugins/obs-nvenc/nvenc-helpers.c
  plugins/obs-qsv11/CMakeLists.txt
Labels: Enhancement

#11410 cmake: Install desktop files and icons on FreeBSD
  UI/cmake/os-freebsd.cmake
Labels: Bug Fix, Enhancement, Other OS (*nix)

#11406 linux-pipewire: Fix memory leaks
  plugins/linux-pipewire/camera-portal.c
  plugins/linux-pipewire/pipewire.c
Labels: Bug Fix, Linux

#11450 UI: Restore frontend API events being dispatched during initialization
  UI/window-basic-main.cpp
Labels: Bug Fix

#11411 UI: Add TikTok Live Studio Virtual Camera to DLL blocklist
  UI/win-dll-blocklist.c
Labels: Bug Fix, Windows

#11412 UI/importers: Translate capture sources depending on display server
  UI/importers/studio.cpp
Labels: Bug Fix, Enhancement, Linux

#11439 librtmp: Use /etc/ssl/certs/ path on FreeBSD
  plugins/obs-outputs/librtmp/rtmp.c
Labels: Bug Fix, Other OS (*nix)

#11448 UI: Open active profile directory via File menu
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#11430 graphics-hook: Fix null pointer dereference
  plugins/win-capture/graphics-hook/d3d10-capture.cpp
  plugins/win-capture/graphics-hook/d3d11-capture.cpp
  plugins/win-capture/graphics-hook/d3d12-capture.cpp
  plugins/win-capture/graphics-hook/d3d9-capture.cpp
  shared/obs-hook-config/graphics-hook-ver.h
Labels: Bug Fix, Windows
