Repository obsproject/obs-studio, pull requests merged in 2024-02, with the labels that each got.

#10176 CI: Update Google Cloud GitHub Actions
  .github/actions/bouf/action.yaml
  .github/workflows/push.yaml
Labels: Code Cleanup, CI

#10183 UI: Update exportOptions template for macOS release code signing
  UI/cmake/macos/exportOptions-extension.plist.in
  UI/cmake/macos/exportOptions.plist.in
Labels: Bug Fix, CI

#10166 deps/obs-scripting: Fix lua tick crash
  deps/obs-scripting/obs-scripting-lua.c
Labels: Bug Fix

#10169 UI: Use signal vectors for transform & source tree
  UI/source-tree.cpp
  UI/source-tree.hpp
  UI/window-basic-transform.cpp
  UI/window-basic-transform.hpp
Labels: Code Cleanup

#10177 libobs-opengl: Specify display attributes
  libobs-opengl/gl-wayland-egl.c
  libobs-opengl/gl-x11-egl.c
Labels: Bug Fix

#10184 obs-ffmpeg: Fix wrong framerate in VUI header
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix

#10187 libobs: Fix free disk space calculation on macOS
  libobs/util/platform-cocoa.m
Labels: Bug Fix, macOS

#10189 image-source: Fix crash when randomize with 0 files
  plugins/image-source/obs-slideshow-mk2.c
Labels: Bug Fix

#10197 CI: Switch to macOS 14 runners and Xcode 15.2
  .github/workflows/build-project.yaml
  .github/workflows/check-format.yaml
  .github/workflows/dispatch.yaml
  .github/workflows/publish.yaml
  .github/workflows/push.yaml
  .github/workflows/scheduled.yaml
Labels: Enhancement, macOS, CI

#10199 UI: Fix RTMP check in Advanced output
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix, Seeking Testers

#10203 win-dshow: Fix YUY2 line size error
  plugins/win-dshow/tiny-nv12-scale.c
Labels: Bug Fix

#10185 CI: Fix Steam workflow getting confused by PDBs
  .github/actions/steam-upload/action.yaml
Labels: CI

#10222 obs-qsv11: Disable texture encoder on linux
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix

#10229 win-dshow: Add generated Windows resource file to virtualcam sources
  plugins/win-dshow/virtualcam-module/CMakeLists.txt
Labels: Bug Fix, Windows

#10209 UI: Fix source remove log scene
  UI/source-tree.cpp
  UI/source-tree.hpp
Labels: Bug Fix

#10216 UI: Include audio devices in macOS microphone permissions prompt
  UI/data/locale/en-US.ini
Labels: Enhancement

#10233 build-aux: Update Flatpak audio plugins branch
  build-aux/com.obsproject.Studio.json
Labels: Bug Fix, Linux

#10243 win-capture: Fix leak in wasapi reroute proc call
  plugins/win-capture/audio-helpers.c
Labels: Bug Fix, Windows

#10259 win-capture: Disable audio source when game capture unhooks
  plugins/win-capture/game-capture.c
Labels: Bug Fix, Seeking Testers, Windows

#10255 mac-avcapture: Add color format selection for capture card source
  plugins/mac-avcapture/OBSAVCapture.m
  plugins/mac-avcapture/plugin-main.m
  plugins/mac-avcapture/plugin-properties.m
Labels: Bug Fix, Seeking Testers, macOS

#10253 mac-capture: Limit number of copied audio channels to libobs limits
  plugins/mac-capture/mac-audio.c
Labels: Bug Fix, macOS

#10254 mac-capture: Fix crash in device reconnect handler
  plugins/mac-capture/mac-audio.c
Labels: Bug Fix, macOS

#10223 UI: Fill audio meter background each update (#9842)
  UI/volume-control.cpp
Labels: Bug Fix

#10266 win-capture: Add line break for capture audio tooltip
  plugins/win-capture/data/locale/en-US.ini
Labels: Enhancement

#10267 mac-avcapture: Fix crash issues on Intel-based Macs and older macOS
  plugins/mac-avcapture/OBSAVCapture.h
  plugins/mac-avcapture/plugin-main.m
  plugins/mac-avcapture/plugin-properties.h
  plugins/mac-avcapture/plugin-properties.m
Labels: Bug Fix, macOS

#10268 UI: Fix problem with Yes/No message box buttons not translated
  UI/window-basic-main.cpp
Labels: Bug Fix

#10242 UI: Fix Remux window only being usable once
  UI/window-remux.cpp
Labels: Bug Fix

#10269 CI: Update deps to 2024-02-20 release
  buildspec.json
Labels: Bug Fix, Enhancement, Seeking Testers

#10290 CI: Fix scheduled language file check running on same commit hash
  .github/workflows/scheduled.yaml
Labels: Bug Fix, CI

#10296 CI: Fix broken pip install to use ephemeral virtual environment
  .github/actions/compatibility-validator/action.yaml
  .github/actions/services-validator/action.yaml
Labels: Bug Fix, CI

#10292 CI: Update deps to 2024-02-26 release
  buildspec.json
Labels: Bug Fix

#10285 UI: Fix context bar not updating on delete
  UI/source-tree.cpp
Labels: Bug Fix

#10294 UI: Fix a bug with Output Settings not updating & Toggle audio multi-tracks correctly
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Bug Fix, Seeking Testers
