Repository obsproject/obs-studio, pull requests merged in 2024-09, with the labels that each got.

#11212 libobs: Always set initial scene item pos to top-left corner
  libobs/obs-scene.c
Labels: Bug Fix

#11243 CI: Update deps to 2024-09-05 release
  buildspec.json
Labels: Enhancement, Seeking Testers

#11244 build-aux: Update Flatpak modules
  build-aux/modules/20-svt-av1.json
  build-aux/modules/30-ffmpeg.json
  build-aux/modules/40-luajit.json
  build-aux/modules/50-libqrcodegencpp.json
  build-aux/modules/90-asio.json
Labels: Enhancement, Seeking Testers, Linux

#11234 win-capture: Fix segfault when calling data.free()
  plugins/win-capture/graphics-hook/dxgi-capture.cpp
Labels: Bug Fix, Windows

#11220 cmake: Avoid breaking ABI through major version bump on Linux
  cmake/linux/helpers.cmake
Labels: Bug Fix, Linux

#10902 obs-qsv11: Fix CBR Spike
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
Labels: Bug Fix, Enhancement

#11180 UI: Fix multitrack video autoconfig option
  UI/window-basic-auto-config.cpp
Labels: Bug Fix, Seeking Testers

#11259 obs-nvenc: Support new error code for too many sessions
  plugins/obs-nvenc/nvenc-helpers.c
Labels: Bug Fix

#11260 obs-nvenc: Check if device index in settings object is actually set
  plugins/obs-nvenc/nvenc.c
Labels: Bug Fix

#11263 obs-nvenc: Fix reading uninitialized variable
  plugins/obs-nvenc/nvenc-helpers.c
Labels: Bug Fix

#11248 Remove legacy_check CMake macro
  UI/CMakeLists.txt
  UI/frontend-plugins/aja-output-ui/CMakeLists.txt
  UI/frontend-plugins/decklink-captions/CMakeLists.txt
  UI/frontend-plugins/decklink-output-ui/CMakeLists.txt
  UI/frontend-plugins/frontend-tools/CMakeLists.txt
  UI/obs-frontend-api/CMakeLists.txt
  UI/win-update/updater/CMakeLists.txt
  cmake/common/helpers_common.cmake
  cmake/windows/architecture.cmake
  deps/w32-pthreads/CMakeLists.txt
  libobs-opengl/CMakeLists.txt
  libobs-winrt/CMakeLists.txt
  libobs/CMakeLists.txt
  plugins/aja/CMakeLists.txt
  plugins/coreaudio-encoder/CMakeLists.txt
  plugins/decklink/CMakeLists.txt
  plugins/image-source/CMakeLists.txt
  plugins/linux-alsa/CMakeLists.txt
  plugins/linux-capture/CMakeLists.txt
  plugins/linux-jack/CMakeLists.txt
  plugins/linux-pipewire/CMakeLists.txt
  plugins/linux-pulseaudio/CMakeLists.txt
  plugins/linux-v4l2/CMakeLists.txt
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/ffmpeg-mux/CMakeLists.txt
  plugins/obs-ffmpeg/obs-amf-test/CMakeLists.txt
  plugins/obs-filters/CMakeLists.txt
  plugins/obs-libfdk/CMakeLists.txt
  plugins/obs-outputs/CMakeLists.txt
  plugins/obs-qsv11/CMakeLists.txt
  plugins/obs-qsv11/obs-qsv-test/CMakeLists.txt
  plugins/obs-transitions/CMakeLists.txt
  plugins/obs-vst/CMakeLists.txt
  plugins/obs-webrtc/CMakeLists.txt
  plugins/obs-x264/CMakeLists.txt
  plugins/oss-audio/CMakeLists.txt
  plugins/rtmp-services/CMakeLists.txt
  plugins/sndio/CMakeLists.txt
  plugins/text-freetype2/CMakeLists.txt
  plugins/vlc-video/CMakeLists.txt
  shared/obs-scripting/CMakeLists.txt
  shared/obs-scripting/obslua/CMakeLists.txt
  shared/obs-scripting/obspython/CMakeLists.txt
  test/test-input/CMakeLists.txt
Labels: Code Cleanup

#11103 obs-webrtc: Fix bug in whip-output.cpp to support stun or turn
  plugins/obs-webrtc/whip-output.cpp
Labels: Bug Fix

#11219 GS/GL Shenannigans (Prep for obs-browser hwaccel on Linux ?)
  libobs-opengl/gl-subsystem.c
Labels: Enhancement, macOS, Linux

#11124 libobs: Update macOS platform implementation
  libobs/obs-cocoa.m
Labels: Code Cleanup, Seeking Testers, macOS

#10092 mac-virtualcam: Compare camera UUIDs using CFUUID
  plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm
Labels: Bug Fix, macOS

#11060 obs-qsv11: Add AV1 Screen Content Coding
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/obs-qsv-test/obs-qsv-test.cpp
Labels: Enhancement

#9694 build-aux: Use fallback-x11 instead of x11
  build-aux/com.obsproject.Studio.json
Labels: Enhancement

#11056 cmake: Update use of MbedTLS to support versions 3.6.0 and beyond
  UI/cmake/feature-whatsnew.cmake
  UI/cmake/os-windows.cmake
  cmake/finders/FindMbedTLS.cmake
  plugins/obs-outputs/CMakeLists.txt
Labels: Bug Fix

#11283 CI: Use Windows 11 SDK 10.0.22621.0
  CMakePresets.json
Labels: Enhancement, Windows, CI

#11284 UI: Fix outdated scene collection and profile method names
  UI/api-interface.cpp
Labels: Bug Fix

#11265 libobs: Remove obs_output_signal_delay
  libobs/obs-output-delay.c
Labels: Code Cleanup

#11280 libobs: Deselect scene item before removing
  libobs/obs-scene.c
Labels: Bug Fix

#11275 docs: Add obs_frontend_get_user_config
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation

#11293 UI: Fix config class mismatch in OBSApp class
  UI/obs-app.cpp
  UI/window-basic-settings.cpp
Labels: Bug Fix

#11270 CI: Set default values for have* outputs in macos-codesigning action
  .github/actions/setup-macos-codesigning/action.yaml
Labels: Bug Fix

#11208 UI: Fix low value of std::clamp gets greater than high value
  UI/volume-control.cpp
Labels: Bug Fix

#11273 CI: Update deps to 2024-09-12 release
  buildspec.json
Labels: Bug Fix, Seeking Testers

#11300 UI: Fix missing support for portable configuration files
  UI/cmake/os-linux.cmake
  UI/obs-app.cpp
  cmake/linux/defaults.cmake
Labels: Bug Fix, Windows, Linux

#11307 libobs: Fix crop values for new nested scene sources being incorrect
  libobs/obs-scene.c
Labels: Bug Fix

#11308 libobs: Disable transform debug logging by default
  libobs/obs-scene.c
Labels: Enhancement

#11315 libobs: Fix source profiling inactive sources
  libobs/util/source-profiler.c
Labels: Bug Fix

#11317 libobs: Fix sending unclamped audio to output handler
  libobs/media-io/audio-io.c
Labels: Bug Fix

#11209 UI: Fix error color at clipping is not displayed on horizontal meter
  UI/volume-control.cpp
Labels: Bug Fix

#11301 UI: Fix crash when creating scene collections with "unsafe" names
  UI/window-basic-main.cpp
Labels: Bug Fix
