Repository obsproject/obs-studio, pull requests merged in 2024-06, with the labels that each got.

#10733 obs-ffmpeg: Check correct VA-API codec support
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Bug Fix

#10740 obs-qsv11: Fix QSV failing on multi-vendor multi-GPU systems
  plugins/obs-qsv11/common_utils_windows.cpp
Labels: Bug Fix, Seeking Testers

#10759 docs: Add return type of obs_source_audio_active
  docs/sphinx/reference-sources.rst
Labels: Documentation

#10765 obs-outputs: Add native mp4 output to legacy cmake
  plugins/obs-outputs/cmake/legacy.cmake
Labels: Bug Fix

#10760 docs: Add versionadded for 30.x functions
  docs/sphinx/reference-core.rst
  docs/sphinx/reference-encoders.rst
  docs/sphinx/reference-frontend-api.rst
  docs/sphinx/reference-libobs-util-deque.rst
  docs/sphinx/reference-modules.rst
  docs/sphinx/reference-properties.rst
  docs/sphinx/reference-settings.rst
  docs/sphinx/reference-sources.rst
Labels: Documentation

#10754 UI: Make status bar record output a weak ref
  UI/window-basic-status-bar.cpp
  UI/window-basic-status-bar.hpp
Labels: Enhancement

#10625 UI: Update volume meter appearance
  UI/data/themes/Yami.obt
  UI/volume-control.cpp
  UI/volume-control.hpp
  libobs/obs-audio-controls.c
  libobs/obs-audio-controls.h
Labels: Enhancement, Request for Comments, UI/UX

#10518 obs-webrtc: Adjust RtcpNackResponder from bitrate
  plugins/obs-webrtc/whip-output.cpp
Labels: Bug Fix

#10633 UI: Add (eRTMP) multitrack video output
  UI/CMakeLists.txt
  UI/api-interface.cpp
  UI/cmake/legacy.cmake
  UI/cmake/os-freebsd.cmake
  UI/cmake/os-linux.cmake
  UI/cmake/os-macos.cmake
  UI/cmake/os-windows.cmake
  UI/data/locale/en-US.ini
  UI/data/themes/Yami.obt
  UI/forms/AutoConfigStreamPage.ui
  UI/forms/OBSBasicSettings.ui
  UI/goliveapi-censoredjson.cpp
  UI/goliveapi-censoredjson.hpp
  UI/goliveapi-network.cpp
  UI/goliveapi-network.hpp
  UI/goliveapi-postdata.cpp
  UI/goliveapi-postdata.hpp
  UI/models/multitrack-video.hpp
  UI/multitrack-video-error.cpp
  UI/multitrack-video-error.hpp
  UI/multitrack-video-output.cpp
  UI/multitrack-video-output.hpp
  UI/obs-app.cpp
  UI/properties-view.cpp
  UI/properties-view.hpp
  UI/qt-helpers.cpp
  UI/qt-helpers.hpp
  UI/system-info-macos.mm
  UI/system-info-posix.cpp
  UI/system-info-windows.cpp
  UI/system-info.hpp
  UI/window-basic-auto-config-test.cpp
  UI/window-basic-auto-config.cpp
  UI/window-basic-auto-config.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings-stream.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: New Feature

#7278 Separation of the controls dock from the main window
  UI/basic-controls.cpp
  UI/basic-controls.hpp
  UI/cmake/legacy.cmake
  UI/cmake/ui-elements.cmake
  UI/cmake/ui-qt.cmake
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Acri.ovt
  UI/forms/OBSBasic.ui
  UI/forms/OBSBasicControls.ui
  UI/noncheckable-button.hpp
  UI/record-button.cpp
  UI/record-button.hpp
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Enhancement, Code Cleanup, UI/UX

#10741 cmake,UI: Fix SOVERSION on Linux
  UI/CMakeLists.txt
  cmake/linux/helpers.cmake
Labels: Bug Fix, Seeking Testers, Linux

#10718 UI: Fix Qt platform override in CMake 3
  UI/cmake/legacy.cmake
  UI/cmake/os-linux.cmake
  UI/obs-app.cpp
  UI/ui-config.h.in
Labels: Bug Fix

#10775 CI: Ignore PVS-Studio's license close to expiry error code
  .github/actions/windows-analysis/action.yaml
Labels: Bug Fix

#10774 UI: Fix crash when entering settings
  UI/window-basic-settings.cpp
Labels: Bug Fix

#10773 libobs: Add buffered file serializer to legacy cmake
  libobs/cmake/legacy.cmake
Labels: Bug Fix

#10276 obs-filters: Do not load NVVFX on OpenGL
  plugins/obs-filters/obs-filters.c
Labels: Bug Fix

#10524 obs-webrtc: Add Link Header support
  plugins/obs-webrtc/whip-output.cpp
  plugins/obs-webrtc/whip-output.h
Labels: New Feature

#10776 UI: Disable Multitrack Video by default
  UI/window-basic-main.cpp
Labels: Bug Fix

#10777 UI: Remove GPU LUID from system info for Multitrack Video
  UI/models/multitrack-video.hpp
  UI/system-info-windows.cpp
Labels: Code Cleanup

#10778 UI: Fix incompatible settings message when streaming Multitrack Video
  UI/multitrack-video-output.cpp
Labels: Bug Fix

#10780 UI: Remove redundant assignments
  UI/multitrack-video-output.cpp
Labels: Code Cleanup

#10783 rtmp-services: Add Amazon IVS service
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#10784 UI: Enable custom server entry for Amazon IVS
  UI/window-basic-settings-stream.cpp
Labels: Enhancement

#10787 UI: Address logging buffer size discrepancies
  UI/obs-app.cpp
  UI/qt-wrappers.cpp
  libobs/util/base.c
Labels: Bug Fix

#10790 UI: Remove dead code from multitrack output
  UI/multitrack-video-output.cpp
Labels: Code Cleanup

#10791 UI: Add config option to use MP4 for debug recording
  UI/multitrack-video-output.cpp
  UI/window-basic-main-outputs.cpp
Labels: Enhancement

#10789 UI: Simplify multitrack encoder availability check
  UI/multitrack-video-output.cpp
Labels: Code Cleanup

#10793 CI: Restrict PVS-Studio analysis to obsproject repo
  .github/workflows/analyze-project.yaml
Labels: CI

#10795 UI: Fix multitrack stream key query parameter concatenation
  UI/multitrack-video-output.cpp
Labels: Bug Fix

#10797 CI: Fix incorrect filenames in release creation
  .github/workflows/push.yaml
Labels: Bug Fix, CI

#10805 CI: Fix input variable name when getting Windows release notes
  .github/actions/windows-patches/action.yaml
Labels: CI

#10801 UI: Remove unnecessary string copy from log filter
  UI/obs-app.cpp
Labels: Code Cleanup

#10803 UI: Add null checks before doing some API calls
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.cpp
  UI/window-basic-preview.cpp
Labels: Bug Fix

#10802 UI: Improve macOS properties tooltip spacing workaround
  UI/properties-view.cpp
Labels: Code Cleanup, macOS

#10804 UI: Always show chapter marker hotkey
  UI/data/locale/en-US.ini
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#10806 UI: Connect replay buffer stopping to signal instead of slot
  UI/basic-controls.cpp
Labels: Bug Fix

#10779 UI: Clean up Settings widget structure and styling
  UI/data/themes/Yami.obt
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Bug Fix, Code Cleanup

#10810 cmake: Copy shared library soname file to rundir on Linux
  cmake/linux/helpers.cmake
Labels: Bug Fix, Linux

#10809 UI: Check VC++ Runtime version on startup
  UI/obs-app.cpp
Labels: Bug Fix, Enhancement, Windows

#10807 UI: Avoid allowing to override provided themes
  UI/obs-app-theming.cpp
Labels: Bug Fix

#10818 obs-ffmpeg: Set encoder error message for CUDA errors
  plugins/obs-ffmpeg/obs-nvenc.c
Labels: Bug Fix

#10819 CI: Update bouf release
  .github/actions/windows-signing/action.yaml
  .github/workflows/push.yaml
Labels: Bug Fix, CI

#10823 UI: Translate Multitrack Video error dialog buttons
  UI/multitrack-video-error.cpp
Labels: Bug Fix

#10820 UI: Fix crash after canceling stream attempt with incompatible settings
  UI/multitrack-video-output.cpp
Labels: Bug Fix

#10831 updater: Fix defaultlib conflict
  UI/win-update/updater/CMakeLists.txt
Labels: Bug Fix

#10828 UI: Prevent recursion in theme dependencies
  UI/obs-app-theming.cpp
Labels: Bug Fix

#10834 UI: Fix themeDir buffer being resized incorrectly
  UI/obs-app-theming.cpp
Labels: Bug Fix

#10838 UI: Use unique_ptr for theme objects
  UI/obs-app-theming.cpp
Labels: Bug Fix

#10841 CI: Add updateChannel to check-tag in Publish workflow
  .github/workflows/publish.yaml
Labels: Bug Fix, CI

#10845 Update multitrack video schema to version 2024-06-04
  UI/goliveapi-postdata.cpp
  UI/models/multitrack-video.hpp
  UI/multitrack-video-output.cpp
  UI/window-basic-auto-config.cpp
Labels: Enhancement

#10847 UI: Fix submenu arrow indicator position in menus
  UI/data/themes/Yami_Classic.ovt
Labels: Bug Fix, UI/UX

#10853 UI: Make audio_configurations.vod optional
  UI/models/multitrack-video.hpp
  UI/multitrack-video-output.cpp
Labels: Enhancement

#10854 UI: Hide multitrack video options for custom output
  UI/window-basic-settings.cpp
Labels: Enhancement, UI/UX

#10826 UI: Remove redundant addAction call
  UI/window-basic-main.cpp
Labels: Code Cleanup

#10830 UI: Fix icon-size values in theme files
  UI/data/themes/System.obt
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Classic.ovt
Labels: Bug Fix, Code Cleanup

#10850 obs-outputs: Add multitrack flag to null output
  plugins/obs-outputs/null-output.c
Labels: Enhancement

#10856 UI: Set Multitrack Video maximum bitrate limit default to 0/Auto
  UI/forms/OBSBasicSettings.ui
Labels: Enhancement, UI/UX

#10860 deps/media-playback: Fix initialization of swscale with hw decode
  deps/media-playback/media-playback/media.c
Labels: Bug Fix

#10862 UI: Set default container for beta builds to hybrid MP4
  UI/window-basic-main.cpp
Labels: Enhancement

#10872 UI: Fix parsing of Multitrack Video stream key query parameters
  UI/multitrack-video-output.cpp
Labels: Bug Fix

#10875 UI: Use advanced mode audio track in multitrack video output
  UI/multitrack-video-output.cpp
  UI/multitrack-video-output.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main-outputs.hpp
Labels: Bug Fix

#10886 CI: Update Windows Patches Action
  .github/actions/windows-patches/action.yaml
Labels: CI

#10887 UI: Only cache multitrack config URL startup argument
  UI/goliveapi-network.cpp
Labels: Bug Fix

#10879 UI: Add supported codecs to GetClientConfiguration request
  UI/goliveapi-postdata.cpp
  UI/models/multitrack-video.hpp
Labels: Bug Fix, Enhancement

#10888 UI: Disable multitrack video settings on non-win32 platforms
  UI/window-basic-settings.cpp
Labels: Enhancement

#10889 CI: Fix FreeBSD package installation
  .cirrus.yml
Labels: Bug Fix, CI

#10883 cmake: Add obs-config.h to libobs headers
  libobs/CMakeLists.txt
Labels: Enhancement

#10869 rtmp-services: Add Dolby Millicast
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#10897 obs-ffmpeg: Close VAAPI device on vaInitialize fail (memory leak fix)
  plugins/obs-ffmpeg/vaapi-utils.c
Labels: Bug Fix, Linux

#10893 UI: Fix multitrack-video audio track index
  UI/window-basic-main-outputs.cpp
Labels: Bug Fix

#10894 UI: Link Qt::DBus on FreeBSD
  UI/cmake/os-freebsd.cmake
Labels: Bug Fix

#10919 cmake: Fix FFmpeg version regex
  cmake/finders/FindFFmpeg.cmake
Labels: Bug Fix

#10911 obs-ffmpeg: Check if current NVENC configuration supports 4:4:4 encode
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-nvenc.c
Labels: Bug Fix

#10912 obs-outputs: Skip trak box if track has no data
  plugins/obs-outputs/mp4-mux.c
Labels: Bug Fix

#10909 obs-x264: Ignore stats/qp file and multipass options
  plugins/obs-x264/obs-x264.c
Labels: Enhancement

#10892 UI: Adjust Yami (Classic) styling
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Classic.ovt
  UI/forms/OBSBasicFilters.ui
Labels: Bug Fix, Enhancement, UI/UX

#10864 UI: Fix capitalization of 'OBS' and 'RTMP'
  UI/data/locale/en-US.ini
Labels: Bug Fix

#10874 UI: Display dialog for multitrack video output audio channels mismatch
  UI/data/locale/en-US.ini
  UI/multitrack-video-output.cpp
Labels: Enhancement

#10896 libobs: Fix destroy_on_stop functionality of encoder groups
  libobs/obs-encoder.c
Labels: Bug Fix, Seeking Testers

#10924 Revert "plugins/win-dshow: Add CUDA decoder"
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix
