Repository obsproject/obs-studio, pull requests merged in 2024-04, with the labels that each got.

#10439 rtmp-services: Update "CHZZK" platform
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#10391 CI: Update formatting actions to use git diff filter before formatting
  .github/actions/check-changes/action.yaml
  .github/actions/run-clang-format/action.yaml
  .github/actions/run-cmake-format/action.yaml
  .github/actions/run-swift-format/action.yaml
Labels: Bug Fix, CI

#10473 UI: Use spacers instead of widgets in macOS Permissions UI
  UI/forms/OBSPermissions.ui
Labels: Code Cleanup, macOS, UI/UX

#10299 cmake: Provide a clear error on version check fail
  cmake/Modules/VersionConfig.cmake
  cmake/common/versionconfig.cmake
Labels: Enhancement

#10482 Revert "UI: Change default format for release builds to fMP4/fMOV"
  UI/window-basic-main.cpp
Labels: Bug Fix

#10170 obs-qsv11: Fix for QSV AV1 in multi-GPU system
  plugins/obs-qsv11/QSV_Encoder.cpp
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/common_utils.cpp
  plugins/obs-qsv11/common_utils.h
  plugins/obs-qsv11/common_utils_windows.cpp
  plugins/obs-qsv11/obs-qsv11.c
Labels: Bug Fix

#10388 obs-qsv11: Remove adaptive CQM option
  plugins/obs-qsv11/QSV_Encoder.h
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
  plugins/obs-qsv11/QSV_Encoder_Internal.h
  plugins/obs-qsv11/data/locale/en-US.ini
  plugins/obs-qsv11/obs-qsv11.c
Labels: Code Cleanup

#10337 UI: Move warnings to bottom of settings window
  UI/forms/OBSBasicSettings.ui
  UI/window-basic-settings.cpp
Labels: Bug Fix, UI/UX

#10478 UI: Log available encoders on load
  UI/window-basic-main.cpp
Labels: Enhancement, UI/UX

#10318 UI: Fix `Start Virtual Camera` Text Cut Off in Corresponding Button
  UI/window-basic-main.cpp
Labels: Bug Fix

#10507 rtmp-services: Update Chaturbate
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#9391 obs-ffmpeg: Remove media source mpegts format override for SRT and RIST
  plugins/obs-ffmpeg/obs-ffmpeg-source.c
Labels: Enhancement, Seeking Testers

#10490 UI: Always retain collection data of unloaded modules
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, Enhancement

#10509 UI: Fix Top Patron threshold
  UI/window-basic-about.cpp
Labels: Bug Fix

#10510 UI: Include duration when copy/pasting scene item transitions
  UI/window-basic-main-transitions.cpp
  UI/window-basic-main.hpp
Labels: Enhancement

#10513 decklink: Update SDK to 12.0
  plugins/decklink/linux/decklink-sdk/DeckLinkAPI.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIConfiguration.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIDeckControl.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIDiscovery.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIModes.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPITypes.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIVersion.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIVideoInput_v10_11.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPIVideoInput_v11_4.h
  plugins/decklink/linux/decklink-sdk/DeckLinkAPI_v9_2.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPI.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIConfiguration.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIDeckControl.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIDiscovery.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIModes.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIStreaming.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPITypes.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIVersion.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIVideoInput_v10_11.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPIVideoInput_v11_4.h
  plugins/decklink/mac/decklink-sdk/DeckLinkAPI_v9_2.h
  plugins/decklink/win/decklink-sdk/DeckLinkAPI.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIConfiguration.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIDeckControl.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIDiscovery.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIModes.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIStreaming.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPITypes.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPIVersion.h
  plugins/decklink/win/decklink-sdk/DeckLinkAPI_v10_11.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPI_v11_4.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPI_v11_5_1.idl
  plugins/decklink/win/decklink-sdk/DeckLinkAPI_v9_2.idl
Labels: Code Cleanup

#10514 UI: Fix double confirmation dialog while discarding source change
  UI/window-basic-properties.cpp
Labels: Bug Fix, Code Cleanup, Seeking Testers, UI/UX

#10517 obs-ffmpeg: Use video_output_info in amf_create_encoder()
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Enhancement, Code Cleanup

#10522 plugins: Set keyframe flag on encoded audio packets
  plugins/coreaudio-encoder/encoder.cpp
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-libfdk/obs-libfdk.c
Labels: Enhancement

#10526 mac-avcapture: Add pointer check for outputting NULL video frames
  plugins/mac-avcapture/OBSAVCapture.m
Labels: Bug Fix, macOS

#10531 linux-pipewire: Remove unused variables
  plugins/linux-pipewire/camera-portal.c
  plugins/linux-pipewire/pipewire.c
Labels: Code Cleanup

#10494 obs-outputs: Fix FLV muxer tag size logic and file info offset
  plugins/obs-outputs/flv-mux.c
Labels: Bug Fix

#7279 UI: Reduce settings dialog default height
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
Labels: Bug Fix, UI/UX

#10402 UI: Change advanced audio controls to use audio_active
  UI/adv-audio-control.cpp
  UI/adv-audio-control.hpp
  UI/window-basic-adv-audio.cpp
  UI/window-basic-adv-audio.hpp
Labels: Enhancement, UI/UX

#10550 cmake: Deprecate legacy CMake for all platforms
  CMakeLists.txt
Labels: Code Cleanup

#10159 obs-webrtc: Add HEVC support
  plugins/obs-webrtc/whip-output.cpp
  plugins/obs-webrtc/whip-output.h
  plugins/obs-webrtc/whip-service.cpp
Labels: New Feature

#10562 CI: Fix generate-docs action
  .github/actions/generate-docs/action.yaml
Labels: Bug Fix, CI

#10552 cmake: Remove find_qt macro
  cmake/common/helpers_common.cmake
Labels: Code Cleanup

#10561 UI: Use System theme volume meter colors for default values
  UI/volume-control.cpp
Labels: Enhancement, Code Cleanup

#10567 libobs: Export NV12/P010 functions
  libobs/graphics/device-exports.h
Labels: Bug Fix

#10541 text-freetype2: Use cached glyph advances
  plugins/text-freetype2/text-functionality.c
Labels: Enhancement

#10549 libobs: Fix `highest_video_ts` tracking
  libobs/obs-output.c
Labels: Bug Fix

#10574 libobs/util: Prevent leaking pipe file descriptors to subprocesses
  libobs/util/pipe-posix.c
Labels: Bug Fix

#10137 obs-ffmpeg: Implement texture encoding for VAAPI
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/cmake/dependencies.cmake
  plugins/obs-ffmpeg/cmake/legacy.cmake
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: Linux, New Feature

#10000 obs-webrtc: Add support for audio-only and video-only outputs
  plugins/obs-webrtc/whip-output.cpp
Labels: Enhancement

#10511 UI: Reset duration when removing show/hide transition
  UI/window-basic-main-transitions.cpp
Labels: Enhancement, UI/UX

#10569 CI: Update softprops/action-gh-release to v2.0.4
  .github/workflows/push.yaml
Labels: Enhancement, CI

#10570 CI: Update yuzutech/annotations-action to v0.5.0
  .github/actions/compatibility-validator/action.yaml
  .github/actions/services-validator/action.yaml
Labels: Enhancement, CI

#10582 obs-ffmpeg: Fix output path logging
  plugins/obs-ffmpeg/obs-ffmpeg-mux.c
Labels: Bug Fix

#10579 UI: Clean up theme file formatting
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Acri.ovt
  UI/data/themes/Yami_Classic.ovt
  UI/data/themes/Yami_Rachni.ovt
Labels: Code Cleanup, UI/UX

#10617 UI: Fix styling of appearance tab
  UI/forms/OBSBasicSettings.ui
Labels: Bug Fix, UI/UX

#10615 UI: Fix volume control button styling
  UI/data/themes/Yami.obt
  UI/volume-control.cpp
Labels: Bug Fix, UI/UX

#10601 win-dshow: Fix compiling with FFmpeg 7.0
  plugins/win-dshow/ffmpeg-decode.c
Labels: Bug Fix

#10606 cmake: Remove more Qt 5 code
  cmake/common/helpers_common.cmake
  cmake/macos/helpers.cmake
  cmake/windows/helpers.cmake
Labels: Code Cleanup
