Repository obsproject/obs-studio, pull requests merged in 2024-05, with the labels that each got.

#10631 CI: Fix Windows Signing action commit hash
  .github/workflows/push.yaml
Labels: Bug Fix, CI

#10583 obs-ffmpeg: Release encode texture early
  plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c
Labels: Enhancement, Linux

#10149 libobs: Add `obs_encoder_parent_video()` method
  docs/sphinx/reference-encoders.rst
  libobs/obs-encoder.c
  libobs/obs.h
Labels: Enhancement

#10613 obs-scripting: Remove Python version upper limit on Linux
  deps/obs-scripting/cmake/python.cmake
  deps/obs-scripting/obspython/CMakeLists.txt
Labels: Enhancement, Linux

#10621 obs-webrtc: Add null terminator to codec array
  plugins/obs-webrtc/whip-service.cpp
  plugins/obs-webrtc/whip-service.h
Labels: Bug Fix

#10587 linux-capture: Rename Screen Capture as Display Capture
  plugins/linux-capture/data/locale/en-US.ini
  plugins/linux-capture/xshm-input.c
Labels: Linux, UI/UX

#10589 UI: Adjust preview scrolling clamp values
  UI/window-basic-preview.cpp
Labels: Enhancement, UI/UX

#10623 UI: Adjust styling of QTabBar tabs
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Acri.ovt
Labels: Enhancement, UI/UX

#10630 UI: Set default recording format to Fragmented MOV on macOS
  UI/window-basic-main.cpp
Labels: Enhancement, macOS

#10626 UI: Restore MuteCheckBox indeterminate state icon in Yami
  UI/data/themes/Yami.obt
Labels: Bug Fix, UI/UX

#10640 build-aux: Disable DeckLink in the Flatpak
  build-aux/com.obsproject.Studio.json
Labels: Linux

#10468 libobs-winrt: Remove interop code now provided by Windows SDK
  libobs-winrt/CMakeLists.txt
  libobs-winrt/cmake/legacy.cmake
  libobs-winrt/winrt-capture.cpp
Labels: Code Cleanup, Windows

#10565 linux-pipewire: Unify ScreenCast source as Screen Capture
  plugins/linux-pipewire/data/locale/en-US.ini
  plugins/linux-pipewire/screencast-portal.c
Labels: Enhancement, Seeking Testers, Linux, UI/UX

#10654 CI: Update deps to 2024-05-08 release
  buildspec.json
Labels: Enhancement

#10658 UI: Improve and update app CMake 3 metainfo file
  UI/cmake/linux/com.obsproject.Studio.metainfo.xml.in
  UI/cmake/os-linux.cmake
Labels: Bug Fix, Enhancement, Seeking Testers, Linux

#10647 UI: Use weak_source_expired instead of getting the source
  UI/window-basic-main.cpp
Labels: Code Cleanup

#10657 libobs: Fix obs_parse_avc_header missing high profile parameters
  libobs/obs-avc.c
Labels: Bug Fix

#10246 UI: Use OBSSourceLabel for item widget labels
  UI/source-tree.cpp
  UI/source-tree.hpp
  UI/visibility-item-widget.cpp
  UI/visibility-item-widget.hpp
Labels: Code Cleanup

#10239 UI: Move projector rename signal
  UI/window-basic-main.cpp
  UI/window-projector.cpp
  UI/window-projector.hpp
Labels: Code Cleanup

#10238 UI: Volume signal cleanup
  UI/volume-control.cpp
  UI/volume-control.hpp
  UI/window-basic-main.cpp
Labels: Code Cleanup

#10659 UI: Fix visibility and lock checkbox styling on system theme
  UI/data/themes/System.obt
Labels: Bug Fix

#10639 UI: Give private spacing helper sources names
  UI/window-basic-preview.cpp
Labels: Enhancement

#10643 UI: Center preview spacing lines
  UI/window-basic-preview.cpp
Labels: Bug Fix, UI/UX

#10662 UI: Adjust font size on macOS
  UI/data/themes/Yami.obt
  UI/data/themes/Yami_Classic.ovt
Labels: Bug Fix, macOS

#10678 CI: Add Ubuntu 24.04
  .github/workflows/build-project.yaml
  .github/workflows/push.yaml
Labels: Enhancement, CI

#10679 CI: Add additional log group to setup_ubuntu script
  .github/scripts/utils.zsh/setup_ubuntu
Labels: Code Cleanup, CI

#10458 mac-capture: Replace pragmas with availability markers
  .clang-format
  plugins/mac-capture/mac-sck-audio-capture.m
  plugins/mac-capture/mac-sck-common.h
  plugins/mac-capture/mac-sck-common.m
  plugins/mac-capture/mac-sck-video-capture.m
Labels: Bug Fix, Code Cleanup, Seeking Testers

#10665 rnnoise: Fix compilation not working on latest gcc
  plugins/obs-filters/rnnoise/src/denoise.c
Labels: Bug Fix

#10680 UI: Keep weak stream output ref in status bar
  UI/window-basic-status-bar.cpp
  UI/window-basic-status-bar.hpp
Labels: Enhancement, Code Cleanup

#10670 libobs/util: Add seeking support to array serializer
  docs/sphinx/reference-libobs-util-serializers.rst
  libobs/util/array-serializer.c
  libobs/util/array-serializer.h
Labels: Enhancement

#10671 libobs/util: Add buffered file serializer
  docs/sphinx/reference-libobs-util-serializers.rst
  libobs/CMakeLists.txt
  libobs/util/buffered-file-serializer.c
  libobs/util/buffered-file-serializer.h
Labels: Enhancement

#10672 obs-outputs: Adjust HEVCDecoderConfigurationRecord for hvc1 tag
  plugins/obs-outputs/rtmp-hevc.c
Labels: Enhancement

#10689 libobs: Ensure audio offsets are positive
  libobs/obs-output.c
Labels: Bug Fix

#10690 coreaudio-encoder: Fix pts/dts not including encoder delay
  plugins/coreaudio-encoder/encoder.cpp
  plugins/coreaudio-encoder/windows-imports.h
Labels: Bug Fix, Windows, macOS

#10687 UI: Give unnamed settings labels relevant names
  UI/forms/OBSBasicSettings.ui
Labels: Code Cleanup, UI/UX

#10692 UI: Fix Grid Mode not persisting from View Menu
  UI/window-basic-main.cpp
Labels: Bug Fix, UI/UX

#10694 UI: Change how the status bar gets weak stream output
  UI/window-basic-status-bar.cpp
Labels: Code Cleanup

#10719 UI: Enforce completely Fusion Qt style on Linux
  UI/obs-app-theming.cpp
  UI/obs-app.cpp
  UI/obs-proxy-style.hpp
Labels: Code Cleanup

#10722 UI: Inline OBSBasic::ThemeChanged()
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#10723 UI: Add undo/redo to Paste Filters on audio mixer and scenes
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix, UI/UX

#10726 libobs: Fix buffer overrun in video_frame_init
  libobs/media-io/video-frame.c
Labels: Bug Fix

#10727 mac-avcapture: Improve av_capture_sync_info formatting
  plugins/mac-avcapture/plugin-main.m
Labels: Code Cleanup

#10706 CI: Generate/Verify Attestation for Windows builds
  .github/actions/windows-patches/action.yaml
  .github/workflows/push.yaml
  .github/workflows/sign-windows.yaml
Labels: CI

#10717 cmake: Do not write build number file if OBS_BUILD_NUMBER set
  cmake/Modules/VersionConfig.cmake
  cmake/common/buildnumber.cmake
Labels: New Feature

#10684 UI: Removed unused friend classes
  UI/auth-twitch.hpp
  UI/window-basic-main.hpp
Labels: Code Cleanup

#10732 UI: Fix Qt 6.7 checkbox signal deprecations
  UI/properties-view.cpp
  UI/window-basic-settings.cpp
  UI/window-basic-settings.hpp
  UI/window-basic-transform.cpp
  UI/window-youtube-actions.cpp
Labels: Bug Fix

#10608 Native Hybrid MP4 Muxer
  UI/api-interface.cpp
  UI/data/locale/en-US.ini
  UI/ffmpeg-utils.cpp
  UI/obs-app.cpp
  UI/obs-frontend-api/obs-frontend-api.cpp
  UI/obs-frontend-api/obs-frontend-api.h
  UI/obs-frontend-api/obs-frontend-internal.hpp
  UI/window-basic-main-outputs.cpp
  UI/window-basic-main.cpp
  UI/window-basic-main.hpp
  UI/window-basic-settings.cpp
  plugins/obs-outputs/CMakeLists.txt
  plugins/obs-outputs/data/locale/en-US.ini
  plugins/obs-outputs/mp4-mux-internal.h
  plugins/obs-outputs/mp4-mux.c
  plugins/obs-outputs/mp4-mux.h
  plugins/obs-outputs/mp4-output.c
  plugins/obs-outputs/obs-outputs.c
Labels: Enhancement, Seeking Testers, New Feature

#10591 rtmp-services: Add sheeta
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#10748 docs: Document obs_frontend_recording_add_chapter()
  docs/sphinx/reference-frontend-api.rst
Labels: Documentation
