Repository obsproject/obs-studio, pull requests merged in 2025-03, with the labels that each got.

#11900 libobs,win-capture,win-wasapi: Fix typo in macro WIN32_LEAN_AND_MEAN
  libobs/obs-video.c
  plugins/win-capture/dc-capture.c
  plugins/win-wasapi/enum-wasapi.hpp
Labels: Bug Fix, Code Cleanup, Windows

#11861 win-dshow: Fix possible crash if frame width or height is zero
  plugins/win-dshow/win-dshow.cpp
Labels: Bug Fix

#11895 mac-avcapture: Prevent race condition in source init/deinit
  plugins/mac-avcapture/plugin-main.m
Labels: Bug Fix, macOS

#11931 CI: Update deps to 2025-03-06 release
  buildspec.json
Labels: Enhancement, Seeking Testers

#11460 obs-qsv11: Fix CBR Spike for Battlemage
  plugins/obs-qsv11/QSV_Encoder_Internal.cpp
Labels: Bug Fix

#11521 obs-ffmpeg: Add AMD AV1 B-frame support
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: New Feature

#11948 CI: Use rebuilt CEF to avoid memory allocation crashes on macOS
  buildspec.json
Labels: Bug Fix, Seeking Testers, macOS, CI

#11710 obs-ffmpeg: Fix throughput checks for older AMD driver
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix

#11911 cmake: Fix some Qt DLLs not being copied due to filename patterns
  cmake/windows/helpers.cmake
Labels: Bug Fix

#11963 CI: Update flatpak-builder and flat-manager actions
  .github/workflows/build-project.yaml
  .github/workflows/publish.yaml
Labels: Linux, CI

#11926 libobs: Reset reconnecting state when can_reconnect is false
  libobs/obs-output.c
Labels: Bug Fix

#11924 obs-nvenc: Fix incorrect CUDA array size allocation
  plugins/obs-nvenc/nvenc-cuda.c
Labels: Bug Fix

#11952 nv-filters: Various bugfixes
  plugins/nv-filters/nvidia-videofx-filter.c
Labels: Bug Fix, Seeking Testers

#11972 mac-avcapture: Clear memory when creating frame struct
  plugins/mac-avcapture/plugin-main.m
Labels: Bug Fix, macOS

#11835 rtmp-services: Update Castr.io ingests
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#11897 frontend: Only emit frontend events for existing scene collection
  frontend/widgets/OBSBasic.cpp
Labels: Bug Fix

#11591 rtmp-services: Add "VRCDN - Live"
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#11887 frontend: Remove Exit button
  frontend/forms/OBSBasicControls.ui
  frontend/widgets/OBSBasic.cpp
  frontend/widgets/OBSBasicControls.cpp
  frontend/widgets/OBSBasicControls.hpp
Labels: Enhancement, UI/UX

#11893 cmake: Adjust macOS SDK detection
  cmake/macos/compilerconfig.cmake
Labels: Bug Fix, macOS
