Repository obsproject/obs-studio, pull requests merged in 2025-07, with the labels that each got.

#12322 frontend: Enforce minimum height for QList items
  frontend/data/themes/Yami.obt
Labels: Bug Fix, UI/UX

#12352 CI: Add GH_TOKEN to fix usage of GitHub CLI
  .github/workflows/publish.yaml
Labels: Bug Fix, CI

#12370 CI: Update deps to 2025-07-11 release
  buildspec.json
Labels: Bug Fix

#12376 build-aux: Use rebuilt CEF on Linux with backported API on Flatpak
  build-aux/modules/99-cef.json
Labels: Bug Fix, Linux

#12303 linux-v4l2: Avoid stopping capture on AVERROR(EAGAIN)
  plugins/linux-v4l2/v4l2-decoder.c
Labels: Bug Fix, Linux

#12405 frontend: Fix progress bar appearance
  frontend/data/themes/Yami.obt
Labels: Bug Fix

#12409 frontend: Fix settings scrollbar size
  frontend/data/themes/Yami.obt
Labels: UI/UX

#12429 CI: Fix failures of analyze workflow runs due to GitHub policy change
  .github/workflows/analyze-project.yaml
Labels: CI

#12422 Revert "linux-pipewire: Fix 10- and 16-bit captures"
  plugins/linux-pipewire/pipewire.c
  plugins/linux-pipewire/screencast-portal.c
Labels: Bug Fix, Linux

#12379 libobs: Start video output even if there is no mix to fix DeckLink outputs
  libobs/obs.c
Labels: Bug Fix
