Repository obsproject/obs-studio, pull requests merged in 2025-04, with the labels that each got.

#11207 linux-pipewire: Fix 10- and 16-bit captures
  plugins/linux-pipewire/pipewire.c
  plugins/linux-pipewire/screencast-portal.c
Labels: Bug Fix, Linux

#11557 frontend: Make list spacing consistent
  frontend/data/themes/Yami.obt
  frontend/forms/OBSBasic.ui
Labels: Enhancement, UI/UX

#11206 libobs: Deprecate obs_get_transition_by_[name|uuid]
  docs/sphinx/reference-core.rst
  libobs/obs.h
Labels: Bug Fix, Code Cleanup

#11182 frontend: Add preview zoom controls
  frontend/data/locale/en-US.ini
  frontend/data/themes/Yami.obt
  frontend/forms/OBSBasic.ui
  frontend/widgets/OBSBasic.cpp
  frontend/widgets/OBSBasic.hpp
  frontend/widgets/OBSBasicPreview.cpp
  frontend/widgets/OBSBasicPreview.hpp
  frontend/widgets/OBSBasic_MainControls.cpp
  frontend/widgets/OBSBasic_Preview.cpp
Labels: Enhancement, UI/UX

#11987 CI: Clean up Flatpak cache detection
  .github/workflows/build-project.yaml
  .github/workflows/publish.yaml
Labels: Code Cleanup, Linux, CI

#10895 mac-avcapture: Use list-based format selector
  plugins/mac-avcapture/AVCaptureDeviceFormat+OBSListable.h
  plugins/mac-avcapture/AVCaptureDeviceFormat+OBSListable.m
  plugins/mac-avcapture/CMakeLists.txt
  plugins/mac-avcapture/OBSAVCapture.h
  plugins/mac-avcapture/OBSAVCapture.m
  plugins/mac-avcapture/data/locale/en-US.ini
  plugins/mac-avcapture/plugin-main.m
  plugins/mac-avcapture/plugin-properties.h
  plugins/mac-avcapture/plugin-properties.m
Labels: Bug Fix, Enhancement, Seeking Testers, macOS

#11555 frontend: Adjust styling for Sources list
  frontend/components/SourceTreeDelegate.cpp
  frontend/data/themes/Yami.obt
Labels: Bug Fix, Enhancement, UI/UX

#11839 frontend: Focus text entry in NameDialog
  frontend/dialogs/NameDialog.cpp
Labels: Bug Fix, UI/UX

#10135 Add OpenH264 support to obs-ffmpeg
  plugins/obs-ffmpeg/CMakeLists.txt
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/obs-ffmpeg-openh264.c
  plugins/obs-ffmpeg/obs-ffmpeg.c
Labels: New Feature

#11996 frontend: Remove additional spacing hack in SourceTreeItem
  frontend/components/SourceTreeItem.cpp
Labels: Enhancement, UI/UX

#11747 CI: Add ARM and Game Capture Dual-Signing
  .github/actions/windows-signing/action.yaml
  .github/actions/windows-signing/config_arm64.toml
  .github/actions/windows-signing/config_x64.toml
  .github/actions/windows-signing/prod-gc.crt
  .github/workflows/push.yaml
  .github/workflows/sign-windows.yaml
Labels: Enhancement

#11492 frontend: Reorganize Preview/Source context menu
  frontend/data/locale/en-US.ini
  frontend/forms/OBSBasic.ui
  frontend/widgets/OBSBasic.cpp
  frontend/widgets/OBSBasic.hpp
  frontend/widgets/OBSBasic_Projectors.cpp
  frontend/widgets/OBSBasic_SceneItems.cpp
  frontend/widgets/OBSBasic_Scenes.cpp
  frontend/widgets/OBSBasic_StudioMode.cpp
  frontend/widgets/OBSBasic_SysTray.cpp
  frontend/widgets/OBSProjector.cpp
Labels: Enhancement, UI/UX

#11966 CI: Update clang-format scripts and actions to version 19.1.1
  .clang-format
  .github/actions/run-clang-format/action.yaml
  build-aux/.run-format.zsh
  frontend/settings/OBSHotkeyWidget.cpp
  frontend/utility/BasicOutputHandler.hpp
  frontend/utility/RemuxWorker.hpp
  libobs/util/threading-windows.c
  plugins/coreaudio-encoder/encoder.cpp
  plugins/mac-capture/mac-display-capture.m
  plugins/nv-filters/nvidia-videofx-filter.c
  plugins/nv-filters/nvvfx-load.h
  plugins/obs-webrtc/whip-output.cpp
  shared/obs-scripting/obs-scripting-python.c
  shared/obs-scripting/obs-scripting.c
Labels: Code Cleanup

#11975 rtmp-services: Add HEVC (h265) to the list of supported video codecs for Bilibili RTMP streaming
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#11983 rtmp-services: Update ingest URL for Niconico Live Streaming(ニコニコ生放送)
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#12065 CI: Use Flatpak action upstream
  .github/workflows/build-project.yaml
  .github/workflows/publish.yaml
Labels: Linux, CI

#11894 obs-qsv11: Remove non-functional CQM-related code
  plugins/obs-qsv11/obs-qsv11.c
Labels: Code Cleanup

#11922 frontend/widgets: Fix integer overflow
  frontend/widgets/OBSBasicPreview.cpp
Labels: Bug Fix

#12051 frontend: Clean up various strings
  frontend/data/locale/en-US.ini
  frontend/forms/OBSBasic.ui
  frontend/widgets/OBSBasic_SceneItems.cpp
  frontend/widgets/OBSBasic_Scenes.cpp
Labels: Enhancement

#11583 graphics-hook: Fix crash with Vulkan DirectDisplay
  plugins/win-capture/graphics-hook/vulkan-capture.c
Labels: Bug Fix, Windows

#12024 media-playback: Fix possible crash if frame width or height is zero
  shared/media-playback/media-playback/media.c
Labels: Bug Fix

#11906 linux-v4l2: Fix virtual camera start failure
  plugins/linux-v4l2/v4l2-output.c
Labels: Bug Fix, Seeking Testers

#12035 mac-capture: Fix incorrect enum comparison
  plugins/mac-capture/mac-sck-audio-capture.m
Labels: Bug Fix, macOS

#11548 obs-ffmpeg: Set the codec level for AMF encoders
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Enhancement

#11998 build-aux: Fix incorrect HEVC vertical resolution on AMD VCN
  build-aux/modules/30-ffmpeg.json
  build-aux/modules/patches/ffmpeg/0001-lavc-vaapi_encode-Query-surface-alignment.patch
  build-aux/modules/patches/ffmpeg/0002-lavc-vaapi_encode_h265-Use-surface-alignment.patch
Labels: Bug Fix

#12076 cmake: Adjust macOS SDK detection
  cmake/macos/compilerconfig.cmake
Labels: Bug Fix

#12018 libobs/util: Prevent locking mutex in child process when checking Qt5
  libobs/util/platform-nix.c
Labels: Bug Fix

#12040 frontend: Use default location for user settings as fallback
  frontend/OBSApp.cpp
Labels: Bug Fix

#12083 cmake: Group blake2 targets under same directory for IDEs
  deps/blake2/CMakeLists.txt
Labels: Enhancement

#12017 frontend: Add dedicated translation of remaining time
  frontend/data/locale/en-US.ini
  frontend/widgets/OBSBasicStats.cpp
Labels: Enhancement

#11985 libobs: Fix setting non-0 order on only scene item
  libobs/obs-scene.c
Labels: Bug Fix

#12021 libobs/callback: Catch fail cases with missing error data
  libobs/callback/decl.c
Labels: Bug Fix

#12022 win-capture: Update hooked state before unhooked signal
  plugins/win-capture/game-capture.c
Labels: Bug Fix, Windows

#12042 libobs: Use absolute path for install prefix module load
  libobs/obs-nix.c
Labels: Bug Fix

#12073 linux-v4l2: Add support for virtual camera on non-Linux environments
  plugins/linux-v4l2/v4l2-output.c
Labels: Enhancement

#11472 UI,libobs,obs-outputs: Remove HAVE_OBSCONFIG_H ifdefs
  frontend/OBSApp.cpp
  frontend/dialogs/OBSAbout.cpp
  frontend/widgets/OBSBasic.cpp
  libobs/CMakeLists.txt
  libobs/cmake/libobsConfig.cmake.in
  libobs/cmake/linux/libobs.pc.in
  libobs/obs-config.h
  plugins/obs-outputs/flv-mux.c
Labels: Code Cleanup

#9978 libobs: Mark data path modification functions as deprecated
  libobs/obs.c
Labels: Code Cleanup
