Repository obsproject/obs-studio, pull requests merged in 2025-05, with the labels that each got.

#11509 rtmp-services: Add Enhanced Streaming support for Dolby Millicast
  plugins/rtmp-services/data/package.json
  plugins/rtmp-services/data/services.json
Labels: Services

#11785 frontend: Use Q_OBJECT macro for BrowserDock
  frontend/docks/BrowserDock.cpp
  frontend/docks/BrowserDock.hpp
Labels: Bug Fix, UI/UX

#12107 libobs: Fix module load in relocatable scenario
  libobs/obs-nix.c
Labels: Bug Fix

#12115 frontend: Make sure all QObject subclasses have Q_OBJECT macro
  frontend/components/DelButton.hpp
  frontend/components/EditWidget.hpp
  frontend/utility/OBSProxyStyle.cpp
  frontend/utility/OBSProxyStyle.hpp
  frontend/utility/SettingsEventFilter.hpp
  frontend/utility/SurfaceEventFilter.hpp
  frontend/widgets/ColorSelect.cpp
  frontend/widgets/ColorSelect.hpp
Labels: Bug Fix

#12118 libobs: Improve readability of scene duplication type
  libobs/obs-scene.c
Labels: Code Cleanup

#12049 libobs/util: Fix os_process_pipe_create on Linux
  libobs/util/pipe-posix.c
Labels: Bug Fix, macOS, Linux

#9352 obs-ffmpeg: New default settings for AMD encoders
  plugins/obs-ffmpeg/data/locale/en-US.ini
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Enhancement

#12111 win-capture: Fix crash if no display is available
  plugins/win-capture/duplicator-monitor-capture.c
Labels: Bug Fix, Windows

#11783 frontend: Use static_cast when casting from void pointers
  frontend/OBSStudioAPI.cpp
  frontend/components/OBSAdvAudioCtrl.cpp
  frontend/components/SourceTree.cpp
  frontend/components/SourceTreeItem.cpp
  frontend/components/SourceTreeModel.cpp
  frontend/components/UIValidation.cpp
  frontend/components/VisibilityItemWidget.cpp
  frontend/dialogs/OBSBasicAdvAudio.cpp
  frontend/dialogs/OBSBasicFilters.cpp
  frontend/dialogs/OBSBasicSourceSelect.cpp
  frontend/dialogs/OBSBasicTransform.cpp
  frontend/utility/QuickTransition.cpp
  frontend/utility/ScreenshotObj.cpp
  frontend/widgets/OBSBasicPreview.cpp
  frontend/widgets/OBSBasicStats.cpp
  frontend/widgets/OBSBasicStatusBar.cpp
  frontend/widgets/OBSBasic_Preview.cpp
  frontend/widgets/OBSBasic_SceneItems.cpp
  frontend/widgets/OBSBasic_Scenes.cpp
  frontend/widgets/OBSBasic_VolControl.cpp
  frontend/widgets/OBSProjector.cpp
  frontend/wizards/AutoConfigTestPage.cpp
Labels: Bug Fix, UI/UX

#12094 media-playback: Fix possible crash on startup
  shared/media-playback/media-playback/media.c
Labels: Bug Fix

#12117 libobs: Add obs_canvas_rename_source()
  libobs/obs-canvas.c
  libobs/obs-internal.h
  libobs/obs-source.c
Labels: Bug Fix, Enhancement

#12119 libobs: Fall back to main canvas dimensions if canvas invalid
  libobs/obs-scene.c
Labels: Bug Fix

#12121 frontend: Fix character encoding issue during profile import
  frontend/widgets/OBSBasic_Profiles.cpp
Labels: Bug Fix, Windows

#12120 libobs/util: Fix build on FreeBSD
  libobs/util/platform-nix.c
Labels: Bug Fix, Other OS (*nix)

#11997 frontend: Allow 5 multitrack reconnect attempts before re-running GCC
  frontend/utility/MultitrackVideoOutput.cpp
  frontend/utility/MultitrackVideoOutput.hpp
Labels: Enhancement

#12103 libobs: Add checks to some graphics API functions
  libobs/graphics/graphics.c
Labels: Bug Fix, Enhancement

#12130 decklink: Fix incorrect HDR min mastering luminance value
  plugins/decklink/OBSVideoFrame.cpp
Labels: Bug Fix

#12144 docs: Fix function name obs_set_video_sdr_white_level
  docs/sphinx/reference-core.rst
Labels: Documentation

#12148 frontend: Fix build on FreeBSD
  frontend/cmake/os-freebsd.cmake
Labels: Bug Fix, Other OS (*nix)

#12150 CI: Update obs-crowdin-sync to latest
  .github/workflows/dispatch.yaml
  .github/workflows/scheduled.yaml
Labels: CI

#12155 frontend: Add close icon
  frontend/forms/images/close.svg
  frontend/forms/obs.qrc
Labels: Bug Fix, UI/UX

#12153 CONTRIBUTING.rst: Fix macOS typo
  CONTRIBUTING.rst
Labels: Documentation

#12093 linux-v4l2: Skip corrupted H264/MJPEG frames during capture
  plugins/linux-v4l2/v4l2-input.c
Labels: Bug Fix, Linux

#12160 libobs-opengl: Promote eglCreateImage failure to LOG_ERROR
  libobs-opengl/gl-egl-common.c
Labels: Enhancement

#12151 obs-outputs: Correct FLV CTS calculation
  plugins/obs-outputs/flv-mux.c
Labels: Bug Fix

#12170 win-capture: Add SDL_app to list of generic classes
  libobs/util/windows/window-helpers.c
Labels: Bug Fix, Windows

#12168 CI: Add CEF and enable obs-browser for Windows on ARM
  CMakePresets.json
  buildspec.json
  plugins/CMakeLists.txt
Labels: Enhancement, Seeking Testers, Windows, CI

#12166 frontend: Fix dock title button sizes
  frontend/data/themes/Dark/close.svg
  frontend/data/themes/Light/close.svg
  frontend/data/themes/Yami.obt
  frontend/forms/images/close.svg
Labels: Bug Fix, UI/UX

#12167 frontend: Explicitly set titlebar item padding
  frontend/data/themes/Yami.obt
Labels: Bug Fix, UI/UX

#12157 frontend: Fix visibility and lock checkbox in System theme
  frontend/components/SourceTreeItem.cpp
Labels: Bug Fix, UI/UX

#12159 frontend: Add missing translations
  frontend/data/locale/en-US.ini
  frontend/forms/OBSBasicSettings.ui
Labels: Bug Fix, UI/UX

#12185 frontend: Swap preview zoom buttons
  frontend/forms/OBSBasic.ui
Labels: UI/UX

#12187 libobs/util: Fix coprocess not having environment variables
  libobs/util/pipe-posix.c
Labels: Bug Fix, macOS, Linux, Other OS (*nix)

#12156 frontend: Fix button pressed color in Rachni theme
  frontend/data/themes/Yami_Rachni.ovt
Labels: Bug Fix, UI/UX

#12198 CI: Update deps to 2025-05-23 release
  buildspec.json
Labels: Bug Fix, Enhancement

#11262 frontend: Enable browser hw accel toggle under Linux
  frontend/OBSApp.cpp
  frontend/settings/OBSBasicSettings.cpp
Labels: Linux, New Feature

#12214 frontend: Ensure cookie ID is always 16 hexadecimal characters
  frontend/widgets/OBSBasic_Browser.cpp
Labels: Bug Fix
