Repository obsproject/obs-studio, pull requests merged in 2025-06, with the labels that each got.

#12225 CI: Fix CEF ubuntu-aarch64 build
  buildspec.json
Labels: Bug Fix, Linux, CI

#12232 frontend/forms: Fix duplicate UI element name warning
  frontend/forms/OBSPermissions.ui
Labels: Bug Fix

#12234 frontend/forms: Fix text cut off in multitrack video info
  frontend/forms/AutoConfigStreamPage.ui
Labels: Bug Fix, UI/UX

#12228 frontend: Fix tab padding for the new appearance options
  frontend/data/themes/Yami.obt
Labels: Bug Fix, UI/UX

#12230 frontend: Fix metatype declaration for scenes and OBSBasic
  frontend/widgets/OBSBasic_Scenes.cpp
Labels: Bug Fix

#12239 CI: Explicitly label Windows artifact and asset architecture
  .github/actions/windows-patches/action.yaml
  .github/workflows/push.yaml
Labels: Code Cleanup, CI

#12098 obs-ffmpeg: Add B-frame CQP support for AMD AV1 encoder
  plugins/obs-ffmpeg/texture-amf.cpp
Labels: Bug Fix

#12254 CI: Fix Steam upload again
  .github/actions/steam-upload/action.yaml
Labels: Bug Fix, Windows, CI

#12256 CI: Update windows-signing to rclone 1.69.3
  .github/actions/windows-signing/action.yaml
Labels: Enhancement, Windows, CI

#12257 CI: Update steam-upload runner to macos-15
  .github/workflows/publish.yaml
Labels: CI

#12272 CI: Update sign-windows commit
  .github/workflows/push.yaml
Labels: Enhancement, Windows, CI

#12280 frontend: Fix group icon position in System theme
  frontend/components/SourceTreeItem.cpp
Labels: Bug Fix, UI/UX

#12262 frontend: Set Frontend-API QActions role to NoRole
  frontend/OBSStudioAPI.cpp
  frontend/widgets/OBSBasic_Docks.cpp
Labels: Bug Fix
