Repository obsproject/obs-studio, pull requests merged in 2025-02, with the labels that each got.

#11804 CI: Fix typo in setup-macos-codesigning action
  .github/actions/setup-macos-codesigning/action.yaml
Labels: Code Cleanup, CI

#11554 cmake: Fix regexp to detect installed FFmpeg version
  cmake/finders/FindFFmpeg.cmake
Labels: Bug Fix

#11358 frontend: Resize Output to Source Size using rounded up values
  frontend/widgets/OBSBasic_OutputHandler.cpp
Labels: UI/UX

#11520 obs-nvenc: Correct max target quality for AV1
  plugins/obs-nvenc/nvenc-properties.c
Labels: Bug Fix, Enhancement

#11843 cmake: Replace COMPILE_FLAGS with COMPILE_OPTIONS
  frontend/cmake/feature-sparkle.cmake
  frontend/cmake/os-macos.cmake
  libobs/cmake/os-macos.cmake
  plugins/mac-avcapture/legacy/CMakeLists.txt
Labels: Code Cleanup, macOS

#11440 frontend: Add support for TEB/Multitrack Video to macOS (arm64 only)
  frontend/settings/OBSBasicSettings.cpp
  frontend/utility/system-info-macos.mm
Labels: macOS, New Feature

#11805 bpm: Fix potential null-pointer dereference
  shared/bpm/bpm.c
Labels: Bug Fix

#11695 libobs: Use limited range for R10l output
  libobs/data/default.effect
Labels: Bug Fix

#11816 obs-nvenc: Fix lookahead depth value logging
  plugins/obs-nvenc/nvenc.c
Labels: Bug Fix

#11834 frontend: Fix manifest commit hash comparison
  frontend/utility/AutoUpdateThread.cpp
Labels: Bug Fix

#11841 cmake: Don't copy legacy, unused Chromium file
  cmake/linux/helpers.cmake
  cmake/windows/helpers.cmake
Labels: Code Cleanup
