Repository obsproject/obs-studio, pull requests merged in 2025-01, with the labels that each got.

#11663 libobs: Fix deadlock on macOS input method change
  libobs/obs-cocoa.m
Labels: Bug Fix, macOS

#11630 UI: Fix remigrating scene collections from absolute to relative
  UI/window-basic-main-scene-collections.cpp
  UI/window-basic-main.hpp
Labels: Bug Fix

#11651 UI: Fix Linux base folder location
  UI/obs-app.cpp
Labels: Bug Fix, Linux

#11626 obs-nvenc: Fix translation string for 4:4:4 unsupported error
  plugins/obs-nvenc/nvenc.c
Labels: Bug Fix

#11625 obs-nvenc: Abort encoder init if custom options are invalid
  plugins/obs-nvenc/data/locale/en-US.ini
  plugins/obs-nvenc/nvenc-internal.h
  plugins/obs-nvenc/nvenc-opts-parser.c
  plugins/obs-nvenc/nvenc.c
Labels: Bug Fix

#11629 image-source: Fix slideshow stopping on last file in random mode
  plugins/image-source/obs-slideshow-mk2.c
Labels: Bug Fix

#11668 libobs: Fix underlinking by adding libx11
  libobs/cmake/os-linux.cmake
Labels: Code Cleanup, Linux

#11736 cmake: Turn off camera reaction by default on macOS 14.4 and later (31.0 cherry-pick)
  UI/cmake/macos/Info.plist.in
Labels: Bug Fix

#11735 frontend: Fix crashes caused by scene collections with empty internal name
  frontend/widgets/OBSBasic_SceneCollections.cpp
Labels: Bug Fix

#11495 libobs/util: Fix tv_nsec becoming 1000000000 in os_event_timedwait
  libobs/util/threading-posix.c
Labels: Bug Fix

#11511 obs-ffmpeg: Fix deprecation with FFmpeg 7.1
  plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c
  plugins/obs-ffmpeg/obs-ffmpeg-output.c
Labels: Enhancement

#11517 obs-outputs: Attempt to generate path if one is not specified
  plugins/obs-outputs/mp4-output.c
Labels: Enhancement

#11615 frontend: Move media control dynamic properties to ui file
  frontend/components/MediaControls.cpp
  frontend/forms/source-toolbar/media-controls.ui
Labels: Code Cleanup, UI/UX

#11737 .gitignore: Remove UI exclusion
  .gitignore
Labels: Code Cleanup

#11518 obs-outputs: Make MP4 output buffer/chunk size configurable
  plugins/obs-outputs/mp4-output.c
Labels: Enhancement

#11590 obs-scripting: Fix macOS Homebrew Python loading
  shared/obs-scripting/obs-scripting-python-import.c
  shared/obs-scripting/obs-scripting-python.c
Labels: Bug Fix, macOS

#11507 libobs: plugins: Use MAD for sRGB functions
  libobs/data/color.effect
  plugins/nv-filters/data/color.effect
  plugins/obs-filters/data/color.effect
  plugins/obs-transitions/data/fade_to_color_transition.effect
  plugins/obs-transitions/data/fade_transition.effect
  plugins/obs-transitions/data/stinger_matte_transition.effect
Labels: Enhancement

#11442 mac-videotoolbox: Add Spatial AQ option (macOS 15)
  plugins/mac-videotoolbox/data/locale/en-US.ini
  plugins/mac-videotoolbox/encoder.c
Labels: macOS, New Feature

#10966 obs-webrtc: Enable PacingHandler
  plugins/obs-webrtc/whip-output.cpp
Labels: Bug Fix

#11733 frontend: Log streaming service recommended maximums
  frontend/utility/AdvancedOutput.cpp
  frontend/utility/SimpleOutput.cpp
Labels: Enhancement

#11215 frontend: Remove unnecessary projector variable
  frontend/widgets/OBSProjector.cpp
  frontend/widgets/OBSProjector.hpp
Labels: Code Cleanup

#11203 frontend: Simplify how projectors are saved/loaded
  frontend/widgets/OBSBasic.hpp
  frontend/widgets/OBSBasic_Preview.cpp
  frontend/widgets/OBSBasic_Projectors.cpp
  frontend/widgets/OBSBasic_SceneCollections.cpp
Labels: Code Cleanup
